SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[SpRetrieveUserWithIndigoClientById]
@UserId bigint
AS

BEGIN
  SELECT
    1 AS Tag,
    NULL AS Parent,
    T1.UserId AS [User!1!UserId], 
    T1.Identifier AS [User!1!Identifier], 
    T1.Password AS [User!1!Password], 
    ISNULL(T1.PasswordHistory, '') AS [User!1!PasswordHistory], 
    T1.Email AS [User!1!Email], 
    ISNULL(T1.Telephone, '') AS [User!1!Telephone], 
    T1.Status AS [User!1!Status], 
    T1.GroupId AS [User!1!GroupId], 
    ISNULL(T1.SyncPassword, '') AS [User!1!SyncPassword], 
    ISNULL(CONVERT(varchar(24), T1.ExpirePasswordOn, 120),'') AS [User!1!ExpirePasswordOn], 
    T1.SuperUser AS [User!1!SuperUser], 
    T1.SuperViewer AS [User!1!SuperViewer], 
    T1.FinancialPlanningAccess AS [User!1!FinancialPlanningAccess], 
    T1.FailedAccessAttempts AS [User!1!FailedAccessAttempts], 
    T1.WelcomePage AS [User!1!WelcomePage], 
    ISNULL(T1.Reference, '') AS [User!1!Reference], 
    ISNULL(T1.CRMContactId, '') AS [User!1!CRMContactId], 
    NULL AS [User!1!SearchData], 
    NULL AS [User!1!RecentData], 
    NULL AS [User!1!RecentWork], 
    ISNULL(T1.IndigoClientId, '') AS [User!1!IndigoClientId], 
    T1.SupportUserFg AS [User!1!SupportUserFg], 
    ISNULL(T1.ActiveRole, '') AS [User!1!ActiveRole], 
    T1.CanLogCases AS [User!1!CanLogCases], 
    T1.RefUserTypeId AS [User!1!RefUserTypeId], 
    T1.Guid AS [User!1!Guid], 
    T1.IsMortgageBenchEnabled AS [User!1!IsMortgageBenchEnabled], 
    T1.ConcurrencyId AS [User!1!ConcurrencyId], 
    NULL AS [IndigoClient!2!IndigoClientId], 
    NULL AS [IndigoClient!2!Identifier], 
    NULL AS [IndigoClient!2!Status], 
    NULL AS [IndigoClient!2!PrimaryContact], 
    NULL AS [IndigoClient!2!ContactId], 
    NULL AS [IndigoClient!2!PhoneNumber], 
    NULL AS [IndigoClient!2!EmailAddress], 
    NULL AS [IndigoClient!2!PrimaryGroupId], 
    NULL AS [IndigoClient!2!NetworkId], 
    NULL AS [IndigoClient!2!SIB], 
    NULL AS [IndigoClient!2!MCCB], 
    NULL AS [IndigoClient!2!FSA], 
    NULL AS [IndigoClient!2!IOProductType], 
    NULL AS [IndigoClient!2!ExpiryDate], 
    NULL AS [IndigoClient!2!AddressLine1], 
    NULL AS [IndigoClient!2!AddressLine2], 
    NULL AS [IndigoClient!2!AddressLine3], 
    NULL AS [IndigoClient!2!AddressLine4], 
    NULL AS [IndigoClient!2!CityTown], 
    NULL AS [IndigoClient!2!County], 
    NULL AS [IndigoClient!2!Postcode], 
    NULL AS [IndigoClient!2!Country], 
    NULL AS [IndigoClient!2!IsNetwork], 
    NULL AS [IndigoClient!2!SupportServiceId], 
    NULL AS [IndigoClient!2!FirmSize], 
    NULL AS [IndigoClient!2!Specialism], 
    NULL AS [IndigoClient!2!OtherSpecialism], 
    NULL AS [IndigoClient!2!SupportLevel], 
    NULL AS [IndigoClient!2!EmailSupOptn], 
    NULL AS [IndigoClient!2!SupportEmail], 
    NULL AS [IndigoClient!2!TelSupOptn], 
    NULL AS [IndigoClient!2!SupportTelephone], 
    NULL AS [IndigoClient!2!AllowPasswordEmail], 
    NULL AS [IndigoClient!2!SessionTimeout], 
    NULL AS [IndigoClient!2!LicenceType], 
    NULL AS [IndigoClient!2!MaxConUsers], 
    NULL AS [IndigoClient!2!MaxULAGCount], 
    NULL AS [IndigoClient!2!UADRestriction], 
    NULL AS [IndigoClient!2!MaxULADCount], 
    NULL AS [IndigoClient!2!AdviserCountRestrict], 
    NULL AS [IndigoClient!2!MaxAdviserCount], 
    NULL AS [IndigoClient!2!MaxFinancialPlanningUsers], 
    NULL AS [IndigoClient!2!EmailFormat], 
    NULL AS [IndigoClient!2!UserNameFormat], 
    NULL AS [IndigoClient!2!NTDomain], 
    NULL AS [IndigoClient!2!IsIndependent], 
    NULL AS [IndigoClient!2!BrandDescriptor], 
    NULL AS [IndigoClient!2!ServiceLevel], 
    NULL AS [IndigoClient!2!HostingFg], 
    NULL AS [IndigoClient!2!CaseLoggingOption], 
    NULL AS [IndigoClient!2!Guid], 
    NULL AS [IndigoClient!2!RefEnvironmentId], 
    NULL AS [IndigoClient!2!IsPortfolioConstructionProvider], 
    NULL AS [IndigoClient!2!IsAuthorProvider], 
    NULL AS [IndigoClient!2!IsAtrProvider], 
    NULL AS [IndigoClient!2!ConcurrencyId]
  FROM TUser T1

  WHERE (T1.UserId = @UserId)

  UNION ALL

  SELECT
    2 AS Tag,
    1 AS Parent,
    T1.UserId, 
    T1.Identifier, 
    T1.Password, 
    ISNULL(T1.PasswordHistory, ''), 
    T1.Email, 
    ISNULL(T1.Telephone, ''), 
    T1.Status, 
    T1.GroupId, 
    ISNULL(T1.SyncPassword, ''), 
    ISNULL(CONVERT(varchar(24), T1.ExpirePasswordOn, 120),''), 
    T1.SuperUser, 
    T1.SuperViewer, 
    T1.FinancialPlanningAccess, 
    T1.FailedAccessAttempts, 
    T1.WelcomePage, 
    ISNULL(T1.Reference, ''), 
    ISNULL(T1.CRMContactId, ''), 
    NULL, 
    NULL, 
    NULL, 
    ISNULL(T1.IndigoClientId, ''), 
    T1.SupportUserFg, 
    ISNULL(T1.ActiveRole, ''), 
    T1.CanLogCases, 
    T1.RefUserTypeId, 
    T1.Guid, 
    T1.IsMortgageBenchEnabled, 
    T1.ConcurrencyId, 
    T2.IndigoClientId, 
    T2.Identifier, 
    T2.Status, 
    T2.PrimaryContact, 
    ISNULL(T2.ContactId, ''), 
    T2.PhoneNumber, 
    T2.EmailAddress, 
    ISNULL(T2.PrimaryGroupId, ''), 
    ISNULL(T2.NetworkId, ''), 
    ISNULL(T2.SIB, ''), 
    ISNULL(T2.MCCB, ''), 
    ISNULL(T2.FSA, ''), 
    T2.IOProductType, 
    CONVERT(varchar(24), T2.ExpiryDate, 120), 
    T2.AddressLine1, 
    ISNULL(T2.AddressLine2, ''), 
    ISNULL(T2.AddressLine3, ''), 
    ISNULL(T2.AddressLine4, ''), 
    ISNULL(T2.CityTown, ''), 
    ISNULL(T2.County, ''), 
    T2.Postcode, 
    T2.Country, 
    T2.IsNetwork, 
    ISNULL(T2.SupportServiceId, ''), 
    T2.FirmSize, 
    T2.Specialism, 
    ISNULL(T2.OtherSpecialism, ''), 
    T2.SupportLevel, 
    T2.EmailSupOptn, 
    T2.SupportEmail, 
    T2.TelSupOptn, 
    T2.SupportTelephone, 
    T2.AllowPasswordEmail, 
    T2.SessionTimeout, 
    T2.LicenceType, 
    ISNULL(T2.MaxConUsers, ''), 
    ISNULL(T2.MaxULAGCount, ''), 
    T2.UADRestriction, 
    ISNULL(T2.MaxULADCount, ''), 
    T2.AdviserCountRestrict, 
    ISNULL(T2.MaxAdviserCount, ''), 
    ISNULL(T2.MaxFinancialPlanningUsers, ''), 
    ISNULL(T2.EmailFormat, ''), 
    ISNULL(T2.UserNameFormat, ''), 
    ISNULL(T2.NTDomain, ''), 
    T2.IsIndependent, 
    ISNULL(T2.BrandDescriptor, ''), 
    ISNULL(T2.ServiceLevel, ''), 
    T2.HostingFg, 
    T2.CaseLoggingOption, 
    T2.Guid, 
    ISNULL(T2.RefEnvironmentId, ''), 
    T2.IsPortfolioConstructionProvider, 
    T2.IsAuthorProvider, 
    T2.IsAtrProvider, 
    T2.ConcurrencyId
  FROM TIndigoClient T2
  INNER JOIN TUser T1
  ON T2.IndigoClientId = T1.IndigoClientId

  WHERE (T1.UserId = @UserId)

  ORDER BY [User!1!UserId], [IndigoClient!2!IndigoClientId]

  FOR XML EXPLICIT

END
RETURN (0)

GO
