SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SpCustomSearchUserByGroup]  
@Identifier varchar (64) = '',  
@GroupId bigint = 0,  
@IndigoClientId bigint,  
@_TopN int = 0  
AS  
  
BEGIN  
-- Limit rows returned?  
IF (@_TopN > 0) SET ROWCOUNT @_TopN  
  
  SELECT  
    1 AS Tag,  
    NULL AS Parent,  
    T1.UserId AS [User!1!UserId],   
    T1.Identifier AS [User!1!Identifier],   
    T1.Password AS [User!1!Password],   
    ISNULL(T1.PasswordHistory, '') AS [User!1!PasswordHistory],   
    T1.Email AS [User!1!Email],   
    ISNULL(T1.Telephone, '') AS [User!1!Telephone],   
    T1.Status AS [User!1!Status],   
    T1.GroupId AS [User!1!GroupId],   
    ISNULL(T1.SyncPassword, '') AS [User!1!SyncPassword],   
    ISNULL(CONVERT(varchar(24), T1.ExpirePasswordOn, 120),'') AS [User!1!ExpirePasswordOn],   
    T1.SuperUser AS [User!1!SuperUser],   
    T1.SuperViewer AS [User!1!SuperViewer],   
    T1.FailedAccessAttempts AS [User!1!FailedAccessAttempts],   
    T1.WelcomePage AS [User!1!WelcomePage],   
    ISNULL(T1.Reference, '') AS [User!1!Reference],   
    ISNULL(T1.CRMContactId, '') AS [User!1!CRMContactId],   
    NULL AS [User!1!SearchData],   
    NULL AS [User!1!RecentData],   
    NULL AS [User!1!RecentWork],   
    ISNULL(T1.IndigoClientId, '') AS [User!1!IndigoClientId],   
    T1.SupportUserFg AS [User!1!SupportUserFg],   
    ISNULL(T1.ActiveRole, '') AS [User!1!ActiveRole],   
    T1.CanLogCases AS [User!1!CanLogCases],   
    T1.RefUserTypeId AS [User!1!RefUserTypeId],   
    T1.Guid AS [User!1!Guid],   
    T1.ConcurrencyId AS [User!1!ConcurrencyId],   
    NULL AS [Group!2!GroupId],   
    NULL AS [Group!2!Identifier],   
    NULL AS [Group!2!GroupingId],   
    NULL AS [Group!2!ParentId],   
    NULL AS [Group!2!CRMContactId],   
    NULL AS [Group!2!IndigoClientId],   
    NULL AS [Group!2!LegalEntity],   
    NULL AS [Group!2!GroupImageLocation],   
    NULL AS [Group!2!AcknowledgementsLocation],   
    NULL AS [Group!2!FinancialYearEnd],   
    NULL AS [Group!2!ApplyFactFindBranding],   
    NULL AS [Group!2!ConcurrencyId],   
    NULL AS [CRMContact!3!CRMContactId],   
    NULL AS [CRMContact!3!RefCRMContactStatusId],   
    NULL AS [CRMContact!3!PersonId],   
    NULL AS [CRMContact!3!CorporateId],   
    NULL AS [CRMContact!3!TrustId],   
    NULL AS [CRMContact!3!AdvisorRef],   
    NULL AS [CRMContact!3!RefSourceOfClientId],   
    NULL AS [CRMContact!3!SourceValue],   
    NULL AS [CRMContact!3!Notes],   
    NULL AS [CRMContact!3!ArchiveFg],   
    NULL AS [CRMContact!3!LastName],   
    NULL AS [CRMContact!3!FirstName],   
    NULL AS [CRMContact!3!CorporateName],   
    NULL AS [CRMContact!3!DOB],   
    NULL AS [CRMContact!3!Postcode],   
    NULL AS [CRMContact!3!OriginalAdviserCRMId],   
    NULL AS [CRMContact!3!CurrentAdviserCRMId],   
    NULL AS [CRMContact!3!CurrentAdviserName],   
    NULL AS [CRMContact!3!CRMContactType],   
    NULL AS [CRMContact!3!IndClientId],   
    NULL AS [CRMContact!3!FactFindId],   
    NULL AS [CRMContact!3!InternalContactFG],   
    NULL AS [CRMContact!3!RefServiceStatusId],   
    NULL AS [CRMContact!3!MigrationRef],   
    NULL AS [CRMContact!3!CreatedDate],   
    NULL AS [CRMContact!3!ExternalReference],   
    NULL AS [CRMContact!3!CampaignDataId],   
    NULL AS [CRMContact!3!AdditionalRef],   
    NULL AS [CRMContact!3!ConcurrencyId],   
    NULL AS [Membership!4!MembershipId],   
    NULL AS [Membership!4!UserId],   
    NULL AS [Membership!4!RoleId],   
    NULL AS [Membership!4!ConcurrencyId],   
    NULL AS [Role!5!RoleId],   
    NULL AS [Role!5!Identifier],   
    NULL AS [Role!5!GroupingId],   
    NULL AS [Role!5!SuperUser],   
    NULL AS [Role!5!IndigoClientId],   
    NULL AS [Role!5!LicensedUserCount],   
    NULL AS [Role!5!Dashboard],   
    NULL AS [Role!5!ShowGroupDashboard],   
    NULL AS [Role!5!ConcurrencyId]  
  FROM TUser T1  
  
  WHERE (T1.Identifier LIKE '%' + @Identifier + '%' Or @Identifier = '') AND   
        (T1.GroupId = @GroupId Or @GroupId = 0) AND   
		T1.RefUserTypeId = 1 AND
        (T1.IndigoClientId = @IndigoClientId)  
  
  UNION ALL  
  
  SELECT  
    2 AS Tag,  
    1 AS Parent,  
    T1.UserId,   
    T1.Identifier,   
    T1.Password,   
    ISNULL(T1.PasswordHistory, ''),   
    T1.Email,   
    ISNULL(T1.Telephone, ''),   
    T1.Status,   
    T1.GroupId,   
    ISNULL(T1.SyncPassword, ''),   
    ISNULL(CONVERT(varchar(24), T1.ExpirePasswordOn, 120),''),   
    T1.SuperUser,   
    T1.SuperViewer,   
    T1.FailedAccessAttempts,   
    T1.WelcomePage,   
    ISNULL(T1.Reference, ''),   
    ISNULL(T1.CRMContactId, ''),   
    NULL,   
    NULL,   
    NULL,   
    ISNULL(T1.IndigoClientId, ''),   
    T1.SupportUserFg,   
    ISNULL(T1.ActiveRole, ''),   
    T1.CanLogCases,   
    T1.RefUserTypeId,   
    T1.Guid,   
    T1.ConcurrencyId,   
    T2.GroupId,   
    T2.Identifier,   
    T2.GroupingId,   
    ISNULL(T2.ParentId, ''),   
    ISNULL(T2.CRMContactId, ''),   
    T2.IndigoClientId,   
    T2.LegalEntity,   
    ISNULL(T2.GroupImageLocation, ''),   
    ISNULL(T2.AcknowledgementsLocation, ''),   
    ISNULL(CONVERT(varchar(24), T2.FinancialYearEnd, 120),''),   
    T2.ApplyFactFindBranding,   
    T2.ConcurrencyId,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL  
  FROM TGroup T2  
  INNER JOIN TUser T1  
  ON T2.GroupId = T1.GroupId  
  
  WHERE (T1.Identifier LIKE '%' + @Identifier + '%' Or @Identifier = '') AND   
        (T1.GroupId = @GroupId Or @GroupId = 0) AND 
		T1.RefUserTypeId = 1 AND 
        (T1.IndigoClientId = @IndigoClientId)  
  
  UNION ALL  
  
  SELECT  
    3 AS Tag,  
    1 AS Parent,  
    T1.UserId,   
    T1.Identifier,   
    T1.Password,   
    ISNULL(T1.PasswordHistory, ''),   
    T1.Email,   
    ISNULL(T1.Telephone, ''),   
    T1.Status,   
    T1.GroupId,   
    ISNULL(T1.SyncPassword, ''),   
    ISNULL(CONVERT(varchar(24), T1.ExpirePasswordOn, 120),''),   
    T1.SuperUser,   
    T1.SuperViewer,   
    T1.FailedAccessAttempts,   
    T1.WelcomePage,   
    ISNULL(T1.Reference, ''),   
    ISNULL(T1.CRMContactId, ''),   
    NULL,   
    NULL,   
    NULL,   
    ISNULL(T1.IndigoClientId, ''),   
    T1.SupportUserFg,   
    ISNULL(T1.ActiveRole, ''),   
    T1.CanLogCases,   
    T1.RefUserTypeId,   
    T1.Guid,   
    T1.ConcurrencyId,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    T3.CRMContactId,   
    ISNULL(T3.RefCRMContactStatusId, ''),   
    ISNULL(T3.PersonId, ''),   
    ISNULL(T3.CorporateId, ''),   
    ISNULL(T3.TrustId, ''),   
    ISNULL(T3.AdvisorRef, ''),   
    ISNULL(T3.RefSourceOfClientId, ''),   
    ISNULL(T3.SourceValue, ''),   
    ISNULL(T3.Notes, ''),   
    ISNULL(T3.ArchiveFg, ''),   
    ISNULL(T3.LastName, ''),   
    ISNULL(T3.FirstName, ''),   
    ISNULL(T3.CorporateName, ''),   
    ISNULL(CONVERT(varchar(24), T3.DOB, 120),''),   
    ISNULL(T3.Postcode, ''),   
    T3.OriginalAdviserCRMId,   
    T3.CurrentAdviserCRMId,   
    ISNULL(T3.CurrentAdviserName, ''),   
    T3.CRMContactType,   
    T3.IndClientId,   
    ISNULL(T3.FactFindId, ''),   
    ISNULL(T3.InternalContactFG, ''),   
    ISNULL(T3.RefServiceStatusId, ''),   
    ISNULL(T3.MigrationRef, ''),   
    CONVERT(varchar(24), T3.CreatedDate, 120),   
    ISNULL(T3.ExternalReference, ''),   
    ISNULL(T3.CampaignDataId, ''),   
    ISNULL(T3.AdditionalRef, ''),   
    T3.ConcurrencyId,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL  
  FROM [CRM].[dbo].TCRMContact T3  
  INNER JOIN TUser T1  
  ON T3.CRMContactId = T1.CRMContactId  
  
  WHERE (T1.Identifier LIKE '%' + @Identifier + '%' Or @Identifier = '') AND   
  (T1.GroupId = @GroupId Or @GroupId = 0) AND   
		T1.RefUserTypeId = 1 AND
        (T1.IndigoClientId = @IndigoClientId)  
  
  UNION ALL  
  
  SELECT  
    4 AS Tag,  
    1 AS Parent,  
    T1.UserId,   
    T1.Identifier,   
    T1.Password,   
    ISNULL(T1.PasswordHistory, ''),   
    T1.Email,   
    ISNULL(T1.Telephone, ''),   
    T1.Status,   
    T1.GroupId,   
    ISNULL(T1.SyncPassword, ''),   
    ISNULL(CONVERT(varchar(24), T1.ExpirePasswordOn, 120),''),   
    T1.SuperUser,   
    T1.SuperViewer,   
    T1.FailedAccessAttempts,   
    T1.WelcomePage,   
    ISNULL(T1.Reference, ''),   
    ISNULL(T1.CRMContactId, ''),   
    NULL,   
    NULL,   
    NULL,   
    ISNULL(T1.IndigoClientId, ''),   
    T1.SupportUserFg,   
    ISNULL(T1.ActiveRole, ''),   
    T1.CanLogCases,   
    T1.RefUserTypeId,   
    T1.Guid,   
    T1.ConcurrencyId,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    T4.MembershipId,   
    T4.UserId,   
    T4.RoleId,   
    T4.ConcurrencyId,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL  
  FROM TMembership T4  
  INNER JOIN TUser T1  
  ON T4.UserId = T1.UserId  
  
  WHERE (T1.Identifier LIKE '%' + @Identifier + '%' Or @Identifier = '') AND   
        (T1.GroupId = @GroupId Or @GroupId = 0) AND 
		T1.RefUserTypeId = 1 AND  
        (T1.IndigoClientId = @IndigoClientId)  
  
  UNION ALL  
  
  SELECT  
    5 AS Tag,  
    4 AS Parent,  
    T1.UserId,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    NULL,   
    T4.MembershipId,   
    T4.UserId,   
    T4.RoleId,   
    T4.ConcurrencyId,   
    T5.RoleId,   
    T5.Identifier,   
    T5.GroupingId,   
    T5.SuperUser,   
    T5.IndigoClientId,   
    T5.LicensedUserCount,   
    ISNULL(T5.Dashboard, ''),   
    ISNULL(T5.ShowGroupDashboard, ''),   
    T5.ConcurrencyId  
  FROM TRole T5  
  INNER JOIN TMembership T4  
  ON T5.RoleId = T4.RoleId  
  INNER JOIN TUser T1  
  ON T4.UserId = T1.UserId  
  
  WHERE (T1.Identifier LIKE '%' + @Identifier + '%' Or @Identifier = '') AND   
        (T1.GroupId = @GroupId Or @GroupId = 0) AND   
		T1.RefUserTypeId = 1 AND
        (T1.IndigoClientId = @IndigoClientId)  
  
  ORDER BY [User!1!UserId], [Membership!4!MembershipId], [Role!5!RoleId], [CRMContact!3!CRMContactId], [Group!2!GroupId]  
  
  FOR XML EXPLICIT  
  
IF (@_TopN > 0) SET ROWCOUNT 0  
  
END  
RETURN (0)  
  
GO
