SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[SpAliasRetrieveUserByIdBasicWithContactDetails]
@UserId bigint
AS

BEGIN
  SELECT
    1 AS Tag,
    NULL AS Parent,
    T1.UserId AS [User!1!UserId], 
    T1.Identifier AS [User!1!Identifier], 
    T1.Password AS [User!1!Password], 
    ISNULL(T1.PasswordHistory, '') AS [User!1!PasswordHistory], 
    T1.Email AS [User!1!Email], 
    ISNULL(T1.Telephone, '') AS [User!1!Telephone], 
    T1.Status AS [User!1!Status], 
    T1.GroupId AS [User!1!GroupId], 
    ISNULL(T1.SyncPassword, '') AS [User!1!SyncPassword], 
    ISNULL(CONVERT(varchar(24), T1.ExpirePasswordOn, 120),'') AS [User!1!ExpirePasswordOn], 
    T1.SuperUser AS [User!1!SuperUser], 
    T1.SuperViewer AS [User!1!SuperViewer], 
    T1.FinancialPlanningAccess AS [User!1!FinancialPlanningAccess], 
    T1.FailedAccessAttempts AS [User!1!FailedAccessAttempts], 
    T1.WelcomePage AS [User!1!WelcomePage], 
    ISNULL(T1.Reference, '') AS [User!1!Reference], 
    ISNULL(T1.CRMContactId, '') AS [User!1!CRMContactId], 
    NULL AS [User!1!SearchData], 
    NULL AS [User!1!RecentData], 
    NULL AS [User!1!RecentWork], 
    ISNULL(T1.IndigoClientId, '') AS [User!1!IndigoClientId], 
    T1.SupportUserFg AS [User!1!SupportUserFg], 
    ISNULL(T1.ActiveRole, '') AS [User!1!ActiveRole], 
    T1.CanLogCases AS [User!1!CanLogCases], 
    T1.RefUserTypeId AS [User!1!RefUserTypeId], 
    T1.Guid AS [User!1!Guid], 
    T1.IsMortgageBenchEnabled AS [User!1!IsMortgageBenchEnabled], 
    T1.ConcurrencyId AS [User!1!ConcurrencyId], 
    NULL AS [Membership!2!MembershipId], 
    NULL AS [Membership!2!UserId], 
    NULL AS [Membership!2!RoleId], 
    NULL AS [Membership!2!ConcurrencyId], 
    NULL AS [RefUserType!3!RefUserTypeId], 
    NULL AS [RefUserType!3!Identifier], 
    NULL AS [RefUserType!3!Url], 
    NULL AS [RefUserType!3!ConcurrencyId], 
    NULL AS [CRMContact!4!CRMContactId], 
    NULL AS [CRMContact!4!RefCRMContactStatusId], 
    NULL AS [CRMContact!4!PersonId], 
    NULL AS [CRMContact!4!CorporateId], 
    NULL AS [CRMContact!4!TrustId], 
    NULL AS [CRMContact!4!AdvisorRef], 
    NULL AS [CRMContact!4!RefSourceOfClientId], 
    NULL AS [CRMContact!4!SourceValue], 
    NULL AS [CRMContact!4!Notes], 
    NULL AS [CRMContact!4!ArchiveFg], 
    NULL AS [CRMContact!4!LastName], 
    NULL AS [CRMContact!4!FirstName], 
    NULL AS [CRMContact!4!CorporateName], 
    NULL AS [CRMContact!4!DOB], 
    NULL AS [CRMContact!4!Postcode], 
    NULL AS [CRMContact!4!OriginalAdviserCRMId], 
    NULL AS [CRMContact!4!CurrentAdviserCRMId], 
    NULL AS [CRMContact!4!CurrentAdviserName], 
    NULL AS [CRMContact!4!CRMContactType], 
    NULL AS [CRMContact!4!IndClientId], 
    NULL AS [CRMContact!4!FactFindId], 
    NULL AS [CRMContact!4!InternalContactFG], 
    NULL AS [CRMContact!4!RefServiceStatusId], 
    NULL AS [CRMContact!4!MigrationRef], 
    NULL AS [CRMContact!4!CreatedDate], 
    NULL AS [CRMContact!4!ExternalReference], 
    NULL AS [CRMContact!4!CampaignDataId], 
    NULL AS [CRMContact!4!AdditionalRef], 
    NULL AS [CRMContact!4!_ParentId], 
    NULL AS [CRMContact!4!_ParentTable], 
    NULL AS [CRMContact!4!_ParentDb], 
    NULL AS [CRMContact!4!_OwnerId], 
    NULL AS [CRMContact!4!ConcurrencyId], 
    NULL AS [Role!5!RoleId], 
    NULL AS [Role!5!Identifier], 
    NULL AS [Role!5!GroupingId], 
    NULL AS [Role!5!SuperUser], 
    NULL AS [Role!5!IndigoClientId], 
    NULL AS [Role!5!LicensedUserCount], 
    NULL AS [Role!5!Dashboard], 
    NULL AS [Role!5!ShowGroupDashboard], 
    NULL AS [Role!5!ConcurrencyId], 
    NULL AS [Person!6!PersonId], 
    NULL AS [Person!6!Title], 
    NULL AS [Person!6!FirstName], 
    NULL AS [Person!6!MiddleName], 
    NULL AS [Person!6!LastName], 
    NULL AS [Person!6!MaidenName], 
    NULL AS [Person!6!DOB], 
    NULL AS [Person!6!GenderType], 
    NULL AS [Person!6!NINumber], 
    NULL AS [Person!6!IsSmoker], 
    NULL AS [Person!6!UKResident], 
    NULL AS [Person!6!ResidentIn], 
    NULL AS [Person!6!Salutation], 
    NULL AS [Person!6!RefSourceTypeId], 
    NULL AS [Person!6!IntroducerSource], 
    NULL AS [Person!6!MaritalStatus], 
    NULL AS [Person!6!MarriedOn], 
    NULL AS [Person!6!Residency], 
    NULL AS [Person!6!UKDomicile], 
    NULL AS [Person!6!Domicile], 
    NULL AS [Person!6!TaxCode], 
    NULL AS [Person!6!Nationality], 
    NULL AS [Person!6!ArchiveFG], 
    NULL AS [Person!6!IndClientId], 
    NULL AS [Person!6!ConcurrencyId]
  FROM TUser T1

  WHERE (T1.UserId = @UserId)

  UNION ALL

  SELECT
    2 AS Tag,
    1 AS Parent,
    T1.UserId, 
    T1.Identifier, 
    T1.Password, 
    ISNULL(T1.PasswordHistory, ''), 
    T1.Email, 
    ISNULL(T1.Telephone, ''), 
    T1.Status, 
    T1.GroupId, 
    ISNULL(T1.SyncPassword, ''), 
    ISNULL(CONVERT(varchar(24), T1.ExpirePasswordOn, 120),''), 
    T1.SuperUser, 
    T1.SuperViewer, 
    T1.FinancialPlanningAccess, 
    T1.FailedAccessAttempts, 
    T1.WelcomePage, 
    ISNULL(T1.Reference, ''), 
    ISNULL(T1.CRMContactId, ''), 
    NULL, 
    NULL, 
    NULL, 
    ISNULL(T1.IndigoClientId, ''), 
    T1.SupportUserFg, 
    ISNULL(T1.ActiveRole, ''), 
    T1.CanLogCases, 
    T1.RefUserTypeId, 
    T1.Guid, 
    T1.IsMortgageBenchEnabled, 
    T1.ConcurrencyId, 
    T2.MembershipId, 
    T2.UserId, 
    T2.RoleId, 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TMembership T2
  INNER JOIN TUser T1
  ON T2.UserId = T1.UserId

  WHERE (T1.UserId = @UserId)

  UNION ALL

  SELECT
    3 AS Tag,
    1 AS Parent,
    T1.UserId, 
    T1.Identifier, 
    T1.Password, 
    ISNULL(T1.PasswordHistory, ''), 
    T1.Email, 
    ISNULL(T1.Telephone, ''), 
    T1.Status, 
    T1.GroupId, 
    ISNULL(T1.SyncPassword, ''), 
    ISNULL(CONVERT(varchar(24), T1.ExpirePasswordOn, 120),''), 
    T1.SuperUser, 
    T1.SuperViewer, 
    T1.FinancialPlanningAccess, 
    T1.FailedAccessAttempts, 
    T1.WelcomePage, 
    ISNULL(T1.Reference, ''), 
    ISNULL(T1.CRMContactId, ''), 
    NULL, 
    NULL, 
    NULL, 
    ISNULL(T1.IndigoClientId, ''), 
    T1.SupportUserFg, 
    ISNULL(T1.ActiveRole, ''), 
    T1.CanLogCases, 
    T1.RefUserTypeId, 
    T1.Guid, 
    T1.IsMortgageBenchEnabled, 
    T1.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T3.RefUserTypeId, 
    T3.Identifier, 
    T3.Url, 
    T3.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TRefUserType T3
  INNER JOIN TUser T1
  ON T3.RefUserTypeId = T1.RefUserTypeId

  WHERE (T1.UserId = @UserId)

  UNION ALL

  SELECT
    4 AS Tag,
    1 AS Parent,
    T1.UserId, 
    T1.Identifier, 
    T1.Password, 
    ISNULL(T1.PasswordHistory, ''), 
    T1.Email, 
    ISNULL(T1.Telephone, ''), 
    T1.Status, 
    T1.GroupId, 
    ISNULL(T1.SyncPassword, ''), 
    ISNULL(CONVERT(varchar(24), T1.ExpirePasswordOn, 120),''), 
    T1.SuperUser, 
    T1.SuperViewer, 
    T1.FinancialPlanningAccess, 
    T1.FailedAccessAttempts, 
    T1.WelcomePage, 
    ISNULL(T1.Reference, ''), 
    ISNULL(T1.CRMContactId, ''), 
    NULL, 
    NULL, 
    NULL, 
    ISNULL(T1.IndigoClientId, ''), 
    T1.SupportUserFg, 
    ISNULL(T1.ActiveRole, ''), 
    T1.CanLogCases, 
    T1.RefUserTypeId, 
    T1.Guid, 
    T1.IsMortgageBenchEnabled, 
    T1.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T4.CRMContactId, 
    ISNULL(T4.RefCRMContactStatusId, ''), 
    ISNULL(T4.PersonId, ''), 
    ISNULL(T4.CorporateId, ''), 
    ISNULL(T4.TrustId, ''), 
    ISNULL(T4.AdvisorRef, ''), 
    ISNULL(T4.RefSourceOfClientId, ''), 
    ISNULL(T4.SourceValue, ''), 
    ISNULL(T4.Notes, ''), 
    ISNULL(T4.ArchiveFg, ''), 
    ISNULL(T4.LastName, ''), 
    ISNULL(T4.FirstName, ''), 
    ISNULL(T4.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T4.DOB, 120),''), 
    ISNULL(T4.Postcode, ''), 
    T4.OriginalAdviserCRMId, 
    T4.CurrentAdviserCRMId, 
    ISNULL(T4.CurrentAdviserName, ''), 
    T4.CRMContactType, 
    T4.IndClientId, 
    ISNULL(T4.FactFindId, ''), 
    ISNULL(T4.InternalContactFG, ''), 
    ISNULL(T4.RefServiceStatusId, ''), 
    ISNULL(T4.MigrationRef, ''), 
    CONVERT(varchar(24), T4.CreatedDate, 120), 
    ISNULL(T4.ExternalReference, ''), 
    ISNULL(T4.CampaignDataId, ''), 
    ISNULL(T4.AdditionalRef, ''), 
    ISNULL(T4._ParentId, ''), 
    ISNULL(T4._ParentTable, ''), 
    ISNULL(T4._ParentDb, ''), 
    ISNULL(T4._OwnerId, ''), 
    T4.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM [CRM].[dbo].TCRMContact T4
  INNER JOIN TUser T1
  ON T4.CRMContactId = T1.CRMContactId

  WHERE (T1.UserId = @UserId)

  UNION ALL

  SELECT
    5 AS Tag,
    2 AS Parent,
    T1.UserId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T2.MembershipId, 
    T2.UserId, 
    T2.RoleId, 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T5.RoleId, 
    T5.Identifier, 
    T5.GroupingId, 
    T5.SuperUser, 
    T5.IndigoClientId, 
    T5.LicensedUserCount, 
    ISNULL(T5.Dashboard, ''), 
    ISNULL(T5.ShowGroupDashboard, ''), 
    T5.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TRole T5
  INNER JOIN TMembership T2
  ON T5.RoleId = T2.RoleId
  INNER JOIN TUser T1
  ON T2.UserId = T1.UserId

  WHERE (T1.UserId = @UserId)

  UNION ALL

  SELECT
    6 AS Tag,
    4 AS Parent,
    T1.UserId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T4.CRMContactId, 
    ISNULL(T4.RefCRMContactStatusId, ''), 
    ISNULL(T4.PersonId, ''), 
    ISNULL(T4.CorporateId, ''), 
    ISNULL(T4.TrustId, ''), 
    ISNULL(T4.AdvisorRef, ''), 
    ISNULL(T4.RefSourceOfClientId, ''), 
    ISNULL(T4.SourceValue, ''), 
    ISNULL(T4.Notes, ''), 
    ISNULL(T4.ArchiveFg, ''), 
    ISNULL(T4.LastName, ''), 
    ISNULL(T4.FirstName, ''), 
    ISNULL(T4.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T4.DOB, 120),''), 
    ISNULL(T4.Postcode, ''), 
    T4.OriginalAdviserCRMId, 
    T4.CurrentAdviserCRMId, 
    ISNULL(T4.CurrentAdviserName, ''), 
    T4.CRMContactType, 
    T4.IndClientId, 
    ISNULL(T4.FactFindId, ''), 
    ISNULL(T4.InternalContactFG, ''), 
    ISNULL(T4.RefServiceStatusId, ''), 
    ISNULL(T4.MigrationRef, ''), 
    CONVERT(varchar(24), T4.CreatedDate, 120), 
    ISNULL(T4.ExternalReference, ''), 
    ISNULL(T4.CampaignDataId, ''), 
    ISNULL(T4.AdditionalRef, ''), 
    ISNULL(T4._ParentId, ''), 
    ISNULL(T4._ParentTable, ''), 
    ISNULL(T4._ParentDb, ''), 
    ISNULL(T4._OwnerId, ''), 
    T4.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T6.PersonId, 
    ISNULL(T6.Title, ''), 
    T6.FirstName, 
    ISNULL(T6.MiddleName, ''), 
    T6.LastName, 
    ISNULL(T6.MaidenName, ''), 
    ISNULL(CONVERT(varchar(24), T6.DOB, 120),''), 
    ISNULL(T6.GenderType, ''), 
    ISNULL(T6.NINumber, ''), 
    ISNULL(T6.IsSmoker, ''), 
    ISNULL(T6.UKResident, ''), 
    ISNULL(T6.ResidentIn, ''), 
    ISNULL(T6.Salutation, ''), 
    ISNULL(T6.RefSourceTypeId, ''), 
    ISNULL(T6.IntroducerSource, ''), 
    ISNULL(T6.MaritalStatus, ''), 
    ISNULL(CONVERT(varchar(24), T6.MarriedOn, 120),''), 
    ISNULL(T6.Residency, ''), 
    ISNULL(T6.UKDomicile, ''), 
    ISNULL(T6.Domicile, ''), 
    ISNULL(T6.TaxCode, ''), 
    ISNULL(T6.Nationality, ''), 
    T6.ArchiveFG, 
    T6.IndClientId, 
    T6.ConcurrencyId
  FROM [CRM].[dbo].TPerson T6
  INNER JOIN [CRM].[dbo].TCRMContact T4
  ON T6.PersonId = T4.PersonId
  INNER JOIN TUser T1
  ON T4.CRMContactId = T1.CRMContactId

  WHERE (T1.UserId = @UserId)

  ORDER BY [User!1!UserId], [CRMContact!4!CRMContactId], [Person!6!PersonId], [RefUserType!3!RefUserTypeId], [Membership!2!MembershipId], [Role!5!RoleId]

  FOR XML EXPLICIT

END
RETURN (0)

GO
