SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[SpAliasRetrieveUserByContactId]
@CRMContactId bigint
AS

BEGIN
  SELECT
    1 AS Tag,
    NULL AS Parent,
    T1.UserId AS [User!1!UserId], 
    T1.Identifier AS [User!1!Identifier], 
    T1.Password AS [User!1!Password], 
    ISNULL(T1.PasswordHistory, '') AS [User!1!PasswordHistory], 
    T1.Email AS [User!1!Email], 
    ISNULL(T1.Telephone, '') AS [User!1!Telephone], 
    T1.Status AS [User!1!Status], 
    T1.GroupId AS [User!1!GroupId], 
    ISNULL(T1.SyncPassword, '') AS [User!1!SyncPassword], 
    ISNULL(CONVERT(varchar(24), T1.ExpirePasswordOn, 120),'') AS [User!1!ExpirePasswordOn], 
    T1.SuperUser AS [User!1!SuperUser], 
    T1.SuperViewer AS [User!1!SuperViewer], 
    T1.FailedAccessAttempts AS [User!1!FailedAccessAttempts], 
    T1.WelcomePage AS [User!1!WelcomePage], 
    ISNULL(T1.Reference, '') AS [User!1!Reference], 
    ISNULL(T1.CRMContactId, '') AS [User!1!CRMContactId], 
    NULL AS [User!1!SearchData], 
    NULL AS [User!1!RecentData], 
    NULL AS [User!1!RecentWork], 
    ISNULL(T1.IndigoClientId, '') AS [User!1!IndigoClientId], 
    T1.SupportUserFg AS [User!1!SupportUserFg], 
    ISNULL(T1.ActiveRole, '') AS [User!1!ActiveRole], 
    T1.CanLogCases AS [User!1!CanLogCases], 
    T1.RefUserTypeId AS [User!1!RefUserTypeId], 
    T1.Guid AS [User!1!Guid], 
    T1.ConcurrencyId AS [User!1!ConcurrencyId], 
    NULL AS [Membership!2!MembershipId], 
    NULL AS [Membership!2!UserId], 
    NULL AS [Membership!2!RoleId], 
    NULL AS [Membership!2!ConcurrencyId], 
    NULL AS [RefUserType!3!RefUserTypeId], 
    NULL AS [RefUserType!3!Identifier], 
    NULL AS [RefUserType!3!Url], 
    NULL AS [RefUserType!3!ConcurrencyId], 
    NULL AS [Group!4!GroupId], 
    NULL AS [Group!4!Identifier], 
    NULL AS [Group!4!GroupingId], 
    NULL AS [Group!4!ParentId], 
    NULL AS [Group!4!CRMContactId], 
    NULL AS [Group!4!IndigoClientId], 
    NULL AS [Group!4!LegalEntity], 
    NULL AS [Group!4!GroupImageLocation], 
    NULL AS [Group!4!AcknowledgementsLocation], 
    NULL AS [Group!4!FinancialYearEnd], 
    NULL AS [Group!4!ApplyFactFindBranding], 
    NULL AS [Group!4!VatRegNbr], 
    NULL AS [Group!4!ConcurrencyId], 
    NULL AS [IndigoClient!5!IndigoClientId], 
    NULL AS [IndigoClient!5!Identifier], 
    NULL AS [IndigoClient!5!Status], 
    NULL AS [IndigoClient!5!PrimaryContact], 
    NULL AS [IndigoClient!5!ContactId], 
    NULL AS [IndigoClient!5!PhoneNumber], 
    NULL AS [IndigoClient!5!EmailAddress], 
    NULL AS [IndigoClient!5!PrimaryGroupId], 
    NULL AS [IndigoClient!5!NetworkId], 
    NULL AS [IndigoClient!5!SIB], 
    NULL AS [IndigoClient!5!MCCB], 
    NULL AS [IndigoClient!5!FSA], 
    NULL AS [IndigoClient!5!IOProductType], 
    NULL AS [IndigoClient!5!ExpiryDate], 
    NULL AS [IndigoClient!5!AddressLine1], 
    NULL AS [IndigoClient!5!AddressLine2], 
    NULL AS [IndigoClient!5!AddressLine3], 
    NULL AS [IndigoClient!5!AddressLine4], 
    NULL AS [IndigoClient!5!CityTown], 
    NULL AS [IndigoClient!5!County], 
    NULL AS [IndigoClient!5!Postcode], 
    NULL AS [IndigoClient!5!Country], 
    NULL AS [IndigoClient!5!IsNetwork], 
    NULL AS [IndigoClient!5!SupportServiceId], 
    NULL AS [IndigoClient!5!FirmSize], 
    NULL AS [IndigoClient!5!Specialism], 
    NULL AS [IndigoClient!5!OtherSpecialism], 
    NULL AS [IndigoClient!5!SupportLevel], 
    NULL AS [IndigoClient!5!EmailSupOptn], 
    NULL AS [IndigoClient!5!SupportEmail], 
    NULL AS [IndigoClient!5!TelSupOptn], 
    NULL AS [IndigoClient!5!SupportTelephone], 
    NULL AS [IndigoClient!5!AllowPasswordEmail], 
    NULL AS [IndigoClient!5!SessionTimeout], 
    NULL AS [IndigoClient!5!LicenceType], 
    NULL AS [IndigoClient!5!MaxConUsers], 
    NULL AS [IndigoClient!5!MaxULAGCount], 
    NULL AS [IndigoClient!5!UADRestriction], 
    NULL AS [IndigoClient!5!MaxULADCount], 
    NULL AS [IndigoClient!5!AdviserCountRestrict], 
    NULL AS [IndigoClient!5!MaxAdviserCount], 
    NULL AS [IndigoClient!5!EmailFormat], 
    NULL AS [IndigoClient!5!UserNameFormat], 
    NULL AS [IndigoClient!5!NTDomain], 
    NULL AS [IndigoClient!5!IsIndependent], 
    NULL AS [IndigoClient!5!BrandDescriptor], 
    NULL AS [IndigoClient!5!ServiceLevel], 
    NULL AS [IndigoClient!5!HostingFg], 
    NULL AS [IndigoClient!5!CaseLoggingOption], 
    NULL AS [IndigoClient!5!Guid], 
    NULL AS [IndigoClient!5!RefEnvironmentId], 
    NULL AS [IndigoClient!5!IsPortfolioConstructionProvider], 
    NULL AS [IndigoClient!5!IsAuthorProvider], 
    NULL AS [IndigoClient!5!ConcurrencyId], 
    NULL AS [Role!6!RoleId], 
    NULL AS [Role!6!Identifier], 
    NULL AS [Role!6!GroupingId], 
    NULL AS [Role!6!SuperUser], 
    NULL AS [Role!6!IndigoClientId], 
    NULL AS [Role!6!LicensedUserCount], 
    NULL AS [Role!6!Dashboard], 
    NULL AS [Role!6!ShowGroupDashboard], 
    NULL AS [Role!6!ConcurrencyId], 
    NULL AS [Grouping!7!GroupingId], 
    NULL AS [Grouping!7!Identifier], 
    NULL AS [Grouping!7!ParentId], 
    NULL AS [Grouping!7!IsPayable], 
    NULL AS [Grouping!7!IndigoClientId], 
    NULL AS [Grouping!7!ConcurrencyId]
  FROM TUser T1

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    2 AS Tag,
    1 AS Parent,
    T1.UserId, 
    T1.Identifier, 
    T1.Password, 
    ISNULL(T1.PasswordHistory, ''), 
    T1.Email, 
    ISNULL(T1.Telephone, ''), 
    T1.Status, 
    T1.GroupId, 
    ISNULL(T1.SyncPassword, ''), 
    ISNULL(CONVERT(varchar(24), T1.ExpirePasswordOn, 120),''), 
    T1.SuperUser, 
    T1.SuperViewer, 
    T1.FailedAccessAttempts, 
    T1.WelcomePage, 
    ISNULL(T1.Reference, ''), 
    ISNULL(T1.CRMContactId, ''), 
    NULL, 
    NULL, 
    NULL, 
    ISNULL(T1.IndigoClientId, ''), 
    T1.SupportUserFg, 
    ISNULL(T1.ActiveRole, ''), 
    T1.CanLogCases, 
    T1.RefUserTypeId, 
    T1.Guid, 
    T1.ConcurrencyId, 
    T2.MembershipId, 
    T2.UserId, 
    T2.RoleId, 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TMembership T2
  INNER JOIN TUser T1
  ON T2.UserId = T1.UserId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    3 AS Tag,
    1 AS Parent,
    T1.UserId, 
    T1.Identifier, 
    T1.Password, 
    ISNULL(T1.PasswordHistory, ''), 
    T1.Email, 
    ISNULL(T1.Telephone, ''), 
    T1.Status, 
    T1.GroupId, 
    ISNULL(T1.SyncPassword, ''), 
    ISNULL(CONVERT(varchar(24), T1.ExpirePasswordOn, 120),''), 
    T1.SuperUser, 
    T1.SuperViewer, 
    T1.FailedAccessAttempts, 
    T1.WelcomePage, 
    ISNULL(T1.Reference, ''), 
    ISNULL(T1.CRMContactId, ''), 
    NULL, 
    NULL, 
    NULL, 
    ISNULL(T1.IndigoClientId, ''), 
    T1.SupportUserFg, 
    ISNULL(T1.ActiveRole, ''), 
    T1.CanLogCases, 
    T1.RefUserTypeId, 
    T1.Guid, 
    T1.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T3.RefUserTypeId, 
    T3.Identifier, 
    T3.Url, 
    T3.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TRefUserType T3
  INNER JOIN TUser T1
  ON T3.RefUserTypeId = T1.RefUserTypeId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    4 AS Tag,
    1 AS Parent,
    T1.UserId, 
    T1.Identifier, 
    T1.Password, 
    ISNULL(T1.PasswordHistory, ''), 
    T1.Email, 
    ISNULL(T1.Telephone, ''), 
    T1.Status, 
    T1.GroupId, 
    ISNULL(T1.SyncPassword, ''), 
    ISNULL(CONVERT(varchar(24), T1.ExpirePasswordOn, 120),''), 
    T1.SuperUser, 
    T1.SuperViewer, 
    T1.FailedAccessAttempts, 
    T1.WelcomePage, 
    ISNULL(T1.Reference, ''), 
    ISNULL(T1.CRMContactId, ''), 
    NULL, 
    NULL, 
    NULL, 
    ISNULL(T1.IndigoClientId, ''), 
    T1.SupportUserFg, 
    ISNULL(T1.ActiveRole, ''), 
    T1.CanLogCases, 
    T1.RefUserTypeId, 
    T1.Guid, 
    T1.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T4.GroupId, 
    T4.Identifier, 
    T4.GroupingId, 
    ISNULL(T4.ParentId, ''), 
    ISNULL(T4.CRMContactId, ''), 
    T4.IndigoClientId, 
    T4.LegalEntity, 
    ISNULL(T4.GroupImageLocation, ''), 
    ISNULL(T4.AcknowledgementsLocation, ''), 
    ISNULL(CONVERT(varchar(24), T4.FinancialYearEnd, 120),''), 
    T4.ApplyFactFindBranding, 
    ISNULL(T4.VatRegNbr, ''), 
    T4.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TGroup T4
  INNER JOIN TUser T1
  ON T4.GroupId = T1.GroupId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    5 AS Tag,
    1 AS Parent,
    T1.UserId, 
    T1.Identifier, 
    T1.Password, 
    ISNULL(T1.PasswordHistory, ''), 
    T1.Email, 
    ISNULL(T1.Telephone, ''), 
    T1.Status, 
    T1.GroupId, 
    ISNULL(T1.SyncPassword, ''), 
    ISNULL(CONVERT(varchar(24), T1.ExpirePasswordOn, 120),''), 
    T1.SuperUser, 
    T1.SuperViewer, 
    T1.FailedAccessAttempts, 
    T1.WelcomePage, 
    ISNULL(T1.Reference, ''), 
    ISNULL(T1.CRMContactId, ''), 
    NULL, 
    NULL, 
    NULL, 
    ISNULL(T1.IndigoClientId, ''), 
    T1.SupportUserFg, 
    ISNULL(T1.ActiveRole, ''), 
    T1.CanLogCases, 
    T1.RefUserTypeId, 
    T1.Guid, 
    T1.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T5.IndigoClientId, 
    T5.Identifier, 
    T5.Status, 
    T5.PrimaryContact, 
    ISNULL(T5.ContactId, ''), 
    T5.PhoneNumber, 
    T5.EmailAddress, 
    ISNULL(T5.PrimaryGroupId, ''), 
    ISNULL(T5.NetworkId, ''), 
    ISNULL(T5.SIB, ''), 
    ISNULL(T5.MCCB, ''), 
    ISNULL(T5.FSA, ''), 
    T5.IOProductType, 
    CONVERT(varchar(24), T5.ExpiryDate, 120), 
    T5.AddressLine1, 
    ISNULL(T5.AddressLine2, ''), 
    ISNULL(T5.AddressLine3, ''), 
    ISNULL(T5.AddressLine4, ''), 
    ISNULL(T5.CityTown, ''), 
    ISNULL(T5.County, ''), 
    T5.Postcode, 
    T5.Country, 
    T5.IsNetwork, 
    ISNULL(T5.SupportServiceId, ''), 
    T5.FirmSize, 
    T5.Specialism, 
    ISNULL(T5.OtherSpecialism, ''), 
    T5.SupportLevel, 
    T5.EmailSupOptn, 
    T5.SupportEmail, 
    T5.TelSupOptn, 
    T5.SupportTelephone, 
    T5.AllowPasswordEmail, 
    T5.SessionTimeout, 
    T5.LicenceType, 
    ISNULL(T5.MaxConUsers, ''), 
    ISNULL(T5.MaxULAGCount, ''), 
    T5.UADRestriction, 
    ISNULL(T5.MaxULADCount, ''), 
    T5.AdviserCountRestrict, 
    ISNULL(T5.MaxAdviserCount, ''), 
    ISNULL(T5.EmailFormat, ''), 
    ISNULL(T5.UserNameFormat, ''), 
    ISNULL(T5.NTDomain, ''), 
    T5.IsIndependent, 
    ISNULL(T5.BrandDescriptor, ''), 
    ISNULL(T5.ServiceLevel, ''), 
    T5.HostingFg, 
    T5.CaseLoggingOption, 
    T5.Guid, 
    ISNULL(T5.RefEnvironmentId, ''), 
    T5.IsPortfolioConstructionProvider, 
    T5.IsAuthorProvider, 
    T5.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TIndigoClient T5
  INNER JOIN TUser T1
  ON T5.IndigoClientId = T1.IndigoClientId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    6 AS Tag,
    2 AS Parent,
    T1.UserId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T2.MembershipId, 
    T2.UserId, 
    T2.RoleId, 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T6.RoleId, 
    T6.Identifier, 
    T6.GroupingId, 
    T6.SuperUser, 
    T6.IndigoClientId, 
    T6.LicensedUserCount, 
    ISNULL(T6.Dashboard, ''), 
    ISNULL(T6.ShowGroupDashboard, ''), 
    T6.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TRole T6
  INNER JOIN TMembership T2
  ON T6.RoleId = T2.RoleId
  INNER JOIN TUser T1
  ON T2.UserId = T1.UserId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    7 AS Tag,
    4 AS Parent,
    T1.UserId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T4.GroupId, 
    T4.Identifier, 
    T4.GroupingId, 
    ISNULL(T4.ParentId, ''), 
    ISNULL(T4.CRMContactId, ''), 
    T4.IndigoClientId, 
    T4.LegalEntity, 
    ISNULL(T4.GroupImageLocation, ''), 
    ISNULL(T4.AcknowledgementsLocation, ''), 
    ISNULL(CONVERT(varchar(24), T4.FinancialYearEnd, 120),''), 
    T4.ApplyFactFindBranding, 
    ISNULL(T4.VatRegNbr, ''), 
    T4.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T7.GroupingId, 
    T7.Identifier, 
    ISNULL(T7.ParentId, ''), 
    T7.IsPayable, 
    T7.IndigoClientId, 
    T7.ConcurrencyId
  FROM TGrouping T7
  INNER JOIN TGroup T4
  ON T7.GroupingId = T4.GroupingId
  INNER JOIN TUser T1
  ON T4.GroupId = T1.GroupId

  WHERE (T1.CRMContactId = @CRMContactId)

  ORDER BY [User!1!UserId], [IndigoClient!5!IndigoClientId], [Group!4!GroupId], [Grouping!7!GroupingId], [RefUserType!3!RefUserTypeId], [Membership!2!MembershipId], [Role!6!RoleId]

  FOR XML EXPLICIT

END
RETURN (0)

GO
