SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[SpUpdateIndigoClientByIdAndConcurrencyId]
@KeyIndigoClientId bigint,
@KeyConcurrencyId int,
@StampUser varchar (255),
@Identifier varchar (64),
@Status varchar (24) = 'New',
@PrimaryContact varchar (128),
@ContactId bigint = NULL,
@PhoneNumber varchar (40),
@EmailAddress varchar (128),
@PrimaryGroupId bigint = NULL,
@NetworkId bigint = NULL,
@SIB varchar (24) = NULL,
@MCCB varchar (24) = NULL,
@IOProductType varchar (50),
@ExpiryDate datetime,
@AddressLine1 varchar (1000),
@AddressLine2 varchar (1000) = NULL,
@AddressLine3 varchar (1000) = NULL,
@AddressLine4 varchar (1000) = NULL,
@CityTown varchar (255) = NULL,
@County varchar (255) = NULL,
@Postcode varchar (20),
@Country varchar (128) = 'UK',
@IsNetwork bit = 0,
@SupportServiceId bigint = NULL,
@FirmSize varchar (50),
@Specialism varchar (128),
@OtherSpecialism varchar (128) = NULL,
@SupportLevel varchar (50),
@EmailSupOptn varchar (50),
@SupportEmail varchar (128),
@TelSupOptn varchar (50),
@SupportTelephone varchar (40),
@AllowPasswordEmail bit = 1,
@SessionTimeout int,
@LicenceType varchar (50),
@MaxConUsers bigint = NULL,
@MaxULAGCount bigint = NULL,
@UADRestriction bit,
@MaxULADCount bigint = NULL,
@AdviserCountRestrict bit,
@MaxAdviserCount bigint = NULL,
@MaxFinancialPlanningUsers bigint = NULL,
@EmailFormat varchar (128) = NULL,
@UserNameFormat varchar (24) = NULL,
@NTDomain varchar (255) = NULL,
@IsIndependent bit = 1,
@BrandDescriptor varchar (64) = NULL,
@ServiceLevel bigint = NULL,
@HostingFg bit = 0,
@CaseLoggingOption int = 0,
@Guid uniqueidentifier = NULL,
@RefEnvironmentId bigint = NULL,
@IsPortfolioConstructionProvider bit = 0,
@IsAuthorProvider bit = 0,
@IsAtrProvider bit = 0
AS

SET NOCOUNT ON

DECLARE @tx int
SELECT @tx = @@TRANCOUNT
IF @tx = 0 BEGIN TRANSACTION TX

BEGIN
  IF @Guid IS NULL SET @Guid = newid()
  INSERT INTO TIndigoClientAudit (
    Identifier, 
    Status, 
    PrimaryContact, 
    ContactId, 
    PhoneNumber, 
    EmailAddress, 
    PrimaryGroupId, 
    NetworkId, 
    SIB, 
    MCCB, 
    IOProductType, 
    ExpiryDate, 
    AddressLine1, 
    AddressLine2, 
    AddressLine3, 
    AddressLine4, 
    CityTown, 
    County, 
    Postcode, 
    Country, 
    IsNetwork, 
    SupportServiceId, 
    FirmSize, 
    Specialism, 
    OtherSpecialism, 
    SupportLevel, 
    EmailSupOptn, 
    SupportEmail, 
    TelSupOptn, 
    SupportTelephone, 
    AllowPasswordEmail, 
    SessionTimeout, 
    LicenceType, 
    MaxConUsers, 
    MaxULAGCount, 
    UADRestriction, 
    MaxULADCount, 
    AdviserCountRestrict, 
    MaxAdviserCount, 
    MaxFinancialPlanningUsers, 
    EmailFormat, 
    UserNameFormat, 
    NTDomain, 
    IsIndependent, 
    BrandDescriptor, 
    ServiceLevel, 
    HostingFg, 
    CaseLoggingOption, 
    Guid, 
    RefEnvironmentId, 
    IsPortfolioConstructionProvider, 
    IsAuthorProvider, 
    IsAtrProvider, 
    ConcurrencyId,
    IndigoClientId,
    StampAction,
    StampDateTime,
    StampUser)
  SELECT
    T1.Identifier, 
    T1.Status, 
    T1.PrimaryContact, 
    T1.ContactId, 
    T1.PhoneNumber, 
    T1.EmailAddress, 
    T1.PrimaryGroupId, 
    T1.NetworkId, 
    T1.SIB, 
    T1.MCCB, 
    T1.IOProductType, 
    T1.ExpiryDate, 
    T1.AddressLine1, 
    T1.AddressLine2, 
    T1.AddressLine3, 
    T1.AddressLine4, 
    T1.CityTown, 
    T1.County, 
    T1.Postcode, 
    T1.Country, 
    T1.IsNetwork, 
    T1.SupportServiceId, 
    T1.FirmSize, 
    T1.Specialism, 
    T1.OtherSpecialism, 
    T1.SupportLevel, 
    T1.EmailSupOptn, 
    T1.SupportEmail, 
    T1.TelSupOptn, 
    T1.SupportTelephone, 
    T1.AllowPasswordEmail, 
    T1.SessionTimeout, 
    T1.LicenceType, 
    T1.MaxConUsers, 
    T1.MaxULAGCount, 
    T1.UADRestriction, 
    T1.MaxULADCount, 
    T1.AdviserCountRestrict, 
    T1.MaxAdviserCount, 
    T1.MaxFinancialPlanningUsers, 
    T1.EmailFormat, 
    T1.UserNameFormat, 
    T1.NTDomain, 
    T1.IsIndependent, 
    T1.BrandDescriptor, 
    T1.ServiceLevel, 
    T1.HostingFg, 
    T1.CaseLoggingOption, 
    T1.Guid, 
    T1.RefEnvironmentId, 
    T1.IsPortfolioConstructionProvider, 
    T1.IsAuthorProvider, 
    T1.IsAtrProvider, 
    T1.ConcurrencyId,
    T1.IndigoClientId,
    'U',
    GetDate(),
    @StampUser

  FROM TIndigoClient T1

  WHERE (T1.IndigoClientId = @KeyIndigoClientId) AND 
        (T1.ConcurrencyId = @KeyConcurrencyId)
  UPDATE T1
  SET 
    T1.Identifier = @Identifier,
    T1.Status = @Status,
    T1.PrimaryContact = @PrimaryContact,
    T1.ContactId = @ContactId,
    T1.PhoneNumber = @PhoneNumber,
    T1.EmailAddress = @EmailAddress,
    T1.PrimaryGroupId = @PrimaryGroupId,
    T1.NetworkId = @NetworkId,
    T1.SIB = @SIB,
    T1.MCCB = @MCCB,
    T1.IOProductType = @IOProductType,
    T1.ExpiryDate = @ExpiryDate,
    T1.AddressLine1 = @AddressLine1,
    T1.AddressLine2 = @AddressLine2,
    T1.AddressLine3 = @AddressLine3,
    T1.AddressLine4 = @AddressLine4,
    T1.CityTown = @CityTown,
    T1.County = @County,
    T1.Postcode = @Postcode,
    T1.Country = @Country,
    T1.IsNetwork = @IsNetwork,
    T1.SupportServiceId = @SupportServiceId,
    T1.FirmSize = @FirmSize,
    T1.Specialism = @Specialism,
    T1.OtherSpecialism = @OtherSpecialism,
    T1.SupportLevel = @SupportLevel,
    T1.EmailSupOptn = @EmailSupOptn,
    T1.SupportEmail = @SupportEmail,
    T1.TelSupOptn = @TelSupOptn,
    T1.SupportTelephone = @SupportTelephone,
    T1.AllowPasswordEmail = @AllowPasswordEmail,
    T1.SessionTimeout = @SessionTimeout,
    T1.LicenceType = @LicenceType,
    T1.MaxConUsers = @MaxConUsers,
    T1.MaxULAGCount = @MaxULAGCount,
    T1.UADRestriction = @UADRestriction,
    T1.MaxULADCount = @MaxULADCount,
    T1.AdviserCountRestrict = @AdviserCountRestrict,
    T1.MaxAdviserCount = @MaxAdviserCount,
    T1.MaxFinancialPlanningUsers = @MaxFinancialPlanningUsers,
    T1.EmailFormat = @EmailFormat,
    T1.UserNameFormat = @UserNameFormat,
    T1.NTDomain = @NTDomain,
    T1.IsIndependent = @IsIndependent,
    T1.BrandDescriptor = @BrandDescriptor,
    T1.ServiceLevel = @ServiceLevel,
    T1.HostingFg = @HostingFg,
    T1.CaseLoggingOption = @CaseLoggingOption,
    T1.Guid = @Guid,
    T1.RefEnvironmentId = @RefEnvironmentId,
    T1.IsPortfolioConstructionProvider = @IsPortfolioConstructionProvider,
    T1.IsAuthorProvider = @IsAuthorProvider,
    T1.IsAtrProvider = @IsAtrProvider,
    T1.ConcurrencyId = T1.ConcurrencyId + 1
  FROM TIndigoClient T1

  WHERE (T1.IndigoClientId = @KeyIndigoClientId) AND 
        (T1.ConcurrencyId = @KeyConcurrencyId)

SELECT * FROM TIndigoClient [IndigoClient]
  WHERE ([IndigoClient].IndigoClientId = @KeyIndigoClientId) AND 
        ([IndigoClient].ConcurrencyId = @KeyConcurrencyId + 1)
 FOR XML AUTO

IF @@ERROR != 0 GOTO errh
IF @tx = 0 COMMIT TRANSACTION TX

END
RETURN (0)

errh:
  IF @tx = 0 ROLLBACK TRANSACTION TX
  RETURN (100)
GO
