SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SpCollideIndigoClientByIdAndConcurrencyId]
	@IndigoClientId bigint,
	@ConcurrencyId int

AS

BEGIN
	SELECT
		T1.IndigoClientId AS OriginalIndigoClientId, 
		T1.Identifier AS OriginalIdentifier, 
		T2.Identifier AS CurrentIdentifier, 
		T1.Status AS OriginalStatus, 
		T2.Status AS CurrentStatus, 
		T1.PrimaryContact AS OriginalPrimaryContact, 
		T2.PrimaryContact AS CurrentPrimaryContact, 
		T1.ContactId AS OriginalContactId, 
		T2.ContactId AS CurrentContactId, 
		T1.PhoneNumber AS OriginalPhoneNumber, 
		T2.PhoneNumber AS CurrentPhoneNumber, 
		T1.EmailAddress AS OriginalEmailAddress, 
		T2.EmailAddress AS CurrentEmailAddress, 
		T1.PrimaryGroupId AS OriginalPrimaryGroupId, 
		T2.PrimaryGroupId AS CurrentPrimaryGroupId, 
		T1.NetworkId AS OriginalNetworkId, 
		T2.NetworkId AS CurrentNetworkId, 
		T1.SIB AS OriginalSIB, 
		T2.SIB AS CurrentSIB, 
		T1.MCCB AS OriginalMCCB, 
		T2.MCCB AS CurrentMCCB, 
		T1.FSA AS OriginalFSA, 
		T2.FSA AS CurrentFSA, 
		T1.IOProductType AS OriginalIOProductType, 
		T2.IOProductType AS CurrentIOProductType, 
		T1.ExpiryDate AS OriginalExpiryDate, 
		T2.ExpiryDate AS CurrentExpiryDate, 
		T1.AddressLine1 AS OriginalAddressLine1, 
		T2.AddressLine1 AS CurrentAddressLine1, 
		T1.AddressLine2 AS OriginalAddressLine2, 
		T2.AddressLine2 AS CurrentAddressLine2, 
		T1.AddressLine3 AS OriginalAddressLine3, 
		T2.AddressLine3 AS CurrentAddressLine3, 
		T1.AddressLine4 AS OriginalAddressLine4, 
		T2.AddressLine4 AS CurrentAddressLine4, 
		T1.CityTown AS OriginalCityTown, 
		T2.CityTown AS CurrentCityTown, 
		T1.County AS OriginalCounty, 
		T2.County AS CurrentCounty, 
		T1.Postcode AS OriginalPostcode, 
		T2.Postcode AS CurrentPostcode, 
		T1.Country AS OriginalCountry, 
		T2.Country AS CurrentCountry, 
		T1.IsNetwork AS OriginalIsNetwork, 
		T2.IsNetwork AS CurrentIsNetwork, 
		T1.SupportServiceId AS OriginalSupportServiceId, 
		T2.SupportServiceId AS CurrentSupportServiceId, 
		T1.FirmSize AS OriginalFirmSize, 
		T2.FirmSize AS CurrentFirmSize, 
		T1.Specialism AS OriginalSpecialism, 
		T2.Specialism AS CurrentSpecialism, 
		T1.OtherSpecialism AS OriginalOtherSpecialism, 
		T2.OtherSpecialism AS CurrentOtherSpecialism, 
		T1.SupportLevel AS OriginalSupportLevel, 
		T2.SupportLevel AS CurrentSupportLevel, 
		T1.EmailSupOptn AS OriginalEmailSupOptn, 
		T2.EmailSupOptn AS CurrentEmailSupOptn, 
		T1.SupportEmail AS OriginalSupportEmail, 
		T2.SupportEmail AS CurrentSupportEmail, 
		T1.TelSupOptn AS OriginalTelSupOptn, 
		T2.TelSupOptn AS CurrentTelSupOptn, 
		T1.SupportTelephone AS OriginalSupportTelephone, 
		T2.SupportTelephone AS CurrentSupportTelephone, 
		T1.AllowPasswordEmail AS OriginalAllowPasswordEmail, 
		T2.AllowPasswordEmail AS CurrentAllowPasswordEmail, 
		T1.SessionTimeout AS OriginalSessionTimeout, 
		T2.SessionTimeout AS CurrentSessionTimeout, 
		T1.LicenceType AS OriginalLicenceType, 
		T2.LicenceType AS CurrentLicenceType, 
		T1.MaxConUsers AS OriginalMaxConUsers, 
		T2.MaxConUsers AS CurrentMaxConUsers, 
		T1.MaxULAGCount AS OriginalMaxULAGCount, 
		T2.MaxULAGCount AS CurrentMaxULAGCount, 
		T1.UADRestriction AS OriginalUADRestriction, 
		T2.UADRestriction AS CurrentUADRestriction, 
		T1.MaxULADCount AS OriginalMaxULADCount, 
		T2.MaxULADCount AS CurrentMaxULADCount, 
		T1.AdviserCountRestrict AS OriginalAdviserCountRestrict, 
		T2.AdviserCountRestrict AS CurrentAdviserCountRestrict, 
		T1.MaxAdviserCount AS OriginalMaxAdviserCount, 
		T2.MaxAdviserCount AS CurrentMaxAdviserCount, 
		T1.EmailFormat AS OriginalEmailFormat, 
		T2.EmailFormat AS CurrentEmailFormat, 
		T1.UserNameFormat AS OriginalUserNameFormat, 
		T2.UserNameFormat AS CurrentUserNameFormat, 
		T1.NTDomain AS OriginalNTDomain, 
		T2.NTDomain AS CurrentNTDomain, 
		T1.IsIndependent AS OriginalIsIndependent, 
		T2.IsIndependent AS CurrentIsIndependent, 
		T1.BrandDescriptor AS OriginalBrandDescriptor, 
		T2.BrandDescriptor AS CurrentBrandDescriptor, 
		T1.ServiceLevel AS OriginalServiceLevel, 
		T2.ServiceLevel AS CurrentServiceLevel, 
		T1.HostingFg AS OriginalHostingFg, 
		T2.HostingFg AS CurrentHostingFg, 
		T1.CaseLoggingOption AS OriginalCaseLoggingOption, 
		T2.CaseLoggingOption AS CurrentCaseLoggingOption, 
		T1.Guid AS OriginalGuid, 
		T2.Guid AS CurrentGuid, 
		T1.RefEnvironmentId AS OriginalRefEnvironmentId, 
		T2.RefEnvironmentId AS CurrentRefEnvironmentId, 
		T1.IsPortfolioConstructionProvider AS OriginalIsPortfolioConstructionProvider, 
		T2.IsPortfolioConstructionProvider AS CurrentIsPortfolioConstructionProvider, 
		T1.IsAuthorProvider AS OriginalIsAuthorProvider, 
		T2.IsAuthorProvider AS CurrentIsAuthorProvider, 
		T1.IsAtrProvider AS OriginalIsAtrProvider, 
		T2.IsAtrProvider AS CurrentIsAtrProvider, 
		T2.ConcurrencyId AS CurrentConcurrencyId
	FROM TIndigoClient T2
	LEFT OUTER JOIN TIndigoClientAudit T1
	ON T1.IndigoClientId = T2.IndigoClientId
	WHERE T1.IndigoClientId = @IndigoClientId AND T1.ConcurrencyId = @ConcurrencyId

END
RETURN (0)
GO
