CREATE TABLE [dbo].[TaskBackup]
(
[TaskId] [int] NOT NULL IDENTITY(1, 1),
[StartDate] [datetime] NULL,
[DueDate] [datetime] NULL,
[PercentComplete] [int] NOT NULL,
[Notes] [varchar] (8000) COLLATE Latin1_General_CI_AS NULL,
[AssignedUserId] [int] NULL,
[PerformedUserId] [int] NULL,
[AssignedToUserId] [int] NULL,
[AssignedToRoleId] [int] NULL,
[ReminderId] [int] NULL,
[Subject] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[RefPriorityId] [int] NULL,
[Other] [varchar] (8000) COLLATE Latin1_General_CI_AS NULL,
[PrivateFg] [tinyint] NULL,
[DateCompleted] [datetime] NULL,
[EstimatedTimeHrs] [int] NULL,
[EstimatedTimeMins] [int] NULL,
[ActualTimeHrs] [int] NULL,
[ActualTimeMins] [int] NULL,
[CRMContactId] [int] NULL,
[URL] [varchar] (500) COLLATE Latin1_General_CI_AS NULL,
[RefTaskStatusId] [int] NULL,
[ActivityOutcomeId] [int] NULL,
[SequentialRef] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[IndigoClientId] [int] NOT NULL,
[ReturnToRoleId] [int] NULL,
[ConcurrencyId] [int] NOT NULL
)
GO
