CREATE TABLE [dbo].[TMortgageOpportunity]
(
[MortgageOpportunityId] [int] NOT NULL IDENTITY(1, 1),
[OpportunityId] [int] NOT NULL,
[LoanPurpose] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[LoanAmount] [decimal] (10, 2) NULL,
[LTV] [decimal] (10, 2) NULL,
[RefMortgageBorrowerTypeId] [int] NULL,
[Term] [decimal] (15, 6) NULL,
[RefMortgageRepaymentMethodId] [int] NULL,
[InterestOnly] [decimal] (10, 2) NULL,
[Repayment] [decimal] (10, 2) NULL,
[Price] [decimal] (10, 2) NULL,
[Deposit] [decimal] (10, 2) NULL,
[PlanPurpose] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[CurrentLender] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CurrentLoanAmount] [decimal] (10, 2) NULL,
[MonthlyRentalIncome] [decimal] (10, 2) NULL,
[Owner] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[RelationshipCRMContactId] [int] NULL,
[EmploymentType] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[IncomeAmount] [decimal] (10, 2) NULL,
[RepaymentAmountMonthly] [decimal] (10, 2) NULL,
[StatusFg] [bit] NULL,
[SelfCertFg] [bit] NULL,
[NonStatusFg] [bit] NULL,
[ExPatFg] [bit] NULL,
[ForeignCitizenFg] [bit] NULL,
[TrueCostOverTerm] [int] NULL,
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF_TMortgageOpportunity_ConcurrencyId] DEFAULT ((1)),
[SourceOfDeposit] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[InterestOnlyRepaymentVehicle] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[RelatedAddressStoreId] [int] NULL,
[RepaymentOfExistingMortgage] [decimal] (10, 2) NULL,
[HomeImprovements] [decimal] (10, 2) NULL,
[MortgageFees] [decimal] (10, 2) NULL,
[Other] [decimal] (10, 2) NULL,
[GuarantorMortgageFg] [bit] NULL,
[GuarantorText] [varchar] (5000) COLLATE Latin1_General_CI_AS NULL,
[DebtConsolidatedFg] [bit] NULL,
[DebtConsolidationText] [varchar] (5000) COLLATE Latin1_General_CI_AS NULL,
[RepaymentTerm] [decimal] (15, 6) NULL,
[InterestOnlyTerm] [decimal] (15, 6) NULL,
[DebtConsolidation] [decimal] (18, 2) NULL,
[Details] [varchar] (5000) COLLATE Latin1_General_CI_AS NULL,
[InterestDetails] [varchar] (250) COLLATE Latin1_General_CI_AS NULL,
[RefMortgageSaleTypeId] [int] NULL,
[IsHighNetWorthClient] [bit] NULL,
[IsMortgageForBusiness] [bit] NULL,
[IsProfessionalClient] [bit] NULL,
[IsRejectedAdvice] [bit] NULL,
[ExecutionOnlyDetails] [varchar] (5000) COLLATE Latin1_General_CI_AS NULL,
[RefOpportunityType2ProdSubTypeId] [int] NULL,
[IsFirstTimeBuyer] [bit] NULL,
[RefEquityReleaseTypeId] [int] NULL,
[PercentageOwnershipSold] [decimal] (10, 2) NULL,
[LumpsumAmount] [decimal] (10, 2) NULL,
[MonthlyIncomeAmount] [decimal] (10, 2) NULL,
[RefAdverseCreditId] [int] NULL,
[RefOpportunityEmploymentTypeId] [int] NULL,
[CurrentLenderId] [int] NULL,
[EquityLoanPercentage] [decimal] (5,2) NULL,
[EquityLoanAmount] [money] NULL
)
GO
ALTER TABLE [dbo].[TMortgageOpportunity] ADD CONSTRAINT [PK_TMortgageOpportunity] PRIMARY KEY NONCLUSTERED  ([MortgageOpportunityId])
GO
ALTER TABLE [dbo].[TMortgageOpportunity] ADD CONSTRAINT [FK_TMortgageOpportunity_TOpportunity] FOREIGN KEY ([OpportunityId]) REFERENCES [dbo].[TOpportunity] ([OpportunityId])
GO
create index IX_TMortgageOpportunity_OpportunityId on TMortgageOpportunity (OpportunityId)
GO
