CREATE TABLE [dbo].[TCRMContactAudit_COPY]
(
[AuditId] [int] NOT NULL,
[RefCRMContactStatusId] [int] NULL,
[PersonId] [int] NULL,
[CorporateId] [int] NULL,
[TrustId] [int] NULL,
[AdvisorRef] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[RefSourceOfClientId] [int] NULL,
[SourceValue] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Notes] [varchar] (8000) COLLATE Latin1_General_CI_AS NULL,
[ArchiveFg] [tinyint] NULL,
[LastName] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[FirstName] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CorporateName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[DOB] [datetime] NULL,
[Postcode] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[OriginalAdviserCRMId] [int] NOT NULL,
[CurrentAdviserCRMId] [int] NOT NULL,
[CurrentAdviserName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[CRMContactType] [tinyint] NOT NULL,
[IndClientId] [int] NOT NULL,
[FactFindId] [int] NULL,
[InternalContactFG] [bit] NULL,
[RefServiceStatusId] [int] NULL,
[_ParentId] [int] NULL,
[_ParentTable] [varchar] (64) COLLATE Latin1_General_CI_AS NULL,
[_ParentDb] [varchar] (64) COLLATE Latin1_General_CI_AS NULL,
[_OwnerId] [int] NULL,
[MigrationRef] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[CreatedDate] [datetime] NOT NULL,
[ExternalReference] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[AdditionalRef] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CampaignDataId] [int] NULL,
[ConcurrencyId] [int] NOT NULL,
[CRMContactId] [int] NOT NULL,
[StampAction] [char] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[StampDateTime] [datetime] NULL,
[StampUser] [varchar] (255) COLLATE Latin1_General_CI_AS NULL
)
GO
