CREATE FUNCTION dbo.fn_parsevaluationerrors (@ErrorDescription varchar(1000))
RETURNS varchar(1000)
AS 
begin
	declare @errorcategory sysname
	select @errorcategory =
	case
	when ltrim(rtrim(@ErrorDescription)) like '%Provider system problem%' then 'Provider system problem'
	when ltrim(rtrim(@ErrorDescription)) like '%Provider unable to supply details of error%' then 'Provider unable to supply details of error'
	when ltrim(rtrim(@ErrorDescription)) like '%Contract not found%' then 'Contract not found'
	when ltrim(rtrim(@ErrorDescription)) like '%The Product Provider%system has encountered an internal error%' then 'The Product Providers system has encountered an internal error'
	when ltrim(rtrim(@ErrorDescription)) like '%Provider system problem%' then 'Provider system problem'
	when ltrim(rtrim(@ErrorDescription)) like '%Intermediary details are incorrect%' then 'Intermediary details are incorrect'
	when ltrim(rtrim(@ErrorDescription)) like '%User not recognized%' then 'User not recognized'
	when ltrim(rtrim(@ErrorDescription)) like '%Provider unable to supply details of error - Contract Enquiry request has failed %' then 'Provider unable to supply details of error - Contract Enquiry request has failed '
	when ltrim(rtrim(@ErrorDescription)) like '%Providers system not available, as it is outside the hours of operation%' then 'Providers system not available, as it is outside the hours of operation'
	when ltrim(rtrim(@ErrorDescription)) like '%online enquiry is not available for this policy%' then 'Online enquiry is not available for this policy'
	when ltrim(rtrim(@ErrorDescription)) like '%Message failed security check%' then 'Message failed security check'
	when ltrim(rtrim(@ErrorDescription)) like '%Invalid authorisation%' then 'Invalid authorisation'
	when ltrim(rtrim(@ErrorDescription)) like '%Service not available%' then 'Service not available'
	when ltrim(rtrim(@ErrorDescription)) like '%XML does not validate%' then 'XML does not validate'
	when ltrim(rtrim(@ErrorDescription)) like '%This contract cannot be accessed under contract enquiry%' then 'This contract cannot be accessed under contract enquiry'
	when ltrim(rtrim(@ErrorDescription)) like '%Contract reference not found%' then 'Contract reference not found'
	when ltrim(rtrim(@ErrorDescription)) like '%policy has been transferred%' then 'Policy has been transferred'
	when ltrim(rtrim(@ErrorDescription)) like '%Login ID for updates is blocked%' then 'Login ID for updates is blocked'
	when ltrim(rtrim(@ErrorDescription)) like '%You are not servicing agent%' then 'You are not servicing agent'
	when ltrim(rtrim(@ErrorDescription)) like '%Client Reference not found%' then 'E700 Client Reference not found'
	when ltrim(rtrim(@ErrorDescription)) like '%valuation is currently not available for this product%' then 'Valuation is currently not available for this product'
	when ltrim(rtrim(@ErrorDescription)) like '%Internal%Error%' then 'Internal Server Error'
	when ltrim(rtrim(@ErrorDescription)) like '%The user specified in the message header must have access to the servicing intermediary %' then 'The user specified in the message header must have access to the servicing intermediary '
	when ltrim(rtrim(@ErrorDescription)) like '%Plan is not In Force%' then 'Plan is not In Force'
	when ltrim(rtrim(@ErrorDescription)) like '%User not allowed access%' then 'User not allowed access'
	when ltrim(rtrim(@ErrorDescription)) like '%If the problem persists, please contact the helpdesk%' then 'If the problem persists, please contact the helpdesk'
	when ltrim(rtrim(@ErrorDescription)) like '%userLockedOut:%' then 'userLockedOut:'
	when ltrim(rtrim(@ErrorDescription)) like '%This policy has matured%' then 'This policy has matured'
	when ltrim(rtrim(@ErrorDescription)) like '%This policy has lapsed%' then 'This policy has lapsed'
	when ltrim(rtrim(@ErrorDescription)) like '%Failed to find PIN record%' then 'Failed to find PIN record'
	when ltrim(rtrim(@ErrorDescription)) like '%Contract undergoing alteration%' then 'Contract undergoing alteration'
	when ltrim(rtrim(@ErrorDescription)) like '%Plan%format not recognised%' then 'Plan no. format not recognised'
	when ltrim(rtrim(@ErrorDescription)) like '%If the problem persists, please contact the helpdesk %' then 'If the problem persists, please contact the helpdesk '
	when ltrim(rtrim(@ErrorDescription)) like '%User ID of the accessing intermediary/intermediary organisation must be a recognized%' then 'E005 User ID of the accessing intermediary/intermediary organisation must be a recognized'
	when ltrim(rtrim(@ErrorDescription)) like '%Enquiries%not%supported%' then 'Enquiries on this Product Type/Sub Type are not supported by Provider'
	when ltrim(rtrim(@ErrorDescription)) like '%Other%' then 'Other'
	when ltrim(rtrim(@ErrorDescription)) like '%This policy has been surrendered%' then 'This policy has been surrendered'
	when ltrim(rtrim(@ErrorDescription)) like '%XML does not validate against the schema%' then 'E505 XML does not validate against the schema'
	when ltrim(rtrim(@ErrorDescription)) like '%Intermediary not registered to make contract enquiries for this service%' then 'Intermediary not registered to make contract enquiries for this service'
	when ltrim(rtrim(@ErrorDescription)) like '%Period to retirement too short%' then 'Period to retirement too short'
	when ltrim(rtrim(@ErrorDescription)) like '%Fatal%error%' then 'Fatal Error'
	when ltrim(rtrim(@ErrorDescription)) like '%This policy has transferred%' then 'This policy has transferred'
	when ltrim(rtrim(@ErrorDescription)) like '%Access to requested clients) not permitted%' then '3000 - Access to requested clients) not permitted'
	when ltrim(rtrim(@ErrorDescription)) like '%Unable to get AgentId%' then '1000 Unable to get AgentId'
	when ltrim(rtrim(@ErrorDescription)) like '%There is a problem with your account%' then 'There is a problem with your account'
	when ltrim(rtrim(@ErrorDescription)) like '%For assistance with your account, please contact our Adviser Support Unit %' then 'For assistance with your account, please contact our Adviser Support Unit '
	when ltrim(rtrim(@ErrorDescription)) like '%In order to use this system, you need to accept Terms and Conditions%' then 'In order to use this system, you need to accept Terms and Conditions'
	when ltrim(rtrim(@ErrorDescription)) like '%Please visit the following site in order to do this: https://eservices.axawealth.co.uk/IFAValuations/Redirect.aspx%' then 'Please visit the following site in order to do this: https://eservices.axawealth.co.uk/IFAValuations/Redirect.aspx'
	when ltrim(rtrim(@ErrorDescription)) like '%This policyholder has died%' then 'This policyholder has died'
	when ltrim(rtrim(@ErrorDescription)) like '%noThirdPartyRelationship:%' then 'noThirdPartyRelationship:'
	when ltrim(rtrim(@ErrorDescription)) like '%An A004 form needs to be submitted before accessing the Remote Service with this provider%' then 'An A004 form needs to be submitted before accessing the Remote Service with this provider'
	when ltrim(rtrim(@ErrorDescription)) like '%This policy cannot be found%' then 'This policy cannot be found'
	when ltrim(rtrim(@ErrorDescription)) like '%Please ensure your records are correct, or contact our Adviser Support Unit%' then 'Please ensure your records are correct, or contact our Adviser Support Unit'
	when ltrim(rtrim(@ErrorDescription)) like '%Plan is not In Force - 83EE  FF%' then 'Plan is not In Force - 83EE  FF'
	when ltrim(rtrim(@ErrorDescription)) like '%CE0001%' then 'This service is currently unavailable.'
	when ltrim(rtrim(@ErrorDescription)) like '%CE0003%' then 'The Product Providers system has encountered an internal error.'
	when ltrim(rtrim(@ErrorDescription)) like '%CE0009%' then 'The policy number requested % is not in a valid format'
	when ltrim(rtrim(@ErrorDescription)) like '%CE0010%' then 'Message failed security check'
	when ltrim(rtrim(@ErrorDescription)) like '%CE0011%' then 'Our records indicate you do not have the correct terms of business for enquiry on policy'
	when ltrim(rtrim(@ErrorDescription)) like '%CE0020%' then 'Policy number % is for a product type unsupported by contract enquiry.'
	when ltrim(rtrim(@ErrorDescription)) like '%CE1004%' then 'The requested policy does not exist on the system expected'
	when ltrim(rtrim(@ErrorDescription)) like '%CE1005%' then 'A Member could not be found'
	when ltrim(rtrim(@ErrorDescription)) like '%CE1007%' then 'Because of the policy type, you cannot currently access this policy online'
	when ltrim(rtrim(@ErrorDescription)) like '%CE1008%' then 'We are sorry, this service is currently unavailable. Please try again later.'
	when ltrim(rtrim(@ErrorDescription)) like '%CE1017%' then 'You do not have enquiry access for this policy.'
	when ltrim(rtrim(@ErrorDescription)) like '%CE1018%' then 'We are unable to provide a contract enquiry for this policy.'
	when ltrim(rtrim(@ErrorDescription)) like '%CE1024%' then 'The policy number requested is currently unavailable online.'
	when ltrim(rtrim(@ErrorDescription)) like '%Response Status: 405%' then 'Method Not Allowed'
	when ltrim(rtrim(@ErrorDescription)) like '%Response Status: 403%' then 'Forbidden'
	when ltrim(rtrim(@ErrorDescription)) like '%Response Status: 503%' then 'Service Unavailable'
	when ltrim(rtrim(@ErrorDescription)) like '%Response Status: 500%' then 'Internal Server Error'
	when ltrim(rtrim(@ErrorDescription)) like '%Response Status: 302%' then 'Moved Temporarily'
	when ltrim(rtrim(@ErrorDescription)) like '%Response Status: 401%' then 'Authorization Required'
	when ltrim(rtrim(@ErrorDescription)) like '%Response Status: 400%' then 'Bad Request'
	when ltrim(rtrim(@ErrorDescription)) like '%Response Status: 401%' then 'Unauthorized'
	when ltrim(rtrim(@ErrorDescription)) like '%Response Status: 404%' then 'Not Found'
	when ltrim(rtrim(@ErrorDescription)) like '%Response Status: 502%' then 'Bad Gateway'
	when ltrim(rtrim(@ErrorDescription)) like '%Response Status: 500%' then 'No buffer space is supported.'
	when ltrim(rtrim(@ErrorDescription)) like '%Response Status: 503%' then 'Server Error'
	when ltrim(rtrim(@ErrorDescription)) like '%no "Holding" data%' then 'There is currently no Holding data for this plan'
	when ltrim(rtrim(@ErrorDescription)) like '%ValidateUser%' then 'ValidateUser failed'
	when ltrim(rtrim(@ErrorDescription)) like '%Invalid response%' then 'Invalid response'
	when ltrim(rtrim(@ErrorDescription)) like '%1000 Error%' then 'Agent is not authorised to View'
	when ltrim(rtrim(@ErrorDescription)) like '%not authorised to View%' then 'Agent is not authorised to View'
	when ltrim(rtrim(@ErrorDescription)) like '%http://www.origoservices.com%' then 'http://www.origoservices.com CECIVValuationResponse.xsd'
	when ltrim(rtrim(@ErrorDescription)) like '%non-wrapped account number%' then 'Wrapper Product indicated for non-wrapped account number'
	when ltrim(rtrim(@ErrorDescription)) like '%Passcode is required%' then 'Passcode is required or Invalid user ID'
	when ltrim(rtrim(@ErrorDescription)) like '%Invalid user ID%' then 'Passcode is required or Invalid user ID'
	when ltrim(rtrim(@ErrorDescription)) like '%Unable to retrieve agent code %' then 'Unable to retrieve agent code for Consultant'
	when ltrim(rtrim(@ErrorDescription)) like '%Only one head account was not found%' then 'Only 1 head acc. not found for ? and ClientID: ? Or account permission was denied'
	when ltrim(rtrim(@ErrorDescription)) like '%An error was returned from the third party%' then 'Third party error'
	when ltrim(rtrim(@ErrorDescription)) like '%Unrecognised Response%' then 'Unrecognised Response'
	when ltrim(rtrim(@ErrorDescription)) like '%valuation could not be obtained%' then 'Valuation could not be obtained'
	when ltrim(rtrim(@ErrorDescription)) like '%valuation could not be obtained%' then 'Valuation could not be obtained'
	when ltrim(rtrim(@ErrorDescription)) like '%Certificate Not Found%' then 'Certificate Not Found'
	when ltrim(rtrim(@ErrorDescription)) like '%Bad%Request%' then 'Bad Request'
	when ltrim(rtrim(@ErrorDescription)) like '%Unauthorized%' then 'Unauthorized'
	when ltrim(rtrim(@ErrorDescription)) like '%username%password%' then 'Username and Password'
	when ltrim(rtrim(@ErrorDescription)) like '%try%again%' then 'Check your details and try again'
	when ltrim(rtrim(@ErrorDescription)) like '%Access%not%permitted%' then 'Access not permitted'
	when ltrim(rtrim(@ErrorDescription)) like '%The policy holder has died%' then 'The policy holder has died'
	when ltrim(rtrim(@ErrorDescription)) like '%time%out%' then 'Timeout'
	when ltrim(rtrim(@ErrorDescription)) like '%Multiple%contracts%' then 'Multiple Contracts'
	when ltrim(rtrim(@ErrorDescription)) like '%First%logon%' then 'Firsttime logon, change password'
	when ltrim(rtrim(@ErrorDescription)) like '%not%registered%Intelliflo%' then 'Not registered for Intelliflo IO real time data download'
	else 'Other'
	end 
	RETURN @errorcategory
end

