SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[SpAliasRetrievePlanTypeForPolicyBusiness]
@PolicyBusinessId bigint
AS

BEGIN
  SELECT
    1 AS Tag,
    NULL AS Parent,
    T1.PolicyBusinessId AS [PolicyBusiness!1!PolicyBusinessId], 
    T1.PolicyDetailId AS [PolicyBusiness!1!PolicyDetailId], 
    ISNULL(T1.PolicyNumber, '') AS [PolicyBusiness!1!PolicyNumber], 
    T1.PractitionerId AS [PolicyBusiness!1!PractitionerId], 
    ISNULL(T1.ReplaceNotes, '') AS [PolicyBusiness!1!ReplaceNotes], 
    ISNULL(T1.TnCCoachId, '') AS [PolicyBusiness!1!TnCCoachId], 
    T1.AdviceTypeId AS [PolicyBusiness!1!AdviceTypeId], 
    T1.BestAdvicePanelUsedFG AS [PolicyBusiness!1!BestAdvicePanelUsedFG], 
    T1.WaiverDefermentPeriod AS [PolicyBusiness!1!WaiverDefermentPeriod], 
    T1.IndigoClientId AS [PolicyBusiness!1!IndigoClientId], 
    T1.SwitchFG AS [PolicyBusiness!1!SwitchFG], 
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), '') AS [PolicyBusiness!1!TotalRegularPremium], 
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), '') AS [PolicyBusiness!1!TotalLumpSum], 
    ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),'') AS [PolicyBusiness!1!MaturityDate], 
    ISNULL(T1.LifeCycleId, '') AS [PolicyBusiness!1!LifeCycleId], 
    ISNULL(CONVERT(varchar(24), T1.PolicyStartDate, 120),'') AS [PolicyBusiness!1!PolicyStartDate], 
    ISNULL(T1.PremiumType, '') AS [PolicyBusiness!1!PremiumType], 
    ISNULL(T1.AgencyNumber, '') AS [PolicyBusiness!1!AgencyNumber], 
    ISNULL(T1.ProviderAddress, '') AS [PolicyBusiness!1!ProviderAddress], 
    T1.OffPanelFg AS [PolicyBusiness!1!OffPanelFg], 
    ISNULL(T1.BaseCurrency, '') AS [PolicyBusiness!1!BaseCurrency], 
    ISNULL(CONVERT(varchar(24), T1.ExpectedPaymentDate, 120),'') AS [PolicyBusiness!1!ExpectedPaymentDate], 
    ISNULL(T1.ProductName, '') AS [PolicyBusiness!1!ProductName], 
    ISNULL(T1.InvestmentTypeId, '') AS [PolicyBusiness!1!InvestmentTypeId], 
    ISNULL(T1.RiskRating, '') AS [PolicyBusiness!1!RiskRating], 
    ISNULL(T1.SequentialRef, '') AS [PolicyBusiness!1!SequentialRef], 
    T1.ConcurrencyId AS [PolicyBusiness!1!ConcurrencyId], 
    ISNULL(TNote.Note, '') AS [PolicyBusiness!1!_note], 
    NULL AS [PolicyDetail!2!PolicyDetailId], 
    NULL AS [PolicyDetail!2!PlanDescriptionId], 
    NULL AS [PolicyDetail!2!TermYears], 
    NULL AS [PolicyDetail!2!WholeOfLifeFg], 
    NULL AS [PolicyDetail!2!LetterOfAuthorityFg], 
    NULL AS [PolicyDetail!2!ContractOutOfSERPSFg], 
    NULL AS [PolicyDetail!2!ContractOutStartDate], 
    NULL AS [PolicyDetail!2!ContractOutStopDate], 
    NULL AS [PolicyDetail!2!AssignedCRMContactId], 
    NULL AS [PolicyDetail!2!JoiningDate], 
    NULL AS [PolicyDetail!2!LeavingDate], 
    NULL AS [PolicyDetail!2!IndigoClientId], 
    NULL AS [PolicyDetail!2!ConcurrencyId], 
    NULL AS [PlanDescription!3!PlanDescriptionId], 
    NULL AS [PlanDescription!3!RefPlanType2ProdSubTypeId], 
    NULL AS [PlanDescription!3!RefProdProviderId], 
    NULL AS [PlanDescription!3!SchemeOwnerCRMContactId], 
    NULL AS [PlanDescription!3!SchemeStatus], 
    NULL AS [PlanDescription!3!SchemeNumber], 
    NULL AS [PlanDescription!3!SchemeName], 
    NULL AS [PlanDescription!3!SchemeStatusDate], 
    NULL AS [PlanDescription!3!SchemeSellingAdvisorPractitionerId], 
    NULL AS [PlanDescription!3!MaturityDate], 
    NULL AS [PlanDescription!3!ConcurrencyId], 
    NULL AS [RefPlanType2ProdSubType!4!RefPlanType2ProdSubTypeId], 
    NULL AS [RefPlanType2ProdSubType!4!RefPlanTypeId], 
    NULL AS [RefPlanType2ProdSubType!4!ProdSubTypeId], 
    NULL AS [RefPlanType2ProdSubType!4!DefaultCategory], 
    NULL AS [RefPlanType2ProdSubType!4!ConcurrencyId], 
    NULL AS [RefPlanType!5!RefPlanTypeId], 
    NULL AS [RefPlanType!5!PlanTypeName], 
    NULL AS [RefPlanType!5!WebPage], 
    NULL AS [RefPlanType!5!OrigoRef], 
    NULL AS [RefPlanType!5!QuoteRef], 
    NULL AS [RefPlanType!5!NBRef], 
    NULL AS [RefPlanType!5!RetireFg], 
    NULL AS [RefPlanType!5!RetireDate], 
    NULL AS [RefPlanType!5!FindFg], 
    NULL AS [RefPlanType!5!SchemeType], 
    NULL AS [RefPlanType!5!IsWrapperFg], 
    NULL AS [RefPlanType!5!AdditionalOwnersFg], 
    NULL AS [RefPlanType!5!ConcurrencyId]
  FROM TPolicyBusiness T1
  -- Note clause
  LEFT JOIN TPolicyBusinessNote TNote
  ON TNote.PolicyBusinessId = T1.PolicyBusinessId AND TNote.IsLatest=1

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    2 AS Tag,
    1 AS Parent,
    T1.PolicyBusinessId, 
    T1.PolicyDetailId, 
    ISNULL(T1.PolicyNumber, ''), 
    T1.PractitionerId, 
    ISNULL(T1.ReplaceNotes, ''), 
    ISNULL(T1.TnCCoachId, ''), 
    T1.AdviceTypeId, 
    T1.BestAdvicePanelUsedFG, 
    T1.WaiverDefermentPeriod, 
    T1.IndigoClientId, 
    T1.SwitchFG, 
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), ''), 
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), ''), 
    ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),''), 
    ISNULL(T1.LifeCycleId, ''), 
    ISNULL(CONVERT(varchar(24), T1.PolicyStartDate, 120),''), 
    ISNULL(T1.PremiumType, ''), 
    ISNULL(T1.AgencyNumber, ''), 
    ISNULL(T1.ProviderAddress, ''), 
    T1.OffPanelFg, 
    ISNULL(T1.BaseCurrency, ''), 
    ISNULL(CONVERT(varchar(24), T1.ExpectedPaymentDate, 120),''), 
    ISNULL(T1.ProductName, ''), 
    ISNULL(T1.InvestmentTypeId, ''), 
    ISNULL(T1.RiskRating, ''), 
    ISNULL(T1.SequentialRef, ''), 
    T1.ConcurrencyId, 
    NULL,
    T2.PolicyDetailId, 
    T2.PlanDescriptionId, 
    ISNULL(T2.TermYears, ''), 
    ISNULL(T2.WholeOfLifeFg, ''), 
    ISNULL(T2.LetterOfAuthorityFg, ''), 
    ISNULL(T2.ContractOutOfSERPSFg, ''), 
    ISNULL(CONVERT(varchar(24), T2.ContractOutStartDate, 120),''), 
    ISNULL(CONVERT(varchar(24), T2.ContractOutStopDate, 120),''), 
    ISNULL(T2.AssignedCRMContactId, ''), 
    ISNULL(CONVERT(varchar(24), T2.JoiningDate, 120),''), 
    ISNULL(CONVERT(varchar(24), T2.LeavingDate, 120),''), 
    T2.IndigoClientId, 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TPolicyDetail T2
  INNER JOIN TPolicyBusiness T1
  ON T2.PolicyDetailId = T1.PolicyDetailId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    3 AS Tag,
    2 AS Parent,
    T1.PolicyBusinessId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    T2.PolicyDetailId, 
    T2.PlanDescriptionId, 
    ISNULL(T2.TermYears, ''), 
    ISNULL(T2.WholeOfLifeFg, ''), 
    ISNULL(T2.LetterOfAuthorityFg, ''), 
    ISNULL(T2.ContractOutOfSERPSFg, ''), 
    ISNULL(CONVERT(varchar(24), T2.ContractOutStartDate, 120),''), 
    ISNULL(CONVERT(varchar(24), T2.ContractOutStopDate, 120),''), 
    ISNULL(T2.AssignedCRMContactId, ''), 
    ISNULL(CONVERT(varchar(24), T2.JoiningDate, 120),''), 
    ISNULL(CONVERT(varchar(24), T2.LeavingDate, 120),''), 
    T2.IndigoClientId, 
    T2.ConcurrencyId, 
    T3.PlanDescriptionId, 
    T3.RefPlanType2ProdSubTypeId, 
    T3.RefProdProviderId, 
    ISNULL(T3.SchemeOwnerCRMContactId, ''), 
    ISNULL(T3.SchemeStatus, ''), 
    ISNULL(T3.SchemeNumber, ''), 
    ISNULL(T3.SchemeName, ''), 
    ISNULL(CONVERT(varchar(24), T3.SchemeStatusDate, 120),''), 
    ISNULL(T3.SchemeSellingAdvisorPractitionerId, ''), 
    ISNULL(CONVERT(varchar(24), T3.MaturityDate, 120),''), 
    T3.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TPlanDescription T3
  INNER JOIN TPolicyDetail T2
  ON T3.PlanDescriptionId = T2.PlanDescriptionId
  INNER JOIN TPolicyBusiness T1
  ON T2.PolicyDetailId = T1.PolicyDetailId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    4 AS Tag,
    3 AS Parent,
    T1.PolicyBusinessId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    T2.PolicyDetailId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T3.PlanDescriptionId, 
    T3.RefPlanType2ProdSubTypeId, 
    T3.RefProdProviderId, 
    ISNULL(T3.SchemeOwnerCRMContactId, ''), 
    ISNULL(T3.SchemeStatus, ''), 
    ISNULL(T3.SchemeNumber, ''), 
    ISNULL(T3.SchemeName, ''), 
    ISNULL(CONVERT(varchar(24), T3.SchemeStatusDate, 120),''), 
    ISNULL(T3.SchemeSellingAdvisorPractitionerId, ''), 
    ISNULL(CONVERT(varchar(24), T3.MaturityDate, 120),''), 
    T3.ConcurrencyId, 
    T4.RefPlanType2ProdSubTypeId, 
    T4.RefPlanTypeId, 
    ISNULL(T4.ProdSubTypeId, ''), 
    ISNULL(T4.DefaultCategory, ''), 
    T4.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TRefPlanType2ProdSubType T4
  INNER JOIN TPlanDescription T3
  ON T4.RefPlanType2ProdSubTypeId = T3.RefPlanType2ProdSubTypeId
  INNER JOIN TPolicyDetail T2
  ON T3.PlanDescriptionId = T2.PlanDescriptionId
  INNER JOIN TPolicyBusiness T1
  ON T2.PolicyDetailId = T1.PolicyDetailId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    5 AS Tag,
    4 AS Parent,
    T1.PolicyBusinessId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    T2.PolicyDetailId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T3.PlanDescriptionId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T4.RefPlanType2ProdSubTypeId, 
    T4.RefPlanTypeId, 
    ISNULL(T4.ProdSubTypeId, ''), 
    ISNULL(T4.DefaultCategory, ''), 
    T4.ConcurrencyId, 
    T5.RefPlanTypeId, 
    T5.PlanTypeName, 
    ISNULL(T5.WebPage, ''), 
    ISNULL(T5.OrigoRef, ''), 
    ISNULL(T5.QuoteRef, ''), 
    ISNULL(T5.NBRef, ''), 
    ISNULL(T5.RetireFg, ''), 
    ISNULL(CONVERT(varchar(24), T5.RetireDate, 120),''), 
    ISNULL(T5.FindFg, ''), 
    T5.SchemeType, 
    ISNULL(T5.IsWrapperFg, ''), 
    T5.AdditionalOwnersFg, 
    T5.ConcurrencyId
  FROM TRefPlanType T5
  INNER JOIN TRefPlanType2ProdSubType T4
  ON T5.RefPlanTypeId = T4.RefPlanTypeId
  INNER JOIN TPlanDescription T3
  ON T4.RefPlanType2ProdSubTypeId = T3.RefPlanType2ProdSubTypeId
  INNER JOIN TPolicyDetail T2
  ON T3.PlanDescriptionId = T2.PlanDescriptionId
  INNER JOIN TPolicyBusiness T1
  ON T2.PolicyDetailId = T1.PolicyDetailId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  ORDER BY [PolicyBusiness!1!PolicyBusinessId], [PolicyDetail!2!PolicyDetailId], [PlanDescription!3!PlanDescriptionId], [RefPlanType2ProdSubType!4!RefPlanType2ProdSubTypeId], [RefPlanType!5!RefPlanTypeId]

  FOR XML EXPLICIT

END
RETURN (0)

GO
