SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SpCustomRetrievePolicyBusinessDetailsByPolicyBusinessId]
 @PolicyBusinessId bigint    
AS    
    
BEGIN    
SELECT    
    1 AS Tag,    
    NULL AS Parent,    
    T1.PolicyBusinessId AS [PolicyBusiness!1!PolicyBusinessId],     
    T1.PolicyDetailId AS [PolicyBusiness!1!PolicyDetailId],     
    ISNULL(T1.PolicyNumber, '') AS [PolicyBusiness!1!PolicyNumber],     
    T1.PractitionerId AS [PolicyBusiness!1!PractitionerId],     
    ISNULL(T1.ReplaceNotes, '') AS [PolicyBusiness!1!ReplaceNotes],     
    ISNULL(T1.TnCCoachId, '') AS [PolicyBusiness!1!TnCCoachId],     
    T1.AdviceTypeId AS [PolicyBusiness!1!AdviceTypeId],     
    T1.BestAdvicePanelUsedFG AS [PolicyBusiness!1!BestAdvicePanelUsedFG],     
    T1.WaiverDefermentPeriod AS [PolicyBusiness!1!WaiverDefermentPeriod],     
    T1.IndigoClientId AS [PolicyBusiness!1!IndigoClientId],     
    T1.SwitchFG AS [PolicyBusiness!1!SwitchFG],     
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), '') AS [PolicyBusiness!1!TotalRegularPremium],     
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), '') AS [PolicyBusiness!1!TotalLumpSum],     
    ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),'') AS [PolicyBusiness!1!MaturityDate],     
    ISNULL(CONVERT(varchar(24), T1.PolicyStartDate, 120), '') AS [PolicyBusiness!1!PolicyStartDate],     
    ISNULL(T1.PremiumType, '') AS [PolicyBusiness!1!PremiumType],     
    ISNULL(T1.SequentialRef, '') AS [PolicyBusiness!1!SequentialRef],     
    ISNULL(T1.AgencyNumber, '') AS [PolicyBusiness!1!AgencyNumber],     
    ISNULL(T1.ProviderAddress, '') AS [PolicyBusiness!1!ProviderAddress],     
    T1.OffPanelFg AS [PolicyBusiness!1!OffPanelFg],    
    ISNULL(T1.BaseCurrency, '') AS [PolicyBusiness!1!BaseCurrency],    
    T1.ExpectedPaymentDate AS [PolicyBusiness!1!ExpectedPaymentDate],    
	T1.ProductName AS [PolicyBusiness!1!ProductName],   
	ISNULL(wrapProv.WrapAllowOtherProvidersFg, 0)  AS [PolicyBusiness!1!WrapAllowOtherProvidersFg],   
    T1.ConcurrencyId AS [PolicyBusiness!1!ConcurrencyId],     
    ISNULL(TNote.Note, '') AS [PolicyBusiness!1!_note],     
    NULL AS [PolicyDetail!2!PolicyDetailId],     
    NULL AS [PolicyDetail!2!PlanDescriptionId],     
    NULL AS [PolicyDetail!2!TermYears],     
    NULL AS [PolicyDetail!2!WholeOfLifeFg],     
    NULL AS [PolicyDetail!2!LetterOfAuthorityFg],     
    NULL AS [PolicyDetail!2!ContractOutOfSERPSFg],     
    NULL AS [PolicyDetail!2!ContractOutStartDate],     
    NULL AS [PolicyDetail!2!ContractOutStopDate],     
    NULL AS [PolicyDetail!2!AssignedCRMContactId],     
    NULL AS [PolicyDetail!2!JoiningDate],     
    NULL AS [PolicyDetail!2!LeavingDate],     
    NULL AS [PolicyDetail!2!IndigoClientId],     
    NULL AS [PolicyDetail!2!ConcurrencyId],     
    NULL AS [AdviceType!3!AdviceTypeId],     
    NULL AS [AdviceType!3!Description],     
    NULL AS [AdviceType!3!IntelligentOfficeAdviceType],     
    NULL AS [AdviceType!3!ArchiveFg],     
    NULL AS [AdviceType!3!IndigoClientId],     
    NULL AS [AdviceType!3!ConcurrencyId],     
    NULL AS [Practitioner!4!PractitionerId],     
    NULL AS [Practitioner!4!IndClientId],     
    NULL AS [Practitioner!4!PersonId],     
    NULL AS [Practitioner!4!CRMContactId],     
    NULL AS [Practitioner!4!TnCCoachId],     
    NULL AS [Practitioner!4!AuthorisedFG],     
    NULL AS [Practitioner!4!PIARef],     
    NULL AS [Practitioner!4!AuthorisedDate],     
    NULL AS [Practitioner!4!ExperienceLevel],     
    NULL AS [Practitioner!4!ConcurrencyId],     
    NULL AS [StatusHistory!5!StatusHistoryId],     
    NULL AS [StatusHistory!5!PolicyBusinessId],     
    NULL AS [StatusHistory!5!StatusId],     
    NULL AS [StatusHistory!5!StatusReasonId],     
    NULL AS [StatusHistory!5!ChangedToDate],     
    NULL AS [StatusHistory!5!ChangedByUserId],     
    NULL AS [StatusHistory!5!DateOfChange],     
    NULL AS [StatusHistory!5!LifeCycleStepFG],     
    NULL AS [StatusHistory!5!ConcurrencyId],     
    NULL AS [PolicyBusinessAttribute!6!PolicyBusinessAttributeId],     
    NULL AS [PolicyBusinessAttribute!6!AttributeValue],     
    NULL AS [PolicyBusinessAttribute!6!PolicyBusinessId],     
    NULL AS [PolicyBusinessAttribute!6!AttributeList2AttributeId],     
    NULL AS [PolicyBusinessAttribute!6!ConcurrencyId],     
	NULL AS [PlanDescription!7!PlanDescriptionId],     
    NULL AS [PlanDescription!7!RefPlanType2ProdSubTypeId],     
	NULL AS [PlanDescription!7!RefPlanTypeId],    
    NULL AS [PlanDescription!7!RefProdProviderId],     
    NULL AS [PlanDescription!7!SchemeOwnerCRMContactId],     
    NULL AS [PlanDescription!7!SchemeStatus],     
    NULL AS [PlanDescription!7!SchemeNumber],     
    NULL AS [PlanDescription!7!SchemeName],     
    NULL AS [PlanDescription!7!SchemeStatusDate],     
    NULL AS [PlanDescription!7!SchemeSellingAdvisorPractitionerId],     
    NULL AS [PlanDescription!7!ConcurrencyId],     
    NULL AS [PolicyOwner!8!PolicyOwnerId],     
    NULL AS [PolicyOwner!8!CRMContactId],     
    NULL AS [PolicyOwner!8!PolicyDetailId],     
    NULL AS [PolicyOwner!8!ConcurrencyId],     
    NULL AS [Owner!9!CRMContactId],     
    NULL AS [Owner!9!RefCRMContactStatusId],     
    NULL AS [Owner!9!PersonId],     
    NULL AS [Owner!9!CorporateId],     
    NULL AS [Owner!9!TrustId],     
    NULL AS [Owner!9!AdvisorRef],     
--    NULL AS [Owner!9!RefSourceOfClientId],     
--    NULL AS [Owner!9!SourceValue],     
    NULL AS [Owner!9!Notes],     
    NULL AS [Owner!9!ArchiveFg],     
    NULL AS [Owner!9!LastName],     
    NULL AS [Owner!9!FirstName],     
    NULL AS [Owner!9!CorporateName],     
    NULL AS [Owner!9!DOB],     
    NULL AS [Owner!9!Postcode],     
    NULL AS [Owner!9!OriginalAdviserCRMId],     
    NULL AS [Owner!9!CurrentAdviserCRMId],     
    NULL AS [Owner!9!CurrentAdviserName],     
    NULL AS [Owner!9!CRMContactType],     
    NULL AS [Owner!9!IndClientId],     
    NULL AS [Owner!9!FactFindId],     
    NULL AS [Owner!9!InternalContactFG],     
    NULL AS [Owner!9!RefServiceStatusId],     
    NULL AS [Owner!9!MigrationRef],     
    NULL AS [Owner!9!ConcurrencyId],     
    NULL AS [Adviser!10!CRMContactId],     
    NULL AS [Adviser!10!RefCRMContactStatusId],     
    NULL AS [Adviser!10!PersonId],     
    NULL AS [Adviser!10!CorporateId],     
    NULL AS [Adviser!10!TrustId],     
    NULL AS [Adviser!10!AdvisorRef],     
--  NULL AS [Adviser!10!RefSourceOfClientId],     
--    NULL AS [Adviser!10!SourceValue],     
    NULL AS [Adviser!10!Notes],     
    NULL AS [Adviser!10!ArchiveFg],     
    NULL AS [Adviser!10!LastName],     
    NULL AS [Adviser!10!FirstName],     
    NULL AS [Adviser!10!FirstNameAndLastName],     
    NULL AS [Adviser!10!CorporateName],     
    NULL AS [Adviser!10!DOB],     
    NULL AS [Adviser!10!Postcode],     
    NULL AS [Adviser!10!OriginalAdviserCRMId],     
    NULL AS [Adviser!10!CurrentAdviserCRMId],     
    NULL AS [Adviser!10!CurrentAdviserName],     
    NULL AS [Adviser!10!CRMContactType],     
    NULL AS [Adviser!10!IndClientId],     
    NULL AS [Adviser!10!FactFindId],     
    NULL AS [Adviser!10!InternalContactFG],     
    NULL AS [Adviser!10!RefServiceStatusId],     
    NULL AS [Adviser!10!MigrationRef],     
    NULL AS [Adviser!10!ConcurrencyId],     
    NULL AS [Status!11!StatusId],     
    NULL AS [Status!11!Name],     
    NULL AS [Status!11!OrigoStatusId],     
    NULL AS [Status!11!IntelligentOfficeStatusType],     
    NULL AS [Status!11!IndigoClientId],     
    NULL AS [Status!11!ConcurrencyId],     
    NULL AS [AttributeList2Attribute!12!AttributeList2AttributeId],     
    NULL AS [AttributeList2Attribute!12!AttributeListId],     
    NULL AS [AttributeList2Attribute!12!AttributeId],     
    NULL AS [AttributeList2Attribute!12!ConcurrencyId],     
    NULL AS [Attribute!13!AttributeId],     
    NULL AS [Attribute!13!Value],     
    NULL AS [Attribute!13!ConcurrencyId],     
    NULL AS [AttributeList!14!AttributeListId],     
    NULL AS [AttributeList!14!Name],     
    NULL AS [AttributeList!14!Type],     
    NULL AS [AttributeList!14!ConcurrencyId]    
  FROM 
	TPolicyBusiness T1    
	INNER JOIN TPOlicyDetail pDet ON T1.PolicyDetailId = pDet.PolicyDetailId    
	INNER JOIN TPlanDescription pDesc ON pDet.PlanDescriptionId = pDesc.PlanDescriptionId    
	JOIN PolicyManagement..TRefPlanType2ProdSubType Plan2Prod ON Plan2Prod.RefPlanType2ProdSubTypeId = pDesc.RefPlanType2ProdSubTypeId
	JOIN PolicyManagement..TRefPlanType PType ON PType.RefPlanTypeId = Plan2Prod.RefPlanTypeId
	LEFT JOIN TWrapperProvider wrapProv ON pDesc.RefProdProviderId = wrapProv.RefProdProviderId AND PType.RefPlanTypeId = wrapProv.RefPlanTypeId
	-- Note clause    
	LEFT JOIN  (
		SELECT T1.Note, TNote1.PolicyBusinessId    
		FROM 
			TPolicyBusinessNote T1     
			JOIN (
				SELECT 
					MAX(PolicyBusinessNoteId) AS PolicyBusinessNoteId,     
					PolicyBusinessId    
				FROM 
					TPolicyBusinessNote     
				WHERE 
					PolicyBusinessId  = @PolicyBusinessId     
				GROUP BY 
					PolicyBusinessId) AS TNote1 ON TNote1.PolicyBusinessNoteId = T1.PolicyBusinessNoteId
		) As TNote ON TNote.PolicyBusinessId = T1.PolicyBusinessId        
  WHERE 
		(T1.PolicyBusinessId = @PolicyBusinessId)    
    
  UNION ALL    
    
  SELECT    
    2 AS Tag,    
    1 AS Parent,    
    T1.PolicyBusinessId,     
    T1.PolicyDetailId,     
    ISNULL(T1.PolicyNumber, ''),     
    T1.PractitionerId,     
    ISNULL(T1.ReplaceNotes, ''),     
    ISNULL(T1.TnCCoachId, ''),     
    T1.AdviceTypeId,     
    T1.BestAdvicePanelUsedFG,     
    T1.WaiverDefermentPeriod,     
    T1.IndigoClientId,     
    T1.SwitchFG,     
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), ''),     
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), ''),     
   ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),'') AS [PolicyBusiness!1!MaturityDate],     
    ISNULL(CONVERT(varchar(24), T1.PolicyStartDate, 120), '') AS [PolicyBusiness!1!PolicyStartDate],     
    ISNULL(T1.PremiumType, '') AS [PolicyBusiness!1!PremiumType],     
    ISNULL(T1.SequentialRef, ''),     
    ISNULL(T1.AgencyNumber, ''),     
    ISNULL(T1.ProviderAddress, ''),     
    T1.OffPanelFg,    
    T1.BaseCurrency,    
    T1.ExpectedPaymentDate,    
 T1.ProductName,   
 NULL,   
    T1.ConcurrencyId,     
    NULL,    
    T2.PolicyDetailId,     
    T2.PlanDescriptionId,     
    ISNULL(T2.TermYears, ''),     
    ISNULL(T2.WholeOfLifeFg, ''),     
    ISNULL(T2.LetterOfAuthorityFg, ''),     
    ISNULL(T2.ContractOutOfSERPSFg, ''),     
    ISNULL(CONVERT(varchar(24), T2.ContractOutStartDate, 120),''),     
    ISNULL(CONVERT(varchar(24), T2.ContractOutStopDate, 120),''),     
    ISNULL(T2.AssignedCRMContactId, ''),     
    ISNULL(CONVERT(varchar(24), T2.JoiningDate, 120),''),     
    ISNULL(CONVERT(varchar(24), T2.LeavingDate, 120),''),     
    T2.IndigoClientId,     
    T2.ConcurrencyId,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
 NULL,  
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
 NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL    
  FROM TPolicyDetail T2    
    
  INNER JOIN TPolicyBusiness T1    
  ON T2.PolicyDetailId = T1.PolicyDetailId    
    
  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)    
    
  UNION ALL    
    
  SELECT    
    3 AS Tag,    
    1 AS Parent,    
    T1.PolicyBusinessId,     
    T1.PolicyDetailId,     
    ISNULL(T1.PolicyNumber, ''),     
    T1.PractitionerId,     
    ISNULL(T1.ReplaceNotes, ''),     
    ISNULL(T1.TnCCoachId, ''),     
    T1.AdviceTypeId,     
    T1.BestAdvicePanelUsedFG,     
    T1.WaiverDefermentPeriod,     
    T1.IndigoClientId,     
    T1.SwitchFG,     
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), ''),     
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), ''),     
ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),'') AS [PolicyBusiness!1!MaturityDate],     
    ISNULL(CONVERT(varchar(24), T1.PolicyStartDate, 120), '') AS [PolicyBusiness!1!PolicyStartDate],     
    ISNULL(T1.PremiumType, '') AS [PolicyBusiness!1!PremiumType],     
    ISNULL(T1.SequentialRef, ''),     
    ISNULL(T1.AgencyNumber, ''),     
    ISNULL(T1.ProviderAddress, ''),     
    T1.OffPanelFg,    
    T1.BaseCurrency,    
    T1.ExpectedPaymentDate,    
 T1.ProductName,   
 NULL,   
    T1.ConcurrencyId,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    T3.AdviceTypeId,     
    T3.Description,     
    T3.IntelligentOfficeAdviceType,     
    T3.ArchiveFg,     
    T3.IndigoClientId,     
    T3.ConcurrencyId,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
 NULL,    
 NULL,  
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL    
  FROM TAdviceType T3    
    
  INNER JOIN TPolicyBusiness T1    
  ON T3.AdviceTypeId = T1.AdviceTypeId    
    
  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)    
    
  UNION ALL    
    
  SELECT    
    4 AS Tag,    
    1 AS Parent,    
    T1.PolicyBusinessId,     
    T1.PolicyDetailId,     
    ISNULL(T1.PolicyNumber, ''),     
    T1.PractitionerId,     
    ISNULL(T1.ReplaceNotes, ''),     
    ISNULL(T1.TnCCoachId, ''),     
    T1.AdviceTypeId,     
    T1.BestAdvicePanelUsedFG,     
    T1.WaiverDefermentPeriod,     
    T1.IndigoClientId,     
    T1.SwitchFG,     
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), ''),     
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), ''),     
ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),'') AS [PolicyBusiness!1!MaturityDate],     
    ISNULL(CONVERT(varchar(24), T1.PolicyStartDate, 120), '') AS [PolicyBusiness!1!PolicyStartDate],     
    ISNULL(T1.PremiumType, '') AS [PolicyBusiness!1!PremiumType],     
    ISNULL(T1.AgencyNumber, ''),     
    ISNULL(T1.ProviderAddress, ''),     
    ISNULL(T1.SequentialRef, ''),     
    T1.OffPanelFg,    
    T1.BaseCurrency,    
    T1.ExpectedPaymentDate,    
 T1.ProductName,    
    NULL,  
    T1.ConcurrencyId,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    T4.PractitionerId,     
    T4.IndClientId,     
    ISNULL(T4.PersonId, ''),     
    ISNULL(T4.CRMContactId, ''),     
    ISNULL(T4.TnCCoachId, ''),     
    T4.AuthorisedFG,     
    ISNULL(T4.PIARef, ''),     
    ISNULL(CONVERT(varchar(24), T4.AuthorisedDate, 120),''),     
    ISNULL(T4.ExperienceLevel, ''),     
    T4.ConcurrencyId,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
 NULL,    
 NULL,  
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
  NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL    
  FROM [CRM].[dbo].TPractitioner T4    
    
  INNER JOIN TPolicyBusiness T1    
  ON T4.PractitionerId = T1.PractitionerId    
    
  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)    
    
  UNION ALL    
    
  SELECT    
    5 AS Tag,    
    1 AS Parent,    
    T1.PolicyBusinessId,     
    T1.PolicyDetailId,     
    ISNULL(T1.PolicyNumber, ''),     
    T1.PractitionerId,     
    ISNULL(T1.ReplaceNotes, ''),     
    ISNULL(T1.TnCCoachId, ''),     
    T1.AdviceTypeId,     
    T1.BestAdvicePanelUsedFG,     
    T1.WaiverDefermentPeriod,     
    T1.IndigoClientId,     
    T1.SwitchFG,     
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), ''),     
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), ''),     
ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),'') AS [PolicyBusiness!1!MaturityDate],     
    ISNULL(CONVERT(varchar(24), T1.PolicyStartDate, 120), '') AS [PolicyBusiness!1!PolicyStartDate],     
    ISNULL(T1.PremiumType, '') AS [PolicyBusiness!1!PremiumType],     
    ISNULL(T1.SequentialRef, ''),     
    ISNULL(T1.AgencyNumber, ''),     
    ISNULL(T1.ProviderAddress, ''),     
    T1.OffPanelFg,    
    T1.BaseCurrency,    
    T1.ExpectedPaymentDate,    
 T1.ProductName,    
 NULL,  
    T1.ConcurrencyId,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    T5.StatusHistoryId,   
    T5.PolicyBusinessId,     
    T5.StatusId,     
    ISNULL(T5.StatusReasonId, ''),     
    CONVERT(varchar(24), T5.ChangedToDate, 120),     
    T5.ChangedByUserId,     
    ISNULL(CONVERT(varchar(24), T5.DateOfChange, 120),''),     
    T5.LifeCycleStepFG,     
    T5.ConcurrencyId,     
    NULL,     
    NULL,     
 NULL,    
 NULL,  
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL    
  FROM TStatusHistory T5    
    
  INNER JOIN TPolicyBusiness T1    
  ON T5.PolicyBusinessId = T1.PolicyBusinessId    
    
  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)    
    
  UNION ALL    
    
  SELECT    
    6 AS Tag,    
    1 AS Parent,    
    T1.PolicyBusinessId,     
    T1.PolicyDetailId,     
    ISNULL(T1.PolicyNumber, ''),     
    T1.PractitionerId,     
    ISNULL(T1.ReplaceNotes, ''),     
    ISNULL(T1.TnCCoachId, ''),     
    T1.AdviceTypeId,     
    T1.BestAdvicePanelUsedFG,     
    T1.WaiverDefermentPeriod,     
    T1.IndigoClientId,     
    T1.SwitchFG,     
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), ''),     
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), ''),     
ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),'') AS [PolicyBusiness!1!MaturityDate],     
    ISNULL(CONVERT(varchar(24), T1.PolicyStartDate, 120), '') AS [PolicyBusiness!1!PolicyStartDate],     
    ISNULL(T1.PremiumType, '') AS [PolicyBusiness!1!PremiumType],     
    ISNULL(T1.SequentialRef, ''),     
    ISNULL(T1.AgencyNumber, ''),     
    ISNULL(T1.ProviderAddress, ''),     
    T1.OffPanelFg,    
    T1.BaseCurrency,    
    T1.ExpectedPaymentDate,    
 T1.ProductName,   
 NULL,   
    T1.ConcurrencyId,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
   NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    T6.PolicyBusinessAttributeId,     
    T6.AttributeValue,    
    T6.PolicyBusinessId,     
    T6.AttributeList2AttributeId,     
    T6.ConcurrencyId,     
    NULL,     
    NULL,     
    NULL,  
 NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL    
  FROM TPolicyBusinessAttribute T6    
    
    
  INNER JOIN TPolicyBusiness T1    
  ON T6.PolicyBusinessId = T1.PolicyBusinessId    
    
  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)    
    
  UNION ALL    
    
  SELECT    
    7 AS Tag,    
    2 AS Parent,    
    T1.PolicyBusinessId,     
 NULL,    
    NULL,     
    NULL,     
    NULL,    
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,    
    NULL,    
    NULL,    
    NULL,     
    NULL,     
    NULL,     
 NULL,  
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    T2.PolicyDetailId,     
    T2.PlanDescriptionId,     
    ISNULL(T2.TermYears, ''),     
    ISNULL(T2.WholeOfLifeFg, ''),     
    ISNULL(T2.LetterOfAuthorityFg, ''),     
    ISNULL(T2.ContractOutOfSERPSFg, ''),     
    ISNULL(CONVERT(varchar(24), T2.ContractOutStartDate, 120),''),     
    ISNULL(CONVERT(varchar(24), T2.ContractOutStopDate, 120),''),     
    ISNULL(T2.AssignedCRMContactId, ''),     
    ISNULL(CONVERT(varchar(24), T2.JoiningDate, 120),''),     
    ISNULL(CONVERT(varchar(24), T2.LeavingDate, 120),''),     
    T2.IndigoClientId,     
    T2.ConcurrencyId,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
NULL,    
    NULL,     
    NULL,     
    T7.PlanDescriptionId,     
    T7.RefPlanType2ProdSubTypeId,     
 T20.RefPlanTypeId,  
    T7.RefProdProviderId,     
    ISNULL(T7.SchemeOwnerCRMContactId, ''),     
    ISNULL(T7.SchemeStatus, ''),     
    ISNULL(T7.SchemeNumber, ''),     
    ISNULL(T7.SchemeName, ''),     
    ISNULL(CONVERT(varchar(24), T7.SchemeStatusDate, 120),''),     
    ISNULL(T7.SchemeSellingAdvisorPractitionerId, ''),     
    T7.ConcurrencyId,     
    NULL,     
  NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
  NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL    
  FROM TPlanDescription T7    
    
  INNER JOIN TPolicyDetail T2    
  ON T7.PlanDescriptionId = T2.PlanDescriptionId    
  JOIN TRefPlanType2ProdSubType T20 ON T20.RefPlanType2ProdSubTypeId = T7.RefPlanType2ProdSubTypeId  
  INNER JOIN TPolicyBusiness T1    
  ON T2.PolicyDetailId = T1.PolicyDetailId    
    
  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)    
    
  UNION ALL    
    
  SELECT    
    8 AS Tag,    
    2 AS Parent,    
    T1.PolicyBusinessId,     
NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,    
    NULL,    
    NULL,     
    NULL,     
    NULL,     
 NULL,  
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,    
    T2.PolicyDetailId,     
    T2.PlanDescriptionId,     
    ISNULL(T2.TermYears, ''),     
    ISNULL(T2.WholeOfLifeFg, ''),     
    ISNULL(T2.LetterOfAuthorityFg, ''),     
    ISNULL(T2.ContractOutOfSERPSFg, ''),     
    ISNULL(CONVERT(varchar(24), T2.ContractOutStartDate, 120),''),     
    ISNULL(CONVERT(varchar(24), T2.ContractOutStopDate, 120),''),     
    ISNULL(T2.AssignedCRMContactId, ''),     
    ISNULL(CONVERT(varchar(24), T2.JoiningDate, 120),''),     
    ISNULL(CONVERT(varchar(24), T2.LeavingDate, 120),''),     
    T2.IndigoClientId,     
    T2.ConcurrencyId,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
 NULL,  
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    T8.PolicyOwnerId,     
    T8.CRMContactId,     
    T8.PolicyDetailId,     
    T8.ConcurrencyId,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL    
  FROM TPolicyOwner T8    
    
  INNER JOIN TPolicyDetail T2    
  ON T8.PolicyDetailId = T2.PolicyDetailId    
  INNER JOIN TPolicyBusiness T1    
  ON T2.PolicyDetailId = T1.PolicyDetailId    
    
  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)    
    
  UNION ALL    
    
  SELECT    
    9 AS Tag,    
    8 AS Parent,    
    T1.PolicyBusinessId,     
NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,    
    NULL,     
    NULL,    
 NULL,  
    NULL,    
    NULL,    
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
  T2.PolicyDetailId,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
NULL,     
    NULL,     
    NULL,  
 NULL,     
    NULL,     
    NULL,     
    NULL,     
    T8.PolicyOwnerId,     
    T8.CRMContactId,     
    T8.PolicyDetailId,     
    T8.ConcurrencyId,     
    T9.CRMContactId,     
    ISNULL(T9.RefCRMContactStatusId, ''),     
    ISNULL(T9.PersonId, ''),     
    ISNULL(T9.CorporateId, ''),     
    ISNULL(T9.TrustId, ''),     
    ISNULL(T9.AdvisorRef, ''),     
--    ISNULL(T9.RefSourceOfClientId, ''),     
--    ISNULL(T9.SourceValue, ''),     
    ISNULL(T9.Notes, ''),     
    ISNULL(T9.ArchiveFg, ''),     
    ISNULL(T9.LastName, ''),     
    ISNULL(T9.FirstName, ''),     
    ISNULL(T9.CorporateName, ''),     
    ISNULL(CONVERT(varchar(24), T9.DOB, 120),''),     
    ISNULL(T9.Postcode, ''),     
    T9.OriginalAdviserCRMId,     
    T9.CurrentAdviserCRMId,     
    ISNULL(T9.CurrentAdviserName, ''),     
    T9.CRMContactType,     
    T9.IndClientId,     
    ISNULL(T9.FactFindId, ''),     
    ISNULL(T9.InternalContactFG, ''),     
    ISNULL(T9.RefServiceStatusId, ''),     
    ISNULL(T9.MigrationRef, ''),     
    T9.ConcurrencyId,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL    
  FROM [CRM].[dbo].TCRMContact T9    
    
  INNER JOIN TPolicyOwner T8    
  ON T9.CRMContactId = T8.CRMContactId    
  INNER JOIN TPolicyDetail T2    
  ON T8.PolicyDetailId = T2.PolicyDetailId    
  INNER JOIN TPolicyBusiness T1    
  ON T2.PolicyDetailId = T1.PolicyDetailId    
    
  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)    
    
    
  UNION ALL    
    
  SELECT    
    10 AS Tag,    
    4 AS Parent,    
    T1.PolicyBusinessId,     
NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,    
    NULL,    
    NULL,    
 NULL,  
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    T4.PractitionerId,     
    T4.IndClientId,     
    ISNULL(T4.PersonId, ''),     
    ISNULL(T4.CRMContactId, ''),     
    ISNULL(T4.TnCCoachId, ''),     
    T4.AuthorisedFG,     
    ISNULL(T4.PIARef, ''),     
    ISNULL(CONVERT(varchar(24), T4.AuthorisedDate, 120),''),     
    ISNULL(T4.ExperienceLevel, ''),     
    T4.ConcurrencyId,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,  
 NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    T10.CRMContactId,     
    ISNULL(T10.RefCRMContactStatusId, ''),     
    ISNULL(T10.PersonId, ''),     
    ISNULL(T10.CorporateId, ''),     
    ISNULL(T10.TrustId, ''),     
    ISNULL(T10.AdvisorRef, ''),     
--    ISNULL(T10.RefSourceOfClientId, ''),     
--    ISNULL(T10.SourceValue, ''),     
    ISNULL(T10.Notes, ''),     
    ISNULL(T10.ArchiveFg, ''),     
    ISNULL(T10.LastName, ''),     
    ISNULL(T10.FirstName, ''),     
    ISNULL(T10.FirstName, '') + ' ' + ISNULL(T10.LastName, ''),      
    ISNULL(T10.CorporateName, ''),     
    ISNULL(CONVERT(varchar(24), T10.DOB, 120),''),     
    ISNULL(T10.Postcode, ''),     
    T10.OriginalAdviserCRMId,     
    T10.CurrentAdviserCRMId,     
    ISNULL(T10.CurrentAdviserName, ''),     
    T10.CRMContactType,     
    T10.IndClientId,     
    ISNULL(T10.FactFindId, ''),     
    ISNULL(T10.InternalContactFG, ''),     
    ISNULL(T10.RefServiceStatusId, ''),     
    ISNULL(T10.MigrationRef, ''),     
   T10.ConcurrencyId,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL    
  FROM [CRM].[dbo].TCRMContact T10    
    
  INNER JOIN [CRM].[dbo].TPractitioner T4    
  ON T10.CRMContactId = T4.CRMContactId    
  INNER JOIN TPolicyBusiness T1    
  ON T4.PractitionerId = T1.PractitionerId    
    
  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)    
    
  UNION ALL    
    
  SELECT    
    11 AS Tag,    
    5 AS Parent,    
    T1.PolicyBusinessId,     
NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
 NULL,  
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,    
    NULL,    
    NULL,    
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    T5.StatusHistoryId,     
    T5.PolicyBusinessId,     
    T5.StatusId,     
    ISNULL(T5.StatusReasonId, ''),     
    CONVERT(varchar(24), T5.ChangedToDate, 120),     
    T5.ChangedByUserId,     
    ISNULL(CONVERT(varchar(24), T5.DateOfChange, 120),''),     
    T5.LifeCycleStepFG,     
    T5.ConcurrencyId,     
    NULL,     
    NULL,     
NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,  
 NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    T11.StatusId,     
    T11.Name,     
    ISNULL(T11.OrigoStatusId, ''),     
    ISNULL(T11.IntelligentOfficeStatusType, ''),     
    T11.IndigoClientId,     
    T11.ConcurrencyId,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL    
  FROM TStatus T11    
    
  INNER JOIN TStatusHistory T5    
  ON T11.StatusId = T5.StatusId    
  INNER JOIN TPolicyBusiness T1    
  ON T5.PolicyBusinessId = T1.PolicyBusinessId    
    
  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)    
    
  UNION ALL    
    
  SELECT    
    12 AS Tag,    
    6 AS Parent,    
    T1.PolicyBusinessId,     
NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
 NULL,  
    NULL,     
    NULL,     
    NULL,    
    NULL,    
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    T6.PolicyBusinessAttributeId,     
    T6.AttributeValue,    
    T6.PolicyBusinessId,     
    T6.AttributeList2AttributeId,     
    T6.ConcurrencyId,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
  NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,  
 NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    T12.AttributeList2AttributeId,     
    T12.AttributeListId,     
    T12.AttributeId,     
    T12.ConcurrencyId,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL    
  FROM TAttributeList2Attribute T12    
    
  INNER JOIN TPolicyBusinessAttribute T6    
  ON T12.AttributeList2AttributeId = T6.AttributeList2AttributeId    
  INNER JOIN TPolicyBusiness T1    
  ON T6.PolicyBusinessId = T1.PolicyBusinessId    
    
  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)    
    
  UNION ALL    
    
  SELECT    
    13 AS Tag,    
    12 AS Parent,    
    T1.PolicyBusinessId,     
NULL,    
    NULL,     
    NULL,     
    NULL,     
 NULL,  
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,    
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    T6.PolicyBusinessAttributeId,     
    NULL,     
NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,  
 NULL,     
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    T12.AttributeList2AttributeId,     
    T12.AttributeListId,     
    T12.AttributeId,     
    T12.ConcurrencyId,     
    T13.AttributeId,     
    T13.Value,     
    T13.ConcurrencyId,     
    NULL,     
    NULL,     
    NULL,     
 NULL    
  FROM TAttribute T13    
    
  INNER JOIN TAttributeList2Attribute T12    
  ON T13.AttributeId = T12.AttributeId    
  INNER JOIN TPolicyBusinessAttribute T6    
  ON T12.AttributeList2AttributeId = T6.AttributeList2AttributeId    
  INNER JOIN TPolicyBusiness T1    
  ON T6.PolicyBusinessId = T1.PolicyBusinessId    
    
  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)    
    
  UNION ALL    
    
  SELECT    
    14 AS Tag,    
    12 AS Parent,    
    T1.PolicyBusinessId,     
 NULL,    
    NULL,     
    NULL,     
    NULL,     
 NULL,  
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,    
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,    
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    T6.PolicyBusinessAttributeId,     
    T6.AttributeValue,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
--    NULL,     
--    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,  
 NULL,--this is the one--  
    NULL,    
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    NULL,     
    T12.AttributeList2AttributeId,     
    T12.AttributeListId,     
    T12.AttributeId,     
    T12.ConcurrencyId,     
    NULL,     
    NULL,     
    NULL,     
    T14.AttributeListId,     
    ISNULL(T14.Name, ''),     
    T14.Type,     
    T14.ConcurrencyId    
  FROM TAttributeList T14    
    
  INNER JOIN TAttributeList2Attribute T12    
  ON T14.AttributeListId = T12.AttributeListId    
  INNER JOIN TPolicyBusinessAttribute T6    
  ON T12.AttributeList2AttributeId = T6.AttributeList2AttributeId    
  INNER JOIN TPolicyBusiness T1    
  ON T6.PolicyBusinessId = T1.PolicyBusinessId    
    
  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)    
    
  ORDER BY [PolicyBusiness!1!PolicyBusinessId], [PolicyBusinessAttribute!6!PolicyBusinessAttributeId], [AttributeList2Attribute!12!AttributeList2AttributeId], [AttributeList!14!AttributeListId], [Attribute!13!AttributeId], [StatusHistory!5!StatusHistoryId],    
 [Status!11!StatusId], [Practitioner!4!PractitionerId], [Adviser!10!CRMContactId], [AdviceType!3!AdviceTypeId], [PolicyDetail!2!PolicyDetailId], [PolicyOwner!8!PolicyOwnerId], [Owner!9!CRMContactId], [PlanDescription!7!PlanDescriptionId]    
    
  FOR XML EXPLICIT    
  
   
    
END    
RETURN (0)    
    
GO
