-- Drop Procedure SpNioCustomOpenSymmetricKeyForPasswordEncryption
Create Procedure SpNioCustomOpenSymmetricKeyForPasswordEncryption
As

OPEN SYMMETRIC KEY SymmetricKeyForPasswordEncryption DECRYPTION BY CERTIFICATE CertificateForPasswordEncryption;

