SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[SpAliasRetrievePolicyBusinessWithExpectedComission]
@PolicyBusinessId bigint
AS

BEGIN
  SELECT
    1 AS Tag,
    NULL AS Parent,
    T1.PolicyBusinessId AS [PolicyBusiness!1!PolicyBusinessId], 
    T1.PolicyDetailId AS [PolicyBusiness!1!PolicyDetailId], 
    ISNULL(T1.PolicyNumber, '') AS [PolicyBusiness!1!PolicyNumber], 
    T1.PractitionerId AS [PolicyBusiness!1!PractitionerId], 
    ISNULL(T1.ReplaceNotes, '') AS [PolicyBusiness!1!ReplaceNotes], 
    ISNULL(T1.TnCCoachId, '') AS [PolicyBusiness!1!TnCCoachId], 
    T1.AdviceTypeId AS [PolicyBusiness!1!AdviceTypeId], 
    T1.BestAdvicePanelUsedFG AS [PolicyBusiness!1!BestAdvicePanelUsedFG], 
    T1.WaiverDefermentPeriod AS [PolicyBusiness!1!WaiverDefermentPeriod], 
    T1.IndigoClientId AS [PolicyBusiness!1!IndigoClientId], 
    T1.SwitchFG AS [PolicyBusiness!1!SwitchFG], 
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), '') AS [PolicyBusiness!1!TotalRegularPremium], 
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), '') AS [PolicyBusiness!1!TotalLumpSum], 
    ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),'') AS [PolicyBusiness!1!MaturityDate], 
    ISNULL(T1.LifeCycleId, '') AS [PolicyBusiness!1!LifeCycleId], 
    ISNULL(T1.SequentialRef , '') AS [PolicyBusiness!1!SequentialRef],
    T1.ConcurrencyId AS [PolicyBusiness!1!ConcurrencyId], 
    ISNULL(TNote.Note, '') AS [PolicyBusiness!1!_note], 
    NULL AS [PolicyExpectedCommission!2!PolicyExpectedCommissionId], 
    NULL AS [PolicyExpectedCommission!2!PolicyBusinessId], 
    NULL AS [PolicyExpectedCommission!2!RefCommissionTypeId], 
    NULL AS [PolicyExpectedCommission!2!RefPaymentDueTypeId], 
    NULL AS [PolicyExpectedCommission!2!RefFrequencyId], 
    NULL AS [PolicyExpectedCommission!2!ChargingPeriodMonths], 
    NULL AS [PolicyExpectedCommission!2!ExpectedAmount], 
    NULL AS [PolicyExpectedCommission!2!ExpectedStartDate], 
    NULL AS [PolicyExpectedCommission!2!ExpectedCommissionType], 
    NULL AS [PolicyExpectedCommission!2!ParentPolicyExpectedCommissionId], 
    NULL AS [PolicyExpectedCommission!2!ConcurrencyId], 
    NULL AS [Practitioner!3!PractitionerId], 
    NULL AS [Practitioner!3!IndClientId], 
    NULL AS [Practitioner!3!PersonId], 
    NULL AS [Practitioner!3!CRMContactId], 
    NULL AS [Practitioner!3!TnCCoachId], 
    NULL AS [Practitioner!3!AuthorisedFG], 
    NULL AS [Practitioner!3!PIARef], 
    NULL AS [Practitioner!3!AuthorisedDate], 
    NULL AS [Practitioner!3!ExperienceLevel], 
    NULL AS [Practitioner!3!_ParentId], 
    NULL AS [Practitioner!3!_ParentTable], 
    NULL AS [Practitioner!3!_ParentDb], 
    NULL AS [Practitioner!3!_OwnerId], 
    NULL AS [Practitioner!3!ConcurrencyId], 
    NULL AS [Adviser!4!CRMContactId], 
    NULL AS [Adviser!4!RefCRMContactStatusId], 
    NULL AS [Adviser!4!PersonId], 
    NULL AS [Adviser!4!CorporateId], 
    NULL AS [Adviser!4!TrustId], 
    NULL AS [Adviser!4!AdvisorRef], 
    NULL AS [Adviser!4!RefSourceOfClientId], 
    NULL AS [Adviser!4!SourceValue], 
    NULL AS [Adviser!4!Notes], 
    NULL AS [Adviser!4!ArchiveFg], 
    NULL AS [Adviser!4!LastName], 
    NULL AS [Adviser!4!FirstName], 
    NULL AS [Adviser!4!CorporateName], 
    NULL AS [Adviser!4!DOB], 
    NULL AS [Adviser!4!Postcode], 
    NULL AS [Adviser!4!OriginalAdviserCRMId], 
    NULL AS [Adviser!4!CurrentAdviserCRMId], 
    NULL AS [Adviser!4!CurrentAdviserName], 
    NULL AS [Adviser!4!CRMContactType], 
    NULL AS [Adviser!4!IndClientId], 
    NULL AS [Adviser!4!FactFindId], 
    NULL AS [Adviser!4!InternalContactFG], 
    NULL AS [Adviser!4!RefServiceStatusId], 
    NULL AS [Adviser!4!MigrationRef], 
    NULL AS [Adviser!4!ConcurrencyId]
  FROM TPolicyBusiness T1
  -- Note clause
  LEFT JOIN TPolicyBusinessNote TNote
  ON TNote.PolicyBusinessId = T1.PolicyBusinessId AND TNote.IsLatest=1

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    2 AS Tag,
    1 AS Parent,
    T1.PolicyBusinessId, 
    T1.PolicyDetailId, 
    ISNULL(T1.PolicyNumber, ''), 
    T1.PractitionerId, 
    ISNULL(T1.ReplaceNotes, ''), 
    ISNULL(T1.TnCCoachId, ''), 
    T1.AdviceTypeId, 
    T1.BestAdvicePanelUsedFG, 
    T1.WaiverDefermentPeriod, 
    T1.IndigoClientId, 
    T1.SwitchFG, 
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), ''), 
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), ''), 
    ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),''), 
    ISNULL(T1.LifeCycleId, ''), 
    T1.SequentialRef, 
    T1.ConcurrencyId, 
    NULL,
    T2.PolicyExpectedCommissionId, 
    T2.PolicyBusinessId, 
    T2.RefCommissionTypeId, 
    T2.RefPaymentDueTypeId, 
    ISNULL(T2.RefFrequencyId, ''), 
    ISNULL(T2.ChargingPeriodMonths, ''), 
    T2.ExpectedAmount, 
    ISNULL(CONVERT(varchar(24), T2.ExpectedStartDate, 120),''), 
    T2.ExpectedCommissionType, 
    ISNULL(T2.ParentPolicyExpectedCommissionId, ''), 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TPolicyExpectedCommission T2
  INNER JOIN TPolicyBusiness T1
  ON T2.PolicyBusinessId = T1.PolicyBusinessId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    3 AS Tag,
    1 AS Parent,
    T1.PolicyBusinessId, 
    T1.PolicyDetailId, 
    ISNULL(T1.PolicyNumber, ''), 
    T1.PractitionerId, 
    ISNULL(T1.ReplaceNotes, ''), 
    ISNULL(T1.TnCCoachId, ''), 
    T1.AdviceTypeId, 
    T1.BestAdvicePanelUsedFG, 
    T1.WaiverDefermentPeriod, 
    T1.IndigoClientId, 
    T1.SwitchFG, 
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), ''), 
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), ''), 
    ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),''), 
    ISNULL(T1.LifeCycleId, ''), 
    T1.SequentialRef, 
    T1.ConcurrencyId, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T3.PractitionerId, 
    T3.IndClientId, 
    ISNULL(T3.PersonId, ''), 
    ISNULL(T3.CRMContactId, ''), 
    ISNULL(T3.TnCCoachId, ''), 
    T3.AuthorisedFG, 
    ISNULL(T3.PIARef, ''), 
    ISNULL(CONVERT(varchar(24), T3.AuthorisedDate, 120),''), 
    ISNULL(T3.ExperienceLevel, ''), 
    ISNULL(T3._ParentId, ''), 
    ISNULL(T3._ParentTable, ''), 
    ISNULL(T3._ParentDb, ''), 
    ISNULL(T3._OwnerId, ''), 
    T3.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM [CRM].[dbo].TPractitioner T3
  INNER JOIN TPolicyBusiness T1
  ON T3.PractitionerId = T1.PractitionerId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    4 AS Tag,
    3 AS Parent,
    T1.PolicyBusinessId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T3.PractitionerId, 
    T3.IndClientId, 
    ISNULL(T3.PersonId, ''), 
    ISNULL(T3.CRMContactId, ''), 
    ISNULL(T3.TnCCoachId, ''), 
    T3.AuthorisedFG, 
    ISNULL(T3.PIARef, ''), 
    ISNULL(CONVERT(varchar(24), T3.AuthorisedDate, 120),''), 
    ISNULL(T3.ExperienceLevel, ''), 
    ISNULL(T3._ParentId, ''), 
    ISNULL(T3._ParentTable, ''), 
    ISNULL(T3._ParentDb, ''), 
    ISNULL(T3._OwnerId, ''), 
    T3.ConcurrencyId, 
    T4.CRMContactId, 
    ISNULL(T4.RefCRMContactStatusId, ''), 
    ISNULL(T4.PersonId, ''), 
    ISNULL(T4.CorporateId, ''), 
    ISNULL(T4.TrustId, ''), 
    ISNULL(T4.AdvisorRef, ''), 
    ISNULL(T4.RefSourceOfClientId, ''), 
    ISNULL(T4.SourceValue, ''), 
    ISNULL(T4.Notes, ''), 
    ISNULL(T4.ArchiveFg, ''), 
    ISNULL(T4.LastName, ''), 
    ISNULL(T4.FirstName, ''), 
    ISNULL(T4.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T4.DOB, 120),''), 
    ISNULL(T4.Postcode, ''), 
    T4.OriginalAdviserCRMId, 
    T4.CurrentAdviserCRMId, 
    ISNULL(T4.CurrentAdviserName, ''), 
    T4.CRMContactType, 
    T4.IndClientId, 
    ISNULL(T4.FactFindId, ''), 
    ISNULL(T4.InternalContactFG, ''), 
    ISNULL(T4.RefServiceStatusId, ''), 
    ISNULL(T4.MigrationRef, ''), 
    T4.ConcurrencyId
  FROM [CRM].[dbo].TCRMContact T4
  INNER JOIN [CRM].[dbo].TPractitioner T3
  ON T4.CRMContactId = T3.CRMContactId
  INNER JOIN TPolicyBusiness T1
  ON T3.PractitionerId = T1.PractitionerId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  ORDER BY [PolicyBusiness!1!PolicyBusinessId], [Practitioner!3!PractitionerId], [Adviser!4!CRMContactId], [PolicyExpectedCommission!2!PolicyExpectedCommissionId]

  FOR XML EXPLICIT

END
RETURN (0)
GO
