SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[SpAliasListClientForPolicyBusiness]
@PolicyBusinessId bigint
AS

BEGIN
  SELECT
    1 AS Tag,
    NULL AS Parent,
    T1.PolicyBusinessId AS [PolicyBusiness!1!PolicyBusinessId], 
    T1.PolicyDetailId AS [PolicyBusiness!1!PolicyDetailId], 
    ISNULL(T1.PolicyNumber, '') AS [PolicyBusiness!1!PolicyNumber], 
    T1.PractitionerId AS [PolicyBusiness!1!PractitionerId], 
    ISNULL(T1.ReplaceNotes, '') AS [PolicyBusiness!1!ReplaceNotes], 
    ISNULL(T1.TnCCoachId, '') AS [PolicyBusiness!1!TnCCoachId], 
    T1.AdviceTypeId AS [PolicyBusiness!1!AdviceTypeId], 
    T1.BestAdvicePanelUsedFG AS [PolicyBusiness!1!BestAdvicePanelUsedFG], 
    T1.WaiverDefermentPeriod AS [PolicyBusiness!1!WaiverDefermentPeriod], 
    T1.IndigoClientId AS [PolicyBusiness!1!IndigoClientId], 
    T1.SwitchFG AS [PolicyBusiness!1!SwitchFG], 
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), '') AS [PolicyBusiness!1!TotalRegularPremium], 
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), '') AS [PolicyBusiness!1!TotalLumpSum], 
    ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),'') AS [PolicyBusiness!1!MaturityDate], 
    ISNULL(T1.LifeCycleId, '') AS [PolicyBusiness!1!LifeCycleId], 
    ISNULL(CONVERT(varchar(24), T1.PolicyStartDate, 120),'') AS [PolicyBusiness!1!PolicyStartDate], 
    ISNULL(T1.PremiumType, '') AS [PolicyBusiness!1!PremiumType], 
    ISNULL(T1.AgencyNumber, '') AS [PolicyBusiness!1!AgencyNumber], 
    ISNULL(T1.ProviderAddress, '') AS [PolicyBusiness!1!ProviderAddress], 
    T1.OffPanelFg AS [PolicyBusiness!1!OffPanelFg], 
    ISNULL(T1.BaseCurrency, '') AS [PolicyBusiness!1!BaseCurrency], 
    ISNULL(CONVERT(varchar(24), T1.ExpectedPaymentDate, 120),'') AS [PolicyBusiness!1!ExpectedPaymentDate], 
    ISNULL(T1.ProductName, '') AS [PolicyBusiness!1!ProductName], 
    ISNULL(T1.InvestmentTypeId, '') AS [PolicyBusiness!1!InvestmentTypeId], 
    ISNULL(T1.RiskRating, '') AS [PolicyBusiness!1!RiskRating], 
    ISNULL(T1.SequentialRef, '') AS [PolicyBusiness!1!SequentialRef], 
    T1.ConcurrencyId AS [PolicyBusiness!1!ConcurrencyId], 
    ISNULL(TNote.Note, '') AS [PolicyBusiness!1!_note], 
    NULL AS [PolicyDetail!2!PolicyDetailId], 
    NULL AS [PolicyDetail!2!PlanDescriptionId], 
    NULL AS [PolicyDetail!2!TermYears], 
    NULL AS [PolicyDetail!2!WholeOfLifeFg], 
    NULL AS [PolicyDetail!2!LetterOfAuthorityFg], 
    NULL AS [PolicyDetail!2!ContractOutOfSERPSFg], 
    NULL AS [PolicyDetail!2!ContractOutStartDate], 
    NULL AS [PolicyDetail!2!ContractOutStopDate], 
    NULL AS [PolicyDetail!2!AssignedCRMContactId], 
    NULL AS [PolicyDetail!2!JoiningDate], 
    NULL AS [PolicyDetail!2!LeavingDate], 
    NULL AS [PolicyDetail!2!IndigoClientId], 
    NULL AS [PolicyDetail!2!ConcurrencyId], 
    NULL AS [PolicyOwner!3!PolicyOwnerId], 
    NULL AS [PolicyOwner!3!CRMContactId], 
    NULL AS [PolicyOwner!3!PolicyDetailId], 
    NULL AS [PolicyOwner!3!ConcurrencyId], 
    NULL AS [CRMContact!4!CRMContactId], 
    NULL AS [CRMContact!4!RefCRMContactStatusId], 
    NULL AS [CRMContact!4!PersonId], 
    NULL AS [CRMContact!4!CorporateId], 
    NULL AS [CRMContact!4!TrustId], 
    NULL AS [CRMContact!4!AdvisorRef], 
    NULL AS [CRMContact!4!RefSourceOfClientId], 
    NULL AS [CRMContact!4!SourceValue], 
    NULL AS [CRMContact!4!Notes], 
    NULL AS [CRMContact!4!ArchiveFg], 
    NULL AS [CRMContact!4!LastName], 
    NULL AS [CRMContact!4!FirstName], 
    NULL AS [CRMContact!4!CorporateName], 
    NULL AS [CRMContact!4!DOB], 
    NULL AS [CRMContact!4!Postcode], 
    NULL AS [CRMContact!4!OriginalAdviserCRMId], 
    NULL AS [CRMContact!4!CurrentAdviserCRMId], 
    NULL AS [CRMContact!4!CurrentAdviserName], 
    NULL AS [CRMContact!4!CRMContactType], 
    NULL AS [CRMContact!4!IndClientId], 
    NULL AS [CRMContact!4!FactFindId], 
    NULL AS [CRMContact!4!InternalContactFG], 
    NULL AS [CRMContact!4!RefServiceStatusId], 
    NULL AS [CRMContact!4!MigrationRef], 
    NULL AS [CRMContact!4!CreatedDate], 
    NULL AS [CRMContact!4!ExternalReference], 
    NULL AS [CRMContact!4!CampaignDataId], 
    NULL AS [CRMContact!4!AdditionalRef], 
    NULL AS [CRMContact!4!_ParentId], 
    NULL AS [CRMContact!4!_ParentTable], 
    NULL AS [CRMContact!4!_ParentDb], 
    NULL AS [CRMContact!4!_OwnerId], 
    NULL AS [CRMContact!4!ConcurrencyId]
  FROM TPolicyBusiness T1
  -- Note clause
  LEFT JOIN TPolicyBusinessNote TNote
  ON TNote.PolicyBusinessId = T1.PolicyBusinessId AND TNote.IsLatest=1

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    2 AS Tag,
    1 AS Parent,
    T1.PolicyBusinessId, 
    T1.PolicyDetailId, 
    ISNULL(T1.PolicyNumber, ''), 
    T1.PractitionerId, 
    ISNULL(T1.ReplaceNotes, ''), 
    ISNULL(T1.TnCCoachId, ''), 
    T1.AdviceTypeId, 
    T1.BestAdvicePanelUsedFG, 
    T1.WaiverDefermentPeriod, 
    T1.IndigoClientId, 
    T1.SwitchFG, 
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), ''), 
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), ''), 
    ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),''), 
    ISNULL(T1.LifeCycleId, ''), 
    ISNULL(CONVERT(varchar(24), T1.PolicyStartDate, 120),''), 
    ISNULL(T1.PremiumType, ''), 
    ISNULL(T1.AgencyNumber, ''), 
    ISNULL(T1.ProviderAddress, ''), 
    T1.OffPanelFg, 
    ISNULL(T1.BaseCurrency, ''), 
    ISNULL(CONVERT(varchar(24), T1.ExpectedPaymentDate, 120),''), 
    ISNULL(T1.ProductName, ''), 
    ISNULL(T1.InvestmentTypeId, ''), 
    ISNULL(T1.RiskRating, ''), 
    ISNULL(T1.SequentialRef, ''), 
    T1.ConcurrencyId, 
    NULL,
    T2.PolicyDetailId, 
    T2.PlanDescriptionId, 
    ISNULL(T2.TermYears, ''), 
    ISNULL(T2.WholeOfLifeFg, ''), 
    ISNULL(T2.LetterOfAuthorityFg, ''), 
    ISNULL(T2.ContractOutOfSERPSFg, ''), 
    ISNULL(CONVERT(varchar(24), T2.ContractOutStartDate, 120),''), 
    ISNULL(CONVERT(varchar(24), T2.ContractOutStopDate, 120),''), 
    ISNULL(T2.AssignedCRMContactId, ''), 
    ISNULL(CONVERT(varchar(24), T2.JoiningDate, 120),''), 
    ISNULL(CONVERT(varchar(24), T2.LeavingDate, 120),''), 
    T2.IndigoClientId, 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TPolicyDetail T2
  INNER JOIN TPolicyBusiness T1
  ON T2.PolicyDetailId = T1.PolicyDetailId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    3 AS Tag,
    2 AS Parent,
    T1.PolicyBusinessId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    T2.PolicyDetailId, 
    T2.PlanDescriptionId, 
    ISNULL(T2.TermYears, ''), 
    ISNULL(T2.WholeOfLifeFg, ''), 
    ISNULL(T2.LetterOfAuthorityFg, ''), 
    ISNULL(T2.ContractOutOfSERPSFg, ''), 
    ISNULL(CONVERT(varchar(24), T2.ContractOutStartDate, 120),''), 
    ISNULL(CONVERT(varchar(24), T2.ContractOutStopDate, 120),''), 
    ISNULL(T2.AssignedCRMContactId, ''), 
    ISNULL(CONVERT(varchar(24), T2.JoiningDate, 120),''), 
    ISNULL(CONVERT(varchar(24), T2.LeavingDate, 120),''), 
    T2.IndigoClientId, 
    T2.ConcurrencyId, 
    T3.PolicyOwnerId, 
    T3.CRMContactId, 
    T3.PolicyDetailId, 
    T3.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TPolicyOwner T3
  INNER JOIN TPolicyDetail T2
  ON T3.PolicyDetailId = T2.PolicyDetailId
  INNER JOIN TPolicyBusiness T1
  ON T2.PolicyDetailId = T1.PolicyDetailId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    4 AS Tag,
    3 AS Parent,
    T1.PolicyBusinessId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    T2.PolicyDetailId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T3.PolicyOwnerId, 
    T3.CRMContactId, 
    T3.PolicyDetailId, 
    T3.ConcurrencyId, 
    T4.CRMContactId, 
    ISNULL(T4.RefCRMContactStatusId, ''), 
    ISNULL(T4.PersonId, ''), 
    ISNULL(T4.CorporateId, ''), 
    ISNULL(T4.TrustId, ''), 
    ISNULL(T4.AdvisorRef, ''), 
    ISNULL(T4.RefSourceOfClientId, ''), 
    ISNULL(T4.SourceValue, ''), 
    ISNULL(T4.Notes, ''), 
    ISNULL(T4.ArchiveFg, ''), 
    ISNULL(T4.LastName, ''), 
    ISNULL(T4.FirstName, ''), 
    ISNULL(T4.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T4.DOB, 120),''), 
    ISNULL(T4.Postcode, ''), 
    T4.OriginalAdviserCRMId, 
    T4.CurrentAdviserCRMId, 
    ISNULL(T4.CurrentAdviserName, ''), 
    T4.CRMContactType, 
    T4.IndClientId, 
    ISNULL(T4.FactFindId, ''), 
    ISNULL(T4.InternalContactFG, ''), 
    ISNULL(T4.RefServiceStatusId, ''), 
    ISNULL(T4.MigrationRef, ''), 
    CONVERT(varchar(24), T4.CreatedDate, 120), 
    ISNULL(T4.ExternalReference, ''), 
    ISNULL(T4.CampaignDataId, ''), 
    ISNULL(T4.AdditionalRef, ''), 
    ISNULL(T4._ParentId, ''), 
    ISNULL(T4._ParentTable, ''), 
    ISNULL(T4._ParentDb, ''), 
    ISNULL(T4._OwnerId, ''), 
    T4.ConcurrencyId
  FROM [CRM].[dbo].TCRMContact T4
  INNER JOIN TPolicyOwner T3
  ON T4.CRMContactId = T3.CRMContactId
  INNER JOIN TPolicyDetail T2
  ON T3.PolicyDetailId = T2.PolicyDetailId
  INNER JOIN TPolicyBusiness T1
  ON T2.PolicyDetailId = T1.PolicyDetailId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  ORDER BY [PolicyBusiness!1!PolicyBusinessId], [PolicyDetail!2!PolicyDetailId], [PolicyOwner!3!PolicyOwnerId], [CRMContact!4!CRMContactId]

  FOR XML EXPLICIT

END
RETURN (0)

GO
