SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[SpNAuditFee] @StampUser VARCHAR(255),
	@FeeId BIGINT,
	@StampAction CHAR(1)
AS
INSERT INTO TFeeAudit (
	RefFeeTypeId,
	NetAmount,
	VATAmount,
	InvoiceDate,
	SentToClientDate,
	NextDueDate,
	BillingPeriodMonths,
	VATExempt,
	RefVATId,
	[Description],
	IsRecurring,
	RefFeeRetainerFrequencyId,
	RecurringFrequencyId,
	StartDate,
	EndDate,
	IsPaidByProvider,
	NumRecurringPayments,
	IndigoClientId,
	SequentialRefLegacy,
	SequentialRef,
	AdviseFeeTypeId,
	AdvisePaymentTypeId,
	AdviseFeeChargingDetailsId,
	ConcurrencyId,
	FeeId,
	RefFeeAdviseTypeId,
	StampAction,
	StampDateTime,
	StampUser,
	DiscountId,
	DiscountReason,
	FeeModelTemplateId,
	RefAdviceContributionTypeId,
	InitialPeriod,
	DiscountAuthorizerId,
	FeePercentage,
	IsFeeEnded,
	IsConsultancyFee,
	MigrationRef,
	DiscountAmount,
	DiscountPercentage,
	WIPPercentage,
	AmountEarned,
  	MinimumFee,
  	MaximumFee,
  	MinimumFeePercentage,
  	MaximumFeePercentage,
	ForwardIncomeToAdviserId,
	ForwardIncomeToUseAdviserBanding,
	IsRetainer,
	FeeCode
	)
SELECT RefFeeTypeId,
	NetAmount,
	VATAmount,
	InvoiceDate,
	SentToClientDate,
	NextDueDate,
	BillingPeriodMonths,
	VATExempt,
	RefVATId,
	[Description],
	IsRecurring,
	RefFeeRetainerFrequencyId,
	RecurringFrequencyId,
	StartDate,
	EndDate,
	IsPaidByProvider,
	NumRecurringPayments,
	IndigoClientId,
	SequentialRefLegacy,
	SequentialRef,
	AdviseFeeTypeId,
	AdvisePaymentTypeId,
	AdviseFeeChargingDetailsId,
	ConcurrencyId,
	FeeId,
	RefFeeAdviseTypeId,
	@StampAction,
	GetDate(),
	@StampUser,
	DiscountId,
	DiscountReason,
	FeeModelTemplateId,
	RefAdviceContributionTypeId,
	InitialPeriod,
	DiscountAuthorizerId,
	FeePercentage,
	IsFeeEnded,
	IsConsultancyFee,
	MigrationRef,
	DiscountAmount,
	DiscountPercentage,
	WIPPercentage,
	AmountEarned,
  	MinimumFee,
  	MaximumFee,
  	MinimumFeePercentage,
  	MaximumFeePercentage,
	ForwardIncomeToAdviserId,
	ForwardIncomeToUseAdviserBanding,
	IsRetainer,
	FeeCode
FROM TFee
WHERE FeeId = @FeeId

IF @@ERROR != 0
	GOTO errh

RETURN (0)

errh:

RETURN (100)
GO
