SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SpCustomCheckIfBCPEnabled]
@ProviderId BIGINT
AS

SET NOCOUNT ON 

	IF EXISTS (SELECT * FROM [TValBulkBCPConfig] WHERE [RefProdProviderId] = @ProviderId)
		SELECT BCPEnabled = 1
	ELSE
		SELECT BCPEnabled = 0

SET NOCOUNT OFF

RETURN (0)
GO
