SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SpNAuditEquityRelease]
	@StampUser varchar (255),
	@EquityReleaseId bigint,
	@StampAction char(1)
AS

INSERT INTO [PolicyManagement].[dbo].[TEquityReleaseAudit]
(
	PolicyBusinessId,
	InterestOnlyAmount,
	RepaymentAmount,
	LoanAmount,
	InterestRate,
	TermInYears,
	RefMortgageRepaymentMethodId,
	AddressStoreId,
	AssetsId,
	IndigoClientId,
	ConcurrencyId,
	EquityReleaseId,
	StampAction,
	StampDateTime,
	StampUser,
	InterestRatePercentage,
	RateType,
    ValueOfProperty,
	PenaltyFg,
	RedemptionTerms,
	PenaltyExpiryDate,
	ApplicableToNewTransaction,
	RefEquityReleaseTypeId,
	PercentageOwnershipSold,
	LumpsumAmount,
	MonthlyIncomeAmount,
	CurrentBalance,
	InterestDetails,
	RateTypeOther,
	TargetCompletionDate,
	TermInMonths, 
	ValuationDate, 
	ValuationInstructed, 
	ValuationReceived, 
	ApplicationSubmitted, 
	CompletionDate, 
	ExchangeDate, 
	OfferIssued, 
	ReviewDiaryDate, 
	CapitalRepaymentTermInMonths, 
	InterestRepaymentTermInMonths,
	BaseRate,
	CollarRate, 
	SchemeRate,
	SchemeEndDate, 
	RedemptionFigure2, 
	RedemptionFigure,
	AddressId,
	IsToBeConsolidated, 
	IsLiabilityToBeRepaid, 
	LiabilityRepaymentDescription
)
Select PolicyBusinessId,
	InterestOnlyAmount,
	RepaymentAmount,
	LoanAmount,
	InterestRate,
	TermInYears,
	RefMortgageRepaymentMethodId,
	AddressStoreId,
	AssetsId,
	IndigoClientId,
	ConcurrencyId,
	EquityReleaseId,
	@StampAction,
	GetDate(),
	@StampUser,
	InterestRatePercentage,
	RateType,
    ValueOfProperty,
	PenaltyFg,
	RedemptionTerms,
	PenaltyExpiryDate,
	ApplicableToNewTransaction,
	RefEquityReleaseTypeId,
	PercentageOwnershipSold,
	LumpsumAmount,
	MonthlyIncomeAmount,
	CurrentBalance,
	InterestDetails,
	RateTypeOther,
	TargetCompletionDate,
	TermInMonths, 
	ValuationDate, 
	ValuationInstructed, 
	ValuationReceived, 
	ApplicationSubmitted, 
	CompletionDate, 
	ExchangeDate, 
	OfferIssued, 
	ReviewDiaryDate, 
	CapitalRepaymentTermInMonths, 
	InterestRepaymentTermInMonths,
	BaseRate,
	CollarRate, 
	SchemeRate,
	SchemeEndDate, 
	RedemptionFigure2, 
	RedemptionFigure,
	AddressId,
	IsToBeConsolidated, 
	IsLiabilityToBeRepaid, 
	LiabilityRepaymentDescription
FROM [PolicyManagement].[dbo].[TEquityRelease]
WHERE EquityReleaseId = @EquityReleaseId

IF @@ERROR != 0 GOTO errh

RETURN (0)

errh:
RETURN (100)
GO
