SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[SpAliasRetrievePolicyCommission]
@PolicyBusinessId bigint
AS

BEGIN
  SELECT
    1 AS Tag,
    NULL AS Parent,
    T1.PolicyBusinessId AS [PolicyBusiness!1!PolicyBusinessId], 
    T1.PolicyDetailId AS [PolicyBusiness!1!PolicyDetailId], 
    ISNULL(T1.PolicyNumber, '') AS [PolicyBusiness!1!PolicyNumber], 
    T1.PractitionerId AS [PolicyBusiness!1!PractitionerId], 
    ISNULL(T1.ReplaceNotes, '') AS [PolicyBusiness!1!ReplaceNotes], 
    ISNULL(T1.TnCCoachId, '') AS [PolicyBusiness!1!TnCCoachId], 
    T1.AdviceTypeId AS [PolicyBusiness!1!AdviceTypeId], 
    T1.BestAdvicePanelUsedFG AS [PolicyBusiness!1!BestAdvicePanelUsedFG], 
    T1.WaiverDefermentPeriod AS [PolicyBusiness!1!WaiverDefermentPeriod], 
    T1.IndigoClientId AS [PolicyBusiness!1!IndigoClientId], 
    T1.SwitchFG AS [PolicyBusiness!1!SwitchFG], 
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), '') AS [PolicyBusiness!1!TotalRegularPremium], 
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), '') AS [PolicyBusiness!1!TotalLumpSum], 
    ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),'') AS [PolicyBusiness!1!MaturityDate], 
    ISNULL(T1.LifeCycleId, '') AS [PolicyBusiness!1!LifeCycleId], 
    ISNULL(CONVERT(varchar(24), T1.PolicyStartDate, 120),'') AS [PolicyBusiness!1!PolicyStartDate], 
    ISNULL(T1.PremiumType, '') AS [PolicyBusiness!1!PremiumType], 
    ISNULL(T1.AgencyNumber, '') AS [PolicyBusiness!1!AgencyNumber], 
    ISNULL(T1.ProviderAddress, '') AS [PolicyBusiness!1!ProviderAddress], 
    T1.OffPanelFg AS [PolicyBusiness!1!OffPanelFg], 
    ISNULL(T1.BaseCurrency, '') AS [PolicyBusiness!1!BaseCurrency], 
    ISNULL(CONVERT(varchar(24), T1.ExpectedPaymentDate, 120),'') AS [PolicyBusiness!1!ExpectedPaymentDate], 
    ISNULL(T1.ProductName, '') AS [PolicyBusiness!1!ProductName], 
    ISNULL(T1.InvestmentTypeId, '') AS [PolicyBusiness!1!InvestmentTypeId], 
    ISNULL(T1.RiskRating, '') AS [PolicyBusiness!1!RiskRating], 
    ISNULL(T1.SequentialRef, '') AS [PolicyBusiness!1!SequentialRef], 
    T1.ConcurrencyId AS [PolicyBusiness!1!ConcurrencyId], 
    ISNULL(TNote.Note, '') AS [PolicyBusiness!1!_note], 
    NULL AS [PolicyDetail!2!PolicyDetailId], 
    NULL AS [PolicyDetail!2!PlanDescriptionId], 
    NULL AS [PolicyDetail!2!TermYears], 
    NULL AS [PolicyDetail!2!WholeOfLifeFg], 
    NULL AS [PolicyDetail!2!LetterOfAuthorityFg], 
    NULL AS [PolicyDetail!2!ContractOutOfSERPSFg], 
    NULL AS [PolicyDetail!2!ContractOutStartDate], 
    NULL AS [PolicyDetail!2!ContractOutStopDate], 
    NULL AS [PolicyDetail!2!AssignedCRMContactId], 
    NULL AS [PolicyDetail!2!JoiningDate], 
    NULL AS [PolicyDetail!2!LeavingDate], 
    NULL AS [PolicyDetail!2!IndigoClientId], 
    NULL AS [PolicyDetail!2!ConcurrencyId], 
    NULL AS [PolicyExpectedCommission!3!PolicyExpectedCommissionId], 
    NULL AS [PolicyExpectedCommission!3!PolicyBusinessId], 
    NULL AS [PolicyExpectedCommission!3!RefCommissionTypeId], 
    NULL AS [PolicyExpectedCommission!3!RefPaymentDueTypeId], 
    NULL AS [PolicyExpectedCommission!3!RefFrequencyId], 
    NULL AS [PolicyExpectedCommission!3!ChargingPeriodMonths], 
    NULL AS [PolicyExpectedCommission!3!ExpectedAmount], 
    NULL AS [PolicyExpectedCommission!3!ExpectedStartDate], 
    NULL AS [PolicyExpectedCommission!3!ExpectedCommissionType], 
    NULL AS [PolicyExpectedCommission!3!ParentPolicyExpectedCommissionId], 
    NULL AS [PolicyExpectedCommission!3!PercentageFund], 
    NULL AS [PolicyExpectedCommission!3!Notes], 
    NULL AS [PolicyExpectedCommission!3!ChangedByUser], 
    NULL AS [PolicyExpectedCommission!3!PreDiscountAmount], 
    NULL AS [PolicyExpectedCommission!3!DiscountReasonId], 
    NULL AS [PolicyExpectedCommission!3!ConcurrencyId], 
    NULL AS [Practitioner!4!PractitionerId], 
    NULL AS [Practitioner!4!IndClientId], 
    NULL AS [Practitioner!4!PersonId], 
    NULL AS [Practitioner!4!CRMContactId], 
    NULL AS [Practitioner!4!TnCCoachId], 
    NULL AS [Practitioner!4!AuthorisedFG], 
    NULL AS [Practitioner!4!PIARef], 
    NULL AS [Practitioner!4!AuthorisedDate], 
    NULL AS [Practitioner!4!ExperienceLevel], 
    NULL AS [Practitioner!4!FSAReference], 
    NULL AS [Practitioner!4!MultiTieFg], 
    NULL AS [Practitioner!4!OffPanelFg], 
    NULL AS [Practitioner!4!PractitionerTypeId], 
    NULL AS [Practitioner!4!_ParentId], 
    NULL AS [Practitioner!4!_ParentTable], 
    NULL AS [Practitioner!4!_ParentDb], 
    NULL AS [Practitioner!4!_OwnerId], 
    NULL AS [Practitioner!4!ConcurrencyId], 
    NULL AS [StatusHistory!5!StatusHistoryId], 
    NULL AS [StatusHistory!5!PolicyBusinessId], 
    NULL AS [StatusHistory!5!StatusId], 
    NULL AS [StatusHistory!5!StatusReasonId], 
    NULL AS [StatusHistory!5!ChangedToDate], 
    NULL AS [StatusHistory!5!ChangedByUserId], 
    NULL AS [StatusHistory!5!DateOfChange], 
    NULL AS [StatusHistory!5!LifeCycleStepFG], 
    NULL AS [StatusHistory!5!CurrentStatusFG], 
    NULL AS [StatusHistory!5!ConcurrencyId], 
    NULL AS [PlanDescription!6!PlanDescriptionId], 
    NULL AS [PlanDescription!6!RefPlanType2ProdSubTypeId], 
    NULL AS [PlanDescription!6!RefProdProviderId], 
    NULL AS [PlanDescription!6!SchemeOwnerCRMContactId], 
    NULL AS [PlanDescription!6!SchemeStatus], 
    NULL AS [PlanDescription!6!SchemeNumber], 
    NULL AS [PlanDescription!6!SchemeName], 
    NULL AS [PlanDescription!6!SchemeStatusDate], 
    NULL AS [PlanDescription!6!SchemeSellingAdvisorPractitionerId], 
    NULL AS [PlanDescription!6!MaturityDate], 
    NULL AS [PlanDescription!6!ConcurrencyId], 
    NULL AS [PolicyOwner!7!PolicyOwnerId], 
    NULL AS [PolicyOwner!7!CRMContactId], 
    NULL AS [PolicyOwner!7!PolicyDetailId], 
    NULL AS [PolicyOwner!7!ConcurrencyId], 
    NULL AS [RefProdProvider!8!RefProdProviderId], 
    NULL AS [RefProdProvider!8!CRMContactId], 
    NULL AS [RefProdProvider!8!FundProviderId], 
    NULL AS [RefProdProvider!8!NewProdProviderId], 
    NULL AS [RefProdProvider!8!RetireFg], 
    NULL AS [RefProdProvider!8!ConcurrencyId], 
    NULL AS [Provider!9!CRMContactId], 
    NULL AS [Provider!9!RefCRMContactStatusId], 
    NULL AS [Provider!9!PersonId], 
    NULL AS [Provider!9!CorporateId], 
    NULL AS [Provider!9!TrustId], 
    NULL AS [Provider!9!AdvisorRef], 
    NULL AS [Provider!9!RefSourceOfClientId], 
    NULL AS [Provider!9!SourceValue], 
    NULL AS [Provider!9!Notes], 
    NULL AS [Provider!9!ArchiveFg], 
    NULL AS [Provider!9!LastName], 
    NULL AS [Provider!9!FirstName], 
    NULL AS [Provider!9!CorporateName], 
    NULL AS [Provider!9!DOB], 
    NULL AS [Provider!9!Postcode], 
    NULL AS [Provider!9!OriginalAdviserCRMId], 
    NULL AS [Provider!9!CurrentAdviserCRMId], 
    NULL AS [Provider!9!CurrentAdviserName], 
    NULL AS [Provider!9!CRMContactType], 
    NULL AS [Provider!9!IndClientId], 
    NULL AS [Provider!9!FactFindId], 
    NULL AS [Provider!9!InternalContactFG], 
    NULL AS [Provider!9!RefServiceStatusId], 
    NULL AS [Provider!9!MigrationRef], 
    NULL AS [Provider!9!CreatedDate], 
    NULL AS [Provider!9!ExternalReference], 
    NULL AS [Provider!9!CampaignDataId], 
    NULL AS [Provider!9!AdditionalRef], 
    NULL AS [Provider!9!_ParentId], 
    NULL AS [Provider!9!_ParentTable], 
    NULL AS [Provider!9!_ParentDb], 
    NULL AS [Provider!9!_OwnerId], 
    NULL AS [Provider!9!ConcurrencyId], 
    NULL AS [Owner!10!CRMContactId], 
    NULL AS [Owner!10!RefCRMContactStatusId], 
    NULL AS [Owner!10!PersonId], 
    NULL AS [Owner!10!CorporateId], 
    NULL AS [Owner!10!TrustId], 
    NULL AS [Owner!10!AdvisorRef], 
    NULL AS [Owner!10!RefSourceOfClientId], 
    NULL AS [Owner!10!SourceValue], 
    NULL AS [Owner!10!Notes], 
    NULL AS [Owner!10!ArchiveFg], 
    NULL AS [Owner!10!LastName], 
    NULL AS [Owner!10!FirstName], 
    NULL AS [Owner!10!CorporateName], 
    NULL AS [Owner!10!DOB], 
    NULL AS [Owner!10!Postcode], 
    NULL AS [Owner!10!OriginalAdviserCRMId], 
    NULL AS [Owner!10!CurrentAdviserCRMId], 
    NULL AS [Owner!10!CurrentAdviserName], 
    NULL AS [Owner!10!CRMContactType], 
    NULL AS [Owner!10!IndClientId], 
    NULL AS [Owner!10!FactFindId], 
    NULL AS [Owner!10!InternalContactFG], 
    NULL AS [Owner!10!RefServiceStatusId], 
    NULL AS [Owner!10!MigrationRef], 
    NULL AS [Owner!10!CreatedDate], 
    NULL AS [Owner!10!ExternalReference], 
    NULL AS [Owner!10!CampaignDataId], 
    NULL AS [Owner!10!AdditionalRef], 
    NULL AS [Owner!10!_ParentId], 
    NULL AS [Owner!10!_ParentTable], 
    NULL AS [Owner!10!_ParentDb], 
    NULL AS [Owner!10!_OwnerId], 
    NULL AS [Owner!10!ConcurrencyId], 
    NULL AS [RefCommissionType!11!RefCommissionTypeId], 
    NULL AS [RefCommissionType!11!CommissionTypeName], 
    NULL AS [RefCommissionType!11!OrigoRef], 
    NULL AS [RefCommissionType!11!InitialCommissionFg], 
    NULL AS [RefCommissionType!11!RecurringCommissionFg], 
    NULL AS [RefCommissionType!11!RetireFg], 
    NULL AS [RefCommissionType!11!ConcurrencyId], 
    NULL AS [RefFrequency!12!RefFrequencyId], 
    NULL AS [RefFrequency!12!FrequencyName], 
    NULL AS [RefFrequency!12!OrigoRef], 
    NULL AS [RefFrequency!12!RetireFg], 
    NULL AS [RefFrequency!12!OrderNo], 
    NULL AS [RefFrequency!12!ConcurrencyId], 
    NULL AS [Adviser!13!CRMContactId], 
    NULL AS [Adviser!13!RefCRMContactStatusId], 
    NULL AS [Adviser!13!PersonId], 
    NULL AS [Adviser!13!CorporateId], 
    NULL AS [Adviser!13!TrustId], 
    NULL AS [Adviser!13!AdvisorRef], 
    NULL AS [Adviser!13!RefSourceOfClientId], 
    NULL AS [Adviser!13!SourceValue], 
    NULL AS [Adviser!13!Notes], 
    NULL AS [Adviser!13!ArchiveFg], 
    NULL AS [Adviser!13!LastName], 
    NULL AS [Adviser!13!FirstName], 
    NULL AS [Adviser!13!CorporateName], 
    NULL AS [Adviser!13!DOB], 
    NULL AS [Adviser!13!Postcode], 
    NULL AS [Adviser!13!OriginalAdviserCRMId], 
    NULL AS [Adviser!13!CurrentAdviserCRMId], 
    NULL AS [Adviser!13!CurrentAdviserName], 
    NULL AS [Adviser!13!CRMContactType], 
    NULL AS [Adviser!13!IndClientId], 
    NULL AS [Adviser!13!FactFindId], 
    NULL AS [Adviser!13!InternalContactFG], 
    NULL AS [Adviser!13!RefServiceStatusId], 
    NULL AS [Adviser!13!MigrationRef], 
    NULL AS [Adviser!13!CreatedDate], 
    NULL AS [Adviser!13!ExternalReference], 
    NULL AS [Adviser!13!CampaignDataId], 
    NULL AS [Adviser!13!AdditionalRef], 
    NULL AS [Adviser!13!_ParentId], 
    NULL AS [Adviser!13!_ParentTable], 
    NULL AS [Adviser!13!_ParentDb], 
    NULL AS [Adviser!13!_OwnerId], 
    NULL AS [Adviser!13!ConcurrencyId], 
    NULL AS [Status!14!StatusId], 
    NULL AS [Status!14!Name], 
    NULL AS [Status!14!OrigoStatusId], 
    NULL AS [Status!14!IntelligentOfficeStatusType], 
    NULL AS [Status!14!PreComplianceCheck], 
    NULL AS [Status!14!PostComplianceCheck], 
    NULL AS [Status!14!SystemSubmitFg], 
    NULL AS [Status!14!IndigoClientId], 
    NULL AS [Status!14!ConcurrencyId]
  FROM TPolicyBusiness T1
  -- Note clause
  LEFT JOIN TPolicyBusinessNote TNote
  ON TNote.PolicyBusinessId = T1.PolicyBusinessId AND TNote.IsLatest=1

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    2 AS Tag,
    1 AS Parent,
    T1.PolicyBusinessId, 
    T1.PolicyDetailId, 
    ISNULL(T1.PolicyNumber, ''), 
    T1.PractitionerId, 
    ISNULL(T1.ReplaceNotes, ''), 
    ISNULL(T1.TnCCoachId, ''), 
    T1.AdviceTypeId, 
    T1.BestAdvicePanelUsedFG, 
    T1.WaiverDefermentPeriod, 
    T1.IndigoClientId, 
    T1.SwitchFG, 
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), ''), 
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), ''), 
    ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),''), 
    ISNULL(T1.LifeCycleId, ''), 
    ISNULL(CONVERT(varchar(24), T1.PolicyStartDate, 120),''), 
    ISNULL(T1.PremiumType, ''), 
    ISNULL(T1.AgencyNumber, ''), 
    ISNULL(T1.ProviderAddress, ''), 
    T1.OffPanelFg, 
    ISNULL(T1.BaseCurrency, ''), 
    ISNULL(CONVERT(varchar(24), T1.ExpectedPaymentDate, 120),''), 
    ISNULL(T1.ProductName, ''), 
    ISNULL(T1.InvestmentTypeId, ''), 
    ISNULL(T1.RiskRating, ''), 
    ISNULL(T1.SequentialRef, ''), 
    T1.ConcurrencyId, 
    NULL,
    T2.PolicyDetailId, 
    T2.PlanDescriptionId, 
    ISNULL(T2.TermYears, ''), 
    ISNULL(T2.WholeOfLifeFg, ''), 
    ISNULL(T2.LetterOfAuthorityFg, ''), 
    ISNULL(T2.ContractOutOfSERPSFg, ''), 
    ISNULL(CONVERT(varchar(24), T2.ContractOutStartDate, 120),''), 
    ISNULL(CONVERT(varchar(24), T2.ContractOutStopDate, 120),''), 
    ISNULL(T2.AssignedCRMContactId, ''), 
    ISNULL(CONVERT(varchar(24), T2.JoiningDate, 120),''), 
    ISNULL(CONVERT(varchar(24), T2.LeavingDate, 120),''), 
    T2.IndigoClientId, 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TPolicyDetail T2
  INNER JOIN TPolicyBusiness T1
  ON T2.PolicyDetailId = T1.PolicyDetailId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    3 AS Tag,
    1 AS Parent,
    T1.PolicyBusinessId, 
    T1.PolicyDetailId, 
    ISNULL(T1.PolicyNumber, ''), 
    T1.PractitionerId, 
    ISNULL(T1.ReplaceNotes, ''), 
    ISNULL(T1.TnCCoachId, ''), 
    T1.AdviceTypeId, 
    T1.BestAdvicePanelUsedFG, 
    T1.WaiverDefermentPeriod, 
    T1.IndigoClientId, 
    T1.SwitchFG, 
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), ''), 
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), ''), 
    ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),''), 
    ISNULL(T1.LifeCycleId, ''), 
    ISNULL(CONVERT(varchar(24), T1.PolicyStartDate, 120),''), 
    ISNULL(T1.PremiumType, ''), 
    ISNULL(T1.AgencyNumber, ''), 
    ISNULL(T1.ProviderAddress, ''), 
    T1.OffPanelFg, 
    ISNULL(T1.BaseCurrency, ''), 
    ISNULL(CONVERT(varchar(24), T1.ExpectedPaymentDate, 120),''), 
    ISNULL(T1.ProductName, ''), 
    ISNULL(T1.InvestmentTypeId, ''), 
    ISNULL(T1.RiskRating, ''), 
    ISNULL(T1.SequentialRef, ''), 
    T1.ConcurrencyId, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T3.PolicyExpectedCommissionId, 
    T3.PolicyBusinessId, 
    T3.RefCommissionTypeId, 
    T3.RefPaymentDueTypeId, 
    ISNULL(T3.RefFrequencyId, ''), 
    ISNULL(T3.ChargingPeriodMonths, ''), 
    T3.ExpectedAmount, 
    ISNULL(CONVERT(varchar(24), T3.ExpectedStartDate, 120),''), 
    T3.ExpectedCommissionType, 
    ISNULL(T3.ParentPolicyExpectedCommissionId, ''), 
    ISNULL(CONVERT(varchar(24), T3.PercentageFund),''), 
    ISNULL(T3.Notes, ''), 
    ISNULL(T3.ChangedByUser, ''), 
    ISNULL(CONVERT(varchar(24), T3.PreDiscountAmount),''), 
    ISNULL(T3.DiscountReasonId, ''), 
    T3.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TPolicyExpectedCommission T3
  INNER JOIN TPolicyBusiness T1
  ON T3.PolicyBusinessId = T1.PolicyBusinessId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    4 AS Tag,
    1 AS Parent,
    T1.PolicyBusinessId, 
    T1.PolicyDetailId, 
    ISNULL(T1.PolicyNumber, ''), 
    T1.PractitionerId, 
    ISNULL(T1.ReplaceNotes, ''), 
    ISNULL(T1.TnCCoachId, ''), 
    T1.AdviceTypeId, 
    T1.BestAdvicePanelUsedFG, 
    T1.WaiverDefermentPeriod, 
    T1.IndigoClientId, 
    T1.SwitchFG, 
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), ''), 
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), ''), 
    ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),''), 
    ISNULL(T1.LifeCycleId, ''), 
    ISNULL(CONVERT(varchar(24), T1.PolicyStartDate, 120),''), 
    ISNULL(T1.PremiumType, ''), 
    ISNULL(T1.AgencyNumber, ''), 
    ISNULL(T1.ProviderAddress, ''), 
    T1.OffPanelFg, 
    ISNULL(T1.BaseCurrency, ''), 
    ISNULL(CONVERT(varchar(24), T1.ExpectedPaymentDate, 120),''), 
    ISNULL(T1.ProductName, ''), 
    ISNULL(T1.InvestmentTypeId, ''), 
    ISNULL(T1.RiskRating, ''), 
    ISNULL(T1.SequentialRef, ''), 
    T1.ConcurrencyId, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T4.PractitionerId, 
    T4.IndClientId, 
    ISNULL(T4.PersonId, ''), 
    ISNULL(T4.CRMContactId, ''), 
    ISNULL(T4.TnCCoachId, ''), 
    T4.AuthorisedFG, 
    ISNULL(T4.PIARef, ''), 
    ISNULL(CONVERT(varchar(24), T4.AuthorisedDate, 120),''), 
    ISNULL(T4.ExperienceLevel, ''), 
    T4.FSAReference, 
    T4.MultiTieFg, 
    T4.OffPanelFg, 
    ISNULL(T4.PractitionerTypeId, ''), 
    ISNULL(T4._ParentId, ''), 
    ISNULL(T4._ParentTable, ''), 
    ISNULL(T4._ParentDb, ''), 
    ISNULL(T4._OwnerId, ''), 
    T4.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM [CRM].[dbo].TPractitioner T4
  INNER JOIN TPolicyBusiness T1
  ON T4.PractitionerId = T1.PractitionerId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    5 AS Tag,
    1 AS Parent,
    T1.PolicyBusinessId, 
    T1.PolicyDetailId, 
    ISNULL(T1.PolicyNumber, ''), 
    T1.PractitionerId, 
    ISNULL(T1.ReplaceNotes, ''), 
    ISNULL(T1.TnCCoachId, ''), 
    T1.AdviceTypeId, 
    T1.BestAdvicePanelUsedFG, 
    T1.WaiverDefermentPeriod, 
    T1.IndigoClientId, 
    T1.SwitchFG, 
    ISNULL(CONVERT(varchar(24), T1.TotalRegularPremium), ''), 
    ISNULL(CONVERT(varchar(24), T1.TotalLumpSum), ''), 
    ISNULL(CONVERT(varchar(24), T1.MaturityDate, 120),''), 
    ISNULL(T1.LifeCycleId, ''), 
    ISNULL(CONVERT(varchar(24), T1.PolicyStartDate, 120),''), 
    ISNULL(T1.PremiumType, ''), 
    ISNULL(T1.AgencyNumber, ''), 
    ISNULL(T1.ProviderAddress, ''), 
    T1.OffPanelFg, 
    ISNULL(T1.BaseCurrency, ''), 
    ISNULL(CONVERT(varchar(24), T1.ExpectedPaymentDate, 120),''), 
    ISNULL(T1.ProductName, ''), 
    ISNULL(T1.InvestmentTypeId, ''), 
    ISNULL(T1.RiskRating, ''), 
    ISNULL(T1.SequentialRef, ''), 
    T1.ConcurrencyId, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T5.StatusHistoryId, 
    T5.PolicyBusinessId, 
    T5.StatusId, 
    ISNULL(T5.StatusReasonId, ''), 
    CONVERT(varchar(24), T5.ChangedToDate, 120), 
    T5.ChangedByUserId, 
    ISNULL(CONVERT(varchar(24), T5.DateOfChange, 120),''), 
    T5.LifeCycleStepFG, 
    T5.CurrentStatusFG, 
    T5.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TStatusHistory T5
  INNER JOIN TPolicyBusiness T1
  ON T5.PolicyBusinessId = T1.PolicyBusinessId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    6 AS Tag,
    2 AS Parent,
    T1.PolicyBusinessId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    T2.PolicyDetailId, 
    T2.PlanDescriptionId, 
    ISNULL(T2.TermYears, ''), 
    ISNULL(T2.WholeOfLifeFg, ''), 
    ISNULL(T2.LetterOfAuthorityFg, ''), 
    ISNULL(T2.ContractOutOfSERPSFg, ''), 
    ISNULL(CONVERT(varchar(24), T2.ContractOutStartDate, 120),''), 
    ISNULL(CONVERT(varchar(24), T2.ContractOutStopDate, 120),''), 
    ISNULL(T2.AssignedCRMContactId, ''), 
    ISNULL(CONVERT(varchar(24), T2.JoiningDate, 120),''), 
    ISNULL(CONVERT(varchar(24), T2.LeavingDate, 120),''), 
    T2.IndigoClientId, 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T6.PlanDescriptionId, 
    T6.RefPlanType2ProdSubTypeId, 
    T6.RefProdProviderId, 
    ISNULL(T6.SchemeOwnerCRMContactId, ''), 
    ISNULL(T6.SchemeStatus, ''), 
    ISNULL(T6.SchemeNumber, ''), 
    ISNULL(T6.SchemeName, ''), 
    ISNULL(CONVERT(varchar(24), T6.SchemeStatusDate, 120),''), 
    ISNULL(T6.SchemeSellingAdvisorPractitionerId, ''), 
    ISNULL(CONVERT(varchar(24), T6.MaturityDate, 120),''), 
    T6.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TPlanDescription T6
  INNER JOIN TPolicyDetail T2
  ON T6.PlanDescriptionId = T2.PlanDescriptionId
  INNER JOIN TPolicyBusiness T1
  ON T2.PolicyDetailId = T1.PolicyDetailId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    7 AS Tag,
    2 AS Parent,
    T1.PolicyBusinessId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    T2.PolicyDetailId, 
    T2.PlanDescriptionId, 
    ISNULL(T2.TermYears, ''), 
    ISNULL(T2.WholeOfLifeFg, ''), 
    ISNULL(T2.LetterOfAuthorityFg, ''), 
    ISNULL(T2.ContractOutOfSERPSFg, ''), 
    ISNULL(CONVERT(varchar(24), T2.ContractOutStartDate, 120),''), 
    ISNULL(CONVERT(varchar(24), T2.ContractOutStopDate, 120),''), 
    ISNULL(T2.AssignedCRMContactId, ''), 
    ISNULL(CONVERT(varchar(24), T2.JoiningDate, 120),''), 
    ISNULL(CONVERT(varchar(24), T2.LeavingDate, 120),''), 
    T2.IndigoClientId, 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T7.PolicyOwnerId, 
    T7.CRMContactId, 
    T7.PolicyDetailId, 
    T7.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TPolicyOwner T7
  INNER JOIN TPolicyDetail T2
  ON T7.PolicyDetailId = T2.PolicyDetailId
  INNER JOIN TPolicyBusiness T1
  ON T2.PolicyDetailId = T1.PolicyDetailId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    8 AS Tag,
    6 AS Parent,
    T1.PolicyBusinessId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    T2.PolicyDetailId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T6.PlanDescriptionId, 
    T6.RefPlanType2ProdSubTypeId, 
    T6.RefProdProviderId, 
    ISNULL(T6.SchemeOwnerCRMContactId, ''), 
    ISNULL(T6.SchemeStatus, ''), 
    ISNULL(T6.SchemeNumber, ''), 
    ISNULL(T6.SchemeName, ''), 
    ISNULL(CONVERT(varchar(24), T6.SchemeStatusDate, 120),''), 
    ISNULL(T6.SchemeSellingAdvisorPractitionerId, ''), 
    ISNULL(CONVERT(varchar(24), T6.MaturityDate, 120),''), 
    T6.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T8.RefProdProviderId, 
    ISNULL(T8.CRMContactId, ''), 
    ISNULL(T8.FundProviderId, ''), 
    ISNULL(T8.NewProdProviderId, ''), 
    T8.RetireFg, 
    T8.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TRefProdProvider T8
  INNER JOIN TPlanDescription T6
  ON T8.RefProdProviderId = T6.RefProdProviderId
  INNER JOIN TPolicyDetail T2
  ON T6.PlanDescriptionId = T2.PlanDescriptionId
  INNER JOIN TPolicyBusiness T1
  ON T2.PolicyDetailId = T1.PolicyDetailId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    9 AS Tag,
    8 AS Parent,
    T1.PolicyBusinessId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    T2.PolicyDetailId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T6.PlanDescriptionId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T8.RefProdProviderId, 
    ISNULL(T8.CRMContactId, ''), 
    ISNULL(T8.FundProviderId, ''), 
    ISNULL(T8.NewProdProviderId, ''), 
    T8.RetireFg, 
    T8.ConcurrencyId, 
    T9.CRMContactId, 
    ISNULL(T9.RefCRMContactStatusId, ''), 
    ISNULL(T9.PersonId, ''), 
    ISNULL(T9.CorporateId, ''), 
    ISNULL(T9.TrustId, ''), 
    ISNULL(T9.AdvisorRef, ''), 
    ISNULL(T9.RefSourceOfClientId, ''), 
    ISNULL(T9.SourceValue, ''), 
    ISNULL(T9.Notes, ''), 
    ISNULL(T9.ArchiveFg, ''), 
    ISNULL(T9.LastName, ''), 
    ISNULL(T9.FirstName, ''), 
    ISNULL(T9.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T9.DOB, 120),''), 
    ISNULL(T9.Postcode, ''), 
    T9.OriginalAdviserCRMId, 
    T9.CurrentAdviserCRMId, 
    ISNULL(T9.CurrentAdviserName, ''), 
    T9.CRMContactType, 
    T9.IndClientId, 
    ISNULL(T9.FactFindId, ''), 
    ISNULL(T9.InternalContactFG, ''), 
    ISNULL(T9.RefServiceStatusId, ''), 
    ISNULL(T9.MigrationRef, ''), 
    CONVERT(varchar(24), T9.CreatedDate, 120), 
    ISNULL(T9.ExternalReference, ''), 
    ISNULL(T9.CampaignDataId, ''), 
    ISNULL(T9.AdditionalRef, ''), 
    ISNULL(T9._ParentId, ''), 
    ISNULL(T9._ParentTable, ''), 
    ISNULL(T9._ParentDb, ''), 
    ISNULL(T9._OwnerId, ''), 
    T9.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM [CRM].[dbo].TCRMContact T9
  INNER JOIN TRefProdProvider T8
  ON T9.CRMContactId = T8.CRMContactId
  INNER JOIN TPlanDescription T6
  ON T8.RefProdProviderId = T6.RefProdProviderId
  INNER JOIN TPolicyDetail T2
  ON T6.PlanDescriptionId = T2.PlanDescriptionId
  INNER JOIN TPolicyBusiness T1
  ON T2.PolicyDetailId = T1.PolicyDetailId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    10 AS Tag,
    7 AS Parent,
    T1.PolicyBusinessId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    T2.PolicyDetailId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T7.PolicyOwnerId, 
    T7.CRMContactId, 
    T7.PolicyDetailId, 
    T7.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T10.CRMContactId, 
    ISNULL(T10.RefCRMContactStatusId, ''), 
    ISNULL(T10.PersonId, ''), 
    ISNULL(T10.CorporateId, ''), 
    ISNULL(T10.TrustId, ''), 
    ISNULL(T10.AdvisorRef, ''), 
    ISNULL(T10.RefSourceOfClientId, ''), 
    ISNULL(T10.SourceValue, ''), 
    ISNULL(T10.Notes, ''), 
    ISNULL(T10.ArchiveFg, ''), 
    ISNULL(T10.LastName, ''), 
    ISNULL(T10.FirstName, ''), 
    ISNULL(T10.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T10.DOB, 120),''), 
    ISNULL(T10.Postcode, ''), 
    T10.OriginalAdviserCRMId, 
    T10.CurrentAdviserCRMId, 
    ISNULL(T10.CurrentAdviserName, ''), 
    T10.CRMContactType, 
    T10.IndClientId, 
    ISNULL(T10.FactFindId, ''), 
    ISNULL(T10.InternalContactFG, ''), 
    ISNULL(T10.RefServiceStatusId, ''), 
    ISNULL(T10.MigrationRef, ''), 
    CONVERT(varchar(24), T10.CreatedDate, 120), 
    ISNULL(T10.ExternalReference, ''), 
    ISNULL(T10.CampaignDataId, ''), 
    ISNULL(T10.AdditionalRef, ''), 
    ISNULL(T10._ParentId, ''), 
    ISNULL(T10._ParentTable, ''), 
    ISNULL(T10._ParentDb, ''), 
    ISNULL(T10._OwnerId, ''), 
    T10.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM [CRM].[dbo].TCRMContact T10
  INNER JOIN TPolicyOwner T7
  ON T10.CRMContactId = T7.CRMContactId
  INNER JOIN TPolicyDetail T2
  ON T7.PolicyDetailId = T2.PolicyDetailId
  INNER JOIN TPolicyBusiness T1
  ON T2.PolicyDetailId = T1.PolicyDetailId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    11 AS Tag,
    3 AS Parent,
    T1.PolicyBusinessId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T3.PolicyExpectedCommissionId, 
    T3.PolicyBusinessId, 
    T3.RefCommissionTypeId, 
    T3.RefPaymentDueTypeId, 
    ISNULL(T3.RefFrequencyId, ''), 
    ISNULL(T3.ChargingPeriodMonths, ''), 
    T3.ExpectedAmount, 
    ISNULL(CONVERT(varchar(24), T3.ExpectedStartDate, 120),''), 
    T3.ExpectedCommissionType, 
    ISNULL(T3.ParentPolicyExpectedCommissionId, ''), 
    ISNULL(CONVERT(varchar(24), T3.PercentageFund),''), 
    ISNULL(T3.Notes, ''), 
    ISNULL(T3.ChangedByUser, ''), 
    ISNULL(CONVERT(varchar(24), T3.PreDiscountAmount),''), 
    ISNULL(T3.DiscountReasonId, ''), 
    T3.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T11.RefCommissionTypeId, 
    ISNULL(T11.CommissionTypeName, ''), 
    ISNULL(T11.OrigoRef, ''), 
    ISNULL(T11.InitialCommissionFg, ''), 
    ISNULL(T11.RecurringCommissionFg, ''), 
    ISNULL(T11.RetireFg, ''), 
    T11.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TRefCommissionType T11
  INNER JOIN TPolicyExpectedCommission T3
  ON T11.RefCommissionTypeId = T3.RefCommissionTypeId
  INNER JOIN TPolicyBusiness T1
  ON T3.PolicyBusinessId = T1.PolicyBusinessId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    12 AS Tag,
    3 AS Parent,
    T1.PolicyBusinessId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T3.PolicyExpectedCommissionId, 
    T3.PolicyBusinessId, 
    T3.RefCommissionTypeId, 
    T3.RefPaymentDueTypeId, 
    ISNULL(T3.RefFrequencyId, ''), 
    ISNULL(T3.ChargingPeriodMonths, ''), 
    T3.ExpectedAmount, 
    ISNULL(CONVERT(varchar(24), T3.ExpectedStartDate, 120),''), 
    T3.ExpectedCommissionType, 
    ISNULL(T3.ParentPolicyExpectedCommissionId, ''), 
    ISNULL(CONVERT(varchar(24), T3.PercentageFund),''), 
    ISNULL(T3.Notes, ''), 
    ISNULL(T3.ChangedByUser, ''), 
    ISNULL(CONVERT(varchar(24), T3.PreDiscountAmount),''), 
    ISNULL(T3.DiscountReasonId, ''), 
    T3.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T12.RefFrequencyId, 
    ISNULL(T12.FrequencyName, ''), 
    ISNULL(T12.OrigoRef, ''), 
    ISNULL(T12.RetireFg, ''), 
    ISNULL(T12.OrderNo, ''), 
    T12.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TRefFrequency T12
  INNER JOIN TPolicyExpectedCommission T3
  ON T12.RefFrequencyId = T3.RefFrequencyId
  INNER JOIN TPolicyBusiness T1
  ON T3.PolicyBusinessId = T1.PolicyBusinessId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    13 AS Tag,
    4 AS Parent,
    T1.PolicyBusinessId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T4.PractitionerId, 
    T4.IndClientId, 
    ISNULL(T4.PersonId, ''), 
    ISNULL(T4.CRMContactId, ''), 
    ISNULL(T4.TnCCoachId, ''), 
    T4.AuthorisedFG, 
    ISNULL(T4.PIARef, ''), 
    ISNULL(CONVERT(varchar(24), T4.AuthorisedDate, 120),''), 
    ISNULL(T4.ExperienceLevel, ''), 
    T4.FSAReference, 
    T4.MultiTieFg, 
    T4.OffPanelFg, 
    ISNULL(T4.PractitionerTypeId, ''), 
    ISNULL(T4._ParentId, ''), 
    ISNULL(T4._ParentTable, ''), 
    ISNULL(T4._ParentDb, ''), 
    ISNULL(T4._OwnerId, ''), 
    T4.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T13.CRMContactId, 
    ISNULL(T13.RefCRMContactStatusId, ''), 
    ISNULL(T13.PersonId, ''), 
    ISNULL(T13.CorporateId, ''), 
    ISNULL(T13.TrustId, ''), 
    ISNULL(T13.AdvisorRef, ''), 
    ISNULL(T13.RefSourceOfClientId, ''), 
    ISNULL(T13.SourceValue, ''), 
    ISNULL(T13.Notes, ''), 
    ISNULL(T13.ArchiveFg, ''), 
    ISNULL(T13.LastName, ''), 
    ISNULL(T13.FirstName, ''), 
    ISNULL(T13.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T13.DOB, 120),''), 
    ISNULL(T13.Postcode, ''), 
    T13.OriginalAdviserCRMId, 
    T13.CurrentAdviserCRMId, 
    ISNULL(T13.CurrentAdviserName, ''), 
    T13.CRMContactType, 
    T13.IndClientId, 
    ISNULL(T13.FactFindId, ''), 
    ISNULL(T13.InternalContactFG, ''), 
    ISNULL(T13.RefServiceStatusId, ''), 
    ISNULL(T13.MigrationRef, ''), 
    CONVERT(varchar(24), T13.CreatedDate, 120), 
    ISNULL(T13.ExternalReference, ''), 
    ISNULL(T13.CampaignDataId, ''), 
    ISNULL(T13.AdditionalRef, ''), 
    ISNULL(T13._ParentId, ''), 
    ISNULL(T13._ParentTable, ''), 
    ISNULL(T13._ParentDb, ''), 
    ISNULL(T13._OwnerId, ''), 
    T13.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM [CRM].[dbo].TCRMContact T13
  INNER JOIN [CRM].[dbo].TPractitioner T4
  ON T13.CRMContactId = T4.CRMContactId
  INNER JOIN TPolicyBusiness T1
  ON T4.PractitionerId = T1.PractitionerId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  UNION ALL

  SELECT
    14 AS Tag,
    5 AS Parent,
    T1.PolicyBusinessId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T5.StatusHistoryId, 
    T5.PolicyBusinessId, 
    T5.StatusId, 
    ISNULL(T5.StatusReasonId, ''), 
    CONVERT(varchar(24), T5.ChangedToDate, 120), 
    T5.ChangedByUserId, 
    ISNULL(CONVERT(varchar(24), T5.DateOfChange, 120),''), 
    T5.LifeCycleStepFG, 
    T5.CurrentStatusFG, 
    T5.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T14.StatusId, 
    T14.Name, 
    ISNULL(T14.OrigoStatusId, ''), 
    ISNULL(T14.IntelligentOfficeStatusType, ''), 
    T14.PreComplianceCheck, 
    T14.PostComplianceCheck, 
    T14.SystemSubmitFg, 
    T14.IndigoClientId, 
    T14.ConcurrencyId
  FROM TStatus T14
  INNER JOIN TStatusHistory T5
  ON T14.StatusId = T5.StatusId
  INNER JOIN TPolicyBusiness T1
  ON T5.PolicyBusinessId = T1.PolicyBusinessId

  WHERE (T1.PolicyBusinessId = @PolicyBusinessId)

  ORDER BY [PolicyBusiness!1!PolicyBusinessId], [StatusHistory!5!StatusHistoryId], [Status!14!StatusId], [Practitioner!4!PractitionerId], [Adviser!13!CRMContactId], [PolicyExpectedCommission!3!PolicyExpectedCommissionId], [RefFrequency!12!RefFrequencyId], [RefCommissionType!11!RefCommissionTypeId], [PolicyDetail!2!PolicyDetailId], [PolicyOwner!7!PolicyOwnerId], [Owner!10!CRMContactId], [PlanDescription!6!PlanDescriptionId], [RefProdProvider!8!RefProdProviderId], [Provider!9!CRMContactId]

  FOR XML EXPLICIT

END
RETURN (0)

GO
