SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SpCreatePensionInfo]
	@StampUser varchar (255),
	@PolicyBusinessId bigint, 
	@SRA int = NULL, 
	@PensionableSalary money = NULL, 
	@RefReturnDeathTypeId bigint = NULL, 
	@ReturnOnDeathRate decimal = NULL, 
	@ProtectedRightsOnly bit = NULL, 
	@QualifiesDSSIncentive bit = NULL, 
	@RefLifeCoverId bigint = NULL, 
	@RebatePaid bit = NULL, 
	@ContributionUpdated bit = NULL, 
	@IsCurrent bit = NULL, 
	@RefSchemeSetUpId bigint = NULL, 
	@HasWidowsPension bit = NULL, 
	@HasProtectionAgainstInflation bit = NULL, 
	@ProvidesTaxFreeLumpSum bit = NULL, 
	@ContractedOutOfS2P bit = NULL, 
	@ExpectedYearsOfService tinyint = NULL, 
	@NumberOfYearsCompleted tinyint = NULL, 
	@IsIndexed bit = NULL, 
	@RefSchemeBasisId bigint = NULL, 
	@FinalSalary money = NULL, 
	@RefContributionPercentageId bigint = NULL, 
	@SpousePensionPayableOnDeath money = NULL, 
	@ServiceBenefitSpouseEntitled money = NULL, 
	@BenefitsPayableOnDeath money = NULL, 
	@DeathBenefit money = NULL, 
	@IsInTrust bit = NULL, 
	@IsNRADeffered bit = NULL,
	@EmploymentDetailId int = NULL,
	@CrystallisationStatus varchar = NULL,
	@PensionSharingPercentage decimal = NULL,
	@PensionAttachmentOrder nvarchar = NULL,
	@UntaxedPensionAmount money = NULL, 
	@CentrelinkDeductibleAmount money = NULL,
	@TaxFreePercentageOfIncome decimal = NULL,
	@HistoricalCrystallisedPercentage int = NULL,
	@CurrentCrystallisedPercentage int = NULL,
	@CrystallisedPercentage int = NULL,
	@UncrystallisedPercentage int = NULL
AS

SET NOCOUNT ON

DECLARE @tx int
SELECT @tx = @@TRANCOUNT
IF @tx = 0 BEGIN TRANSACTION TX

BEGIN
	
	DECLARE @PensionInfoId bigint
			
	
	INSERT INTO TPensionInfo (
		PolicyBusinessId, 
		SRA, 
		PensionableSalary, 
		RefReturnDeathTypeId, 
		ReturnOnDeathRate, 
		ProtectedRightsOnly, 
		QualifiesDSSIncentive, 
		RefLifeCoverId, 
		RebatePaid, 
		ContributionUpdated, 
		IsCurrent, 
		RefSchemeSetUpId, 
		HasWidowsPension, 
		HasProtectionAgainstInflation, 
		ProvidesTaxFreeLumpSum, 
		ContractedOutOfS2P, 
		ExpectedYearsOfService, 
		NumberOfYearsCompleted, 
		IsIndexed, 
		RefSchemeBasisId, 
		FinalSalary, 
		RefContributionPercentageId, 
		SpousePensionPayableOnDeath, 
		ServiceBenefitSpouseEntitled, 
		BenefitsPayableOnDeath, 
		DeathBenefit, 
		IsInTrust, 
		IsNRADeffered, 
		ConcurrencyId,
		EmploymentDetailId,
		CrystallisationStatus,
		PensionSharingPercentage,
		PensionAttachmentOrder,
		UntaxedPensionAmount,
		CentrelinkDeductibleAmount,
		TaxFreePercentageOfIncome,
		HistoricalCrystallisedPercentage,
		CurrentCrystallisedPercentage,
		CrystallisedPercentage,
		UncrystallisedPercentage)
		
	VALUES(
		@PolicyBusinessId, 
		@SRA, 
		@PensionableSalary, 
		@RefReturnDeathTypeId, 
		@ReturnOnDeathRate, 
		@ProtectedRightsOnly, 
		@QualifiesDSSIncentive, 
		@RefLifeCoverId, 
		@RebatePaid, 
		@ContributionUpdated, 
		@IsCurrent, 
		@RefSchemeSetUpId, 
		@HasWidowsPension, 
		@HasProtectionAgainstInflation, 
		@ProvidesTaxFreeLumpSum, 
		@ContractedOutOfS2P, 
		@ExpectedYearsOfService, 
		@NumberOfYearsCompleted, 
		@IsIndexed, 
		@RefSchemeBasisId, 
		@FinalSalary, 
		@RefContributionPercentageId, 
		@SpousePensionPayableOnDeath, 
		@ServiceBenefitSpouseEntitled, 
		@BenefitsPayableOnDeath, 
		@DeathBenefit, 
		@IsInTrust, 
		@IsNRADeffered,
		1,
		@EmploymentDetailId,
		@CrystallisationStatus,
		@PensionSharingPercentage,
		@PensionAttachmentOrder,
		@UntaxedPensionAmount,
		@CentrelinkDeductibleAmount,
		@TaxFreePercentageOfIncome,
		@HistoricalCrystallisedPercentage,
		@CurrentCrystallisedPercentage,
		@CrystallisedPercentage,
		@UncrystallisedPercentage)

	SELECT @PensionInfoId = SCOPE_IDENTITY()

	INSERT INTO TPensionInfoAudit (
		PolicyBusinessId, 
		SRA, 
		PensionableSalary, 
		RefReturnDeathTypeId, 
		ReturnOnDeathRate, 
		ProtectedRightsOnly, 
		QualifiesDSSIncentive, 
		RefLifeCoverId, 
		RebatePaid, 
		ContributionUpdated, 
		IsCurrent, 
		RefSchemeSetUpId, 
		HasWidowsPension, 
		HasProtectionAgainstInflation, 
		ProvidesTaxFreeLumpSum, 
		ContractedOutOfS2P, 
		ExpectedYearsOfService, 
		NumberOfYearsCompleted, 
		IsIndexed, 
		RefSchemeBasisId, 
		FinalSalary, 
		RefContributionPercentageId, 
		SpousePensionPayableOnDeath, 
		ServiceBenefitSpouseEntitled, 
		BenefitsPayableOnDeath, 
		DeathBenefit, 
		IsInTrust, 
		IsNRADeffered, 
		ConcurrencyId,
		PensionInfoId,
		StampAction,
		StampDateTime,
		StampUser,
		EmploymentDetailId,
		CrystallisationStatus,
		PensionSharingPercentage,
		PensionAttachmentOrder,
		UntaxedPensionAmount,
		CentrelinkDeductibleAmount,
		TaxFreePercentageOfIncome,
		HistoricalCrystallisedPercentage,
		CurrentCrystallisedPercentage,
		CrystallisedPercentage,
		UncrystallisedPercentage)
	SELECT  
		PolicyBusinessId, 
		SRA, 
		PensionableSalary, 
		RefReturnDeathTypeId, 
		ReturnOnDeathRate, 
		ProtectedRightsOnly, 
		QualifiesDSSIncentive, 
		RefLifeCoverId, 
		RebatePaid, 
		ContributionUpdated, 
		IsCurrent, 
		RefSchemeSetUpId, 
		HasWidowsPension, 
		HasProtectionAgainstInflation, 
		ProvidesTaxFreeLumpSum, 
		ContractedOutOfS2P, 
		ExpectedYearsOfService, 
		NumberOfYearsCompleted, 
		IsIndexed, 
		RefSchemeBasisId, 
		FinalSalary, 
		RefContributionPercentageId, 
		SpousePensionPayableOnDeath, 
		ServiceBenefitSpouseEntitled, 
		BenefitsPayableOnDeath, 
		DeathBenefit, 
		IsInTrust, 
		IsNRADeffered, 
		ConcurrencyId,
		PensionInfoId,
		'C',
		GetDate(),
		@StampUser,
		EmploymentDetailId,
		CrystallisationStatus,
		PensionSharingPercentage,
		PensionAttachmentOrder,
		UntaxedPensionAmount,
		CentrelinkDeductibleAmount,
		TaxFreePercentageOfIncome,
		HistoricalCrystallisedPercentage,
		CurrentCrystallisedPercentage,
		CrystallisedPercentage,
		UncrystallisedPercentage
		
		
	FROM TPensionInfo
	WHERE PensionInfoId = @PensionInfoId

	EXEC SpRetrievePensionInfoById @PensionInfoId

IF @@ERROR != 0 GOTO errh
IF @tx = 0 COMMIT TRANSACTION TX

END
RETURN (0)

errh:
  IF @tx = 0 ROLLBACK TRANSACTION TX
  RETURN (100)

GO
