SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SpCreateMortgage]
	@StampUser varchar (255),
	@PolicyBusinessId bigint, 
	@IndigoClientId bigint, 
	@MortgageRefNo varchar(50)  = NULL, 
	@LoanAmount money = NULL, 
	@InterestRate decimal (10,5)  = NULL, 
	@MortgageType varchar(100)  = NULL, 
	@MortgageTypeOther varchar(1000)  = NULL, 
	@FeatureExpiryDate datetime = NULL, 
	@PenaltyFg bit, 
	@PenaltyExpiryDate datetime = NULL, 
	@RedemptionTerms varchar(1000)  = NULL, 
	@SchemeRate decimal (10,2)  = NULL, 
	@SchemeEndDate datetime = NULL, 
	@CompletionDate datetime = NULL, 
	@SVR decimal (10,2)  = NULL, 
	@PortableFg bit = 1, 
	@RedeemedFg bit = NULL, 
	@SoldFg bit = NULL, 
	@AssetsId bigint = NULL, 
	@LiabilitiesId bigint = NULL, 
	@ReviewDiaryDate datetime = NULL, 
	@RefMortgageBorrowerTypeId bigint = NULL, 
	@RefMortgageRepaymentMethodId bigint = NULL, 
	@RefMortgageProductTypeId bigint = NULL, 
	@MortgageTerm int = NULL, 
	@MortgageTermMonths int = NULL, 
	@RemainingTerm int = NULL, 
	@PropertyValue bigint = NULL, 
	@IncomeEvidencedFg bit = 0, 
	@AddressStoreId bigint = NULL, 
	@LoanPurpose varchar(50)  = NULL, 
	@PriceValuation money = NULL, 
	@Deposit money = NULL, 
	@InterestOnlyAmount money = NULL, 
	@RepaymentAmount money = NULL, 
	@LTV decimal (10,2)  = NULL, 
	@ApplicationSubmitted datetime = NULL, 
	@ValuationInstructed datetime = NULL, 
	@ValuationDate datetime = NULL, 
	@ValuationReceived datetime = NULL, 
	@OfferIssued datetime = NULL, 
	@ExchangeDate datetime = NULL, 
	@IsCurrentResidence bit = NULL, 
	@IsResdidenceAfterComplete bit = NULL, 
	@CurrentBalance money = NULL, 
	@WillPayRedemption bit = NULL, 
	@WillBeDischarged bit = NULL, 
	@RedemptionAmount money = NULL, 
	@StatusFg bit = 0, 
	@NonStatusFg bit = 0, 
	@SelfCertFg bit = 0	
AS

SET NOCOUNT ON

DECLARE @tx int
SELECT @tx = @@TRANCOUNT
IF @tx = 0 BEGIN TRANSACTION TX

BEGIN
	
	DECLARE @MortgageId bigint
			
	
	INSERT INTO TMortgage (
		PolicyBusinessId, 
		IndigoClientId, 
		MortgageRefNo, 
		LoanAmount, 
		InterestRate, 
		MortgageType, 
		MortgageTypeOther, 
		FeatureExpiryDate, 
		PenaltyFg, 
		PenaltyExpiryDate, 
		RedemptionTerms, 
		SchemeRate, 
		SchemeEndDate, 
		CompletionDate, 
		SVR, 
		PortableFg, 
		RedeemedFg, 
		SoldFg, 
		AssetsId, 
		LiabilitiesId, 
		ReviewDiaryDate, 
		RefMortgageBorrowerTypeId, 
		RefMortgageRepaymentMethodId, 
		RefMortgageProductTypeId, 
		MortgageTerm, 
		MortgageTermMonths, 
		RemainingTerm, 
		PropertyValue, 
		IncomeEvidencedFg, 
		AddressStoreId, 
		LoanPurpose, 
		PriceValuation, 
		Deposit, 
		InterestOnlyAmount, 
		RepaymentAmount, 
		LTV, 
		ApplicationSubmitted, 
		ValuationInstructed, 
		ValuationDate, 
		ValuationReceived, 
		OfferIssued, 
		ExchangeDate, 
		IsCurrentResidence, 
		IsResdidenceAfterComplete, 
		CurrentBalance, 
		WillPayRedemption, 
		WillBeDischarged, 
		RedemptionAmount, 
		StatusFg, 
		NonStatusFg, 
		SelfCertFg, 
		ConcurrencyId)
		
	VALUES(
		@PolicyBusinessId, 
		@IndigoClientId, 
		@MortgageRefNo, 
		@LoanAmount, 
		@InterestRate, 
		@MortgageType, 
		@MortgageTypeOther, 
		@FeatureExpiryDate, 
		@PenaltyFg, 
		@PenaltyExpiryDate, 
		@RedemptionTerms, 
		@SchemeRate, 
		@SchemeEndDate, 
		@CompletionDate, 
		@SVR, 
		@PortableFg, 
		@RedeemedFg, 
		@SoldFg, 
		@AssetsId, 
		@LiabilitiesId, 
		@ReviewDiaryDate, 
		@RefMortgageBorrowerTypeId, 
		@RefMortgageRepaymentMethodId, 
		@RefMortgageProductTypeId, 
		@MortgageTerm, 
		@MortgageTermMonths, 
		@RemainingTerm, 
		@PropertyValue, 
		@IncomeEvidencedFg, 
		@AddressStoreId, 
		@LoanPurpose, 
		@PriceValuation, 
		@Deposit, 
		@InterestOnlyAmount, 
		@RepaymentAmount, 
		@LTV, 
		@ApplicationSubmitted, 
		@ValuationInstructed, 
		@ValuationDate, 
		@ValuationReceived, 
		@OfferIssued, 
		@ExchangeDate, 
		@IsCurrentResidence, 
		@IsResdidenceAfterComplete, 
		@CurrentBalance, 
		@WillPayRedemption, 
		@WillBeDischarged, 
		@RedemptionAmount, 
		@StatusFg, 
		@NonStatusFg, 
		@SelfCertFg,
		1)

	SELECT @MortgageId = SCOPE_IDENTITY()
	
	INSERT INTO TMortgageAudit (
		PolicyBusinessId, 
		IndigoClientId, 
		MortgageRefNo, 
		LoanAmount, 
		InterestRate, 
		MortgageType, 
		MortgageTypeOther, 
		FeatureExpiryDate, 
		PenaltyFg, 
		PenaltyExpiryDate, 
		RedemptionTerms, 
		SchemeRate, 
		SchemeEndDate, 
		CompletionDate, 
		SVR, 
		PortableFg, 
		RedeemedFg, 
		SoldFg, 
		AssetsId, 
		LiabilitiesId, 
		ReviewDiaryDate, 
		RefMortgageBorrowerTypeId, 
		RefMortgageRepaymentMethodId, 
		RefMortgageProductTypeId, 
		MortgageTerm, 
		MortgageTermMonths, 
		RemainingTerm, 
		PropertyValue, 
		IncomeEvidencedFg, 
		AddressStoreId, 
		LoanPurpose, 
		PriceValuation, 
		Deposit, 
		InterestOnlyAmount, 
		RepaymentAmount, 
		LTV, 
		ApplicationSubmitted, 
		ValuationInstructed, 
		ValuationDate, 
		ValuationReceived, 
		OfferIssued, 
		ExchangeDate, 
		IsCurrentResidence, 
		IsResdidenceAfterComplete, 
		CurrentBalance, 
		WillPayRedemption, 
		WillBeDischarged, 
		RedemptionAmount, 
		StatusFg, 
		NonStatusFg, 
		SelfCertFg, 
		ConcurrencyId,
		MortgageId,
		StampAction,
    	StampDateTime,
    	StampUser)
	SELECT  
		PolicyBusinessId, 
		IndigoClientId, 
		MortgageRefNo, 
		LoanAmount, 
		InterestRate, 
		MortgageType, 
		MortgageTypeOther, 
		FeatureExpiryDate, 
		PenaltyFg, 
		PenaltyExpiryDate, 
		RedemptionTerms, 
		SchemeRate, 
		SchemeEndDate, 
		CompletionDate, 
		SVR, 
		PortableFg, 
		RedeemedFg, 
		SoldFg, 
		AssetsId, 
		LiabilitiesId, 
		ReviewDiaryDate, 
		RefMortgageBorrowerTypeId, 
		RefMortgageRepaymentMethodId, 
		RefMortgageProductTypeId, 
		MortgageTerm, 
		MortgageTermMonths, 
		RemainingTerm, 
		PropertyValue, 
		IncomeEvidencedFg, 
		AddressStoreId, 
		LoanPurpose, 
		PriceValuation, 
		Deposit, 
		InterestOnlyAmount, 
		RepaymentAmount, 
		LTV, 
		ApplicationSubmitted, 
		ValuationInstructed, 
		ValuationDate, 
		ValuationReceived, 
		OfferIssued, 
		ExchangeDate, 
		IsCurrentResidence, 
		IsResdidenceAfterComplete, 
		CurrentBalance, 
		WillPayRedemption, 
		WillBeDischarged, 
		RedemptionAmount, 
		StatusFg, 
		NonStatusFg, 
		SelfCertFg, 
		ConcurrencyId,
		MortgageId,
		'C',
    	GetDate(),
    	@StampUser
	FROM TMortgage
	WHERE MortgageId = @MortgageId
	EXEC SpRetrieveMortgageById @MortgageId

IF @@ERROR != 0 GOTO errh
IF @tx = 0 COMMIT TRANSACTION TX

END
RETURN (0)

errh:
  IF @tx = 0 ROLLBACK TRANSACTION TX
  RETURN (100)
GO
