CREATE TABLE [dbo].[TPensionInfoAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[PolicyBusinessId] [int] NOT NULL,
[SRA] [int] NULL,
[PensionableSalary] [money] NULL,
[RefReturnDeathTypeId] [int] NULL,
[ReturnOnDeathRate] [decimal] (5, 2) NULL,
[ProtectedRightsOnly] [bit] NULL,
[QualifiesDSSIncentive] [bit] NULL,
[RefLifeCoverId] [int] NULL,
[RebatePaid] [bit] NULL,
[ContributionUpdated] [bit] NULL,
[IsCurrent] [bit] NULL,
[RefSchemeSetUpId] [int] NULL,
[HasWidowsPension] [bit] NULL,
[HasProtectionAgainstInflation] [bit] NULL,
[ProvidesTaxFreeLumpSum] [bit] NULL,
[ContractedOutOfS2P] [bit] NULL,
[ExpectedYearsOfService] [tinyint] NULL,
[NumberOfYearsCompleted] [tinyint] NULL,
[IsIndexed] [bit] NULL,
[RefSchemeBasisId] [int] NULL,
[FinalSalary] [money] NULL,
[RefContributionPercentageId] [int] NULL,
[SpousePensionPayableOnDeath] [money] NULL,
[ServiceBenefitSpouseEntitled] [money] NULL,
[BenefitsPayableOnDeath] [money] NULL,
[DeathBenefit] [money] NULL,
[IsInTrust] [bit] NULL,
[IsNRADeffered] [bit] NULL,
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF_TPensionIn_ConcurrencyId_1__98] DEFAULT ((1)),
[PensionInfoId] [int] NOT NULL,
[StampAction] [char] (1) NOT NULL,
[StampDateTime] [datetime] NULL CONSTRAINT [DF_TPensionIn_StampDateTime_2__98] DEFAULT (getdate()),
[StampUser] [varchar] (255) NULL,
[AccrualRate] [int] NULL,
[NICSaving] [tinyint] NULL,
[PercentageReinvestedToPension] [decimal] (18, 0) NULL,
[NICSavingemployee] [tinyint] NULL,
[SECommencementDate] [datetime] NULL,
[IsContributionsPaid] [bit] NULL,
[GMPAmount] [money] NULL,
[ProspectivePensionAtRetirement] [money] NULL,
[ProspectiveLumpSumAtRetirement] [money] NULL,
[PostSacrificeSalary] [money] NULL,
[SelectedRetirementAge] [int] NULL,
[EarlyRetirementFactorNotes] [varchar] (1000) null,
[DependantBenefits] [varchar] (100) null,
[IndexationNotes] [varchar] (1000) null,
[EnhancedTaxFreeCash] [varchar] (100) null,
[GuaranteedAnnuityRate] [varchar] (100) null,
[ApplicablePenalties] [varchar] (100) null,
[EfiLoyaltyTerminalBonus] [varchar] (100) null,
[GuaranteedGrowthRate] [varchar] (100) null,
[OptionsAvailableAtRetirement] [varchar] (1000) null,
[OtherBenefitsAndMaterialFeatures] [varchar] (1000) null,
[ProspectivePensionAtRetirementLumpSumTaken] [money] NULL,
[LifetimeAllowanceUsed] [decimal] (5, 2) NULL,
[PlanMigrationRef] [varchar] (255) NULL,
[IndigoClientId] [int] NULL,
[EmployerContributionDetail] [VARCHAR](4000) NULL,
[IsLifeStylingStrategy] [BIT] NULL,
[LifeStylingStrategyDetail] [VARCHAR](4000) NULL,
[YearsPurchaseAvailability] [bit] NULL,
[YearsPurchaseAvailabilityDetails] [varchar] (4000) NULL,
[AffinityContributionAvailability] [bit] NULL,
[AffinityContributionAvailabilityDetails] [varchar] (4000) NULL,
[CashEquivalentTransferValue] [money] NULL,
[TransferExpiryDate] [date] NULL,
[EmploymentDetailId] [int] NULL,
[CrystallisationStatus] [varchar](20) NULL,
[PensionSharingPercentage] [decimal](5, 2) NULL,
[PensionAttachmentOrder] [nvarchar](100) NULL,
[TaxedPensionAmount] [money] NULL,
[UntaxedPensionAmount] [money] NULL,
[CentrelinkDeductibleAmount] [money] NULL,
[TaxFreePercentageOfIncome] [decimal](5, 2) NULL,
[HistoricalCrystallisedPercentage] [decimal] (10, 2) NULL,
[CurrentCrystallisedPercentage] [decimal] (10, 2) NULL,
[CrystallisedPercentage] [decimal] (10, 2) NULL,
[UncrystallisedPercentage] [decimal] (10, 2) NULL,
[PensionArrangement] [varchar] (100) NULL
)
GO
ALTER TABLE [dbo].[TPensionInfoAudit] ADD CONSTRAINT [PK_TPensionInfoAudit_3__98] PRIMARY KEY NONCLUSTERED  ([AuditId])
GO
CREATE NONCLUSTERED INDEX [IDXAudit_TPensionInfoAudit_PensionInfoId_ConcurrencyId] ON [dbo].[TPensionInfoAudit] ([PensionInfoId], [ConcurrencyId])
GO
CREATE NONCLUSTERED INDEX [IX_TPensionInfoAudit_StampDateTime_ProtectionId] ON [dbo].[TPensionInfoAudit] ([StampDateTime], [PensionInfoId])
GO