CREATE TABLE [dbo].[TValBulkNotMatched](
	[ValBulkNotMatchedId] [bigint] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
	[CustomerReference] [varchar](100) NULL,
	[PortfolioReference] [varchar](100) NULL,
	[CustomerSubType] [varchar](100) NULL,
	[Title] [varchar](100) NULL,
	[CustomerFirstName] [varchar](100) NULL,
	[CustomerLastName] [varchar](100) NULL,
	[CustomerDoB] [varchar](50) NULL,
	[CustomerNINumber] [varchar](50) NULL,
	[ClientAddressLine1] [varchar](255) NULL,
	[ClientAddressLine2] [varchar](255) NULL,
	[ClientAddressLine3] [varchar](255) NULL,
	[ClientAddressLine4] [varchar](255) NULL,
	[ClientPostCode] [varchar](20) NULL,
	[AdviserReference] [varchar](100) NULL,
	[AdviserFirstName] [varchar](100) NULL,
	[AdviserLastName] [varchar](100) NULL,
	[AdviserCompanyName] [varchar](255) NULL,
	[AdviserOfficePostCode] [varchar](20) NULL,
	[PortfolioId] [varchar](255) NULL,
	[HoldingId] [varchar](255) NULL,
	[PortfolioType] [varchar](255) NULL,
	[Designation] [varchar](255) NULL,
	[FundProviderName] [varchar](255) NULL,
	[_FundName] [varchar](255) NULL,
	[ISIN] [varchar](50) NULL,
	[MexId] [varchar](50) NULL,
	[Sedol] [varchar](50) NULL,
	[FundQuantity] [varchar](50) NULL,
	[EffectiveDate] [varchar](50) NULL,
	[Price] [varchar](50) NULL,
	[FundPriceDate] [varchar](50) NULL,
	[HoldingValue] [varchar](100) NULL,
	[Currency] [varchar](50) NULL,
	[WorkInProgressIndicator] [varchar](10) NULL,
	[EpicCode] [varchar](50) NULL,
	[CitiCode] [varchar](50) NULL,
	[GBPBalance] [varchar](50) NULL,
	[ForeignBalance] [varchar](50) NULL,
	[AvailableCash] [varchar](50) NULL,
	[AccountName] [varchar](255) NULL,
	[AccountReference] [varchar](255) NULL,
	[BalanceDate] [varchar](50) NULL,
	[SubPlanReference] [varchar](255) NULL,
	[SubPlanType] [varchar](255) NULL,
	[PolicyProviderName] [varchar](255) NULL,
	[ProviderFundCode] [varchar](50) NULL,
	[FundDeleteBreaker] [bit] NULL,
	[FundUpdateBreaker] [bit] NULL,
	[PlanMatched] [bit] NULL,
	[PolicyBusinessId] [int] NULL,
	[FundMatched] [bit] NULL,
	[PolicyBusinessFundId] [int] NULL,
	[ValuationUpdated] [bit] NULL,
	[PlanValuationId] [bigint] NULL,
	[PlanInEligibilityMask] [int] NULL,
	[PlanUpdateBreaker] [bit] NULL,
	[CreatedDateTime] [datetime] NULL,
	[Remarks] [varchar](1000) NULL,
	[ConcurrencyId] [int] NULL,
	[ValScheduleId] [int] NULL,
	[FormattedPolicyNumber] [varchar](60) NULL,
	[IndigoClientId] [int] NULL,
	[FundID] [int] NULL,
	[FundTypeID] [int] NULL,
	[CategoryId] [int] NULL,
	[CategoryName] [varchar](255) NULL,
	[FundUnitPrice] [money] NULL,
	[Feed] [bit] NULL,
	[ValBulkHoldingId] [int] NULL,
	[ValBulkHoldingResultId] [int] NULL,
	[ValScheduleItemId] [int] NULL,
	[FundName] [varchar](255) NULL,
	[PolicyStartDate] [datetime] NULL,
	[Qtimestamp] [datetime2](7) NOT NULL,
	[xflag] [tinyint] NULL,
	[ModelPortfolioName] [varchar] (2000)NULL,
	[DFMName] [varchar] (2000) NULL
)
GO
ALTER TABLE [dbo].[TValBulkNotMatched] ADD CONSTRAINT [PK_TValBulkNotMatched] PRIMARY KEY NONCLUSTERED([ValBulkNotMatchedId], [Qtimestamp])
GO
CREATE CLUSTERED INDEX CLX_TValBulkNotMatched_ValScheduleId ON TValBulkNotMatched ([ValScheduleId])
GO