CREATE TABLE [dbo].[TGroupSchemeCategoryAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1),
[GroupSchemeId] [int] NOT NULL,
[TenantId] [int] NOT NULL,
[CategoryName] [varchar] (100) NOT NULL,
[MinServiceRequirementAmount] [int] NULL,
[MinServiceRequirementType] [tinyint] NULL,
[EligibilityAgeFrom] [tinyint] NULL,
[EligibilityAgeTo] [tinyint] NULL,
[StandardRetirementAgeMale] [tinyint] NULL,
[StandardRetirementAgeFemale] [tinyint] NULL,
[EmployeeContribution] [money] NULL,
[EmployerContribution] [money] NULL,
[BasisOfSalary] [tinyint] NULL,
[BasisOfSalaryOther] [varchar] (50) NULL,
[BasisOfSalaryAsAt] [tinyint] NULL,
[FreeCoverAmount] [money] NULL,
[FreeCoverAmountType] [tinyint] NULL,
[CoverAmount] [money] NULL,
[CoverAmountType] [tinyint] NULL,
[CoverAmountNotes] [varchar] (255) NULL,
[CoverToAge] [tinyint] NULL,
[MethodOfCosting] [tinyint] NULL,
[RateGuaranteeExpires] [datetime] NULL,
[DeferredPeriod] [tinyint] NULL,
[DeferredPeriodType] [tinyint] NULL,
[ClaimEscalationRate] [decimal] (10, 2) NULL,
[IncreasesAt] [tinyint] NULL,
[LimitedClaimPeriod] [smallint] NULL,
[LimitedClaimPeriodType] [tinyint] NULL,
[DisabilityDefinition] [varchar] (1000) NULL,
[IsPensionContributionCovered] [bit] NULL,
[PensionContributionCoveredEmployeeAmount] [money] NULL,
[PensionContributionCoveredEmployerAmount] [money] NULL,
[PSTRNumber] [varchar] (50) NULL,
[TemporaryAbsence] [tinyint] NULL,
[IsSpousesBenefitsIncluded] [bit] NULL,
[SpousesCoverAmount] [money] NULL,
[SpousesCoverToAge] [tinyint] NULL,
[SpousesMethodOfCosting] [tinyint] NULL,
[IsArchived] [bit] NOT NULL CONSTRAINT [DF_TGroupSchemeCategoryAudit_IsArchived] DEFAULT ((0)),
[IsDefault] [bit] NOT NULL CONSTRAINT [DF_TGroupSchemeCategoryAudit_IsDefault] DEFAULT ((0)),
[IsCalculateContribution] [bit] NOT NULL CONSTRAINT [DF_TGroupSchemeCategoryAudit_IsCalculateContribution] DEFAULT ((0)),
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF_TGroupSchemeCategoryAudit_ConcurrencyId] DEFAULT ((1)),
[GroupSchemeCategoryId] [int] NOT NULL,
[StampAction] [char] (1) NOT NULL,
[StampDateTime] [datetime] NULL CONSTRAINT [DF_TGroupSchemeCategoryAudit_StampDateTime] DEFAULT (getdate()),
[StampUser] [varchar] (255) NULL,
[FeeModelId] [int] NULL,
[Discriminator] [char] (2) NULL
)
GO
ALTER TABLE [dbo].[TGroupSchemeCategoryAudit] ADD CONSTRAINT [PK_TGroupSchemeCategoryAudit] PRIMARY KEY CLUSTERED  ([AuditId])
GO
CREATE NONCLUSTERED INDEX [IDX_TGroupSchemeCategoryAudit_GroupSchemeCategoryId_ConcurrencyId] ON [dbo].[TGroupSchemeCategoryAudit] ([GroupSchemeCategoryId], [ConcurrencyId])
GO
