CREATE TABLE [dbo].[TEquityRelease]
(
[EquityReleaseId] [int] NOT NULL IDENTITY(1, 1),
[PolicyBusinessId] [int] NOT NULL,
[InterestOnlyAmount] [decimal] (18, 2) NULL,
[RepaymentAmount] [decimal] (18, 2) NULL,
[LoanAmount] [decimal] (18, 2) NULL,
[InterestRate] [decimal] (10, 2) NULL,
[TermInYears] [decimal] (15, 6) NULL,
[RefMortgageRepaymentMethodId] [int] NULL,
[AddressStoreId] [int] NULL,
[AssetsId] [int] NULL,
[IndigoClientId] [int] NOT NULL,
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF_TEquityRelease_ConcurrencyId] DEFAULT ((1)),
[PricePerValuation] [decimal] (18, 2) NULL,
[DepositPerEquity] [decimal] (18, 2) NULL,
[LTV] [decimal] (18, 2) NULL,
[InterestRatePercentage] [decimal] (10, 2) NULL,
[RateType] [varchar](100) NULL,
[ValueOfProperty] [money] NULL,
[PenaltyFg] [bit] NULL,
[RedemptionTerms] [varchar] (1000)  NULL,
[PenaltyExpiryDate] [datetime] NULL,
[ApplicableToNewTransaction] [bit] NULL,
[RefEquityReleaseTypeId] [int] NULL,
[PercentageOwnershipSold] [decimal] (10, 2) NULL,
[LumpsumAmount] [decimal] (10, 2) NULL,
[MonthlyIncomeAmount] [decimal] (10, 2) NULL,
[CurrentBalance] [money] NULL,
[InterestDetails] [varchar] (250)  NULL,
[RateTypeOther] [varchar] (1000)  NULL,
[TargetCompletionDate] [datetime] NULL,
[TermInMonths] [int] NULL,
[ValuationDate] [datetime] NULL,
[ValuationInstructed] [datetime] NULL,
[ValuationReceived] [datetime] NULL,
[ApplicationSubmitted] [datetime] NULL,
[CompletionDate] [datetime] NULL,
[ExchangeDate] [datetime] NULL,
[OfferIssued] [datetime] NULL,
[ReviewDiaryDate] [datetime] NULL,
[CapitalRepaymentTermInMonths] [int] NULL,
[InterestRepaymentTermInMonths] [int] NULL,
[BaseRate] [varchar] (50) NULL,
[CollarRate] [decimal] (5, 2) NULL,
[SchemeRate] [decimal] (5, 2) NULL,
[SchemeEndDate] [datetime] NULL,
[RedemptionFigure2] [money] NULL,
[RedemptionFigure] [money] NULL,
[AddressId] [int] NULL,
[IsToBeConsolidated] [bit] NOT NULL CONSTRAINT [DF_TEquityRelease_IsToBeConsolidated] DEFAULT((0)),
[IsLiabilityToBeRepaid] [bit] NULL,
[LiabilityRepaymentDescription] [varchar] (500) NULL
)
GO
ALTER TABLE [dbo].[TEquityRelease] ADD CONSTRAINT [PK_TEquityRelease] PRIMARY KEY CLUSTERED  ([EquityReleaseId])
GO
CREATE NONCLUSTERED INDEX [IDX_TEquityRelease_PolicyBusinessId] ON [dbo].[TEquityRelease] ([PolicyBusinessId])
GO
CREATE NONCLUSTERED INDEX [IX_TEquityRelease_AddressId] ON [dbo].[TEquityRelease] ([AddressId])
GO