CREATE TABLE [dbo].[TQuoteMortgageSourceAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1),
[TenantId] [int] NOT NULL,
[QuoteId] [int] NOT NULL,
[OpportunityId] [int] NOT NULL,
[FullQuoteId] [int] NULL,
[InternalProductID] [varchar] (512) COLLATE Latin1_General_CI_AS NULL,
[LenderName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[LenderCategory] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[LenderProductCode] [varchar] (32) COLLATE Latin1_General_CI_AS NULL,
[LenderProductName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[ProductType] [varchar] (32) COLLATE Latin1_General_CI_AS NULL,
[MaximumLTV] [decimal] (9, 4) NULL,
[InitialInterestRate] [decimal] (9, 4) NULL,
[Ends] [smallint] NULL,
[OverhangMonth] [smallint] NULL,
[ReviosnaryRate] [decimal] (9, 4) NULL,
[CompletionFeeAmount] [money] NULL,
[BookingFeeAmount] [money] NULL,
[CashBackAmount] [money] NULL,
[EarlyRepaymentCharge] [decimal] (9, 4) NULL,
[HLCAmount] [money] NULL,
[MonthlyPaymentAmount] [money] NULL,
[MonthlyPaymentAmountInterestOnly] [money] NULL,
[MonthlyPaymentAmountCapitalAndInterest] [money] NULL,
[TrueCostofMortgage] [money] NULL,
[TrueCostofMortgageInterestOnly] [money] NULL,
[TrueCostofMortgageRepaymentOnly] [money] NULL,
[TrueCostTerm] [tinyint] NULL,
[ValuationFee] [money] NULL,
[LaunchDate] [datetime] NULL,
[WithdrawalDate] [datetime] NULL,
[AdditionalInformation] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[SourceMatchLevel] [varchar] (32) COLLATE Latin1_General_CI_AS NULL,
[NearMissOrRejectExplanation] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[IsKFIAvailable] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[IsResidential] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[IsBuyToLet] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[IsFirstTimeBuyer] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[IsSecondTimeBuyer] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[IsRemortgage] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[IsFeesAvailable] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[IsExclusive] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[ExclusiveTo] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[IsCompletionFeeAddableToLoan] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[IsBookingFeeAddableToLoan] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[IsFreeLegal] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[IsFreeValuation] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[IsUnderPaymentsAllowed] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[IsOverPaymentsAllowed] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[IsDrawdown] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[IsPaymentHoliday] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[IsBorrowBack] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[IsPortable] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[WithoutExtendedERC] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[WithoutHLC] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF_TQuoteMortgageSourceAudit_ConcurrencyId] DEFAULT ((1)),
[QuoteMortgageSourceId] [int] NOT NULL,
[StampAction] [char] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[StampDateTime] [datetime] NULL CONSTRAINT [DF_TQuoteMortgageSourceAudit_StampDateTime] DEFAULT (getdate()),
[StampUser] [varchar] (255) COLLATE Latin1_General_CI_AS NULL
)
GO
ALTER TABLE [dbo].[TQuoteMortgageSourceAudit] ADD CONSTRAINT [PK_TQuoteMortgageSourceAudit] PRIMARY KEY NONCLUSTERED  ([AuditId])
GO
CREATE NONCLUSTERED INDEX [IDX_TQuoteMortgageSourceAudit_QuoteMortgageSourceId_ConcurrencyId] ON [dbo].[TQuoteMortgageSourceAudit] ([QuoteMortgageSourceId], [ConcurrencyId]) WITH (FILLFACTOR=90)
GO
