CREATE TABLE [dbo].[TPolicyBusinessAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1),
[PolicyDetailId] [int] NOT NULL,
[PolicyNumber] [varchar] (50)  NULL,
[PractitionerId] [int] NOT NULL,
[ReplaceNotes] [varchar] (8000)  NULL,
[TnCCoachId] [int] NULL,
[AdviceTypeId] [int] NOT NULL,
[BestAdvicePanelUsedFG] [bit] NOT NULL CONSTRAINT [DF_TPolicyBusinessAudit_BestAdvicePanelUsedFG] DEFAULT ((0)),
[WaiverDefermentPeriod] [int] NOT NULL CONSTRAINT [DF_TPolicyBusinessAudit_WaiverDefermentPeriod] DEFAULT ((0)),
[IndigoClientId] [int] NOT NULL,
[SwitchFG] [tinyint] NOT NULL CONSTRAINT [DF_TPolicyBusinessAudit_SwitchFG] DEFAULT ((0)),
[TotalRegularPremium] [money] NULL,
[TotalLumpSum] [money] NULL,
[MaturityDate] [datetime] NULL,
[LifeCycleId] [int] NULL,
[PolicyStartDate] [datetime] NULL,
[PremiumType] [varchar] (50)  NULL,
[AgencyNumber] [varchar] (50)  NULL,
[ProviderAddress] [varchar] (1000)  NULL,
[OffPanelFg] [bit] NOT NULL CONSTRAINT [DF_TPolicyBusinessAudit_OffPanelFg] DEFAULT ((0)),
[BaseCurrency] [varchar] (50)  NULL CONSTRAINT [DF_TPolicyBusinessAudit_BaseCurrency] DEFAULT ('GBP'),
[ExpectedPaymentDate] [datetime] NULL,
[ProductName] [varchar] (200)  NULL,
[InvestmentTypeId] [int] NULL,
[RiskRating] [int] NULL,
[SequentialRef] [varchar] (50)  NULL,
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF_TPolicyBusinessAudit_ConcurrencyId] DEFAULT ((1)),
[PolicyBusinessId] [int] NOT NULL,
[StampAction] [char] (1)  NOT NULL,
[StampDateTime] [datetime] NOT NULL CONSTRAINT [DF_TPolicyBusinessAudit_StampDateTime] DEFAULT (getdate()),
[StampUser] [varchar] (255)  NULL,
[IsGuaranteedToProtectOriginalInvestment] [bit] NULL,
[ClientTypeId] [int] NULL,
[PlanMigrationRef] [varchar] (255)  NULL,
[UsePriceFeed] [bit] NULL,
[LowMaturityValue] [money] NULL,
[MediumMaturityValue] [money] NULL,
[HighMaturityValue] [money] NULL,
[ProjectionDetails] [varchar] (5000)  NULL,
[TopupMasterPolicyBusinessId] [int] NULL,
[ServicingUserId] [int] NULL,
[PropositionTypeId] [int] NULL,
[ParaplannerUserId] [int] NULL,
[GroupId] [int] NULL,
[PerformanceStartDate] [datetime2] NULL,
[PerformanceEndDate] [datetime2] NULL,
[ProviderCode2] [varchar] (50) NULL,
[ProviderCode3] [varchar] (50) NULL
)
GO
CREATE CLUSTERED INDEX [CLX_TPolicyBusinessAudit_PolicyBusinessId] ON [dbo].[TPolicyBusinessAudit] ([PolicyBusinessId])
GO
CREATE NONCLUSTERED INDEX [IX_TPolicyBusinessAudit_StampDateTimeON] ON [dbo].[TPolicyBusinessAudit] ([StampDateTime])
GO