CREATE TABLE [dbo].[TQuoteMortgageSource]
(
[QuoteMortgageSourceId] [int] NOT NULL IDENTITY(1, 1),
[TenantId] [int] NOT NULL,
[QuoteId] [int] NOT NULL,
[OpportunityId] [int] NOT NULL,
[FullQuoteId] [int] NULL,
[InternalProductID] [varchar] (512)  NULL,
[LenderName] [varchar] (255)  NULL,
[LenderCategory] [varchar] (255)  NULL,
[LenderProductCode] [varchar] (32)  NULL,
[LenderProductName] [varchar] (255)  NULL,
[ProductType] [varchar] (32)  NULL,
[MaximumLTV] [decimal] (9, 4) NULL,
[InitialInterestRate] [decimal] (9, 4) NULL,
[Ends] [smallint] NULL,
[OverhangMonth] [smallint] NULL,
[ReviosnaryRate] [decimal] (9, 4) NULL,
[CompletionFeeAmount] [money] NULL,
[BookingFeeAmount] [money] NULL,
[CashBackAmount] [money] NULL,
[EarlyRepaymentCharge] [decimal] (9, 4) NULL,
[HLCAmount] [money] NULL,
[MonthlyPaymentAmount] [money] NULL,
[MonthlyPaymentAmountInterestOnly] [money] NULL,
[MonthlyPaymentAmountCapitalAndInterest] [money] NULL,
[TrueCostofMortgage] [money] NULL,
[TrueCostofMortgageInterestOnly] [money] NULL,
[TrueCostofMortgageRepaymentOnly] [money] NULL,
[TrueCostTerm] [tinyint] NULL,
[ValuationFee] [money] NULL,
[LaunchDate] [datetime] NULL,
[WithdrawalDate] [datetime] NULL,
[AdditionalInformation] [varchar] (1000)  NULL,
[SourceMatchLevel] [varchar] (32)  NULL,
[NearMissOrRejectExplanation] [varchar] (1000)  NULL,
[IsKFIAvailable] [varchar] (16)  NULL,
[IsResidential] [varchar] (16)  NULL,
[IsBuyToLet] [varchar] (16)  NULL,
[IsFirstTimeBuyer] [varchar] (16)  NULL,
[IsSecondTimeBuyer] [varchar] (16)  NULL,
[IsRemortgage] [varchar] (16)  NULL,
[IsFeesAvailable] [varchar] (16)  NULL,
[IsExclusive] [varchar] (16)  NULL,
[ExclusiveTo] [varchar] (255)  NULL,
[IsCompletionFeeAddableToLoan] [varchar] (16)  NULL,
[IsBookingFeeAddableToLoan] [varchar] (16)  NULL,
[IsFreeLegal] [varchar] (16)  NULL,
[IsFreeValuation] [varchar] (16)  NULL,
[IsUnderPaymentsAllowed] [varchar] (16)  NULL,
[IsOverPaymentsAllowed] [varchar] (16)  NULL,
[IsDrawdown] [varchar] (16)  NULL,
[IsPaymentHoliday] [varchar] (16)  NULL,
[IsBorrowBack] [varchar] (16)  NULL,
[IsPortable] [varchar] (16)  NULL,
[WithoutExtendedERC] [varchar] (16)  NULL,
[WithoutHLC] [varchar] (16)  NULL,
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF_TQuoteMortgageSource_ConcurrencyId] DEFAULT ((1))
)
GO
ALTER TABLE [dbo].[TQuoteMortgageSource] ADD CONSTRAINT [PK_TQuoteMortgageSource] PRIMARY KEY NONCLUSTERED  ([QuoteMortgageSourceId])
GO
CREATE CLUSTERED INDEX [IDX_TQuoteMortgageSource_TenantId_OpportunityId_FullQuoteId] ON [dbo].[TQuoteMortgageSource] ([TenantId], [OpportunityId], [FullQuoteId])
GO
ALTER TABLE [dbo].[TQuoteMortgageSource] WITH CHECK ADD CONSTRAINT [FK_TQuoteMortgageSource_QuoteId_TQuote] FOREIGN KEY ([QuoteId]) REFERENCES [dbo].[TQuote] ([QuoteId])
GO
