CREATE TABLE [dbo].[TPlanTypeExceptionAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1),
[PlanTypeExceptionId] [int] NOT NULL,
[RefPlanType2ProdSubTypeId] [int] NULL,
[PreSaleSumAssured] [decimal] (15, 2) NULL,
[PreSaleLumpSumContribution] [decimal] (15, 2) NULL,
[PreSaleRegularContribution] [decimal] (15, 2) NULL,
[PreSaleAgeLowerLimit] [int] NULL,
[PreSaleAgeUpperLimit] [int] NULL,
[PostSaleSumAssured] [decimal] (15, 2) NULL,
[PostSaleLumpSumContribution] [decimal] (15, 2) NULL,
[PostSaleRegularContribution] [decimal] (15, 2) NULL,
[PostSaleAgeLowerLimit] [int] NULL,
[PostSaleAgeUpperLimit] [int] NULL,
[TenantId] [int] NOT NULL,
[ConcurrencyId] [int] NOT NULL,
[StampAction] [char] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[StampDateTime] [datetime] NULL,
[StampUser] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[PlanTypeExceptionName] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[SumAssured] [decimal] (15, 2) NULL,
[LumpSumContribution] [decimal] (15, 2) NULL,
[RegularContribution] [decimal] (15, 2) NULL,
[AgeLowerLimit] [int] NULL,
[AgeUpperLimit] [int] NULL,
[IsPreSale] [bit] NULL,
[IsPostSale] [bit] NULL,
[IsArchived] [bit] NULL,
[IsPOA] [bit] NULL,
[RiskProfileType] [int] NULL,
[Location] [varchar](255) NULL,
[AtrTemplateId] [int] NULL,
[AdviceCaseStatusId] [int] NULL,
[IsVulnerableCustomer] [bit] NULL)
GO
