CREATE TABLE [dbo].[THomeInsuranceQuoteAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1),
[RefPropertyTypeId] [int] NOT NULL,
[Postcode] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[NumberOfBedrooms] [int] NOT NULL,
[IncludeAccidentalBuildingDamageCover] [bit] NOT NULL,
[IncludeAccidentalContentsDamageCover] [bit] NOT NULL,
[NoClaimYearsBuilding] [int] NOT NULL,
[NoClaimYearsContents] [int] NOT NULL,
[RefCoverTypeId] [int] NOT NULL,
[BuildYear] [int] NOT NULL,
[UnspecifiedItemAmount] [money] NULL,
[IncludeBuildingsExtraCover] [bit] NOT NULL,
[IncludeContentsExtraCover] [bit] NOT NULL,
[IncludeHomeEmergencyCover] [bit] NOT NULL,
[IncludeLegalAssistanceCover] [bit] NOT NULL,
[PolicyExcess] [money] NULL,
[IsMasonryBuild] [tinyint] NOT NULL,
[IsPermanentlyOccupied] [tinyint] NOT NULL,
[HasSubsidence] [tinyint] NOT NULL,
[ApplicantOrFamilyHasConviction] [tinyint] NOT NULL,
[UnoccupiedSixtyPlusDays] [tinyint] NOT NULL,
[UsedForBusinessPurposes] [tinyint] NOT NULL,
[ApplicantHasPreviousClaims] [tinyint] NOT NULL,
[IsFurnished] [bit] NOT NULL,
[NoOfPSLandlordPolicy] [int] NOT NULL,
[IsPrivateIndividual] [tinyint] NOT NULL,
[HasInsuranceDeclined] [tinyint] NOT NULL,
[UsedForAsylumSeekers] [tinyint] NOT NULL,
[IsDirectTenancyAgreement] [tinyint] NOT NULL,
[HasLessThanSixIndividuals] [tinyint] NOT NULL,
[IsSelfContainedUnits] [tinyint] NOT NULL,
[HasPropertyFlooded] [tinyint] NOT NULL,
[IncludeStudentTenants] [bit] NOT NULL,
[IncludeDsstenants] [bit] NOT NULL,
[ConcurrencyId] [int] NOT NULL,
[QuoteId] [int] NOT NULL,
[StampAction] [char] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[StampDateTime] [datetime] NULL CONSTRAINT [DF_THomeInsuranceQuoteAudit_StampDateTime] DEFAULT (getdate()),
[StampUser] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[PropertyDetailId] [int] NULL
)
GO
ALTER TABLE [dbo].[THomeInsuranceQuoteAudit] ADD CONSTRAINT [PK_THomeInsuranceQuoteAudit] PRIMARY KEY NONCLUSTERED  ([AuditId])
GO
