CREATE TABLE [dbo].[TQuoteResultAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1),
[RefProductTypeId] [int] NOT NULL,
[QuoteId] [int] NOT NULL,
[QuoteItemId] [int] NULL,
[QuoteReference] [varchar] (64) COLLATE Latin1_General_CI_AS NOT NULL,
[QuoteDate] [datetime] NOT NULL,
[ProductReferenceNumber] [varchar] (56) COLLATE Latin1_General_CI_AS NULL,
[PSLProductRefNo] [varchar] (64) COLLATE Latin1_General_CI_AS NULL,
[TenantId] [int] NOT NULL,
[PolicyFeeExcIPT] [smallmoney] NULL,
[InsurancePremiumTax] [smallmoney] NULL,
[AnnualIPT] [smallmoney] NULL,
[AnnualPremium] [smallmoney] NULL,
[AnnualPremiumExcIPT] [smallmoney] NULL,
[TotalMonthlyCost] [smallmoney] NULL,
[TotalMonthlyCostExcIPT] [smallmoney] NULL,
[MonthlyPremium] [smallmoney] NULL,
[MonthlyPremiumExcIpt] [smallmoney] NULL,
[TotalPremium] [smallmoney] NULL,
[TotalPremiumExcIPT] [smallmoney] NULL,
[InsurerName] [varchar] (128) COLLATE Latin1_General_CI_AS NULL,
[InsurerCode] [varchar] (64) COLLATE Latin1_General_CI_AS NULL,
[PolicyFee] [smallmoney] NULL,
[InitialExclusionPeriod] [int] NULL,
[IEPWaivedBenefit] [smallmoney] NULL,
[IEPAppliedBenefit] [smallmoney] NULL,
[IsReferred] [bit] NULL,
[FiveYearPremium] [smallmoney] NULL,
[CreditorInsurerName] [varchar] (128) COLLATE Latin1_General_CI_AS NULL,
[Customer1Premium] [smallmoney] NULL,
[Customer2Premium] [smallmoney] NULL,
[BuildingsContentsPremium] [smallmoney] NULL,
[BuildingsContentsPremiumExcIPT] [smallmoney] NULL,
[BuildingsPremium] [smallmoney] NULL,
[BuildingsPremiumExcIPT] [smallmoney] NULL,
[ContentsPremium] [smallmoney] NULL,
[ContentsPremiumExcIPT] [smallmoney] NULL,
[HomeEmergencyPremium] [smallmoney] NULL,
[HomeEmergencyPremiumExcIPT] [smallmoney] NULL,
[LegalCoverInsurerName] [varchar] (128) COLLATE Latin1_General_CI_AS NULL,
[LegalCoverInsurerCode] [varchar] (64) COLLATE Latin1_General_CI_AS NULL,
[LegalCoverPremium] [smallmoney] NULL,
[LegalCoverPremiumExcIPT] [smallmoney] NULL,
[HouseholdInsurerName] [varchar] (128) COLLATE Latin1_General_CI_AS NULL,
[HouseholdInsurerCode] [varchar] (64) COLLATE Latin1_General_CI_AS NULL,
[HomeEmergencyInsurerName] [varchar] (128) COLLATE Latin1_General_CI_AS NULL,
[HomeEmergencyInsurerCode] [varchar] (64) COLLATE Latin1_General_CI_AS NULL,
[ConcurrencyId] [int] NOT NULL,
[QuoteResultId] [int] NOT NULL,
[StampAction] [char] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[StampDateTime] [datetime] NULL CONSTRAINT [DF_TQuoteResultAudit_StampDateTime] DEFAULT (getdate()),
[StampUser] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[QuoteSystemProductType] [varchar] (64) COLLATE Latin1_General_CI_AS NULL,
[QuoteResultInternal] [xml] NULL,
[IsMarked] [bit] NULL,
[ProductDescription] [varchar] (256) COLLATE Latin1_General_CI_AS NULL,
[ExpiryDate] [datetime] NULL,
[ProviderName] [varchar] (256) COLLATE Latin1_General_CI_AS NULL
)
GO
ALTER TABLE [dbo].[TQuoteResultAudit] ADD CONSTRAINT [PK_TQuoteResultAudit] PRIMARY KEY NONCLUSTERED  ([AuditId])
GO
CREATE NONCLUSTERED INDEX [IDXAudit_TQuoteResultAudit_QuoteResultId_ConcurrencyId] ON [dbo].[TQuoteResultAudit] ([QuoteResultId], [ConcurrencyId])
GO
CREATE NONCLUSTERED INDEX [IX_TQuoteResultAudit_StampDateTime_QuoteResultId] ON [dbo].[TQuoteResultAudit] ([StampDateTime], [QuoteResultId])
GO
