CREATE TABLE [dbo].[TRefVAT]
(
[RefVATId] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[VATName] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[VATRate] [float] NULL,
[IsDefault] [bit] NOT NULL CONSTRAINT [DF_TRefVAT_IsDefault] DEFAULT ((0)),
[IsArchived] [bit] NOT NULL CONSTRAINT [DF_TRefVAT_IsArchived] DEFAULT ((0)),
[ConcurrencyId] [int] NULL CONSTRAINT [DF_TRefVAT_ConcurrencyId_1__61] DEFAULT ((1))
)
GO
ALTER TABLE [dbo].[TRefVAT] ADD CONSTRAINT [PK_TRefVAT_2__61] PRIMARY KEY NONCLUSTERED  ([RefVATId]) WITH (FILLFACTOR=80)
GO
