CREATE TABLE [dbo].[TPolicyBusinessExtAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1),
[PolicyBusinessId] [int] NOT NULL,
[BandingTemplateId] [int] NOT NULL,
[MigrationRef] [varchar] (255) NULL,
[PortalReference] [varchar] (50) NULL,
[ReportNotes] [varchar] (4000) NULL,
[AnnualCharges] [decimal] (18, 2) NULL,
[WrapperCharge] [decimal] (18, 2) NULL,
[InitialAdviceCharge] [decimal] (18, 2) NULL,
[OngoingAdviceCharge] [decimal] (18, 2) NULL,
[PensionIncrease] [varchar] (50) NULL,
[ReservedValue] [decimal] (18, 2) NULL,
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF_TPolicyBusinessExtAudit_ConcurrencyId] DEFAULT ((1)),
[PolicyBusinessExtId] [int] NOT NULL,
[StampAction] [char] (1) NOT NULL,
[StampDateTime] [datetime] NULL CONSTRAINT [DF_TPolicyBusinessExtAudit_StampDateTime] DEFAULT (getdate()),
[StampUser] [varchar] (255) NULL,
[QuoteResultId] [int] NULL,
[ApplicationReference] [varchar] (100) NULL,
[MortgageRepayPercentage] [money] NULL,
[MortgageRepayAmount] [money] NULL,
[IsJointExternal] [bit] NULL,
[IsLendersSolicitorsUsed] [bit] NULL,
[SystemPortalReference] [varchar] (50) NULL,
[FundIncome] [varchar] (50) NULL,
[IsVisibleToClient] [bit] NULL,
[IsVisibilityUpdatedByStatusChange] [bit] NULL,
[HasDfm] [bit] NULL,
[HasModelPortfolio] [bit] NULL,
[AgencyStatus] [varchar] (50) NULL,
[AgencyStatusDate] [datetime] NULL,
[AdditionalNotes] [varchar] (1000) null,
[InterestRate] [money] NULL,
[IsPlanValueVisibleToClient] [bit] NULL,
[ModelId] [INT] NULL,
[ForwardIncomeToAdviserId] [int] NULL,
[ForwardIncomeToUseAdviserBanding] [bit] NULL,
[SortCode] [VARCHAR](50) NULL,
[WhoCreatedUserId] [int] NULL,
[IsProviderManaged] [bit] NULL,
[PlatformReference] [varchar] (50) NULL,
[IsTargetMarket] [TINYINT] NULL,
[TargetMarketExplanation] [VARCHAR](250) NULL,
[DocumentDeliveryMethod] [VARCHAR](100) NOT NULL CONSTRAINT [DF_TPolicyBusinessExtAudit_DocumentDeliveryMethod] DEFAULT ('NoPreference'),
[CreatedAt] [datetime] NULL,
[QuoteId] [int] NULL,
[ProgramId] [int] NULL,
[RiskProfileId] [int] NULL
)
GO
ALTER TABLE [dbo].[TPolicyBusinessExtAudit] ADD CONSTRAINT [PK_TPolicyBusinessExtAudit] PRIMARY KEY CLUSTERED  ([AuditId])
GO