CREATE TABLE [dbo].[TMortgage]
(
[MortgageId] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[PolicyBusinessId] [int] NOT NULL,
[IndigoClientId] [int] NOT NULL,
[MortgageRefNo] [varchar] (50) NULL,
[LoanAmount] [money] NULL,
[InterestRate] [decimal] (10, 5) NULL,
[MortgageType] [varchar] (100) NULL,
[MortgageTypeOther] [varchar] (1000) NULL,
[FeatureExpiryDate] [datetime] NULL,
[PenaltyFg] [bit] NULL,
[PenaltyExpiryDate] [datetime] NULL,
[RedemptionTerms] [varchar] (1000) NULL,
[SchemeRate] [decimal] (10, 2) NULL,
[SchemeEndDate] [datetime] NULL,
[CompletionDate] [datetime] NULL,
[SVR] [decimal] (10, 2) NULL,
[PortableFg] [bit] NULL,
[RedeemedFg] [bit] NULL,
[SoldFg] [bit] NULL,
[AssetsId] [int] NULL,
[LiabilitiesId] [int] NULL,
[ReviewDiaryDate] [datetime] NULL,
[RefMortgageBorrowerTypeId] [int] NULL,
[RefMortgageRepaymentMethodId] [int] NULL,
[RefMortgageProductTypeId] [int] NULL,
[MortgageTerm] [decimal] (15, 6) NULL,
[MortgageTermMonths] [int] NULL,
[RemainingTerm] [decimal] (15, 6) NULL,
[PropertyValue] [int] NULL,
[IncomeEvidencedFg] [bit] NULL CONSTRAINT [DF_TMortgage_IncomeEvidencedFg] DEFAULT ((0)),
[AddressStoreId] [int] NULL,
[LoanPurpose] [varchar] (50) NULL,
[PriceValuation] [money] NULL,
[Deposit] [money] NULL,
[InterestOnlyAmount] [money] NULL,
[RepaymentAmount] [money] NULL,
[LTV] [decimal] (10, 2) NULL,
[ApplicationSubmitted] [datetime] NULL,
[ValuationInstructed] [datetime] NULL,
[ValuationDate] [datetime] NULL,
[ValuationReceived] [datetime] NULL,
[OfferIssued] [datetime] NULL,
[ExchangeDate] [datetime] NULL,
[IsCurrentResidence] [bit] NULL,
[IsResdidenceAfterComplete] [bit] NULL,
[CurrentBalance] [money] NULL,
[WillPayRedemption] [bit] NULL,
[WillBeDischarged] [bit] NULL,
[RedemptionAmount] [money] NULL,
[StatusFg] [bit] NULL,
[NonStatusFg] [bit] NULL,
[SelfCertFg] [bit] NULL,
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF_TMortgage_ConcurrencyId] DEFAULT ((1)),
[ApplicableToNewTransaction] [bit] NULL,
[BaseRate] [varchar] (50) NULL,
[LoadingPct] [decimal] (10, 2) NULL,
[LenderFee] [money] NULL,
[IsGuarantorMortgage] [bit] NULL,
[IsOverHang] [bit] NULL,
[RatePeriodFromCompletionMonths] [int] NULL,
[IsCollaredRate] [bit] NULL,
[CollarPct] [decimal] (10, 2) NULL,
[IsAddToMortgageAdvance] [bit] NOT NULL CONSTRAINT [DF__TMortgage__IsAdd__74F0ADE3] DEFAULT ((0)),
[RepayDebtFg] [bit] NULL,
[MonthlyRepaymentAmount] [money] NULL,
[InterestOnlyRepaymentVehicle] [varchar] (255) NULL,
[CapitalRepaymentTerm] [decimal] (15, 6) NULL,
[InterestOnlyTerm] [decimal] (15, 6) NULL,
[ValueOfProperty] [money] NULL,
[PropertyType] [varchar] (50) NULL,
[InterestDetails] [varchar] (250) NULL,
[IsFirstTimeBuyer] [bit] NULL,
[TargetCompletionDate] [datetime] NULL,
[PlanMigrationRef] [varchar] (255) NULL,
[ProductPeriodId] [int] NULL,
[RedemptionFigure] [money] NULL,
[RedemptionFigure2] [money] NULL,
[NetProceed] [money] NULL,
[ProductRatePeriodInYears] [int] NULL,
[InterestRateAPR] [decimal] (10, 2) NULL,
[ConsentToLetFg] [bit] NULL,
[ConsentToLetExpiryDate] [datetime] NULL,
[PercentageOwnership] [decimal] (5, 2) NULL,
[SharedOwnershipBody] [varchar] (50) NULL,
[RentMonthly] [money] NULL,
[RefEquityLoanSchemeId] [int] NULL,
[EquitySchemeProvider] [varchar] (100) NULL,
[EquityRepaymentStartDate] [datetime] NULL,
[EquityLoanPercentage] [decimal] (5,2) NULL,
[EquityLoanAmount] [money] NULL,
[AddressId] [int] NULL,
[IsToBeConsolidated] [bit] NOT NULL CONSTRAINT [DF_TMortgage_IsToBeConsolidated] DEFAULT((0)),
[IsLiabilityToBeRepaid] [bit] NULL,
[LiabilityRepaymentDescription] [varchar](500) NULL
)
GO
ALTER TABLE [dbo].[TMortgage] ADD CONSTRAINT [PK_TMortgage] PRIMARY KEY CLUSTERED  ([MortgageId])
GO
CREATE UNIQUE NONCLUSTERED INDEX [IDX_TMortgage_PolicyBusinessId] ON [dbo].[TMortgage] ([PolicyBusinessId]) include (LoanAmount)
GO
CREATE NONCLUSTERED INDEX [IX_TMortgage_AddressStoreID] ON [dbo].[TMortgage] ([AddressStoreId]) with (Sort_in_tempdb = on)
GO
CREATE NONCLUSTERED INDEX [IX_TMortgage_AddressId] ON [dbo].[TMortgage] ([AddressId])
GO