CREATE TABLE [dbo].[TValBulkHoldingAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1),
[ValScheduleItemId] [int] NULL,
[CustomerReference] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[PortfolioReference] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[CustomerSubType] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[FirstName] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Title] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[LastName] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[CorporateName] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[DOB] [datetime] NULL,
[NINumber] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ClientAddressLine1] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[ClientAddressLine2] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[ClientAddressLine3] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[ClientAddressLine4] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[ClientPostCode] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[AdviserReference] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[AdviserFirstName] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[AdviserLastName] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[CompanyName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[AdviserPostCode] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[PortfolioId] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[HoldingId] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[PortfolioType] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Designation] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[FundProviderName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[FundName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[ISIN] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[MexId] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Sedol] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Quantity] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[EffectiveDate] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Price] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[PriceDate] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[HoldingValue] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Currency] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[WorkInProgress] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[CRMContactId] [int] NULL,
[PractitionerId] [int] NULL,
[PolicyBusinessId] [int] NULL,
[Status] [varchar] (600) COLLATE Latin1_General_CI_AS NULL,
[IsLatestFG] [bit] NOT NULL,
[SubPlanReference] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[SubPlanType] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[EpicCode] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CitiCode] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[GBPBalance] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ForeignBalance] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[AvailableCash] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[AccountName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[AccountReference] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[PolicyProviderName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[ProviderFundCode] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF_TValBulkHoldingAudit_ConcurrencyId] DEFAULT ((1)),
[ValBulkHoldingId] [int] NOT NULL,
[StampAction] [char] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[StampDateTime] [datetime] NULL CONSTRAINT [DF_TValBulkHoldingAudit_StampDateTime] DEFAULT (getdate()),
[StampUser] [varchar] (255) COLLATE Latin1_General_CI_AS NULL
)
GO
ALTER TABLE [dbo].[TValBulkHoldingAudit] ADD CONSTRAINT [PK_TValBulkHoldingAduit] PRIMARY KEY NONCLUSTERED  ([AuditId]) WITH (FILLFACTOR=80)
GO
create index IX_TValBulkHoldingAudit_StampDateTime on TValBulkHoldingAudit (StampDateTime)
go