CREATE TABLE [dbo].[TQuoteAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1),
[RefApplicationId] [int] NOT NULL,
[ExternalReference] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[RefProductTypeId] [int] NOT NULL,
[RefQuoteStatusId] [int] NOT NULL,
[Term] [int] NULL,
[MessageDateTime] [datetime] NOT NULL,
[QuoteAdviserPartyId] [int] NULL,
[AccountUserId] [int] NOT NULL,
[LoggedOnUserId] [int] NOT NULL,
[QuoteClientId1] [int] NULL,
[QuoteClientTitle1] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CRMContactId1] [int] NULL,
[QuoteClientId2] [int] NULL,
[QuoteClientTitle2] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CRMContactId2] [int] NULL,
[PolicyBusinessId] [int] NULL,
[NumberofQuoteRequests] [int] NULL,
[NumberofQuoteResponses] [int] NULL,
[DataXML] [varchar] (6000) COLLATE Latin1_General_CI_AS NULL,
[SummaryXML] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[IndigoClientId] [int] NULL,
[SequentialRef] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Guid] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[ErrorMessage] [varchar] (max) COLLATE Latin1_General_CI_AS NULL,
[ConcurrencyId] [int] NOT NULL,
[QuoteId] [int] NOT NULL,
[StampAction] [char] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[StampDateTime] [datetime] NULL,
[StampUser] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[QuoteSystemProductType] [varchar] (64) COLLATE Latin1_General_CI_AS NULL,
[QuoteInternal] [xml] NULL,
[IsLegacyQuote] [bit] NOT NULL CONSTRAINT [DF_TQuoteAudit_IsLegacyQuote] DEFAULT ((0)),
[QuoteRequestedAmount] [money] NULL,
)
GO
ALTER TABLE [dbo].[TQuoteAudit] ADD CONSTRAINT [PK_TQuoteAudit_AuditId] PRIMARY KEY NONCLUSTERED  ([AuditId]) WITH (FILLFACTOR=80)
GO
