CREATE TABLE [dbo].[TMortgageBackup]
(
[MortgageId] [int] NOT NULL IDENTITY(1, 1),
[PolicyBusinessId] [int] NOT NULL,
[IndigoClientId] [int] NOT NULL,
[MortgageRefNo] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[LoanAmount] [money] NULL,
[InterestRate] [decimal] (10, 5) NULL,
[MortgageType] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[MortgageTypeOther] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[FeatureExpiryDate] [datetime] NULL,
[PenaltyFg] [bit] NOT NULL,
[PenaltyExpiryDate] [datetime] NULL,
[RedemptionTerms] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[SchemeRate] [decimal] (10, 2) NULL,
[SchemeEndDate] [datetime] NULL,
[CompletionDate] [datetime] NULL,
[SVR] [decimal] (10, 2) NULL,
[PortableFg] [bit] NOT NULL CONSTRAINT [DF_TMortgageBackup_PortableFg] DEFAULT ((1)),
[RedeemedFg] [bit] NULL,
[SoldFg] [bit] NULL,
[AssetsId] [int] NULL,
[LiabilitiesId] [int] NULL,
[ReviewDiaryDate] [datetime] NULL,
[RefMortgageBorrowerTypeId] [int] NULL,
[RefMortgageRepaymentMethodId] [int] NULL,
[RefMortgageProductTypeId] [int] NULL,
[MortgageTerm] [int] NULL,
[MortgageTermMonths] [int] NULL,
[RemainingTerm] [int] NULL,
[PropertyValue] [int] NULL,
[IncomeEvidencedFg] [bit] NULL CONSTRAINT [DF_TMortgageBackup_IncomeEvidencedFg] DEFAULT ((0)),
[AddressStoreId] [int] NULL,
[LoanPurpose] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[PriceValuation] [money] NULL,
[Deposit] [money] NULL,
[InterestOnlyAmount] [money] NULL,
[RepaymentAmount] [money] NULL,
[LTV] [decimal] (10, 2) NULL,
[ApplicationSubmitted] [datetime] NULL,
[ValuationInstructed] [datetime] NULL,
[ValuationDate] [datetime] NULL,
[ValuationReceived] [datetime] NULL,
[OfferIssued] [datetime] NULL,
[ExchangeDate] [datetime] NULL,
[IsCurrentResidence] [bit] NULL,
[IsResdidenceAfterComplete] [bit] NULL,
[CurrentBalance] [money] NULL,
[WillPayRedemption] [bit] NULL,
[WillBeDischarged] [bit] NULL,
[RedemptionAmount] [money] NULL,
[StatusFg] [bit] NULL,
[NonStatusFg] [bit] NULL,
[SelfCertFg] [bit] NULL,
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF_TMortgageBackup_ConcurrencyId] DEFAULT ((1))
)
GO
