CREATE TABLE [dbo].[TIncomeShieldQuoteAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1),
[RefAsuPhiCoverTypeId] [int] NOT NULL,
[RefDeferredPremiumLengthId] [int] NOT NULL,
[IsTransferCover] [tinyint] NOT NULL,
[BenefitAmount] [money] NULL,
[IsNewLoan] [tinyint] NOT NULL,
[RefPaymentshieldBenefitPeriodId] [int] NOT NULL,
[RefEmploymentTypeId] [int] NOT NULL,
[QualPeriodUnemploymentId] [int] NOT NULL,
[QualTypeUnemploymentId] [int] NOT NULL,
[QualPeriodDisabilityId] [int] NOT NULL,
[QualTypeDisabilityId] [int] NOT NULL,
[IsLivingInTheUK] [tinyint] NOT NULL,
[IsTemporaryWork] [tinyint] NOT NULL,
[IsTwelveMonthEmployed] [tinyint] NOT NULL,
[IsAwareOfPreExistingMedicalExclusions] [tinyint] NOT NULL,
[IsAwareOfClaim] [tinyint] NOT NULL,
[AwareOfClaimAdditionalInfo] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[IsJobAtRisk] [tinyint] NOT NULL,
[IsCutInWorkForce] [tinyint] NOT NULL,
[IsEmployerIntoAdministrationLiquidation] [tinyint] NOT NULL,
[IsRegisteredUnemployed] [tinyint] NOT NULL,
[RefPhiTransferCoverTypeId] [int] NOT NULL,
[BenefitInsured] [money] NULL,
[CurrentProviderID] [int] NULL,
[StartDate] [datetime] NULL,
[HasMadeUnemploymentClaim] [tinyint] NOT NULL,
[ConcurrencyId] [int] NOT NULL,
[QuoteId] [int] NOT NULL,
[StampAction] [char] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[StampDateTime] [datetime] NULL CONSTRAINT [DF_TIncomeShieldQuoteAudit_StampDateTime] DEFAULT (getdate()),
[StampUser] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[NewLoanStartDate] [datetime] NULL,
[IsReferred] [bit] NULL,
[HasArrangedCredit] [int] NULL
)
GO
ALTER TABLE [dbo].[TIncomeShieldQuoteAudit] ADD CONSTRAINT [PK_TIncomeShieldQuoteAudit] PRIMARY KEY NONCLUSTERED  ([AuditId])
GO
