CREATE TABLE [dbo].[TProtectionAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[IndigoClientId] [int] NOT NULL,
[PolicyBusinessId] [int] NOT NULL,
[RefPlanSubCategoryId] [int] NOT NULL,
[PremiumLoading] [varchar] (50) NULL,
[Exclusions] [varchar] (2500) NULL,
[RenewalDate] [datetime] NULL,
[ConcurrencyId] [int] NOT NULL,
[ProtectionId] [int] NOT NULL,
[AssuredLife1Id] [int] NULL,
[AssuredLife2Id] [int] NULL,
[StampAction] [char] (1) NOT NULL,
[StampDateTime] [datetime] NULL CONSTRAINT [DF_TProtectionAudit_StampDateTime] DEFAULT (getdate()),
[StampUser] [varchar] (255) NULL,
[InTrust] [bit] NULL,
[ToWhom] [varchar] (250) NULL,
[TermValue] [int] NULL,
[PercentOfPremiumToInvest] [float] NULL,
[TermTypeId] [int] NULL,
[IndexTypeId] [int] NULL,
[LifeCoverSumAssured] [decimal] (18, 6) NULL,
[CriticalIllnessSumAssured] [decimal] (18, 6) NULL,
[WaitingPeriod] [int] NULL,
[InitialEarningsPeriodId] [int] NULL,
[PaymentBasisId] [int] NULL,
[CriticalIllnessTermValue] [int] NULL,
[ReviewDate] [datetime] NULL,
[IsForProtectionShortfallCalculation] [bit] NULL,
[PropertyInsuranceType] [varchar] (50) NULL,
[PlanMigrationRef] [varchar] (255) NULL,
[BenefitSummary] [varchar] (5000) NULL,
[ExpensePremiumStructure][varchar] (25) NULL,
[IncomePremiumStructure][varchar] (25) NULL,
[ProtectionPayoutType][varchar] (25) NULL,
[LifeCoverPremiumStructure][varchar] (25) NULL,
[LifeCoverUntilAge][int] NULL,
[CriticalIllnessPremiumStructure][varchar] (25) NULL,
[CriticalIllnessUntilAge][int] NULL,
[SeverityCoverAmount][money] NULL,
[SeverityCoverPremiumStructure][varchar] (25) NULL,
[SeverityCoverTerm][int] NULL,
[SeverityCoverUntilAge][int] NULL,
[PtdCoverAmount][money] NULL,
[PtdCoverPremiumStructure][varchar] (25) NULL,
[PtdCoverTerm][int] NULL,
[PtdCoverUntilAge][int] NULL,
[IncomeCoverTerm] [int] NULL,
[IncomeCoverUntilAge] [int] NULL,
[ExpenseCoverTerm] [int] NULL,
[ExpenseCoverUntilAge] [int] NULL
)
GO
ALTER TABLE [dbo].[TProtectionAudit] ADD CONSTRAINT [PK_TProtectionAudit] PRIMARY KEY NONCLUSTERED  ([AuditId])
GO
CREATE CLUSTERED INDEX [CLX_TProtectionAudit_ProtectionId] ON [dbo].[TProtectionAudit] ([ProtectionId])
GO