CREATE TABLE [dbo].[TPropertytobeMortgagedAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1),
[CRMContactId] [int] NOT NULL,
[SelectAddress] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[AddressLine1] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[AddressLine2] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[AddressLine3] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[AddressLine4] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[CityTown] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[County] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Country] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[PostCode] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[HouseType] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[PropertyType] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[TenureType] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[PropertyStatus] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[PropertyStatusOther] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Construction] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[PropertyExtended] [bit] NULL,
[YearBuilt] [decimal] (10, 2) NULL,
[GroundRent] [decimal] (10, 2) NULL,
[ServiceCharge] [decimal] (10, 2) NULL,
[Bedrooms] [decimal] (10, 2) NULL,
[DiningRooms] [decimal] (10, 2) NULL,
[AdditionalRooms] [decimal] (10, 2) NULL,
[Kitchens] [decimal] (10, 2) NULL,
[Bathrooms] [decimal] (10, 2) NULL,
[Toilets] [decimal] (10, 2) NULL,
[numfloors] [decimal] (10, 2) NULL,
[SingleGarages] [decimal] (10, 2) NULL,
[DoubleGarages] [decimal] (10, 2) NULL,
[Conservatory] [bit] NULL,
[BrickStone] [bit] NULL,
[TileSlate] [bit] NULL,
[SelfBuild] [bit] NULL,
[Commercial] [bit] NULL,
[AgriculturalTie] [bit] NULL,
[FloorInBlock] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[FlatsInBlock] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Walls] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Roof] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[LinktoAsset] [int] NULL,
[Linktoliability] [int] NULL,
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF_TPropertytobeMortgagedAudit_ConcurrencyId] DEFAULT ((1)),
[PropertytobeMortgagedId] [int] NOT NULL,
[StampAction] [char] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[StampDateTime] [datetime] NULL,
[StampUser] [varchar] (255) COLLATE Latin1_General_CI_AS NULL
)
GO
ALTER TABLE [dbo].[TPropertytobeMortgagedAudit] ADD CONSTRAINT [PK_TPropertytobeMortgagedAudit] PRIMARY KEY NONCLUSTERED  ([AuditId]) WITH (FILLFACTOR=80)
GO
