CREATE TABLE [dbo].[TMortgagePreferences]
(
[MortgagePreferencesId] [int] NOT NULL IDENTITY(1, 1),
[CRMContactId] [int] NOT NULL,
[likelyToChange] [bit] NULL,
[incomeTimescale] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[expenditureTimescale] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[redeemFg] [bit] NULL,
[avoidUncertainty] [bit] NULL,
[fixingPayments] [bit] NULL,
[upperLimitEarly] [bit] NULL,
[minPaymEarly] [bit] NULL,
[lendingChargeFg] [bit] NULL,
[speed] [bit] NULL,
[addFeeFg] [bit] NULL,
[varyRepaym] [bit] NULL,
[varyNoPenalty] [bit] NULL,
[overpayNoPenalty] [bit] NULL,
[underpay] [bit] NULL,
[paymHoliday] [bit] NULL,
[linkToAccount] [bit] NULL,
[freeLegalFees] [bit] NULL,
[noValFee] [bit] NULL,
[valRefunded] [bit] NULL,
[bookingFeeFg] [bit] NULL,
[cashback] [bit] NULL,
[prefLenderFg] [bit] NULL CONSTRAINT [DF__TMortgage__prefL__76EC6E40] DEFAULT ((0)),
[borrowingsFg] [bit] NULL CONSTRAINT [DF__TMortgage__borro__77E09279] DEFAULT ((0)),
[addBorrowingsFg] [bit] NULL CONSTRAINT [DF__TMortgage__addBo__78D4B6B2] DEFAULT ((0)),
[freeLegalFeesImpFg] [bit] NULL CONSTRAINT [DF__TMortgage__freeL__79C8DAEB] DEFAULT ((0)),
[notSteppedFg] [bit] NULL CONSTRAINT [DF__TMortgage__notSt__7ABCFF24] DEFAULT ((0)),
[offsetFg] [bit] NULL CONSTRAINT [DF__TMortgage__offse__7BB1235D] DEFAULT ((0)),
[borrowBack] [bit] NULL CONSTRAINT [DF__TMortgage__borro__7CA54796] DEFAULT ((0)),
[creditCard] [bit] NULL CONSTRAINT [DF__TMortgage__credi__7D996BCF] DEFAULT ((0)),
[other] [bit] NULL CONSTRAINT [DF__TMortgage__other__7E8D9008] DEFAULT ((0)),
[feesRef] [bit] NULL CONSTRAINT [DF__TMortgage__feesR__7F81B441] DEFAULT ((0)),
[portable] [bit] NULL CONSTRAINT [DF__TMortgage__porta__0075D87A] DEFAULT ((0)),
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF_TMortgagePreferences_ConcurrencyId] DEFAULT ((1)),
[LikelyToMove] [bit] NULL,
[ExpectedMoveDate] [datetime] NULL,
[HighLendingCharge] [bit] NULL,
[DailyInterestRates] [bit] NULL,
[ClubFeeMortgageAdvance] [bit] NULL
)
GO
ALTER TABLE [dbo].[TMortgagePreferences] ADD CONSTRAINT [PK_TMortgagePreferences] PRIMARY KEY NONCLUSTERED  ([MortgagePreferencesId]) WITH (FILLFACTOR=80)
GO
