CREATE TABLE [dbo].[TFieldAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1),
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF_TFieldAudit_ConcurrencyId] DEFAULT ((1)),
[EntityId] [int] NULL,
[Identifier] [varchar] (128) COLLATE Latin1_General_CI_AS NULL,
[Label] [varchar] (512) COLLATE Latin1_General_CI_AS NULL,
[Type] [varchar] (32) COLLATE Latin1_General_CI_AS NULL,
[TableName] [varchar] (64) COLLATE Latin1_General_CI_AS NULL,
[Path] [varchar] (512) COLLATE Latin1_General_CI_AS NULL,
[RefPath] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Regex] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[ErrorMessage] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[Height] [smallint] NULL,
[Width] [smallint] NULL,
[MaxLength] [smallint] NULL,
[Position] [smallint] NULL,
[PopupUrl] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[PopupHeight] [smallint] NULL,
[PopupWidth] [smallint] NULL,
[Required] [bit] NULL,
[Style] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[PdfSentenceTrigger] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[PdfSentence] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[ShowInGrid] [bit] NULL,
[Editable] [bit] NULL,
[CRMContactTypeId] [int] NULL,
[MoveableFg] [bit] NULL,
[Nab] [bit] NULL,
[IsJoint] [bit] NULL,
[PdfHide] [bit] NULL,
[ExpandInPdf] [bit] NULL,
[HideFromPortalUserFg] [bit] NOT NULL CONSTRAINT [DF_TFieldAudit_HideFromPortalUserFg] DEFAULT ((0)),
[ManageOwnersFg] [bit] NOT NULL CONSTRAINT [DF_TFieldAudit_ManageOwnersFg] DEFAULT ((0)),
[OnBlur] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Calculated] [bit] NULL,
[FieldId] [int] NOT NULL,
[StampAction] [char] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[StampDateTime] [datetime] NULL CONSTRAINT [DF_TFieldAudit_StampDateTime] DEFAULT (getdate()),
[StampUser] [varchar] (255) COLLATE Latin1_General_CI_AS NULL
)
GO
ALTER TABLE [dbo].[TFieldAudit] ADD CONSTRAINT [PK_TFieldAudit] PRIMARY KEY NONCLUSTERED  ([AuditId]) WITH (FILLFACTOR=80)
GO
