CREATE TABLE [dbo].[TEmploymentDetailAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[EmploymentStatus] [varchar] (512) NULL,
[EmploymentBusinessType] [varchar] (50) NULL,
[EmploymentStatusDescription] [varchar] (1000) NULL,
[Role] [varchar] (512) NULL,
[RefOccupationId] [int] NULL,
[Employer] [varchar] (512)  NULL,
[EmployerAddress] [varchar] (1536) NULL,
[Title] [varchar] (512) NULL,
[Share] [varchar] (512) NULL,
[StartDate] [datetime] NULL,
[Packaging] [bit] NULL,
[PackagingDetails] [varchar] (1536) NULL,
[ChangeEmployment] [bit] NULL,
[Salary] [money] NULL,
[ReviewDate] [datetime] NULL,
[BenefitsInKind] [money] NULL,
[Allowances] [money] NULL,
[Commissions] [money] NULL,
[Bonus] [money] NULL,
[NonTaxableDetails] [varchar] (1536) NULL,
[OtherTaxable] [money] NULL,
[OtherNonTaxable] [money] NULL,
[Total] [money] NULL,
[ExpectedIncomeChange] [bit] NULL,
[ExpectedIncomeChangeAmount] [money] NULL,
[CRMContactId] [int] NOT NULL,
[EmploymentDetailId] [int] NOT NULL,
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF__TEmploymentDetailAudit__ConcurrencyId] DEFAULT ((1)),
[STAMPACTION] [char] (1)  NOT NULL,
[STAMPDATETIME] [datetime] NULL,
[STAMPUSER] [varchar] (255)  NULL,
[IntendedRetirementAge] [tinyint] NULL,
[GrossAnnualEarnings] [money] NULL,
[InProbation] [bit] NULL,
[ProbationPeriod] [varchar] (16)   NULL,
[HasProjectionsForCurrentYear] [bit] NULL,
[HasStatementOfAccounts] [bit] NULL,
[HasTaxReturns] [bit] NULL,
[NumberOfYearsAccountsAvailable] [varchar] (16)  NULL,
[EmployerAddressLine1] [varchar] (255) NULL,
[EmployerAddressLine2] [varchar] (255) NULL,
[EmployerAddressLine3] [varchar] (255) NULL,
[EmployerAddressLine4] [varchar] (255) NULL,
[EmployerCityTown] [varchar] (255) NULL,
[RefCountyId] [int] NULL,
[RefCountryId] [int] NULL,
[EmployerPostcode] [varchar] (255) NULL,
[PreviousFinancialYear] [money] NULL,
[PreviousFinancialYearEndDate] [datetime] NULL,
[SecondPreviousFinancialYear] [money] NULL,
[SecondPreviousFinancialYearEndDate] [datetime] NULL,
[ThirdPreviousFinancialYear] [money] NULL,
[ThirdPreviousFinancialYearEndDate] [datetime] NULL,
[IsPastEmployment] [bit] NULL,
[EmploymentHistoryId] [int] NULL,
[EndDate] [datetime] NULL,
[BasicAnnualIncome] [money] NULL,
[GuaranteedOvertime] [money] NULL,
[GuaranteedBonus] [money] NULL,
[RegularOvertime] [money] NULL,
[RegularBonus] [money] NULL,
[MigrationRef] [varchar] (255)  NULL,
[AnyOvertimeIncome] [bit] NULL,
[AnyBonusIncome] [bit] NULL,
[NetBasicMonthlyIncome] [money] NULL,
[NetBasicMonthlyIncomeInAffordability] [bit] NULL,
[NetGuaranteedOvertime] [money] NULL,
[NetGuaranteedOvertimeInAffordability] [bit] NULL,
[NetGuaranteedBonus] [money] NULL,
[NetGuaranteedBonusInAffordability] [bit] NULL,
[NetRegularOvertime] [money] NULL,
[NetRegularOvertimeInAffordability] [bit] NULL,
[NetRegularBonus] [money] NULL,
[NetRegularBonusInAffordability] [bit] NULL,
[OtherGrossIncome] [money] NULL,
[RecentGrossPreTaxProfit] [money] NULL,
[Class] [varchar] (100)  NULL,
[ProbationPeriodMonths] [tinyint] NULL,
[AccountsAvailableYears] [tinyint] NULL,
[EmploymentHistoryDuplicateId] [int] NULL,
[IndustryType] [varchar] (100) NULL
)
GO
ALTER TABLE [dbo].[TEmploymentDetailAudit] ADD CONSTRAINT [PK_TEmploymentDetailAudit] PRIMARY KEY NONCLUSTERED  ([AuditId]) WITH (FILLFACTOR=80)
GO
CREATE NONCLUSTERED INDEX [IDX_TEmploymentDetailAudit_EmploymentDetailId_ConcurrencyId] ON [dbo].[TEmploymentDetailAudit] ([EmploymentDetailId], [ConcurrencyId]) WITH (FILLFACTOR=80)
GO
