CREATE TABLE [dbo].[TMortgagePreferencesAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1),
[CRMContactId] [int] NOT NULL,
[likelyToChange] [bit] NULL,
[incomeTimescale] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[expenditureTimescale] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[redeemFg] [bit] NULL,
[avoidUncertainty] [bit] NULL,
[fixingPayments] [bit] NULL,
[upperLimitEarly] [bit] NULL,
[minPaymEarly] [bit] NULL,
[lendingChargeFg] [bit] NULL,
[speed] [bit] NULL,
[addFeeFg] [bit] NULL,
[varyRepaym] [bit] NULL,
[varyNoPenalty] [bit] NULL,
[overpayNoPenalty] [bit] NULL,
[underpay] [bit] NULL,
[paymHoliday] [bit] NULL,
[linkToAccount] [bit] NULL,
[freeLegalFees] [bit] NULL,
[noValFee] [bit] NULL,
[valRefunded] [bit] NULL,
[bookingFeeFg] [bit] NULL,
[cashback] [bit] NULL,
[prefLenderFg] [bit] NULL,
[borrowingsFg] [bit] NULL,
[addBorrowingsFg] [bit] NULL,
[freeLegalFeesImpFg] [bit] NULL,
[notSteppedFg] [bit] NULL,
[offsetFg] [bit] NULL,
[borrowBack] [bit] NULL,
[creditCard] [bit] NULL,
[other] [bit] NULL,
[feesRef] [bit] NULL,
[portable] [bit] NULL,
[ConcurrencyId] [int] NOT NULL,
[MortgagePreferencesId] [int] NOT NULL,
[StampAction] [char] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[StampDateTime] [datetime] NULL,
[StampUser] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[LikelyToMove] [bit] NULL,
[ExpectedMoveDate] [datetime] NULL,
[HighLendingCharge] [bit] NULL,
[DailyInterestRates] [bit] NULL,
[ClubFeeMortgageAdvance] [bit] NULL
)
GO
ALTER TABLE [dbo].[TMortgagePreferencesAudit] ADD CONSTRAINT [PK_TMortgagePreferencesAudit] PRIMARY KEY NONCLUSTERED  ([AuditId]) WITH (FILLFACTOR=80)
GO
CREATE NONCLUSTERED INDEX [IDX_TMortgagePreferencesAudit_MortgagePreferencesId_ConcurrencyId] ON [dbo].[TMortgagePreferencesAudit] ([MortgagePreferencesId], [ConcurrencyId]) WITH (FILLFACTOR=80)
GO
