CREATE TABLE [dbo].[TAdviceareasAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[CRMContactId] [int] NOT NULL,
[DateOfFirstInterview] [datetime] NULL,
[AnybodyElsePresent] [bit] NULL,
[AnybodyElsePresentDetails] [varchar] (512) COLLATE Latin1_General_CI_AS NULL,
[UnprotectedLiabilities] [bit] NULL,
[SufferInIllness] [bit] NULL,
[ProtectionAdvice] [bit] NULL,
[HasPensionProvision] [bit] NULL,
[PensionProvisionProvidesRetirementIncome] [bit] NULL,
[RetirementAdvice] [bit] NULL,
[HasRegularSavings] [bit] NULL,
[HasCashDeposits] [bit] NULL,
[InvestmentAdvice] [bit] NULL,
[HasValidWill] [bit] NULL,
[IsWillUptoDate] [bit] NULL,
[EstateAdvice] [bit] NULL,
[AdviceOption] [varchar] (512) COLLATE Latin1_General_CI_AS NULL,
[PA] [bit] NULL,
[RPA] [bit] NULL,
[SIA] [bit] NULL,
[ProtectAgainstDeath] [bit] NULL,
[ProtectAgainstIllness] [bit] NULL,
[ProtectEarnings] [bit] NULL,
[ProvideRetirementIncome] [bit] NULL,
[ProtectMortgage] [bit] NULL,
[PMI] [bit] NULL,
[InvestingCapital] [bit] NULL,
[RegSavings] [bit] NULL,
[InheritanceTaxPlanning] [bit] NULL,
[SchoolFeesPlanning] [bit] NULL,
[LongTermCare] [bit] NULL,
[PurchasingProperty] [bit] NULL,
[RemortgagingProperty] [bit] NULL,
[RaisingCapital] [bit] NULL,
[MortgageAdvice] [bit] NULL,
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF__TAdviceAreasAudit__ConcurrencyId] DEFAULT ((1)),
[AdviceareasId] [int] NOT NULL,
[StampAction] [char] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[StampDateTime] [datetime] NULL,
[StampUser] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[RefInterviewTypeId] [int] NULL,
[ClientsPresent] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[HasBeenAdvisedToMakeWill] [bit] NULL
)
GO
ALTER TABLE [dbo].[TAdviceareasAudit] ADD CONSTRAINT [PK_TAdviceareasAudit] PRIMARY KEY NONCLUSTERED  ([AuditId]) WITH (FILLFACTOR=80)
GO
CREATE CLUSTERED INDEX [IX_TAdviceareasAudit_CRMContactId] ON [dbo].[TAdviceareasAudit] ([CRMContactId]) WITH (FILLFACTOR=80)
GO
