CREATE TABLE [dbo].[_MetadataLog](
    [MetadataLogId] [INT] IDENTITY(1,1) NOT NULL,
    [Type] [NVARCHAR](512) NOT NULL,
    [Hash] [NVARCHAR](512) NULL,    
    [TimeStamp] [DATETIME] NULL CONSTRAINT [DF_MetadataLog_TimeStamp]  DEFAULT (GETDATE()),
 CONSTRAINT [PK_MetadataLog] PRIMARY KEY CLUSTERED 
(
    [MetadataLogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO