CREATE TABLE [dbo].[TIndigoClientAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[Identifier] [varchar] (64) COLLATE Latin1_General_CI_AS NOT NULL,
[Status] [varchar] (24) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_TIndigoClientAudit_Status] DEFAULT ('New'),
[PrimaryContact] [varchar] (128) COLLATE Latin1_General_CI_AS NOT NULL,
[ContactId] [int] NULL,
[PhoneNumber] [varchar] (40) COLLATE Latin1_General_CI_AS NOT NULL,
[EmailAddress] [varchar] (128) COLLATE Latin1_General_CI_AS NOT NULL,
[AdminEmail] [varchar] (128) COLLATE Latin1_General_CI_AS NULL,
[PrimaryGroupId] [int] NULL,
[NetworkId] [int] NULL,
[SIB] [varchar] (24) COLLATE Latin1_General_CI_AS NULL,
[MCCB] [varchar] (24) COLLATE Latin1_General_CI_AS NULL,
[FSA] [varchar] (24) COLLATE Latin1_General_CI_AS NULL,
[IOProductType] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[ExpiryDate] [datetime] NOT NULL,
[AddressLine1] [varchar] (1000) COLLATE Latin1_General_CI_AS NOT NULL,
[AddressLine2] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[AddressLine3] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[AddressLine4] [varchar] (1000) COLLATE Latin1_General_CI_AS NULL,
[CityTown] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[County] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[Postcode] [varchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[Country] [varchar] (128) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_TIndigoClientAudit_Country] DEFAULT ('UK'),
[IsNetwork] [bit] NOT NULL CONSTRAINT [DF_TIndigoClientAudit_NetOrSupSvcFg] DEFAULT ((0)),
[SupportServiceId] [int] NULL,
[FirmSize] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[Specialism] [varchar] (128) COLLATE Latin1_General_CI_AS NOT NULL,
[OtherSpecialism] [varchar] (128) COLLATE Latin1_General_CI_AS NULL,
[SupportLevel] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[EmailSupOptn] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[SupportEmail] [varchar] (128) COLLATE Latin1_General_CI_AS NOT NULL,
[TelSupOptn] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[SupportTelephone] [varchar] (40) COLLATE Latin1_General_CI_AS NOT NULL,
[AllowPasswordEmail] [bit] NOT NULL CONSTRAINT [DF_TIndigoClientAudit_AllowPasswordEmail] DEFAULT ((1)),
[SessionTimeout] [int] NOT NULL,
[LicenceType] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[MaxConUsers] [int] NULL,
[MaxULAGCount] [int] NULL,
[UADRestriction] [bit] NOT NULL,
[MaxULADCount] [int] NULL,
[AdviserCountRestrict] [bit] NOT NULL,
[MaxAdviserCount] [int] NULL,
[MaxFinancialPlanningUsers] [int] NULL,
[EmailFormat] [varchar] (128) COLLATE Latin1_General_CI_AS NULL,
[UserNameFormat] [varchar] (24) COLLATE Latin1_General_CI_AS NULL,
[NTDomain] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[IsIndependent] [bit] NOT NULL CONSTRAINT [DF_TIndigoClientAudit_IsIndependent] DEFAULT ((1)),
[BrandDescriptor] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ServiceLevel] [int] NULL,
[HostingFg] [bit] NOT NULL CONSTRAINT [DF_TIndigoClientAudit_HostingFg] DEFAULT ((0)),
[CaseLoggingOption] [int] NOT NULL CONSTRAINT [DF_TIndigoClientAudit_CaseLoggingOption] DEFAULT ((0)),
[Guid] [uniqueidentifier] NULL CONSTRAINT [DF_TIndigoClientAudit_Guid] DEFAULT (newid()),
[RefEnvironmentId] [int] NULL,
[IsPortfolioConstructionProvider] [bit] NOT NULL CONSTRAINT [DF_TIndigoClientAudit_IsPortfolioConstructionProvider] DEFAULT ((0)),
[IsAuthorProvider] [bit] NOT NULL CONSTRAINT [DF_TIndigoClientAudit_IsAuthorProvider] DEFAULT ((0)),
[IsAtrProvider] [bit] NOT NULL CONSTRAINT [DF_TIndigoClientAudit_IsAtrProvider] DEFAULT ((0)),
[MortgageBenchLicenceCount] [bit] NULL,
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF_TIndigoClientAudit_ConcurrencyId] DEFAULT ((1)),
[IndigoClientId] [int] NOT NULL,
[StampAction] [char] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[StampDateTime] [datetime] NULL CONSTRAINT [DF_TIndigoClientAudit_StampDateTime] DEFAULT (getdate()),
[StampUser] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[MaxOutlookExtensionUsers] [int] NULL,
[MaxAdvisaCentaCoreUsers] [int] NULL,
[MaxAdvisaCentaCorePlusLifetimePlannerUsers] [int] NULL,
[MaxFeAnalyticsCoreUsers] [int] NULL,
[MaxVoyantUsers] [int] NULL,
[MaxAdvisaCentaFullUsers] [int] NULL,
[MaxAdvisaCentaFullPlusLifetimePlannerUsers] [int] NULL,
[MaxPensionFreedomPlannerUsers] [int] NULL,
[MaxSolutionBuilderUsers] [int] NULL,
[LEI] [NVARCHAR](20) NULL,
[RefTenantTypeId] [int] NULL
)
GO
ALTER TABLE [dbo].[TIndigoClientAudit] ADD CONSTRAINT [PK_TIndigoClientAudit_AuditId] PRIMARY KEY NONCLUSTERED  ([AuditId]) WITH (FILLFACTOR=80)
GO
CREATE NONCLUSTERED INDEX [IDXAudit_TIndigoClientAudit_IndigoClientId_ConcurrencyId] ON [dbo].[TIndigoClientAudit] ([IndigoClientId], [ConcurrencyId]) WITH (FILLFACTOR=80)
GO
