SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TUserGroup](
	UserGroupId INT IDENTITY(1,1) NOT NULL,	
	UserId		INT NOT NULL,
	GroupId		INT NOT NULL,
	RoleId		INT NOT NULL,
	ConcurrencyId	INT NOT NULL
	CONSTRAINT [PK_TUserGroup] PRIMARY KEY NONCLUSTERED 
(
	UserGroupId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TUserGroup] ADD  CONSTRAINT [DF_TUserGroup_ConcurrencyId]  DEFAULT ((1)) FOR [ConcurrencyId]
GO

ALTER TABLE [dbo].[TUserGroup] ADD CONSTRAINT UC_TUserGroup_UserId_GroupId_RoleId UNIQUE (UserId, GroupId, RoleId)
GO

CREATE CLUSTERED INDEX [IX_TUserGroup_UserId] ON [dbo].[TUserGroup]
(
	[UserId] ASC
)
GO


