CREATE TABLE [dbo].[TUserAudit]
(
[AuditId] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[Identifier] [varchar] (64) COLLATE Latin1_General_CI_AS NOT NULL,
[Password] [varchar] (max) COLLATE Latin1_General_CI_AS NULL,
[PasswordSalt] [varchar] (max) COLLATE Latin1_General_CI_AS NULL,
[PasswordHistory] [varchar] (512) COLLATE Latin1_General_CI_AS NULL CONSTRAINT [DF_TUserAudit_PasswordHistory] DEFAULT (''),
[Email] [varchar] (128) COLLATE Latin1_General_CI_AS NOT NULL,
[Telephone] [varchar] (16) COLLATE Latin1_General_CI_AS NULL,
[Status] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[GroupId] [int] NOT NULL,
[SyncPassword] [bit] NULL CONSTRAINT [DF_TUserAudit_SyncPassword] DEFAULT ((0)),
[ExpirePasswordOn] [datetime] NULL,
[SuperUser] [bit] NOT NULL CONSTRAINT [DF_TUserAudit_SuperUser] DEFAULT ((0)),
[SuperViewer] [bit] NOT NULL CONSTRAINT [DF_TUserAudit_SuperViewer] DEFAULT ((0)),
[FinancialPlanningAccess] [bit] NOT NULL CONSTRAINT [DF_TUserAudit_FinancialPlanningAccess] DEFAULT ((0)),
[FailedAccessAttempts] [tinyint] NOT NULL CONSTRAINT [DF_TUserAudit_FailedAccessAttempts] DEFAULT ((0)),
[WelcomePage] [varchar] (64) COLLATE Latin1_General_CI_AS NOT NULL CONSTRAINT [DF_TUserAudit_WelcomePage] DEFAULT ('goto,news,links'),
[Reference] [varchar] (64) COLLATE Latin1_General_CI_AS NULL,
[CRMContactId] [int] NULL,
[SearchData] [text] COLLATE Latin1_General_CI_AS NULL,
[RecentData] [text] COLLATE Latin1_General_CI_AS NULL,
[RecentWork] [text] COLLATE Latin1_General_CI_AS NULL,
[IndigoClientId] [int] NULL,
[SupportUserFg] [bit] NOT NULL CONSTRAINT [DF_TUserAudit_SupportUserFg] DEFAULT ((0)),
[ActiveRole] [int] NULL,
[CanLogCases] [bit] NOT NULL CONSTRAINT [DF_TUserAudit_CanLogCases] DEFAULT ((0)),
[RefUserTypeId] [int] NOT NULL CONSTRAINT [DF_TUserAudit_RefUserTypeId] DEFAULT ((1)),
[Guid] [uniqueidentifier] NOT NULL,
[ConcurrencyId] [int] NOT NULL CONSTRAINT [DF_TUserAudit_ConcurrencyId] DEFAULT ((1)),
[IsMortgageBenchEnabled] [bit] NOT NULL CONSTRAINT [DF_TUserAudit_IsMortgageBenchEnabled] DEFAULT ((0)),
[IsMIReportDesigner] [bit] NOT NULL CONSTRAINT [DF_TUserAudit_IsMIReportDesigner] DEFAULT ((0)),
[IsMIReportManager] [bit] NOT NULL CONSTRAINT [DF_TUserAudit_IsMIReportManager] DEFAULT ((0)),
[UserId] [int] NOT NULL,
[StampAction] [char] (1) COLLATE Latin1_General_CI_AS NOT NULL,
[StampDateTime] [datetime] NULL CONSTRAINT [DF_TUserAudit_StampDateTime] DEFAULT (getdate()),
[StampUser] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[LockedOutUntilDateTime] [datetime] NULL,
[EmailConfirmed] [bit] NOT NULL CONSTRAINT [DF_TUserAudit_EmailConfirmed] DEFAULT ((1)),
[IsOutLookExtensionUser] [bit] NOT NULL CONSTRAINT [DF_TUserAudit_IsOutLookExtensionUser] DEFAULT ((0)),
[AdvisaCentaCoreAccess] [bit] NULL,
[AdvisaCentaCorePlusAccess] [bit] NULL,
[PensionFreedomPlanner] [bit] NULL,
[FeAnalyticsAccess] [bit] NULL,
[IsVoyantUser] [bit] NOT NULL CONSTRAINT [DF_TUserAudit_IsVoyantUser] DEFAULT ((0)),
[AdvisaCentaFullAccess] [bit] NOT NULL CONSTRAINT [DF_TUSERAUDIT_AdvisaCentaFullAccess] DEFAULT ((0)),
[AdvisaCentaFullAccessPlusLifetimePlanner] [bit] NOT NULL CONSTRAINT [DF_TUSERAUDIT_AdvisaCentaFullAccessPlusLifetimePlanner] DEFAULT ((0)),
[SolutionBuilderAccess] [bit] NOT NULL CONSTRAINT [DF_USERAUDIT_SolutionBuilderAccess] DEFAULT ((0)),
[Timezone] [varchar] (100) NOT NULL CONSTRAINT [DF_TUserAudit_Timezone]  DEFAULT ('Europe/London'),
[Is2faEnabled] [bit] NOT NULL CONSTRAINT [DF_TUserAudit_Is2faEnabled] DEFAULT((0)),
[HasGroupDataAccess] [bit] NOT NULL CONSTRAINT [DF_TUserAudit_HasGroupDataAccess] DEFAULT((0)),
[LastLoginAt] [datetime] NULL,
[Qualification] [varchar](100) NULL,
[JobTitle] [varchar](100) NULL,
[Signature] [varchar](250) NULL
)
GO
ALTER TABLE [dbo].[TUserAudit] ADD CONSTRAINT [PK_TUserAudit_AuditId] PRIMARY KEY NONCLUSTERED  ([AuditId]) WITH (FILLFACTOR=90)
GO
CREATE NONCLUSTERED INDEX [IX_TUserAudit_ConcurrencyId_UserId] ON [dbo].[TUserAudit] ([ConcurrencyId], [UserId]) INCLUDE ([ActiveRole], [CanLogCases], [CRMContactId], [Email], [ExpirePasswordOn], [FailedAccessAttempts], [GroupId], [Guid], [Identifier], [IndigoClientId], [Password], [PasswordHistory], [Reference], [RefUserTypeId], [Status], [SuperUser], [SuperViewer], [SupportUserFg], [SyncPassword], [Telephone], [WelcomePage]) WITH (FILLFACTOR=90)
GO
CREATE NONCLUSTERED INDEX [IX_TUserAudit_StampDateTime_UserId] ON [dbo].[TUserAudit] ([StampDateTime], [UserId])
GO
