CREATE TABLE [dbo].[TStructure]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[OrganisationName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[OGroupId] [int] NULL,
[GroupName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[GGroupId] [int] NULL,
[DivisionName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[DGroupId] [int] NULL,
[RegionName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[RGroupId] [int] NULL,
[AreaName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[AGroupId] [int] NULL,
[NewOrUpdated] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[AdviserName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[FirstName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[LastName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[UserId] [int] NULL,
[UserLogon] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[OUGroupId] [int] NULL,
[OriginalDivisionName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[ODGroupId] [int] NULL,
[OriginalRegionName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[ORGroupId] [int] NULL,
[OriginalAreaName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[OAGroupId] [int] NULL,
[OAParentId] [int] NULL,
[ProcessedState] [int] NULL CONSTRAINT [DF__TStructur__Proce__3F9C3956] DEFAULT ((0))
)
GO
