SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[SpRetrievePractitionerWithCRMContactKyCRMContactIdThenCRMContactWithUserOnAdministrationKyCRMContactIdById]
@PractitionerId bigint
AS

BEGIN
  SELECT
    1 AS Tag,
    NULL AS Parent,
    T1.PractitionerId AS [Practitioner!1!PractitionerId], 
    T1.IndClientId AS [Practitioner!1!IndClientId], 
    ISNULL(T1.PersonId, '') AS [Practitioner!1!PersonId], 
    ISNULL(T1.CRMContactId, '') AS [Practitioner!1!CRMContactId], 
    ISNULL(T1.TnCCoachId, '') AS [Practitioner!1!TnCCoachId], 
    T1.AuthorisedFG AS [Practitioner!1!AuthorisedFG], 
    ISNULL(T1.PIARef, '') AS [Practitioner!1!PIARef], 
    ISNULL(CONVERT(varchar(24), T1.AuthorisedDate, 120),'') AS [Practitioner!1!AuthorisedDate], 
    ISNULL(T1.ExperienceLevel, '') AS [Practitioner!1!ExperienceLevel], 
    T1.FSAReference AS [Practitioner!1!FSAReference], 
    T1.MultiTieFg AS [Practitioner!1!MultiTieFg], 
    T1.OffPanelFg AS [Practitioner!1!OffPanelFg], 
    ISNULL(T1.PractitionerTypeId, '') AS [Practitioner!1!PractitionerTypeId], 
    ISNULL(T1._ParentId, '') AS [Practitioner!1!_ParentId], 
    ISNULL(T1._ParentTable, '') AS [Practitioner!1!_ParentTable], 
    ISNULL(T1._ParentDb, '') AS [Practitioner!1!_ParentDb], 
    ISNULL(T1._OwnerId, '') AS [Practitioner!1!_OwnerId], 
    T1.ConcurrencyId AS [Practitioner!1!ConcurrencyId], 
    NULL AS [CRMContact!2!CRMContactId], 
    NULL AS [CRMContact!2!RefCRMContactStatusId], 
    NULL AS [CRMContact!2!PersonId], 
    NULL AS [CRMContact!2!CorporateId], 
    NULL AS [CRMContact!2!TrustId], 
    NULL AS [CRMContact!2!AdvisorRef], 
    NULL AS [CRMContact!2!RefSourceOfClientId], 
    NULL AS [CRMContact!2!SourceValue], 
    NULL AS [CRMContact!2!Notes], 
    NULL AS [CRMContact!2!ArchiveFg], 
    NULL AS [CRMContact!2!LastName], 
    NULL AS [CRMContact!2!FirstName], 
    NULL AS [CRMContact!2!CorporateName], 
    NULL AS [CRMContact!2!DOB], 
    NULL AS [CRMContact!2!Postcode], 
    NULL AS [CRMContact!2!OriginalAdviserCRMId], 
    NULL AS [CRMContact!2!CurrentAdviserCRMId], 
    NULL AS [CRMContact!2!CurrentAdviserName], 
    NULL AS [CRMContact!2!CRMContactType], 
    NULL AS [CRMContact!2!IndClientId], 
    NULL AS [CRMContact!2!FactFindId], 
    NULL AS [CRMContact!2!InternalContactFG], 
    NULL AS [CRMContact!2!RefServiceStatusId], 
    NULL AS [CRMContact!2!MigrationRef], 
    NULL AS [CRMContact!2!CreatedDate], 
    NULL AS [CRMContact!2!ExternalReference], 
    NULL AS [CRMContact!2!CampaignDataId], 
    NULL AS [CRMContact!2!AdditionalRef], 
    NULL AS [CRMContact!2!_ParentId], 
    NULL AS [CRMContact!2!_ParentTable], 
    NULL AS [CRMContact!2!_ParentDb], 
    NULL AS [CRMContact!2!_OwnerId], 
    NULL AS [CRMContact!2!ConcurrencyId], 
    NULL AS [User!3!UserId], 
    NULL AS [User!3!Identifier], 
    NULL AS [User!3!Password], 
    NULL AS [User!3!PasswordHistory], 
    NULL AS [User!3!Email], 
    NULL AS [User!3!Telephone], 
    NULL AS [User!3!Status], 
    NULL AS [User!3!GroupId], 
    NULL AS [User!3!SyncPassword], 
    NULL AS [User!3!ExpirePasswordOn], 
    NULL AS [User!3!SuperUser], 
    NULL AS [User!3!SuperViewer], 
    NULL AS [User!3!FinancialPlanningAccess], 
    NULL AS [User!3!FailedAccessAttempts], 
    NULL AS [User!3!WelcomePage], 
    NULL AS [User!3!Reference], 
    NULL AS [User!3!CRMContactId], 
    NULL AS [User!3!SearchData], 
    NULL AS [User!3!RecentData], 
    NULL AS [User!3!RecentWork], 
    NULL AS [User!3!IndigoClientId], 
    NULL AS [User!3!SupportUserFg], 
    NULL AS [User!3!ActiveRole], 
    NULL AS [User!3!CanLogCases], 
    NULL AS [User!3!RefUserTypeId], 
    NULL AS [User!3!Guid], 
    NULL AS [User!3!IsMortgageBenchEnabled], 
    NULL AS [User!3!ConcurrencyId]
  FROM TPractitioner T1

  WHERE (T1.PractitionerId = @PractitionerId)

  UNION ALL

  SELECT
    2 AS Tag,
    1 AS Parent,
    T1.PractitionerId, 
    T1.IndClientId, 
    ISNULL(T1.PersonId, ''), 
    ISNULL(T1.CRMContactId, ''), 
    ISNULL(T1.TnCCoachId, ''), 
    T1.AuthorisedFG, 
    ISNULL(T1.PIARef, ''), 
    ISNULL(CONVERT(varchar(24), T1.AuthorisedDate, 120),''), 
    ISNULL(T1.ExperienceLevel, ''), 
    T1.FSAReference, 
    T1.MultiTieFg, 
    T1.OffPanelFg, 
    ISNULL(T1.PractitionerTypeId, ''), 
    ISNULL(T1._ParentId, ''), 
    ISNULL(T1._ParentTable, ''), 
    ISNULL(T1._ParentDb, ''), 
    ISNULL(T1._OwnerId, ''), 
    T1.ConcurrencyId, 
    T2.CRMContactId, 
    ISNULL(T2.RefCRMContactStatusId, ''), 
    ISNULL(T2.PersonId, ''), 
    ISNULL(T2.CorporateId, ''), 
    ISNULL(T2.TrustId, ''), 
    ISNULL(T2.AdvisorRef, ''), 
    ISNULL(T2.RefSourceOfClientId, ''), 
    ISNULL(T2.SourceValue, ''), 
    ISNULL(T2.Notes, ''), 
    ISNULL(T2.ArchiveFg, ''), 
    ISNULL(T2.LastName, ''), 
    ISNULL(T2.FirstName, ''), 
    ISNULL(T2.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T2.DOB, 120),''), 
    ISNULL(T2.Postcode, ''), 
    T2.OriginalAdviserCRMId, 
    T2.CurrentAdviserCRMId, 
    ISNULL(T2.CurrentAdviserName, ''), 
    T2.CRMContactType, 
    T2.IndClientId, 
    ISNULL(T2.FactFindId, ''), 
    ISNULL(T2.InternalContactFG, ''), 
    ISNULL(T2.RefServiceStatusId, ''), 
    ISNULL(T2.MigrationRef, ''), 
    CONVERT(varchar(24), T2.CreatedDate, 120), 
    ISNULL(T2.ExternalReference, ''), 
    ISNULL(T2.CampaignDataId, ''), 
    ISNULL(T2.AdditionalRef, ''), 
    ISNULL(T2._ParentId, ''), 
    ISNULL(T2._ParentTable, ''), 
    ISNULL(T2._ParentDb, ''), 
    ISNULL(T2._OwnerId, ''), 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TCRMContact T2
  INNER JOIN TPractitioner T1
  ON T2.CRMContactId = T1.CRMContactId

  WHERE (T1.PractitionerId = @PractitionerId)

  UNION ALL

  SELECT
    3 AS Tag,
    2 AS Parent,
    T1.PractitionerId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T2.CRMContactId, 
    ISNULL(T2.RefCRMContactStatusId, ''), 
    ISNULL(T2.PersonId, ''), 
    ISNULL(T2.CorporateId, ''), 
    ISNULL(T2.TrustId, ''), 
    ISNULL(T2.AdvisorRef, ''), 
    ISNULL(T2.RefSourceOfClientId, ''), 
    ISNULL(T2.SourceValue, ''), 
    ISNULL(T2.Notes, ''), 
    ISNULL(T2.ArchiveFg, ''), 
    ISNULL(T2.LastName, ''), 
    ISNULL(T2.FirstName, ''), 
    ISNULL(T2.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T2.DOB, 120),''), 
    ISNULL(T2.Postcode, ''), 
    T2.OriginalAdviserCRMId, 
    T2.CurrentAdviserCRMId, 
    ISNULL(T2.CurrentAdviserName, ''), 
    T2.CRMContactType, 
    T2.IndClientId, 
    ISNULL(T2.FactFindId, ''), 
    ISNULL(T2.InternalContactFG, ''), 
    ISNULL(T2.RefServiceStatusId, ''), 
    ISNULL(T2.MigrationRef, ''), 
    CONVERT(varchar(24), T2.CreatedDate, 120), 
    ISNULL(T2.ExternalReference, ''), 
    ISNULL(T2.CampaignDataId, ''), 
    ISNULL(T2.AdditionalRef, ''), 
    ISNULL(T2._ParentId, ''), 
    ISNULL(T2._ParentTable, ''), 
    ISNULL(T2._ParentDb, ''), 
    ISNULL(T2._OwnerId, ''), 
    T2.ConcurrencyId, 
    T3.UserId, 
    T3.Identifier, 
    T3.Password, 
    ISNULL(T3.PasswordHistory, ''), 
    T3.Email, 
    ISNULL(T3.Telephone, ''), 
    T3.Status, 
    T3.GroupId, 
    ISNULL(T3.SyncPassword, ''), 
    ISNULL(CONVERT(varchar(24), T3.ExpirePasswordOn, 120),''), 
    T3.SuperUser, 
    T3.SuperViewer, 
    T3.FinancialPlanningAccess, 
    T3.FailedAccessAttempts, 
    T3.WelcomePage, 
    ISNULL(T3.Reference, ''), 
    ISNULL(T3.CRMContactId, ''), 
    NULL, 
    NULL, 
    NULL, 
    ISNULL(T3.IndigoClientId, ''), 
    T3.SupportUserFg, 
    ISNULL(T3.ActiveRole, ''), 
    T3.CanLogCases, 
    T3.RefUserTypeId, 
    T3.Guid, 
    T3.IsMortgageBenchEnabled, 
    T3.ConcurrencyId
  FROM [Administration].[dbo].TUser T3
  INNER JOIN TCRMContact T2
  ON T3.CRMContactId = T2.CRMContactId
  INNER JOIN TPractitioner T1
  ON T2.CRMContactId = T1.CRMContactId

  WHERE (T1.PractitionerId = @PractitionerId)

  ORDER BY [Practitioner!1!PractitionerId], [CRMContact!2!CRMContactId], [User!3!UserId]

  FOR XML EXPLICIT

END
RETURN (0)

GO
