SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[SpAliasEventListWithActivities]
@EventListId bigint
AS

BEGIN
  SELECT
    1 AS Tag,
    NULL AS Parent,
    T1.EventListId AS [EventList!1!EventListId], 
    T1.Name AS [EventList!1!Name], 
    T1.EventListTemplateId AS [EventList!1!EventListTemplateId], 
    T1.OwnerUserId AS [EventList!1!OwnerUserId], 
    ISNULL(CONVERT(varchar(24), T1.StartDate, 120),'') AS [EventList!1!StartDate], 
    T1.ClientCRMContactId AS [EventList!1!ClientCRMContactId], 
    ISNULL(T1.PlanId, '') AS [EventList!1!PlanId], 
    T1.IndigoClientId AS [EventList!1!IndigoClientId], 
    T1.ConcurrencyId AS [EventList!1!ConcurrencyId], 
    NULL AS [EventListActivity!2!EventListActivityId], 
    NULL AS [EventListActivity!2!EventListId], 
    NULL AS [EventListActivity!2!EventListTemplateActivityId], 
    NULL AS [EventListActivity!2!FixedDate], 
    NULL AS [EventListActivity!2!Duration], 
    NULL AS [EventListActivity!2!ElapsedDays], 
    NULL AS [EventListActivity!2!EditElapsedDaysFg], 
    NULL AS [EventListActivity!2!AssignedUserId], 
    NULL AS [EventListActivity!2!AssignedRoleId], 
    NULL AS [EventListActivity!2!StartDate], 
    NULL AS [EventListActivity!2!DeletedFg], 
    NULL AS [EventListActivity!2!CompletedFg], 
    NULL AS [EventListActivity!2!ConcurrencyId], 
    NULL AS [EventListTemplateActivity!3!EventListTemplateActivityId], 
    NULL AS [EventListTemplateActivity!3!EventListTemplateId], 
    NULL AS [EventListTemplateActivity!3!ActivityCategoryId], 
    NULL AS [EventListTemplateActivity!3!FixedDateFg], 
    NULL AS [EventListTemplateActivity!3!DeletableFg], 
    NULL AS [EventListTemplateActivity!3!Duration], 
    NULL AS [EventListTemplateActivity!3!ElapsedDays], 
    NULL AS [EventListTemplateActivity!3!EditElapsedDaysFg], 
    NULL AS [EventListTemplateActivity!3!AssignedUserId], 
    NULL AS [EventListTemplateActivity!3!ConcurrencyId], 
    NULL AS [User!4!UserId], 
    NULL AS [User!4!Identifier], 
    NULL AS [User!4!Password], 
    NULL AS [User!4!PasswordHistory], 
    NULL AS [User!4!Email], 
    NULL AS [User!4!Telephone], 
    NULL AS [User!4!Status], 
    NULL AS [User!4!GroupId], 
    NULL AS [User!4!SyncPassword], 
    NULL AS [User!4!ExpirePasswordOn], 
    NULL AS [User!4!SuperUser], 
    NULL AS [User!4!SuperViewer], 
    NULL AS [User!4!FinancialPlanningAccess], 
    NULL AS [User!4!FailedAccessAttempts], 
    NULL AS [User!4!WelcomePage], 
    NULL AS [User!4!Reference], 
    NULL AS [User!4!CRMContactId], 
    NULL AS [User!4!SearchData], 
    NULL AS [User!4!RecentData], 
    NULL AS [User!4!RecentWork], 
    NULL AS [User!4!IndigoClientId], 
    NULL AS [User!4!SupportUserFg], 
    NULL AS [User!4!ActiveRole], 
    NULL AS [User!4!CanLogCases], 
    NULL AS [User!4!RefUserTypeId], 
    NULL AS [User!4!Guid], 
    NULL AS [User!4!ConcurrencyId], 
    NULL AS [ActivityCategory!5!ActivityCategoryId], 
    NULL AS [ActivityCategory!5!Name], 
    NULL AS [ActivityCategory!5!ActivityCategoryParentId], 
    NULL AS [ActivityCategory!5!LifeCycleTransitionId], 
    NULL AS [ActivityCategory!5!IndigoClientId], 
    NULL AS [ActivityCategory!5!ClientRelatedFG], 
    NULL AS [ActivityCategory!5!PlanRelatedFG], 
    NULL AS [ActivityCategory!5!FeeRelatedFG], 
    NULL AS [ActivityCategory!5!RetainerRelatedFG], 
    NULL AS [ActivityCategory!5!OpportunityRelatedFG], 
    NULL AS [ActivityCategory!5!AdviserRelatedFg], 
    NULL AS [ActivityCategory!5!ActivityEvent], 
    NULL AS [ActivityCategory!5!RefSystemEventId], 
    NULL AS [ActivityCategory!5!TemplateTypeId], 
    NULL AS [ActivityCategory!5!TemplateId], 
    NULL AS [ActivityCategory!5!ConcurrencyId], 
    NULL AS [CRMContact!6!CRMContactId], 
    NULL AS [CRMContact!6!RefCRMContactStatusId], 
    NULL AS [CRMContact!6!PersonId], 
    NULL AS [CRMContact!6!CorporateId], 
    NULL AS [CRMContact!6!TrustId], 
    NULL AS [CRMContact!6!AdvisorRef], 
    NULL AS [CRMContact!6!RefSourceOfClientId], 
    NULL AS [CRMContact!6!SourceValue], 
    NULL AS [CRMContact!6!Notes], 
    NULL AS [CRMContact!6!ArchiveFg], 
    NULL AS [CRMContact!6!LastName], 
    NULL AS [CRMContact!6!FirstName], 
    NULL AS [CRMContact!6!CorporateName], 
    NULL AS [CRMContact!6!DOB], 
    NULL AS [CRMContact!6!Postcode], 
    NULL AS [CRMContact!6!OriginalAdviserCRMId], 
    NULL AS [CRMContact!6!CurrentAdviserCRMId], 
    NULL AS [CRMContact!6!CurrentAdviserName], 
    NULL AS [CRMContact!6!CRMContactType], 
    NULL AS [CRMContact!6!IndClientId], 
    NULL AS [CRMContact!6!FactFindId], 
    NULL AS [CRMContact!6!InternalContactFG], 
    NULL AS [CRMContact!6!RefServiceStatusId], 
    NULL AS [CRMContact!6!MigrationRef], 
    NULL AS [CRMContact!6!CreatedDate], 
    NULL AS [CRMContact!6!ExternalReference], 
    NULL AS [CRMContact!6!CampaignDataId], 
    NULL AS [CRMContact!6!AdditionalRef], 
    NULL AS [CRMContact!6!_ParentId], 
    NULL AS [CRMContact!6!_ParentTable], 
    NULL AS [CRMContact!6!_ParentDb], 
    NULL AS [CRMContact!6!_OwnerId], 
    NULL AS [CRMContact!6!ConcurrencyId]
  FROM TEventList T1

  WHERE (T1.EventListId = @EventListId)

  UNION ALL

  SELECT
    2 AS Tag,
    1 AS Parent,
    T1.EventListId, 
    T1.Name, 
    T1.EventListTemplateId, 
    T1.OwnerUserId, 
    ISNULL(CONVERT(varchar(24), T1.StartDate, 120),''), 
    T1.ClientCRMContactId, 
    ISNULL(T1.PlanId, ''), 
    T1.IndigoClientId, 
    T1.ConcurrencyId, 
    T2.EventListActivityId, 
    T2.EventListId, 
    T2.EventListTemplateActivityId, 
    ISNULL(CONVERT(varchar(24), T2.FixedDate, 120),''), 
    ISNULL(T2.Duration, ''), 
    ISNULL(T2.ElapsedDays, ''), 
    T2.EditElapsedDaysFg, 
    ISNULL(T2.AssignedUserId, ''), 
    ISNULL(T2.AssignedRoleId, ''), 
    ISNULL(CONVERT(varchar(24), T2.StartDate, 120),''), 
    T2.DeletedFg, 
    T2.CompletedFg, 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TEventListActivity T2
  INNER JOIN TEventList T1
  ON T2.EventListId = T1.EventListId

  WHERE (T1.EventListId = @EventListId)

  UNION ALL

  SELECT
    3 AS Tag,
    2 AS Parent,
    T1.EventListId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T2.EventListActivityId, 
    T2.EventListId, 
    T2.EventListTemplateActivityId, 
    ISNULL(CONVERT(varchar(24), T2.FixedDate, 120),''), 
    ISNULL(T2.Duration, ''), 
    ISNULL(T2.ElapsedDays, ''), 
    T2.EditElapsedDaysFg, 
    ISNULL(T2.AssignedUserId, ''), 
    ISNULL(T2.AssignedRoleId, ''), 
    ISNULL(CONVERT(varchar(24), T2.StartDate, 120),''), 
    T2.DeletedFg, 
    T2.CompletedFg, 
    T2.ConcurrencyId, 
    T3.EventListTemplateActivityId, 
    T3.EventListTemplateId, 
    T3.ActivityCategoryId, 
    T3.FixedDateFg, 
    T3.DeletableFg, 
    ISNULL(T3.Duration, ''), 
    ISNULL(T3.ElapsedDays, ''), 
    T3.EditElapsedDaysFg, 
    ISNULL(T3.AssignedUserId, ''), 
    T3.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TEventListTemplateActivity T3
  INNER JOIN TEventListActivity T2
  ON T3.EventListTemplateActivityId = T2.EventListTemplateActivityId
  INNER JOIN TEventList T1
  ON T2.EventListId = T1.EventListId

  WHERE (T1.EventListId = @EventListId)

  UNION ALL

  SELECT
    4 AS Tag,
    2 AS Parent,
    T1.EventListId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T2.EventListActivityId, 
    T2.EventListId, 
    T2.EventListTemplateActivityId, 
    ISNULL(CONVERT(varchar(24), T2.FixedDate, 120),''), 
    ISNULL(T2.Duration, ''), 
    ISNULL(T2.ElapsedDays, ''), 
    T2.EditElapsedDaysFg, 
    ISNULL(T2.AssignedUserId, ''), 
    ISNULL(T2.AssignedRoleId, ''), 
    ISNULL(CONVERT(varchar(24), T2.StartDate, 120),''), 
    T2.DeletedFg, 
    T2.CompletedFg, 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T4.UserId, 
    T4.Identifier, 
    T4.Password, 
    ISNULL(T4.PasswordHistory, ''), 
    T4.Email, 
    ISNULL(T4.Telephone, ''), 
    T4.Status, 
    T4.GroupId, 
    ISNULL(T4.SyncPassword, ''), 
    ISNULL(CONVERT(varchar(24), T4.ExpirePasswordOn, 120),''), 
    T4.SuperUser, 
    T4.SuperViewer, 
    T4.FinancialPlanningAccess, 
    T4.FailedAccessAttempts, 
    T4.WelcomePage, 
    ISNULL(T4.Reference, ''), 
    ISNULL(T4.CRMContactId, ''), 
    NULL, 
    NULL, 
    NULL, 
    ISNULL(T4.IndigoClientId, ''), 
    T4.SupportUserFg, 
    ISNULL(T4.ActiveRole, ''), 
    T4.CanLogCases, 
    T4.RefUserTypeId, 
    T4.Guid, 
    T4.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM [Administration].[dbo].TUser T4
  INNER JOIN TEventListActivity T2
  ON T4.UserId = T2.AssignedUserId
  INNER JOIN TEventList T1
  ON T2.EventListId = T1.EventListId

  WHERE (T1.EventListId = @EventListId)

  UNION ALL

  SELECT
    5 AS Tag,
    3 AS Parent,
    T1.EventListId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T2.EventListActivityId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T3.EventListTemplateActivityId, 
    T3.EventListTemplateId, 
    T3.ActivityCategoryId, 
    T3.FixedDateFg, 
    T3.DeletableFg, 
    ISNULL(T3.Duration, ''), 
    ISNULL(T3.ElapsedDays, ''), 
    T3.EditElapsedDaysFg, 
    ISNULL(T3.AssignedUserId, ''), 
    T3.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T5.ActivityCategoryId, 
    T5.Name, 
    ISNULL(T5.ActivityCategoryParentId, ''), 
    ISNULL(T5.LifeCycleTransitionId, ''), 
    T5.IndigoClientId, 
    T5.ClientRelatedFG, 
    T5.PlanRelatedFG, 
    T5.FeeRelatedFG, 
    T5.RetainerRelatedFG, 
    T5.OpportunityRelatedFG, 
    T5.AdviserRelatedFg, 
    ISNULL(T5.ActivityEvent, ''), 
    ISNULL(T5.RefSystemEventId, ''), 
    ISNULL(T5.TemplateTypeId, ''), 
    ISNULL(T5.TemplateId, ''), 
    T5.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TActivityCategory T5
  INNER JOIN TEventListTemplateActivity T3
  ON T5.ActivityCategoryId = T3.ActivityCategoryId
  INNER JOIN TEventListActivity T2
  ON T3.EventListTemplateActivityId = T2.EventListTemplateActivityId
  INNER JOIN TEventList T1
  ON T2.EventListId = T1.EventListId

  WHERE (T1.EventListId = @EventListId)

  UNION ALL

  SELECT
    6 AS Tag,
    4 AS Parent,
    T1.EventListId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T2.EventListActivityId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T4.UserId, 
    T4.Identifier, 
    T4.Password, 
    ISNULL(T4.PasswordHistory, ''), 
    T4.Email, 
    ISNULL(T4.Telephone, ''), 
    T4.Status, 
    T4.GroupId, 
    ISNULL(T4.SyncPassword, ''), 
    ISNULL(CONVERT(varchar(24), T4.ExpirePasswordOn, 120),''), 
    T4.SuperUser, 
    T4.SuperViewer, 
    T4.FinancialPlanningAccess, 
    T4.FailedAccessAttempts, 
    T4.WelcomePage, 
    ISNULL(T4.Reference, ''), 
    ISNULL(T4.CRMContactId, ''), 
    NULL, 
    NULL, 
    NULL, 
    ISNULL(T4.IndigoClientId, ''), 
    T4.SupportUserFg, 
    ISNULL(T4.ActiveRole, ''), 
    T4.CanLogCases, 
    T4.RefUserTypeId, 
    T4.Guid, 
    T4.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T6.CRMContactId, 
    ISNULL(T6.RefCRMContactStatusId, ''), 
    ISNULL(T6.PersonId, ''), 
    ISNULL(T6.CorporateId, ''), 
    ISNULL(T6.TrustId, ''), 
    ISNULL(T6.AdvisorRef, ''), 
    ISNULL(T6.RefSourceOfClientId, ''), 
    ISNULL(T6.SourceValue, ''), 
    ISNULL(T6.Notes, ''), 
    ISNULL(T6.ArchiveFg, ''), 
    ISNULL(T6.LastName, ''), 
    ISNULL(T6.FirstName, ''), 
    ISNULL(T6.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T6.DOB, 120),''), 
    ISNULL(T6.Postcode, ''), 
    T6.OriginalAdviserCRMId, 
    T6.CurrentAdviserCRMId, 
    ISNULL(T6.CurrentAdviserName, ''), 
    T6.CRMContactType, 
    T6.IndClientId, 
    ISNULL(T6.FactFindId, ''), 
    ISNULL(T6.InternalContactFG, ''), 
    ISNULL(T6.RefServiceStatusId, ''), 
    ISNULL(T6.MigrationRef, ''), 
    CONVERT(varchar(24), T6.CreatedDate, 120), 
    ISNULL(T6.ExternalReference, ''), 
    ISNULL(T6.CampaignDataId, ''), 
    ISNULL(T6.AdditionalRef, ''), 
    ISNULL(T6._ParentId, ''), 
    ISNULL(T6._ParentTable, ''), 
    ISNULL(T6._ParentDb, ''), 
    ISNULL(T6._OwnerId, ''), 
    T6.ConcurrencyId
  FROM [CRM].[dbo].TCRMContact T6
  INNER JOIN [Administration].[dbo].TUser T4
  ON T6.CRMContactId = T4.CRMContactId
  INNER JOIN TEventListActivity T2
  ON T4.UserId = T2.AssignedUserId
  INNER JOIN TEventList T1
  ON T2.EventListId = T1.EventListId

  WHERE (T1.EventListId = @EventListId)

  ORDER BY [EventList!1!EventListId], [EventListActivity!2!EventListActivityId], [User!4!UserId], [CRMContact!6!CRMContactId], [EventListTemplateActivity!3!EventListTemplateActivityId], [ActivityCategory!5!ActivityCategoryId]

  FOR XML EXPLICIT

END
RETURN (0)

GO
