SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SpGetBinderIdsLinkedToAdviceCases]
@BinderIds dbo.tvp_int READONLY
AS

BEGIN
	SELECT BinderId FROM TAdviceCase
	WHERE BinderId IN (SELECT [VALUE] FROM @BinderIds)
END
GO
