SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SpAliasGetContactSummary]
@CRMContactId bigint
AS

BEGIN
  SELECT
    1 AS Tag,
    NULL AS Parent,
    T1.CRMContactId AS [CRMContact!1!CRMContactId], 
    ISNULL(T1.RefCRMContactStatusId, '') AS [CRMContact!1!RefCRMContactStatusId], 
    ISNULL(T1.PersonId, '') AS [CRMContact!1!PersonId], 
    ISNULL(T1.CorporateId, '') AS [CRMContact!1!CorporateId], 
    ISNULL(T1.TrustId, '') AS [CRMContact!1!TrustId], 
    ISNULL(T1.AdvisorRef, '') AS [CRMContact!1!AdvisorRef], 
    ISNULL(T1.RefSourceOfClientId, '') AS [CRMContact!1!RefSourceOfClientId], 
    ISNULL(T1.SourceValue, '') AS [CRMContact!1!SourceValue], 
    ISNULL(T1.Notes, '') AS [CRMContact!1!Notes], 
    ISNULL(T1.ArchiveFg, '') AS [CRMContact!1!ArchiveFg], 
    ISNULL(T1.LastName, '') AS [CRMContact!1!LastName], 
    ISNULL(T1.FirstName, '') AS [CRMContact!1!FirstName], 
    ISNULL(T1.CorporateName, '') AS [CRMContact!1!CorporateName], 
    ISNULL(CONVERT(varchar(24), T1.DOB, 120),'') AS [CRMContact!1!DOB], 
    ISNULL(T1.Postcode, '') AS [CRMContact!1!Postcode], 
    T1.OriginalAdviserCRMId AS [CRMContact!1!OriginalAdviserCRMId], 
    T1.CurrentAdviserCRMId AS [CRMContact!1!CurrentAdviserCRMId], 
    ISNULL(T1.CurrentAdviserName, '') AS [CRMContact!1!CurrentAdviserName], 
    T1.CRMContactType AS [CRMContact!1!CRMContactType], 
    T1.IndClientId AS [CRMContact!1!IndClientId], 
    ISNULL(T1.FactFindId, '') AS [CRMContact!1!FactFindId], 
    ISNULL(T1.InternalContactFG, '') AS [CRMContact!1!InternalContactFG], 
    ISNULL(T1.RefServiceStatusId, '') AS [CRMContact!1!RefServiceStatusId], 
    ISNULL(T1.MigrationRef, '') AS [CRMContact!1!MigrationRef], 
    CONVERT(varchar(24), T1.CreatedDate, 120) AS [CRMContact!1!CreatedDate], 
    ISNULL(T1.ExternalReference, '') AS [CRMContact!1!ExternalReference], 
    ISNULL(T1.CampaignDataId, '') AS [CRMContact!1!CampaignDataId], 
    ISNULL(T1.AdditionalRef, '') AS [CRMContact!1!AdditionalRef], 
    ISNULL(T1._ParentId, '') AS [CRMContact!1!_ParentId], 
    ISNULL(T1._ParentTable, '') AS [CRMContact!1!_ParentTable], 
    ISNULL(T1._ParentDb, '') AS [CRMContact!1!_ParentDb], 
    ISNULL(T1._OwnerId, '') AS [CRMContact!1!_OwnerId], 
    T1.ConcurrencyId AS [CRMContact!1!ConcurrencyId], 
    ISNULL(TNote.Note, '') AS [CRMContact!1!_note], 
    NULL AS [CRMContactExt!2!CRMContactExtId], 
    NULL AS [CRMContactExt!2!CRMContactId], 
    NULL AS [CRMContactExt!2!CreditedGroupId], 
    NULL AS [CRMContactExt!2!ConcurrencyId], 
    NULL AS [Person!3!PersonId], 
    NULL AS [Person!3!Title], 
    NULL AS [Person!3!FirstName], 
    NULL AS [Person!3!MiddleName], 
    NULL AS [Person!3!LastName], 
    NULL AS [Person!3!MaidenName], 
    NULL AS [Person!3!DOB], 
    NULL AS [Person!3!GenderType], 
    NULL AS [Person!3!NINumber], 
    NULL AS [Person!3!IsSmoker], 
    NULL AS [Person!3!UKResident], 
    NULL AS [Person!3!ResidentIn], 
    NULL AS [Person!3!Salutation], 
    NULL AS [Person!3!RefSourceTypeId], 
    NULL AS [Person!3!IntroducerSource], 
    NULL AS [Person!3!MaritalStatus], 
    NULL AS [Person!3!MarriedOn], 
    NULL AS [Person!3!Residency], 
    NULL AS [Person!3!UKDomicile], 
    NULL AS [Person!3!Domicile], 
    NULL AS [Person!3!TaxCode], 
    NULL AS [Person!3!Nationality], 
    NULL AS [Person!3!ArchiveFG], 
    NULL AS [Person!3!IndClientId], 
    NULL AS [Person!3!ConcurrencyId], 
    NULL AS [Corporate!4!CorporateId], 
    NULL AS [Corporate!4!IndClientId], 
    NULL AS [Corporate!4!CorporateName], 
    NULL AS [Corporate!4!ArchiveFg], 
    NULL AS [Corporate!4!BusinessType], 
    NULL AS [Corporate!4!RefCorporateTypeId], 
    NULL AS [Corporate!4!CompanyRegNo], 
    NULL AS [Corporate!4!EstIncorpDate], 
    NULL AS [Corporate!4!YearEnd], 
    NULL AS [Corporate!4!VatRegFg], 
    NULL AS [Corporate!4!VatRegNo], 
    NULL AS [Corporate!4!ConcurrencyId], 
    NULL AS [Trust!5!TrustId], 
    NULL AS [Trust!5!RefTrustTypeId], 
    NULL AS [Trust!5!IndClientId], 
    NULL AS [Trust!5!TrustName], 
    NULL AS [Trust!5!EstDate], 
    NULL AS [Trust!5!ArchiveFG], 
    NULL AS [Trust!5!ConcurrencyId], 
    NULL AS [Address!6!AddressId], 
    NULL AS [Address!6!IndClientId], 
    NULL AS [Address!6!CRMContactId], 
    NULL AS [Address!6!AddressStoreId], 
    NULL AS [Address!6!RefAddressTypeId], 
    NULL AS [Address!6!AddressTypeName], 
    NULL AS [Address!6!DefaultFg], 
    NULL AS [Address!6!RefAddressStatusId], 
    NULL AS [Address!6!ResidentFromDate], 
    NULL AS [Address!6!ConcurrencyId], 
    NULL AS [Contact!7!ContactId], 
    NULL AS [Contact!7!IndClientId], 
    NULL AS [Contact!7!CRMContactId], 
    NULL AS [Contact!7!RefContactType], 
    NULL AS [Contact!7!Description], 
    NULL AS [Contact!7!Value], 
    NULL AS [Contact!7!DefaultFg], 
    NULL AS [Contact!7!ConcurrencyId], 
    NULL AS [RefServiceStatus!8!RefServiceStatusId], 
    NULL AS [RefServiceStatus!8!ServiceStatusName], 
    NULL AS [RefServiceStatus!8!IndigoClientId], 
    NULL AS [RefServiceStatus!8!ConcurrencyId], 
    NULL AS [CampaignData!9!CampaignDataId], 
    NULL AS [CampaignData!9!CampaignId], 
    NULL AS [CampaignData!9!Description], 
    NULL AS [CampaignData!9!Cost], 
    NULL AS [CampaignData!9!ConcurrencyId], 
    NULL AS [Deceased!10!DeceasedId], 
    NULL AS [Deceased!10!CRMContactId], 
    NULL AS [Deceased!10!DeceasedFG], 
    NULL AS [Deceased!10!DeceasedDate], 
    NULL AS [Deceased!10!ConcurrencyId], 
    NULL AS [Group!11!GroupId], 
    NULL AS [Group!11!Identifier], 
    NULL AS [Group!11!GroupingId], 
    NULL AS [Group!11!ParentId], 
    NULL AS [Group!11!CRMContactId], 
    NULL AS [Group!11!IndigoClientId], 
    NULL AS [Group!11!LegalEntity], 
    NULL AS [Group!11!GroupImageLocation], 
    NULL AS [Group!11!AcknowledgementsLocation], 
    NULL AS [Group!11!FinancialYearEnd], 
    NULL AS [Group!11!ApplyFactFindBranding], 
    NULL AS [Group!11!VatRegNbr], 
    NULL AS [Group!11!ConcurrencyId], 
    NULL AS [RefCorporateType!12!RefCorporateTypeId], 
    NULL AS [RefCorporateType!12!TypeName], 
    NULL AS [RefCorporateType!12!HasCompanyRegFg], 
    NULL AS [RefCorporateType!12!ArchiveFg], 
    NULL AS [RefCorporateType!12!ConcurrencyId], 
    NULL AS [RefTrustType!13!RefTrustTypeId], 
    NULL AS [RefTrustType!13!TrustTypeName], 
    NULL AS [RefTrustType!13!ArchiveFG], 
    NULL AS [RefTrustType!13!ConcurrencyId], 
    NULL AS [AddressStore!14!AddressStoreId], 
    NULL AS [AddressStore!14!IndClientId], 
    NULL AS [AddressStore!14!AddressLine1], 
    NULL AS [AddressStore!14!AddressLine2], 
    NULL AS [AddressStore!14!AddressLine3], 
    NULL AS [AddressStore!14!AddressLine4], 
    NULL AS [AddressStore!14!CityTown], 
    NULL AS [AddressStore!14!RefCountyId], 
    NULL AS [AddressStore!14!Postcode], 
    NULL AS [AddressStore!14!RefCountryId], 
    NULL AS [AddressStore!14!PostCodeX], 
    NULL AS [AddressStore!14!PostCodeY], 
    NULL AS [AddressStore!14!ConcurrencyId], 
    NULL AS [RefCounty!15!RefCountyId], 
    NULL AS [RefCounty!15!CountyName], 
    NULL AS [RefCounty!15!RefCountryId], 
    NULL AS [RefCounty!15!ArchiveFG], 
    NULL AS [RefCounty!15!ConcurrencyId], 
    NULL AS [Campaign!16!CampaignId], 
    NULL AS [Campaign!16!CampaignTypeId], 
    NULL AS [Campaign!16!IndigoClientId], 
    NULL AS [Campaign!16!GroupId], 
    NULL AS [Campaign!16!CampaignName], 
    NULL AS [Campaign!16!ArchiveFG], 
    NULL AS [Campaign!16!IsOrganisational], 
    NULL AS [Campaign!16!ConcurrencyId], 
    NULL AS [CampaignType!17!CampaignTypeId], 
    NULL AS [CampaignType!17!IndigoClientId], 
    NULL AS [CampaignType!17!CampaignType], 
    NULL AS [CampaignType!17!ArchiveFG], 
    NULL AS [CampaignType!17!ConcurrencyId]
  FROM TCRMContact T1
  -- Note clause
  LEFT JOIN TCRMContactNote TNote
  ON TNote.CRMContactId = T1.CRMContactId AND TNote.IsLatest=1

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    2 AS Tag,
    1 AS Parent,
    T1.CRMContactId, 
    ISNULL(T1.RefCRMContactStatusId, ''), 
    ISNULL(T1.PersonId, ''), 
    ISNULL(T1.CorporateId, ''), 
    ISNULL(T1.TrustId, ''), 
    ISNULL(T1.AdvisorRef, ''), 
    ISNULL(T1.RefSourceOfClientId, ''), 
    ISNULL(T1.SourceValue, ''), 
    ISNULL(T1.Notes, ''), 
    ISNULL(T1.ArchiveFg, ''), 
    ISNULL(T1.LastName, ''), 
    ISNULL(T1.FirstName, ''), 
    ISNULL(T1.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T1.DOB, 120),''), 
    ISNULL(T1.Postcode, ''), 
    T1.OriginalAdviserCRMId, 
    T1.CurrentAdviserCRMId, 
    ISNULL(T1.CurrentAdviserName, ''), 
    T1.CRMContactType, 
    T1.IndClientId, 
    ISNULL(T1.FactFindId, ''), 
    ISNULL(T1.InternalContactFG, ''), 
    ISNULL(T1.RefServiceStatusId, ''), 
    ISNULL(T1.MigrationRef, ''), 
    CONVERT(varchar(24), T1.CreatedDate, 120), 
    ISNULL(T1.ExternalReference, ''), 
    ISNULL(T1.CampaignDataId, ''), 
    ISNULL(T1.AdditionalRef, ''), 
    ISNULL(T1._ParentId, ''), 
    ISNULL(T1._ParentTable, ''), 
    ISNULL(T1._ParentDb, ''), 
    ISNULL(T1._OwnerId, ''), 
    T1.ConcurrencyId, 
    NULL,
    T2.CRMContactExtId, 
    T2.CRMContactId, 
    ISNULL(T2.CreditedGroupId, ''), 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TCRMContactExt T2
  INNER JOIN TCRMContact T1
  ON T2.CRMContactId = T1.CRMContactId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    3 AS Tag,
    1 AS Parent,
    T1.CRMContactId, 
    ISNULL(T1.RefCRMContactStatusId, ''), 
    ISNULL(T1.PersonId, ''), 
    ISNULL(T1.CorporateId, ''), 
    ISNULL(T1.TrustId, ''), 
    ISNULL(T1.AdvisorRef, ''), 
    ISNULL(T1.RefSourceOfClientId, ''), 
    ISNULL(T1.SourceValue, ''), 
    ISNULL(T1.Notes, ''), 
    ISNULL(T1.ArchiveFg, ''), 
    ISNULL(T1.LastName, ''), 
    ISNULL(T1.FirstName, ''), 
    ISNULL(T1.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T1.DOB, 120),''), 
    ISNULL(T1.Postcode, ''), 
    T1.OriginalAdviserCRMId, 
    T1.CurrentAdviserCRMId, 
    ISNULL(T1.CurrentAdviserName, ''), 
    T1.CRMContactType, 
    T1.IndClientId, 
    ISNULL(T1.FactFindId, ''), 
    ISNULL(T1.InternalContactFG, ''), 
    ISNULL(T1.RefServiceStatusId, ''), 
    ISNULL(T1.MigrationRef, ''), 
    CONVERT(varchar(24), T1.CreatedDate, 120), 
    ISNULL(T1.ExternalReference, ''), 
    ISNULL(T1.CampaignDataId, ''), 
    ISNULL(T1.AdditionalRef, ''), 
    ISNULL(T1._ParentId, ''), 
    ISNULL(T1._ParentTable, ''), 
    ISNULL(T1._ParentDb, ''), 
    ISNULL(T1._OwnerId, ''), 
    T1.ConcurrencyId, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T3.PersonId, 
    ISNULL(T3.Title, ''), 
    T3.FirstName, 
    ISNULL(T3.MiddleName, ''), 
    T3.LastName, 
    ISNULL(T3.MaidenName, ''), 
    ISNULL(CONVERT(varchar(24), T3.DOB, 120),''), 
    ISNULL(T3.GenderType, ''), 
    ISNULL(T3.NINumber, ''), 
    ISNULL(T3.IsSmoker, ''), 
    ISNULL(T3.UKResident, ''), 
    ISNULL(T3.ResidentIn, ''), 
    ISNULL(T3.Salutation, ''), 
    ISNULL(T3.RefSourceTypeId, ''), 
    ISNULL(T3.IntroducerSource, ''), 
    ISNULL(T3.MaritalStatus, ''), 
    ISNULL(CONVERT(varchar(24), T3.MarriedOn, 120),''), 
    ISNULL(T3.Residency, ''), 
    ISNULL(T3.UKDomicile, ''), 
    ISNULL(T3.Domicile, ''), 
    ISNULL(T3.TaxCode, ''), 
    ISNULL(T3.Nationality, ''), 
    T3.ArchiveFG, 
    T3.IndClientId, 
    T3.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TPerson T3
  INNER JOIN TCRMContact T1
  ON T3.PersonId = T1.PersonId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    4 AS Tag,
    1 AS Parent,
    T1.CRMContactId, 
    ISNULL(T1.RefCRMContactStatusId, ''), 
    ISNULL(T1.PersonId, ''), 
    ISNULL(T1.CorporateId, ''), 
    ISNULL(T1.TrustId, ''), 
    ISNULL(T1.AdvisorRef, ''), 
    ISNULL(T1.RefSourceOfClientId, ''), 
    ISNULL(T1.SourceValue, ''), 
    ISNULL(T1.Notes, ''), 
    ISNULL(T1.ArchiveFg, ''), 
    ISNULL(T1.LastName, ''), 
    ISNULL(T1.FirstName, ''), 
    ISNULL(T1.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T1.DOB, 120),''), 
    ISNULL(T1.Postcode, ''), 
    T1.OriginalAdviserCRMId, 
    T1.CurrentAdviserCRMId, 
    ISNULL(T1.CurrentAdviserName, ''), 
    T1.CRMContactType, 
    T1.IndClientId, 
    ISNULL(T1.FactFindId, ''), 
    ISNULL(T1.InternalContactFG, ''), 
    ISNULL(T1.RefServiceStatusId, ''), 
    ISNULL(T1.MigrationRef, ''), 
    CONVERT(varchar(24), T1.CreatedDate, 120), 
    ISNULL(T1.ExternalReference, ''), 
    ISNULL(T1.CampaignDataId, ''), 
    ISNULL(T1.AdditionalRef, ''), 
    ISNULL(T1._ParentId, ''), 
    ISNULL(T1._ParentTable, ''), 
    ISNULL(T1._ParentDb, ''), 
    ISNULL(T1._OwnerId, ''), 
    T1.ConcurrencyId, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T4.CorporateId, 
    ISNULL(T4.IndClientId, ''), 
    ISNULL(T4.CorporateName, ''), 
    ISNULL(T4.ArchiveFg, ''), 
    ISNULL(T4.BusinessType, ''), 
    ISNULL(T4.RefCorporateTypeId, ''), 
    ISNULL(T4.CompanyRegNo, ''), 
    ISNULL(CONVERT(varchar(24), T4.EstIncorpDate, 120),''), 
    ISNULL(CONVERT(varchar(24), T4.YearEnd, 120),''), 
    ISNULL(T4.VatRegFg, ''), 
    ISNULL(T4.VatRegNo, ''), 
    T4.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TCorporate T4
  INNER JOIN TCRMContact T1
  ON T4.CorporateId = T1.CorporateId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    5 AS Tag,
    1 AS Parent,
    T1.CRMContactId, 
    ISNULL(T1.RefCRMContactStatusId, ''), 
    ISNULL(T1.PersonId, ''), 
    ISNULL(T1.CorporateId, ''), 
    ISNULL(T1.TrustId, ''), 
    ISNULL(T1.AdvisorRef, ''), 
    ISNULL(T1.RefSourceOfClientId, ''), 
    ISNULL(T1.SourceValue, ''), 
    ISNULL(T1.Notes, ''), 
    ISNULL(T1.ArchiveFg, ''), 
    ISNULL(T1.LastName, ''), 
    ISNULL(T1.FirstName, ''), 
    ISNULL(T1.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T1.DOB, 120),''), 
    ISNULL(T1.Postcode, ''), 
    T1.OriginalAdviserCRMId, 
    T1.CurrentAdviserCRMId, 
    ISNULL(T1.CurrentAdviserName, ''), 
    T1.CRMContactType, 
    T1.IndClientId, 
    ISNULL(T1.FactFindId, ''), 
    ISNULL(T1.InternalContactFG, ''), 
    ISNULL(T1.RefServiceStatusId, ''), 
    ISNULL(T1.MigrationRef, ''), 
    CONVERT(varchar(24), T1.CreatedDate, 120), 
    ISNULL(T1.ExternalReference, ''), 
    ISNULL(T1.CampaignDataId, ''), 
    ISNULL(T1.AdditionalRef, ''), 
    ISNULL(T1._ParentId, ''), 
    ISNULL(T1._ParentTable, ''), 
    ISNULL(T1._ParentDb, ''), 
    ISNULL(T1._OwnerId, ''), 
    T1.ConcurrencyId, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T5.TrustId, 
    T5.RefTrustTypeId, 
    T5.IndClientId, 
    T5.TrustName, 
    ISNULL(CONVERT(varchar(24), T5.EstDate, 120),''), 
    T5.ArchiveFG, 
    T5.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TTrust T5
  INNER JOIN TCRMContact T1
  ON T5.TrustId = T1.TrustId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    6 AS Tag,
    1 AS Parent,
    T1.CRMContactId, 
    ISNULL(T1.RefCRMContactStatusId, ''), 
    ISNULL(T1.PersonId, ''), 
    ISNULL(T1.CorporateId, ''), 
    ISNULL(T1.TrustId, ''), 
    ISNULL(T1.AdvisorRef, ''), 
    ISNULL(T1.RefSourceOfClientId, ''), 
    ISNULL(T1.SourceValue, ''), 
    ISNULL(T1.Notes, ''), 
    ISNULL(T1.ArchiveFg, ''), 
    ISNULL(T1.LastName, ''), 
    ISNULL(T1.FirstName, ''), 
    ISNULL(T1.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T1.DOB, 120),''), 
    ISNULL(T1.Postcode, ''), 
    T1.OriginalAdviserCRMId, 
    T1.CurrentAdviserCRMId, 
    ISNULL(T1.CurrentAdviserName, ''), 
    T1.CRMContactType, 
    T1.IndClientId, 
    ISNULL(T1.FactFindId, ''), 
    ISNULL(T1.InternalContactFG, ''), 
    ISNULL(T1.RefServiceStatusId, ''), 
    ISNULL(T1.MigrationRef, ''), 
    CONVERT(varchar(24), T1.CreatedDate, 120), 
    ISNULL(T1.ExternalReference, ''), 
    ISNULL(T1.CampaignDataId, ''), 
    ISNULL(T1.AdditionalRef, ''), 
    ISNULL(T1._ParentId, ''), 
    ISNULL(T1._ParentTable, ''), 
    ISNULL(T1._ParentDb, ''), 
    ISNULL(T1._OwnerId, ''), 
    T1.ConcurrencyId, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T6.AddressId, 
    T6.IndClientId, 
    ISNULL(T6.CRMContactId, ''), 
    ISNULL(T6.AddressStoreId, ''), 
    T6.RefAddressTypeId, 
    ISNULL(T6.AddressTypeName, ''), 
    T6.DefaultFg, 
    T6.RefAddressStatusId, 
    CONVERT(varchar(24), T6.ResidentFromDate, 120), 
    T6.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TAddress T6
  INNER JOIN TCRMContact T1
  ON T6.CRMContactId = T1.CRMContactId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    7 AS Tag,
    1 AS Parent,
    T1.CRMContactId, 
    ISNULL(T1.RefCRMContactStatusId, ''), 
    ISNULL(T1.PersonId, ''), 
    ISNULL(T1.CorporateId, ''), 
    ISNULL(T1.TrustId, ''), 
    ISNULL(T1.AdvisorRef, ''), 
    ISNULL(T1.RefSourceOfClientId, ''), 
    ISNULL(T1.SourceValue, ''), 
    ISNULL(T1.Notes, ''), 
    ISNULL(T1.ArchiveFg, ''), 
    ISNULL(T1.LastName, ''), 
    ISNULL(T1.FirstName, ''), 
    ISNULL(T1.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T1.DOB, 120),''), 
    ISNULL(T1.Postcode, ''), 
    T1.OriginalAdviserCRMId, 
    T1.CurrentAdviserCRMId, 
    ISNULL(T1.CurrentAdviserName, ''), 
    T1.CRMContactType, 
    T1.IndClientId, 
    ISNULL(T1.FactFindId, ''), 
    ISNULL(T1.InternalContactFG, ''), 
    ISNULL(T1.RefServiceStatusId, ''), 
    ISNULL(T1.MigrationRef, ''), 
    CONVERT(varchar(24), T1.CreatedDate, 120), 
    ISNULL(T1.ExternalReference, ''), 
    ISNULL(T1.CampaignDataId, ''), 
    ISNULL(T1.AdditionalRef, ''), 
    ISNULL(T1._ParentId, ''), 
    ISNULL(T1._ParentTable, ''), 
    ISNULL(T1._ParentDb, ''), 
    ISNULL(T1._OwnerId, ''), 
    T1.ConcurrencyId, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T7.ContactId, 
    T7.IndClientId, 
    T7.CRMContactId, 
    T7.RefContactType, 
    ISNULL(T7.Description, ''), 
    T7.Value, 
    T7.DefaultFg, 
    T7.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TContact T7
  INNER JOIN TCRMContact T1
  ON T7.CRMContactId = T1.CRMContactId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    8 AS Tag,
    1 AS Parent,
    T1.CRMContactId, 
    ISNULL(T1.RefCRMContactStatusId, ''), 
    ISNULL(T1.PersonId, ''), 
    ISNULL(T1.CorporateId, ''), 
    ISNULL(T1.TrustId, ''), 
    ISNULL(T1.AdvisorRef, ''), 
    ISNULL(T1.RefSourceOfClientId, ''), 
    ISNULL(T1.SourceValue, ''), 
    ISNULL(T1.Notes, ''), 
    ISNULL(T1.ArchiveFg, ''), 
    ISNULL(T1.LastName, ''), 
    ISNULL(T1.FirstName, ''), 
    ISNULL(T1.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T1.DOB, 120),''), 
    ISNULL(T1.Postcode, ''), 
    T1.OriginalAdviserCRMId, 
    T1.CurrentAdviserCRMId, 
    ISNULL(T1.CurrentAdviserName, ''), 
    T1.CRMContactType, 
    T1.IndClientId, 
    ISNULL(T1.FactFindId, ''), 
    ISNULL(T1.InternalContactFG, ''), 
    ISNULL(T1.RefServiceStatusId, ''), 
    ISNULL(T1.MigrationRef, ''), 
    CONVERT(varchar(24), T1.CreatedDate, 120), 
    ISNULL(T1.ExternalReference, ''), 
    ISNULL(T1.CampaignDataId, ''), 
    ISNULL(T1.AdditionalRef, ''), 
    ISNULL(T1._ParentId, ''), 
    ISNULL(T1._ParentTable, ''), 
    ISNULL(T1._ParentDb, ''), 
    ISNULL(T1._OwnerId, ''), 
    T1.ConcurrencyId, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T8.RefServiceStatusId, 
    T8.ServiceStatusName, 
    T8.IndigoClientId, 
    T8.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TRefServiceStatus T8
  INNER JOIN TCRMContact T1
  ON T8.RefServiceStatusId = T1.RefServiceStatusId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    9 AS Tag,
    1 AS Parent,
    T1.CRMContactId, 
    ISNULL(T1.RefCRMContactStatusId, ''), 
    ISNULL(T1.PersonId, ''), 
    ISNULL(T1.CorporateId, ''), 
    ISNULL(T1.TrustId, ''), 
    ISNULL(T1.AdvisorRef, ''), 
    ISNULL(T1.RefSourceOfClientId, ''), 
    ISNULL(T1.SourceValue, ''), 
    ISNULL(T1.Notes, ''), 
    ISNULL(T1.ArchiveFg, ''), 
    ISNULL(T1.LastName, ''), 
    ISNULL(T1.FirstName, ''), 
    ISNULL(T1.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T1.DOB, 120),''), 
    ISNULL(T1.Postcode, ''), 
    T1.OriginalAdviserCRMId, 
    T1.CurrentAdviserCRMId, 
    ISNULL(T1.CurrentAdviserName, ''), 
    T1.CRMContactType, 
    T1.IndClientId, 
    ISNULL(T1.FactFindId, ''), 
    ISNULL(T1.InternalContactFG, ''), 
    ISNULL(T1.RefServiceStatusId, ''), 
    ISNULL(T1.MigrationRef, ''), 
    CONVERT(varchar(24), T1.CreatedDate, 120), 
    ISNULL(T1.ExternalReference, ''), 
    ISNULL(T1.CampaignDataId, ''), 
    ISNULL(T1.AdditionalRef, ''), 
    ISNULL(T1._ParentId, ''), 
    ISNULL(T1._ParentTable, ''), 
    ISNULL(T1._ParentDb, ''), 
    ISNULL(T1._OwnerId, ''), 
    T1.ConcurrencyId, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T9.CampaignDataId, 
    T9.CampaignId, 
    ISNULL(T9.Description, ''), 
    ISNULL(CONVERT(varchar(24), T9.Cost),''), 
    T9.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TCampaignData T9
  INNER JOIN TCRMContact T1
  ON T9.CampaignDataId = T1.CampaignDataId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    10 AS Tag,
    1 AS Parent,
    T1.CRMContactId, 
    ISNULL(T1.RefCRMContactStatusId, ''), 
    ISNULL(T1.PersonId, ''), 
    ISNULL(T1.CorporateId, ''), 
    ISNULL(T1.TrustId, ''), 
    ISNULL(T1.AdvisorRef, ''), 
    ISNULL(T1.RefSourceOfClientId, ''), 
    ISNULL(T1.SourceValue, ''), 
    ISNULL(T1.Notes, ''), 
    ISNULL(T1.ArchiveFg, ''), 
    ISNULL(T1.LastName, ''), 
    ISNULL(T1.FirstName, ''), 
    ISNULL(T1.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T1.DOB, 120),''), 
    ISNULL(T1.Postcode, ''), 
    T1.OriginalAdviserCRMId, 
    T1.CurrentAdviserCRMId, 
    ISNULL(T1.CurrentAdviserName, ''), 
    T1.CRMContactType, 
    T1.IndClientId, 
    ISNULL(T1.FactFindId, ''), 
    ISNULL(T1.InternalContactFG, ''), 
    ISNULL(T1.RefServiceStatusId, ''), 
    ISNULL(T1.MigrationRef, ''), 
    CONVERT(varchar(24), T1.CreatedDate, 120), 
    ISNULL(T1.ExternalReference, ''), 
    ISNULL(T1.CampaignDataId, ''), 
    ISNULL(T1.AdditionalRef, ''), 
    ISNULL(T1._ParentId, ''), 
    ISNULL(T1._ParentTable, ''), 
    ISNULL(T1._ParentDb, ''), 
    ISNULL(T1._OwnerId, ''), 
    T1.ConcurrencyId, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T10.DeceasedId, 
    T10.CRMContactId, 
    T10.DeceasedFG, 
    ISNULL(CONVERT(varchar(24), T10.DeceasedDate, 120),''), 
    T10.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TDeceased T10
  INNER JOIN TCRMContact T1
  ON T10.CRMContactId = T1.CRMContactId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    11 AS Tag,
    2 AS Parent,
    T1.CRMContactId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    T2.CRMContactExtId, 
    T2.CRMContactId, 
    ISNULL(T2.CreditedGroupId, ''), 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T11.GroupId, 
    T11.Identifier, 
    T11.GroupingId, 
    ISNULL(T11.ParentId, ''), 
    ISNULL(T11.CRMContactId, ''), 
    T11.IndigoClientId, 
    T11.LegalEntity, 
    ISNULL(T11.GroupImageLocation, ''), 
    ISNULL(T11.AcknowledgementsLocation, ''), 
    ISNULL(CONVERT(varchar(24), T11.FinancialYearEnd, 120),''), 
    T11.ApplyFactFindBranding, 
    ISNULL(T11.VatRegNbr, ''), 
    T11.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM [Administration].[dbo].TGroup T11
  INNER JOIN TCRMContactExt T2
  ON T11.GroupId = T2.CreditedGroupId
  INNER JOIN TCRMContact T1
  ON T2.CRMContactId = T1.CRMContactId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    12 AS Tag,
    4 AS Parent,
    T1.CRMContactId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T4.CorporateId, 
    ISNULL(T4.IndClientId, ''), 
    ISNULL(T4.CorporateName, ''), 
    ISNULL(T4.ArchiveFg, ''), 
    ISNULL(T4.BusinessType, ''), 
    ISNULL(T4.RefCorporateTypeId, ''), 
    ISNULL(T4.CompanyRegNo, ''), 
    ISNULL(CONVERT(varchar(24), T4.EstIncorpDate, 120),''), 
    ISNULL(CONVERT(varchar(24), T4.YearEnd, 120),''), 
    ISNULL(T4.VatRegFg, ''), 
    ISNULL(T4.VatRegNo, ''), 
    T4.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T12.RefCorporateTypeId, 
    ISNULL(T12.TypeName, ''), 
    ISNULL(T12.HasCompanyRegFg, ''), 
    ISNULL(T12.ArchiveFg, ''), 
    T12.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TRefCorporateType T12
  INNER JOIN TCorporate T4
  ON T12.RefCorporateTypeId = T4.RefCorporateTypeId
  INNER JOIN TCRMContact T1
  ON T4.CorporateId = T1.CorporateId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    13 AS Tag,
    5 AS Parent,
    T1.CRMContactId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T5.TrustId, 
    T5.RefTrustTypeId, 
    T5.IndClientId, 
    T5.TrustName, 
    ISNULL(CONVERT(varchar(24), T5.EstDate, 120),''), 
    T5.ArchiveFG, 
    T5.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T13.RefTrustTypeId, 
    T13.TrustTypeName, 
    T13.ArchiveFG, 
    T13.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TRefTrustType T13
  INNER JOIN TTrust T5
  ON T13.RefTrustTypeId = T5.RefTrustTypeId
  INNER JOIN TCRMContact T1
  ON T5.TrustId = T1.TrustId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    14 AS Tag,
    6 AS Parent,
    T1.CRMContactId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T6.AddressId, 
    T6.IndClientId, 
    ISNULL(T6.CRMContactId, ''), 
    ISNULL(T6.AddressStoreId, ''), 
    T6.RefAddressTypeId, 
    ISNULL(T6.AddressTypeName, ''), 
    T6.DefaultFg, 
    T6.RefAddressStatusId, 
    CONVERT(varchar(24), T6.ResidentFromDate, 120), 
    T6.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T14.AddressStoreId, 
    T14.IndClientId, 
    ISNULL(T14.AddressLine1, ''), 
    ISNULL(T14.AddressLine2, ''), 
    ISNULL(T14.AddressLine3, ''), 
    ISNULL(T14.AddressLine4, ''), 
    ISNULL(T14.CityTown, ''), 
    ISNULL(T14.RefCountyId, ''), 
    ISNULL(T14.Postcode, ''), 
    ISNULL(T14.RefCountryId, ''), 
    ISNULL(T14.PostCodeX, ''), 
    ISNULL(T14.PostCodeY, ''), 
    T14.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TAddressStore T14
  INNER JOIN TAddress T6
  ON T14.AddressStoreId = T6.AddressStoreId
  INNER JOIN TCRMContact T1
  ON T6.CRMContactId = T1.CRMContactId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    15 AS Tag,
    14 AS Parent,
    T1.CRMContactId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T6.AddressId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T14.AddressStoreId, 
    T14.IndClientId, 
    ISNULL(T14.AddressLine1, ''), 
    ISNULL(T14.AddressLine2, ''), 
    ISNULL(T14.AddressLine3, ''), 
    ISNULL(T14.AddressLine4, ''), 
    ISNULL(T14.CityTown, ''), 
    ISNULL(T14.RefCountyId, ''), 
    ISNULL(T14.Postcode, ''), 
    ISNULL(T14.RefCountryId, ''), 
    ISNULL(T14.PostCodeX, ''), 
    ISNULL(T14.PostCodeY, ''), 
    T14.ConcurrencyId, 
    T15.RefCountyId, 
    ISNULL(T15.CountyName, ''), 
    T15.RefCountryId, 
    T15.ArchiveFG, 
    T15.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TRefCounty T15
  INNER JOIN TAddressStore T14
  ON T15.RefCountyId = T14.RefCountyId
  INNER JOIN TAddress T6
  ON T14.AddressStoreId = T6.AddressStoreId
  INNER JOIN TCRMContact T1
  ON T6.CRMContactId = T1.CRMContactId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    16 AS Tag,
    9 AS Parent,
    T1.CRMContactId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T9.CampaignDataId, 
    T9.CampaignId, 
    ISNULL(T9.Description, ''), 
    ISNULL(CONVERT(varchar(24), T9.Cost),''), 
    T9.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T16.CampaignId, 
    T16.CampaignTypeId, 
    T16.IndigoClientId, 
    ISNULL(T16.GroupId, ''), 
    T16.CampaignName, 
    T16.ArchiveFG, 
    T16.IsOrganisational, 
    T16.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TCampaign T16
  INNER JOIN TCampaignData T9
  ON T16.CampaignId = T9.CampaignId
  INNER JOIN TCRMContact T1
  ON T9.CampaignDataId = T1.CampaignDataId

  WHERE (T1.CRMContactId = @CRMContactId)

  UNION ALL

  SELECT
    17 AS Tag,
    16 AS Parent,
    T1.CRMContactId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL,
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T9.CampaignDataId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T16.CampaignId, 
    T16.CampaignTypeId, 
    T16.IndigoClientId, 
    ISNULL(T16.GroupId, ''), 
    T16.CampaignName, 
    T16.ArchiveFG, 
    T16.IsOrganisational, 
    T16.ConcurrencyId, 
    T17.CampaignTypeId, 
    T17.IndigoClientId, 
    T17.CampaignType, 
    T17.ArchiveFG, 
    T17.ConcurrencyId
  FROM TCampaignType T17
  INNER JOIN TCampaign T16
  ON T17.CampaignTypeId = T16.CampaignTypeId
  INNER JOIN TCampaignData T9
  ON T16.CampaignId = T9.CampaignId
  INNER JOIN TCRMContact T1
  ON T9.CampaignDataId = T1.CampaignDataId

  WHERE (T1.CRMContactId = @CRMContactId)

  ORDER BY [CRMContact!1!CRMContactId], [Deceased!10!DeceasedId], [CampaignData!9!CampaignDataId], [Campaign!16!CampaignId], [CampaignType!17!CampaignTypeId], [RefServiceStatus!8!RefServiceStatusId], [Contact!7!ContactId], [Address!6!AddressId], [AddressStore!14!AddressStoreId], [RefCounty!15!RefCountyId], [Trust!5!TrustId], [RefTrustType!13!RefTrustTypeId], [Corporate!4!CorporateId], [RefCorporateType!12!RefCorporateTypeId], [Person!3!PersonId], [CRMContactExt!2!CRMContactExtId], [Group!11!GroupId]

  FOR XML EXPLICIT

END
RETURN (0)

GO
