SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS OFF
GO
CREATE PROCEDURE [dbo].[SpAliasGetRelationshipsforCRMContact]
@CRMContactFromId bigint
AS

BEGIN
  SELECT
    1 AS Tag,
    NULL AS Parent,
    T1.RelationshipId AS [Relationship!1!RelationshipId], 
    ISNULL(T1.RefRelTypeId, '') AS [Relationship!1!RefRelTypeId], 
    ISNULL(T1.RefRelCorrespondTypeId, '') AS [Relationship!1!RefRelCorrespondTypeId], 
    T1.CRMContactFromId AS [Relationship!1!CRMContactFromId], 
    ISNULL(T1.CRMContactToId, '') AS [Relationship!1!CRMContactToId], 
    ISNULL(T1.ExternalContact, '') AS [Relationship!1!ExternalContact], 
    ISNULL(T1.ExternalURL, '') AS [Relationship!1!ExternalURL], 
    ISNULL(T1.OtherRelationship, '') AS [Relationship!1!OtherRelationship], 
    ISNULL(T1.IsPartnerFg, '') AS [Relationship!1!IsPartnerFg], 
    ISNULL(T1.IsFamilyFg, '') AS [Relationship!1!IsFamilyFg], 
    T1.ConcurrencyId AS [Relationship!1!ConcurrencyId], 
    NULL AS [CRMContact!2!CRMContactId], 
    NULL AS [CRMContact!2!RefCRMContactStatusId], 
    NULL AS [CRMContact!2!PersonId], 
    NULL AS [CRMContact!2!CorporateId], 
    NULL AS [CRMContact!2!TrustId], 
    NULL AS [CRMContact!2!AdvisorRef], 
    NULL AS [CRMContact!2!RefSourceOfClientId], 
    NULL AS [CRMContact!2!SourceValue], 
    NULL AS [CRMContact!2!Notes], 
    NULL AS [CRMContact!2!ArchiveFg], 
    NULL AS [CRMContact!2!LastName], 
    NULL AS [CRMContact!2!FirstName], 
    NULL AS [CRMContact!2!CorporateName], 
    NULL AS [CRMContact!2!DOB], 
    NULL AS [CRMContact!2!Postcode], 
    NULL AS [CRMContact!2!OriginalAdviserCRMId], 
    NULL AS [CRMContact!2!CurrentAdviserCRMId], 
    NULL AS [CRMContact!2!CurrentAdviserName], 
    NULL AS [CRMContact!2!CRMContactType], 
    NULL AS [CRMContact!2!IndClientId], 
    NULL AS [CRMContact!2!FactFindId], 
    NULL AS [CRMContact!2!InternalContactFG], 
    NULL AS [CRMContact!2!RefServiceStatusId], 
    NULL AS [CRMContact!2!MigrationRef], 
    NULL AS [CRMContact!2!CreatedDate], 
    NULL AS [CRMContact!2!ExternalReference], 
    NULL AS [CRMContact!2!CampaignDataId], 
    NULL AS [CRMContact!2!AdditionalRef], 
    NULL AS [CRMContact!2!_ParentId], 
    NULL AS [CRMContact!2!_ParentTable], 
    NULL AS [CRMContact!2!_ParentDb], 
    NULL AS [CRMContact!2!_OwnerId], 
    NULL AS [CRMContact!2!ConcurrencyId], 
    NULL AS [RefRelationshipType!3!RefRelationshipTypeId], 
    NULL AS [RefRelationshipType!3!RelationshipTypeName], 
    NULL AS [RefRelationshipType!3!ArchiveFg], 
    NULL AS [RefRelationshipType!3!PersonFg], 
    NULL AS [RefRelationshipType!3!CorporateFg], 
    NULL AS [RefRelationshipType!3!TrustFg], 
    NULL AS [RefRelationshipType!3!ConcurrencyId], 
    NULL AS [Lead!4!LeadId], 
    NULL AS [Lead!4!CRMContactId], 
    NULL AS [Lead!4!LeadSourceId], 
    NULL AS [Lead!4!IndigoClientId], 
    NULL AS [Lead!4!ConcurrencyId], 
    NULL AS [Person!5!PersonId], 
    NULL AS [Person!5!Title], 
    NULL AS [Person!5!FirstName], 
    NULL AS [Person!5!MiddleName], 
    NULL AS [Person!5!LastName], 
    NULL AS [Person!5!MaidenName], 
    NULL AS [Person!5!DOB], 
    NULL AS [Person!5!GenderType], 
    NULL AS [Person!5!NINumber], 
    NULL AS [Person!5!IsSmoker], 
    NULL AS [Person!5!UKResident], 
    NULL AS [Person!5!ResidentIn], 
    NULL AS [Person!5!Salutation], 
    NULL AS [Person!5!RefSourceTypeId], 
    NULL AS [Person!5!IntroducerSource], 
    NULL AS [Person!5!MaritalStatus], 
    NULL AS [Person!5!MarriedOn], 
    NULL AS [Person!5!Residency], 
    NULL AS [Person!5!UKDomicile], 
    NULL AS [Person!5!Domicile], 
    NULL AS [Person!5!TaxCode], 
    NULL AS [Person!5!Nationality], 
    NULL AS [Person!5!ArchiveFG], 
    NULL AS [Person!5!IndClientId], 
    NULL AS [Person!5!ConcurrencyId]
  FROM TRelationship T1

  WHERE (T1.CRMContactFromId = @CRMContactFromId)

  UNION ALL

  SELECT
    2 AS Tag,
    1 AS Parent,
    T1.RelationshipId, 
    ISNULL(T1.RefRelTypeId, ''), 
    ISNULL(T1.RefRelCorrespondTypeId, ''), 
    T1.CRMContactFromId, 
    ISNULL(T1.CRMContactToId, ''), 
    ISNULL(T1.ExternalContact, ''), 
    ISNULL(T1.ExternalURL, ''), 
    ISNULL(T1.OtherRelationship, ''), 
    ISNULL(T1.IsPartnerFg, ''), 
    ISNULL(T1.IsFamilyFg, ''), 
    T1.ConcurrencyId, 
    T2.CRMContactId, 
    ISNULL(T2.RefCRMContactStatusId, ''), 
    ISNULL(T2.PersonId, ''), 
    ISNULL(T2.CorporateId, ''), 
    ISNULL(T2.TrustId, ''), 
    ISNULL(T2.AdvisorRef, ''), 
    ISNULL(T2.RefSourceOfClientId, ''), 
    ISNULL(T2.SourceValue, ''), 
    ISNULL(T2.Notes, ''), 
    ISNULL(T2.ArchiveFg, ''), 
    ISNULL(T2.LastName, ''), 
    ISNULL(T2.FirstName, ''), 
    ISNULL(T2.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T2.DOB, 120),''), 
    ISNULL(T2.Postcode, ''), 
    T2.OriginalAdviserCRMId, 
    T2.CurrentAdviserCRMId, 
    ISNULL(T2.CurrentAdviserName, ''), 
    T2.CRMContactType, 
    T2.IndClientId, 
    ISNULL(T2.FactFindId, ''), 
    ISNULL(T2.InternalContactFG, ''), 
    ISNULL(T2.RefServiceStatusId, ''), 
    ISNULL(T2.MigrationRef, ''), 
    CONVERT(varchar(24), T2.CreatedDate, 120), 
    ISNULL(T2.ExternalReference, ''), 
    ISNULL(T2.CampaignDataId, ''), 
    ISNULL(T2.AdditionalRef, ''), 
    ISNULL(T2._ParentId, ''), 
    ISNULL(T2._ParentTable, ''), 
    ISNULL(T2._ParentDb, ''), 
    ISNULL(T2._OwnerId, ''), 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TCRMContact T2
  INNER JOIN TRelationship T1
  ON T2.CRMContactId = T1.CRMContactToId

  WHERE (T1.CRMContactFromId = @CRMContactFromId)

  UNION ALL

  SELECT
    3 AS Tag,
    1 AS Parent,
    T1.RelationshipId, 
    ISNULL(T1.RefRelTypeId, ''), 
    ISNULL(T1.RefRelCorrespondTypeId, ''), 
    T1.CRMContactFromId, 
    ISNULL(T1.CRMContactToId, ''), 
    ISNULL(T1.ExternalContact, ''), 
    ISNULL(T1.ExternalURL, ''), 
    ISNULL(T1.OtherRelationship, ''), 
    ISNULL(T1.IsPartnerFg, ''), 
    ISNULL(T1.IsFamilyFg, ''), 
    T1.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T3.RefRelationshipTypeId, 
    ISNULL(T3.RelationshipTypeName, ''), 
    ISNULL(T3.ArchiveFg, ''), 
    ISNULL(T3.PersonFg, ''), 
    ISNULL(T3.CorporateFg, ''), 
    ISNULL(T3.TrustFg, ''), 
    T3.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TRefRelationshipType T3
  INNER JOIN TRelationship T1
  ON T3.RefRelationshipTypeId = T1.RefRelTypeId

  WHERE (T1.CRMContactFromId = @CRMContactFromId)

  UNION ALL

  SELECT
    4 AS Tag,
    2 AS Parent,
    T1.RelationshipId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T2.CRMContactId, 
    ISNULL(T2.RefCRMContactStatusId, ''), 
    ISNULL(T2.PersonId, ''), 
    ISNULL(T2.CorporateId, ''), 
    ISNULL(T2.TrustId, ''), 
    ISNULL(T2.AdvisorRef, ''), 
    ISNULL(T2.RefSourceOfClientId, ''), 
    ISNULL(T2.SourceValue, ''), 
    ISNULL(T2.Notes, ''), 
    ISNULL(T2.ArchiveFg, ''), 
    ISNULL(T2.LastName, ''), 
    ISNULL(T2.FirstName, ''), 
    ISNULL(T2.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T2.DOB, 120),''), 
    ISNULL(T2.Postcode, ''), 
    T2.OriginalAdviserCRMId, 
    T2.CurrentAdviserCRMId, 
    ISNULL(T2.CurrentAdviserName, ''), 
    T2.CRMContactType, 
    T2.IndClientId, 
    ISNULL(T2.FactFindId, ''), 
    ISNULL(T2.InternalContactFG, ''), 
    ISNULL(T2.RefServiceStatusId, ''), 
    ISNULL(T2.MigrationRef, ''), 
    CONVERT(varchar(24), T2.CreatedDate, 120), 
    ISNULL(T2.ExternalReference, ''), 
    ISNULL(T2.CampaignDataId, ''), 
    ISNULL(T2.AdditionalRef, ''), 
    ISNULL(T2._ParentId, ''), 
    ISNULL(T2._ParentTable, ''), 
    ISNULL(T2._ParentDb, ''), 
    ISNULL(T2._OwnerId, ''), 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T4.LeadId, 
    T4.CRMContactId, 
    ISNULL(T4.LeadSourceId, ''), 
    T4.IndigoClientId, 
    T4.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL
  FROM TLead T4
  INNER JOIN TCRMContact T2
  ON T4.CRMContactId = T2.CRMContactId
  INNER JOIN TRelationship T1
  ON T2.CRMContactId = T1.CRMContactToId

  WHERE (T1.CRMContactFromId = @CRMContactFromId)

  UNION ALL

  SELECT
    5 AS Tag,
    2 AS Parent,
    T1.RelationshipId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T2.CRMContactId, 
    ISNULL(T2.RefCRMContactStatusId, ''), 
    ISNULL(T2.PersonId, ''), 
    ISNULL(T2.CorporateId, ''), 
    ISNULL(T2.TrustId, ''), 
    ISNULL(T2.AdvisorRef, ''), 
    ISNULL(T2.RefSourceOfClientId, ''), 
    ISNULL(T2.SourceValue, ''), 
    ISNULL(T2.Notes, ''), 
    ISNULL(T2.ArchiveFg, ''), 
    ISNULL(T2.LastName, ''), 
    ISNULL(T2.FirstName, ''), 
    ISNULL(T2.CorporateName, ''), 
    ISNULL(CONVERT(varchar(24), T2.DOB, 120),''), 
    ISNULL(T2.Postcode, ''), 
    T2.OriginalAdviserCRMId, 
    T2.CurrentAdviserCRMId, 
    ISNULL(T2.CurrentAdviserName, ''), 
    T2.CRMContactType, 
    T2.IndClientId, 
    ISNULL(T2.FactFindId, ''), 
    ISNULL(T2.InternalContactFG, ''), 
    ISNULL(T2.RefServiceStatusId, ''), 
    ISNULL(T2.MigrationRef, ''), 
    CONVERT(varchar(24), T2.CreatedDate, 120), 
    ISNULL(T2.ExternalReference, ''), 
    ISNULL(T2.CampaignDataId, ''), 
    ISNULL(T2.AdditionalRef, ''), 
    ISNULL(T2._ParentId, ''), 
    ISNULL(T2._ParentTable, ''), 
    ISNULL(T2._ParentDb, ''), 
    ISNULL(T2._OwnerId, ''), 
    T2.ConcurrencyId, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    NULL, 
    T5.PersonId, 
    ISNULL(T5.Title, ''), 
    T5.FirstName, 
    ISNULL(T5.MiddleName, ''), 
    T5.LastName, 
    ISNULL(T5.MaidenName, ''), 
    ISNULL(CONVERT(varchar(24), T5.DOB, 120),''), 
    ISNULL(T5.GenderType, ''), 
    ISNULL(T5.NINumber, ''), 
    ISNULL(T5.IsSmoker, ''), 
    ISNULL(T5.UKResident, ''), 
    ISNULL(T5.ResidentIn, ''), 
    ISNULL(T5.Salutation, ''), 
    ISNULL(T5.RefSourceTypeId, ''), 
    ISNULL(T5.IntroducerSource, ''), 
    ISNULL(T5.MaritalStatus, ''), 
    ISNULL(CONVERT(varchar(24), T5.MarriedOn, 120),''), 
    ISNULL(T5.Residency, ''), 
    ISNULL(T5.UKDomicile, ''), 
    ISNULL(T5.Domicile, ''), 
    ISNULL(T5.TaxCode, ''), 
    ISNULL(T5.Nationality, ''), 
    T5.ArchiveFG, 
    T5.IndClientId, 
    T5.ConcurrencyId
  FROM TPerson T5
  INNER JOIN TCRMContact T2
  ON T5.PersonId = T2.PersonId
  INNER JOIN TRelationship T1
  ON T2.CRMContactId = T1.CRMContactToId

  WHERE (T1.CRMContactFromId = @CRMContactFromId)

  ORDER BY [Relationship!1!RelationshipId], [RefRelationshipType!3!RefRelationshipTypeId], [CRMContact!2!CRMContactId], [Person!5!PersonId], [Lead!4!LeadId]

  FOR XML EXPLICIT

END
RETURN (0)

GO
