SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[FnGetRecurrenceActivityType](@RFCCode AS NVARCHAR(1000))
RETURNS NVARCHAR(100)
AS
BEGIN
	DECLARE @RESULT AS NVARCHAR(1000)

	SELECT @RESULT = CASE 
	WHEN CHARINDEX('DAILY',@RFCCode) > 1 THEN 'Daily' 
	WHEN CHARINDEX('WEEKLY',@RFCCode) > 1 THEN 'Weekly' 
	WHEN (CHARINDEX('MONTHLY;',@RFCCode) > 1 and CHARINDEX('INTERVAL=1',@RFCCode) > 1) THEN 'Monthly'
	WHEN (CHARINDEX('MONTHLY;',@RFCCode) > 1 and CHARINDEX('INTERVAL=3',@RFCCode) > 1)THEN 'Quarterly'
	WHEN (CHARINDEX('MONTHLY;',@RFCCode) > 1 and CHARINDEX('INTERVAL=6',@RFCCode) >  1)THEN 'Half Yearly'
	WHEN (CHARINDEX('MONTHLY;',@RFCCode) > 1 ) THEN 'Monthly'
	WHEN CHARINDEX('YEARLY;',@RFCCode) > 1 THEN 'Yearly' 
	ELSE @RFCCode 
END 
	RETURN @RESULT
END

GO
