SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SpNAuditEmploymentDetail]
	@StampUser varchar (255),
	@EmploymentDetailId bigint,
	@StampAction char(1)
AS

INSERT INTO TEmploymentDetailAudit 
( Allowances,
  AnyBonusIncome,
  AnyOvertimeIncome,
  BasicAnnualIncome, 
  BenefitsInKind,
  Bonus, 
  ChangeEmployment,
  Class, 
  Commissions,
  ConcurrencyId,
  CRMContactId, 
  Employer, 
  EmployerAddress,
  EmployerAddressLine1,
  EmployerAddressLine2,
  EmployerAddressLine3, 
  EmployerAddressLine4,
  EmployerCityTown, 
  EmployerPostcode,
  EmploymentHistoryId, 
  EmploymentStatus,
  EmploymentStatusDescription,
  EmploymentBusinessType,
  EndDate, 
  ExpectedIncomeChange, 
  ExpectedIncomeChangeAmount, 
  GrossAnnualEarnings, 
  GuaranteedBonus,
  GuaranteedOvertime, 
  HasProjectionsForCurrentYear, 
  HasStatementOfAccounts,
  HasTaxReturns,
  InProbation, 
  IntendedRetirementAge, 
  IsPastEmployment,
  MigrationRef,
  NetBasicMonthlyIncome,
  NetBasicMonthlyIncomeInAffordability, 
  NetGuaranteedBonus,
  NetGuaranteedBonusInAffordability,
  NetGuaranteedOvertime, 
  NetGuaranteedOvertimeInAffordability, 
  NetRegularBonus, 
  NetRegularBonusInAffordability, 
  NetRegularOvertime, 
  NetRegularOvertimeInAffordability, 
  NonTaxableDetails, 
  NumberOfYearsAccountsAvailable, 
  OtherGrossIncome, 
  OtherNonTaxable, 
  OtherTaxable, 
  Packaging,
  PackagingDetails,
  PreviousFinancialYear, 
  PreviousFinancialYearEndDate,
  ProbationPeriod, 
  RecentGrossPreTaxProfit, 
  RefCountryId, 
  RefCountyId,
  RefOccupationId, 
  RegularBonus,
  RegularOvertime, 
  ReviewDate,
  Role,
  Salary, 
  SecondPreviousFinancialYear, 
  SecondPreviousFinancialYearEndDate,
  Share,
  StartDate, 
  ThirdPreviousFinancialYear, 
  ThirdPreviousFinancialYearEndDate,
  Title,
  Total, 
  EmploymentDetailId, 
  StampAction,
  StampDateTime, 
  StampUser, 
  ProbationPeriodMonths, 
  AccountsAvailableYears,
  EmploymentHistoryDuplicateId,
  IndustryType ) 
Select 
  Allowances, 
  AnyBonusIncome, 
  AnyOvertimeIncome, 
  BasicAnnualIncome, 
  BenefitsInKind,
  Bonus, 
  ChangeEmployment, 
  Class, 
  Commissions,
  ConcurrencyId,
  CRMContactId,
  Employer, 
  EmployerAddress,
  EmployerAddressLine1, 
  EmployerAddressLine2, 
  EmployerAddressLine3, 
  EmployerAddressLine4, 
  EmployerCityTown,
  EmployerPostcode,
  EmploymentHistoryId, 
  EmploymentStatus,
  EmploymentStatusDescription,
  EmploymentBusinessType,
  EndDate, 
  ExpectedIncomeChange, 
  ExpectedIncomeChangeAmount, 
  GrossAnnualEarnings, 
  GuaranteedBonus,
  GuaranteedOvertime,
  HasProjectionsForCurrentYear, 
  HasStatementOfAccounts,
  HasTaxReturns,
  InProbation,
  IntendedRetirementAge, 
  IsPastEmployment,
  MigrationRef,
  NetBasicMonthlyIncome,
  NetBasicMonthlyIncomeInAffordability, 
  NetGuaranteedBonus,
  NetGuaranteedBonusInAffordability,
  NetGuaranteedOvertime,
  NetGuaranteedOvertimeInAffordability, 
  NetRegularBonus,
  NetRegularBonusInAffordability, 
  NetRegularOvertime,
  NetRegularOvertimeInAffordability, 
  NonTaxableDetails, 
  NumberOfYearsAccountsAvailable, 
  OtherGrossIncome, 
  OtherNonTaxable, 
  OtherTaxable, 
  Packaging, 
  PackagingDetails, 
  PreviousFinancialYear, 
  PreviousFinancialYearEndDate, 
  ProbationPeriod, 
  RecentGrossPreTaxProfit, 
  RefCountryId, 
  RefCountyId,
  RefOccupationId, 
  RegularBonus,
  RegularOvertime, 
  ReviewDate,
  Role, 
  Salary, 
  SecondPreviousFinancialYear, 
  SecondPreviousFinancialYearEndDate, 
  Share, 
  StartDate,
  ThirdPreviousFinancialYear, 
  ThirdPreviousFinancialYearEndDate, 
  Title,
  Total, 
  EmploymentDetailId, 
  @StampAction, 
  GetDate(),
  @StampUser, 
  ProbationPeriodMonths, 
  AccountsAvailableYears,
  EmploymentHistoryDuplicateId,
  IndustryType
FROM TEmploymentDetail
WHERE EmploymentDetailId = @EmploymentDetailId

IF @@ERROR != 0 GOTO errh

RETURN (0)

errh:
RETURN (100)
GO
