 
-----------------------------------------------------------------------------
-- Table: PolicyManagement.TProdSubType
--    Join: 
--   Where: 
-----------------------------------------------------------------------------
 
 
USE PolicyManagement
 
 
-- check if this script has already run
IF EXISTS (
   SELECT 1 FROM TExecutedDataScript 
   WHERE ScriptGuid = '4455FBE5-38FE-44EF-9A7E-1DF7B46F52AE'
) RETURN 
 
SET NOCOUNT ON 
SET XACT_ABORT ON
 
DECLARE @starttrancount int
BEGIN TRY
    SELECT @starttrancount = @@TRANCOUNT
    IF @starttrancount = 0
    BEGIN TRANSACTION
 
        -- insert the records
        SET IDENTITY_INSERT TProdSubType ON; 
 
        INSERT INTO TProdSubType([ProdSubTypeId], [QuoteProductId], [NBProductId], [OrigoTableName], [ProdSubTypeName], [QuoteSubRef], [NBSubRef], [ClientSummary], [ProductSummary], [Extensible], [ConcurrencyId])
        SELECT 1,NULL,NULL, NULL, 'Maxi', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 2,NULL,NULL, NULL, 'Mini Cash', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 3,NULL,NULL, NULL, 'Mini Insurance', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 4,NULL,NULL, NULL, 'Mini Equity', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 5,NULL,NULL, NULL, 'Tessa Only', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 6,NULL,NULL, NULL, 'Critical Illness', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 7,NULL,NULL, NULL, 'Decreasing Term', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 8,NULL,NULL, NULL, 'Directors Share Protection', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 9,NULL,NULL, NULL, 'Family Income Benefit', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 10,NULL,NULL, NULL, 'Key Person Assurance', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 11,NULL,NULL, NULL, 'Mortgage Protection', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 12,NULL,NULL, NULL, 'Partnership Protection', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 13,NULL,NULL, NULL, 'Building & Contents', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 14,NULL,NULL, NULL, 'Building', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 16,NULL,NULL, NULL, 'Convertible', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 17,NULL,NULL, NULL, 'Level', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 18,NULL,NULL, NULL, 'Maxi/Mini Transfer', NULL, NULL, NULL, NULL,NULL,2 UNION ALL 
        SELECT 19,NULL,NULL, NULL, 'Increasing Term', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 20,NULL,NULL, NULL, 'Private Motor', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 21,NULL,NULL, NULL, 'Travel', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 22,NULL,NULL, NULL, 'Pre-Funded', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 23,NULL,NULL, NULL, 'Immediate', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 24,NULL,NULL, NULL, 'Unsecured', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 25,NULL,NULL, NULL, 'Secured', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 28,NULL,NULL, NULL, 'Stocks And Shares', NULL, NULL, NULL, NULL,NULL,2 UNION ALL 
        SELECT 29,NULL,NULL, NULL, 'Cash', NULL, NULL, NULL, NULL,NULL,2 UNION ALL 
        SELECT 30,NULL,NULL, NULL, 'Full Status', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 31,NULL,NULL, NULL, 'Non Status', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 32,NULL,NULL, NULL, 'Self Cert', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 33,NULL,NULL, NULL, 'Buy To Let', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 34,NULL,NULL, NULL, 'Let To Buy', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 35,NULL,NULL, NULL, 'Home Purchase Plan', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1000,NULL,NULL, NULL, 'Protected Rights', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1001,NULL,NULL, NULL, 'Non Protected Rights', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1002,NULL,NULL, NULL, 'Remortgage', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1003,NULL,NULL, NULL, 'Further Advance', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1004,NULL,NULL, NULL, 'With Profits', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1005,NULL,NULL, NULL, 'Unit Linked', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1006,NULL,NULL, NULL, 'Flexible', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1007,NULL,NULL, NULL, 'Conventional', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1008,NULL,NULL, NULL, 'Temporary', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1009,NULL,NULL, NULL, 'Investment', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1010,NULL,NULL, NULL, 'Non Investment', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1011,NULL,NULL, NULL, 'With Profits', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1012,NULL,NULL, NULL, 'Distribution', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1013,NULL,NULL, NULL, 'Executive', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1014,NULL,NULL, NULL, 'Key person', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1015,NULL,NULL, NULL, 'Renewable', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1016,NULL,NULL, NULL, 'Impaired Life', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1017,NULL,NULL, NULL, 'Premium Bonds', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1018,NULL,NULL, NULL, 'National Savings Certificate', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1019,NULL,NULL, NULL, 'Guaranteed Equity Bond', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1020,NULL,NULL, NULL, 'Index Linked Certificate', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1021,NULL,NULL, NULL, 'Fixed Interest Certificate', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1022,NULL,NULL, NULL, 'Child Bonus Bond', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1023,NULL,NULL, NULL, 'Medium Term Note', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1024,NULL,NULL, NULL, 'Deposit', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1025,NULL,NULL, NULL, 'Lifetime', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1026,NULL,NULL, NULL, 'Flexible', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1027,NULL,NULL, NULL, 'Capped', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1028,NULL,NULL, NULL, 'Let Property', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1030,NULL,NULL, NULL, 'Cash', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1031,NULL,NULL, NULL, 'Stocks And Shares', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1029,NULL,NULL, NULL, 'Income Protection', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1032,NULL,NULL, NULL, 'Decreasing Term - CI', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1033,NULL,NULL, NULL, 'Cash ISA', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1036,NULL,NULL, NULL, 'Stocks & Shares ISA', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1037,NULL,NULL, NULL, 'Decreasing Term - Life & CI', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1038,NULL,NULL, NULL, 'Family Income Benefit - CI', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1039,NULL,NULL, NULL, 'Family Income Benefit - Life & CI', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1040,NULL,NULL, NULL, 'Level - Life & CI', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 15,NULL,NULL, NULL, 'Contents', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1041,NULL,NULL, NULL, 'Professional Indemnity', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1042,NULL,NULL, NULL, 'Commercial Motor', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1043,NULL,NULL, NULL, 'Liability', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1044,NULL,NULL, NULL, 'Non-Regulated', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1045,NULL,NULL, NULL, 'Regulated', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1046,NULL,NULL, NULL, 'Bridging Loan', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1047,NULL,NULL, NULL, 'Council/Tenant to Buy', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1048,NULL,NULL, NULL, 'Second Home', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1050,NULL,NULL, NULL, 'Right to Buy', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1051,NULL,NULL, NULL, 'Help to Buy/Shared Equity', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1052,NULL,NULL, NULL, 'Shared Ownership', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1053,NULL,NULL, NULL, 'Standard Residential', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1054,NULL,NULL, NULL, 'Self-Build', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1055,NULL,NULL, NULL, 'Offshore', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1056,NULL,NULL, NULL, 'Overseas', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1057,NULL,NULL, NULL, 'Commercial', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1058,NULL,NULL, NULL, 'NISA', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1059,NULL,NULL, NULL, 'Non-Regulated', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1060,NULL,NULL, NULL, 'Payment Protection', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1061,NULL,NULL, NULL, 'Legal Expenses', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1062,NULL,NULL, NULL, 'Extended Warranty', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1063,NULL,NULL, NULL, 'NISA', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1064,NULL,NULL, NULL, 'Flexi-Access', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 38,NULL,NULL, NULL, 'Second Charge', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1071,NULL,NULL, NULL, 'AIM', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1068,NULL,NULL, NULL, 'Help to Buy', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1066,NULL,NULL, NULL, 'Excepted', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1067,NULL,NULL, NULL, 'Registered', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1070,NULL,NULL, NULL, 'Foreign Currency', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1069,NULL,NULL, NULL, 'Consumer Buy to Let', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1074,NULL,NULL, NULL, 'Cash', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1075,NULL,NULL, NULL, 'Stocks And Shares', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1073,NULL,NULL, NULL, 'Bridging Loan', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1072,NULL,NULL, NULL, 'Beneficiary', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1076,NULL,NULL, NULL, 'Product Transfer', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1077,NULL,NULL, NULL, 'Product Transfer', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1078,NULL,NULL, NULL, 'Further Advance', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1079,NULL,NULL, NULL, 'Commercial Combined', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1080,NULL,NULL, NULL, 'Directors and Officers', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1081,NULL,NULL, NULL, 'Income Bond', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1082,NULL,NULL, NULL, 'Level - Life', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1083,NULL,NULL, NULL, 'Level - CI', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1084,NULL,NULL, NULL, 'Level - Life & CI', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1085,NULL,NULL, NULL, 'Decreasing - Life', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1086,NULL,NULL, NULL, 'Decreasing - CI', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1087,NULL,NULL, NULL, 'Decreasing - Life & CI', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1090,NULL,NULL, NULL, 'Limited Company', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1089,NULL,NULL, NULL, 'Retirement Interest Only', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1094,NULL,NULL, NULL, 'Life', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1126,NULL,NULL, NULL, 'Lifetime', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1127,NULL,NULL, NULL, 'Guaranteed', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1119,NULL,NULL, NULL, 'Allocated', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1120,NULL,NULL, NULL, 'Term Allocated', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1121,NULL,NULL, NULL, 'Account Based', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1122,NULL,NULL, NULL, 'TTR', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1123,NULL,NULL, NULL, 'Lifetime', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1124,NULL,NULL, NULL, 'Life Expectancy', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1125,NULL,NULL, NULL, 'Fixed Term', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1095,NULL,NULL, NULL, 'Life & TPD', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1096,NULL,NULL, NULL, 'TPD', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1097,NULL,NULL, NULL, 'Life & Trauma', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1098,NULL,NULL, NULL, 'Life, TPD & Trauma', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1099,NULL,NULL, NULL, 'Trauma', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1100,NULL,NULL, NULL, 'Trauma & TPD', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1102,NULL,NULL, NULL, 'Business Succession Planning', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1103,NULL,NULL, NULL, 'Debt Personal Guarantees', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1104,NULL,NULL, NULL, 'Debt Protection', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1105,NULL,NULL, NULL, 'Key Person', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1148,NULL,NULL, NULL, 'Impaired Life', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1106,NULL,NULL, NULL, 'Family', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1107,NULL,NULL, NULL, 'Single', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1108,NULL,NULL, NULL, 'Corporate', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1109,NULL,NULL, NULL, 'Overseas', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1146,NULL,NULL, NULL, 'Business Expense', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1110,NULL,NULL, NULL, 'Personal Retail Fund', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1111,NULL,NULL, NULL, 'Industry Fund', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1112,NULL,NULL, NULL, 'Eligible Rollover Fund', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1113,NULL,NULL, NULL, 'Approved Deposit Fund', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1114,NULL,NULL, NULL, 'Corporate Fund', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1115,NULL,NULL, NULL, 'Public Sector Funds', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1116,NULL,NULL, NULL, 'Employer Retail Fund', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1149,NULL,NULL, NULL, 'Deferred', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1137,NULL,NULL, NULL, 'Building', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1138,NULL,NULL, NULL, 'Building & Contents', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1139,NULL,NULL, NULL, 'Commercial', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1140,NULL,NULL, NULL, 'Contents', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1141,NULL,NULL, NULL, 'Liability', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1142,NULL,NULL, NULL, 'Motor Vehicle', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1143,NULL,NULL, NULL, 'Professional Indemnity', NULL, NULL, NULL, NULL,NULL,1 UNION ALL 
        SELECT 1144,NULL,NULL, NULL, 'Travel', NULL, NULL, NULL, NULL,NULL,1 
 
        SET IDENTITY_INSERT TProdSubType OFF
 
        -- record execution so the script won't run again
        INSERT INTO TExecutedDataScript (ScriptGuid, Comments, TenantId, Timestamp) 
        VALUES (
         '4455FBE5-38FE-44EF-9A7E-1DF7B46F52AE', 
         'Initial load (162 total rows, file 1 of 1) for table TProdSubType',
         null, 
         getdate() )
 
   IF @starttrancount = 0
    COMMIT TRANSACTION
 
END TRY
BEGIN CATCH
    DECLARE @ErrorMessage varchar(1000), @ErrorSeverity INT, @ErrorState INT, @ErrorLine INT, @ErrorNumber INT
    SELECT @ErrorMessage = ERROR_MESSAGE() , @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = ERROR_STATE(), @ErrorNumber = ERROR_NUMBER(), @ErrorLine = ERROR_LINE()
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState, @ErrorNumber, @ErrorLine)
END CATCH
 
 SET XACT_ABORT OFF
 SET NOCOUNT OFF
-----------------------------------------------------------------------------
-- #Rows Exported: 162
-- Created by AndyF's RefDataExtractor, Nov 12 2020  3:48PM
-----------------------------------------------------------------------------
