 
-----------------------------------------------------------------------------
-- Table: PolicyManagement.TRiskProfile
--    Join: 
--   Where: WHERE IndigoClientId=466
-----------------------------------------------------------------------------
 
 
USE PolicyManagement
 
 
-- check if this script has already run
IF EXISTS (
   SELECT 1 FROM TExecutedDataScript 
   WHERE ScriptGuid = 'D6C8E4F2-E129-4BFC-88DC-CA2D875F47B0'
     AND TenantId = 466
) RETURN 
 
SET NOCOUNT ON 
SET XACT_ABORT ON
 
DECLARE @starttrancount int
BEGIN TRY
    SELECT @starttrancount = @@TRANCOUNT
    IF @starttrancount = 0
    BEGIN TRANSACTION
 
        -- insert the records
        SET IDENTITY_INSERT TRiskProfile ON; 
 
        INSERT INTO TRiskProfile([RiskProfileId], [Descriptor], [BriefDescription], [IndigoClientId], [RiskNumber], [LowerBand], [UpperBand], [AtrTemplateGuid], [Guid], [ConcurrencyId])
        SELECT 62, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will contain a small amount of riskier assets in order to increase the chance of obtaining better long term returns. A typical Cautious investor will be invested in fixed interest and cash and will also include an element of equities and property. The range of assets provides diversification benefits to reduce the overall risk.', 'Cautious',466,1,9,12,'C029D6F7-D7C7-4C61-9A98-DA62945FE6C1','9D2C8885-604F-4A6E-B5FC-35187CB457BA',2 UNION ALL 
        SELECT 63, 'You are prepared to take some investment risk in order to increase the chances of achieving a reasonable return but would still like to ensure that capital protection is still considered.  A typical Cautious to Moderate investor will be invested in a moderate amount of fixed interest, but with a greater proportion in equities and property. At the shorter terms there may also be some cash.', 'Cautious to Moderate',466,2,13,21,'C029D6F7-D7C7-4C61-9A98-DA62945FE6C1','569DC52A-460B-44C7-91A4-DC69D7F2FE22',1 UNION ALL 
        SELECT 64, 'You are prepared to take a reasonable amount of investment risk in order to increase the chance of achieving a better return. Capital protection is less important to you than the return on the investment. A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a higher proportion of equities compared to fixed interest and cash, and the range of assets provides diversification benefits.', 'Moderate',466,3,22,28,'C029D6F7-D7C7-4C61-9A98-DA62945FE6C1','9C75E9A0-6A02-47FF-AC2F-AD31DD3EC3C2',1 UNION ALL 
        SELECT 65, 'You are prepared to take some risk with your investment in return for the prospect of the improving longer term investment performance as short term capital protection is not important. A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'Moderate to Adventurous',466,4,29,36,'C029D6F7-D7C7-4C61-9A98-DA62945FE6C1','742EFE0E-18FA-44DB-844E-8EAB69CF3A50',2 UNION ALL 
        SELECT 66, 'You are prepared to take greater risks with your investment in return for the prospect of the highest longer term investment performance. You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term. A typical Adventurous investor will be invested fully in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities.', 'Adventurous',466,5,37,41,'C029D6F7-D7C7-4C61-9A98-DA62945FE6C1','2784308F-B012-427A-AB24-60E7C45561F3',1 UNION ALL 
        SELECT 67, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will contain a small amount of riskier assets in order to increase the chance of obtaining better long term returns. A typical Cautious investor will be invested in fixed interest and cash and will also include an element of equities and property. The range of assets provides diversification benefits to reduce the overall risk.', 'Cautious',466,1,9,12,'CF1FD26B-875D-4F86-9908-405BFAC21C84','F7D6B763-691E-4108-A8C8-4F80DCC6D7DA',2 UNION ALL 
        SELECT 68, 'You are prepared to take some investment risk in order to increase the chances of achieving a reasonable return but would still like to ensure that capital protection is still considered.  A typical Cautious to Moderate investor will be invested in a moderate amount of fixed interest, but with a greater proportion in equities and property. At the shorter terms there may also be some cash.', 'Cautious to Moderate',466,2,13,21,'CF1FD26B-875D-4F86-9908-405BFAC21C84','C7DD5DC0-10BC-475E-8F88-42F36602E4C2',1 UNION ALL 
        SELECT 69, 'You are prepared to take a reasonable amount of investment risk in order to increase the chance of achieving a better return. Capital protection is less important to you than the return on the investment. A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a higher proportion of equities compared to fixed interest and cash, and the range of assets provides diversification benefits.', 'Moderate',466,3,22,28,'CF1FD26B-875D-4F86-9908-405BFAC21C84','6B604BAE-7605-4EDB-90F2-D28AFEA9A6CC',1 UNION ALL 
        SELECT 70, 'You are prepared to take some risk with your investment in return for the prospect of the improving longer term investment performance as short term capital protection is not important. A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'Moderate to Adventurous',466,4,29,36,'CF1FD26B-875D-4F86-9908-405BFAC21C84','703C06B0-C99E-434F-A614-51CF0ED21D5C',2 UNION ALL 
        SELECT 71, 'You are prepared to take greater risks with your investment in return for the prospect of the highest longer term investment performance. You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term. A typical Adventurous investor will be invested fully in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities.', 'Adventurous',466,5,37,41,'CF1FD26B-875D-4F86-9908-405BFAC21C84','B701682C-9845-460F-A78A-27514A65C042',1 UNION ALL 
        SELECT 72, 'You are not prepared to take investment risk. This means you are prepared to accept lower long term returns to meet your risk criteria.  A typical Very Cautious investor would invest mainly in cash and fixed interest investments, but could include small elements of equity or property for longer term investment objectives.', 'Very Cautious',466,1,14,17,'AF78842B-99B6-4EE1-8457-47B917CFA0C8','4C89EB80-7F80-4A2C-B4DE-D020FE0399CE',2 UNION ALL 
        SELECT 73, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will contain a small amount of riskier assets in order to increase the chance of obtaining better long term returns. A typical Cautious investor will be invested in fixed interest and cash and will also include an element of equities and property. The range of assets provides diversification benefits to reduce the overall risk.', 'Cautious',466,2,18,21,'AF78842B-99B6-4EE1-8457-47B917CFA0C8','4F3CA00E-AE32-41A4-9661-AEAD02903FEA',2 UNION ALL 
        SELECT 74, 'You are comfortable in taking a small amount of investment risk and capital protection is fairly important. This means that your portfolio will contain a relatively small amount of riskier assets in order to increase the chance of obtaining better long term returns. A typical Cautious to Low Moderate investor will be invested in fixed interest and cash and will also include an element of equities and property. The range of assets provides diversification benefits to reduce the overall risk.', 'Cautious to Low Moderate',466,3,22,30,'AF78842B-99B6-4EE1-8457-47B917CFA0C8','C1C3F652-D048-489C-B6DA-930E4E048B13',2 UNION ALL 
        SELECT 75, 'You are prepared to take some investment risk in order to increase the chances of achieving a reasonable return but would still like to ensure that capital protection is still considered.  A typical Cautious to Moderate investor will be invested in a moderate amount of fixed interest, but with a greater proportion in equities and property. At the shorter terms there may also be some cash.', 'Cautious to Moderate',466,4,31,35,'AF78842B-99B6-4EE1-8457-47B917CFA0C8','20BEF9AD-E81A-4E5C-8689-5075356BA034',1 UNION ALL 
        SELECT 76, 'You are comfortable in taking some investment risk in order to increase the chances of achieving a reasonable return but would still like to ensure that capital protection is still considered.  A typical Low Moderate investor will be invested in a moderate amount of fixed interest, but with a greater proportion in equities and property. At the shorter terms there may also be some cash. ', 'Low Moderate',466,5,36,43,'AF78842B-99B6-4EE1-8457-47B917CFA0C8','27AFC6DC-C276-4EA1-80CE-62D07A150A0E',2 UNION ALL 
        SELECT 77, 'You are prepared to take a reasonable amount of investment risk in order to increase the chance of achieving a better return. Capital protection is less important to you than the return on the investment. A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a higher proportion of equities compared to fixed interest and cash, and the range of assets provides diversification benefits.', 'Moderate',466,6,44,49,'AF78842B-99B6-4EE1-8457-47B917CFA0C8','6A5DE18B-E576-4D7C-819D-A45A48B58D4C',1 UNION ALL 
        SELECT 78, 'You are comfortable in taking a reasonable amount of investment risk in order to increase the chance of achieving a better return. Capital protection is less important to you than the return on the investment. A typical Moderate to Low Adventurous investor will usually invest in a variety of assets to obtain diversification. There would be a higher proportion of equities compared to fixed interest and cash, and the range of assets provides diversification benefits.', 'Moderate to Low Adventurous',466,7,50,56,'AF78842B-99B6-4EE1-8457-47B917CFA0C8','F10075C6-29E5-4E6F-B687-3912F2A68051',2 UNION ALL 
        SELECT 79, 'You are prepared to take some risk with your investment in return for the prospect of the improving longer term investment performance as short term capital protection is not important. A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'Moderate to Adventurous',466,8,57,59,'AF78842B-99B6-4EE1-8457-47B917CFA0C8','94F7DD57-4FEB-45E6-BC93-D2ADF6C84F57',1 UNION ALL 
        SELECT 80, 'You are comfortable in taking some risk with your investment in return for the prospect of the improving longer term investment performance as short term capital protection is not important. A typical Low Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'Low Adventurous',466,9,60,63,'AF78842B-99B6-4EE1-8457-47B917CFA0C8','D84459EE-40D2-4301-946B-6170FDA572A7',2 UNION ALL 
        SELECT 81, 'You are prepared to take greater risks with your investment in return for the prospect of the highest longer term investment performance. You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term. A typical Adventurous investor will be invested fully in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities.', 'Adventurous',466,10,64,68,'AF78842B-99B6-4EE1-8457-47B917CFA0C8','31641659-B1F9-4D78-A851-6226EECA5A6F',1 UNION ALL 
        SELECT 82, 'You are not prepared to take investment risk. This means you are prepared to accept lower long term returns to meet your risk criteria.  A typical Very Cautious investor would invest mainly in cash and fixed interest investments, but could include small elements of equity or property for longer term investment objectives.', 'Very Cautious',466,1,14,17,'4D5499D3-5FAD-4D6C-9052-E17D2FBE70AD','1C88638D-DA60-4664-A9B4-F4902E619526',2 UNION ALL 
        SELECT 83, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will contain a small amount of riskier assets in order to increase the chance of obtaining better long term returns. A typical Cautious investor will be invested in fixed interest and cash and will also include an element of equities and property. The range of assets provides diversification benefits to reduce the overall risk.', 'Cautious',466,2,18,21,'4D5499D3-5FAD-4D6C-9052-E17D2FBE70AD','D953D2BB-919D-4313-8533-9E0671209D07',2 UNION ALL 
        SELECT 84, 'You are comfortable in taking a small amount of investment risk and capital protection is fairly important. This means that your portfolio will contain a relatively small amount of riskier assets in order to increase the chance of obtaining better long term returns. A typical Cautious to Low Moderate investor will be invested in fixed interest and cash and will also include an element of equities and property. The range of assets provides diversification benefits to reduce the overall risk.', 'Cautious to Low Moderate',466,3,22,30,'4D5499D3-5FAD-4D6C-9052-E17D2FBE70AD','AF6B4993-B63D-4517-BD6E-B5E2E3D17FCB',2 UNION ALL 
        SELECT 85, 'You are prepared to take some investment risk in order to increase the chances of achieving a reasonable return but would still like to ensure that capital protection is still considered.  A typical Cautious to Moderate investor will be invested in a moderate amount of fixed interest, but with a greater proportion in equities and property. At the shorter terms there may also be some cash.', 'Cautious to Moderate',466,4,31,35,'4D5499D3-5FAD-4D6C-9052-E17D2FBE70AD','4968999F-439F-4635-A30C-A1463BCA5A01',1 UNION ALL 
        SELECT 86, 'You are comfortable in taking some investment risk in order to increase the chances of achieving a reasonable return but would still like to ensure that capital protection is still considered.  A typical Low Moderate investor will be invested in a moderate amount of fixed interest, but with a greater proportion in equities and property. At the shorter terms there may also be some cash. ', 'Low Moderate',466,5,36,43,'4D5499D3-5FAD-4D6C-9052-E17D2FBE70AD','3E1B559B-FC19-488B-8EA7-030CED7EA9F0',2 UNION ALL 
        SELECT 87, 'You are prepared to take a reasonable amount of investment risk in order to increase the chance of achieving a better return. Capital protection is less important to you than the return on the investment. A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a higher proportion of equities compared to fixed interest and cash, and the range of assets provides diversification benefits.', 'Moderate',466,6,44,49,'4D5499D3-5FAD-4D6C-9052-E17D2FBE70AD','8E5D3735-67C4-4F2E-A6FC-EE7F1B607315',1 UNION ALL 
        SELECT 88, 'You are comfortable in taking a reasonable amount of investment risk in order to increase the chance of achieving a better return. Capital protection is less important to you than the return on the investment. A typical Moderate to Low Adventurous investor will usually invest in a variety of assets to obtain diversification. There would be a higher proportion of equities compared to fixed interest and cash, and the range of assets provides diversification benefits.', 'Moderate to Low Adventurous',466,7,50,56,'4D5499D3-5FAD-4D6C-9052-E17D2FBE70AD','4D61F22E-B70C-44F3-ACA8-AD71652BBB74',2 UNION ALL 
        SELECT 89, 'You are prepared to take some risk with your investment in return for the prospect of the improving longer term investment performance as short term capital protection is not important. A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'Moderate to Adventurous',466,8,57,59,'4D5499D3-5FAD-4D6C-9052-E17D2FBE70AD','65240FB1-AE93-4ADA-872F-0C21800D0141',1 UNION ALL 
        SELECT 90, 'You are comfortable in taking some risk with your investment in return for the prospect of the improving longer term investment performance as short term capital protection is not important. A typical Low Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'Low Adventurous',466,9,60,63,'4D5499D3-5FAD-4D6C-9052-E17D2FBE70AD','0DD515E0-F1D5-4F2F-A785-FA56ECDA2446',2 UNION ALL 
        SELECT 91, 'You are prepared to take greater risks with your investment in return for the prospect of the highest longer term investment performance. You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term. A typical Adventurous investor will be invested fully in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities.', 'Adventurous',466,10,64,68,'4D5499D3-5FAD-4D6C-9052-E17D2FBE70AD','89324B7C-4811-41C2-AB2C-630B9A0F12F3',1 UNION ALL 
        SELECT 5031, 'You are prepared to take a medium degree of risk with your investment in return for the prospect of improving longer term investment performance.  Short term capital protection is not important to you and you are willing to sacrifice some long term protection for the likelihood of greater returns.  A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio. Because you are a Low end of Moderate to Adventurous investor there will be slightly more invested in fixed interest and cash.', 'Low end of Moderate to Adventurous',466,7,55,60,'FD599F18-DD7E-41FD-9798-B520520D2B61','5F428085-22D5-45FC-9DB7-4D49276E5AA7',1 UNION ALL 
        SELECT 5032, 'You are prepared to take a limited investment risk in order to increase the chances of achieving a positive return but you only want to risk a small part of your capital to achieve this.  A typical Cautious to Moderate portfolio will have up to half invested in fixed interest products which are low risk but have low returns. The larger part of the portfolio will be invested in equities and property which can boost longer term returns but are associated with more risk. Because you are a Low end of Cautious to Moderate investor there will be slightly more invested in fixed interest and cash.  The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Low end of Cautious to Moderate',466,3,34,37,'FD599F18-DD7E-41FD-9798-B520520D2B61','00034B86-847A-4D96-8272-0A53E2EC53BD',1 UNION ALL 
        SELECT 5033, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment.  A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash. Because you are a Low end of Moderate investor there will be slightly more invested in fixed interest and cash.  The range of asset types helps reduce the overall risks as well as increasing the chance of better returns.', 'Low end of Moderate',466,5,43,47,'FD599F18-DD7E-41FD-9798-B520520D2B61','EB32C758-7A61-4F64-B594-C5FD48F67EAC',1 UNION ALL 
        SELECT 5034, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance.  You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term.  A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities.', 'Adventurous',466,9,68,74,'FD599F18-DD7E-41FD-9798-B520520D2B61','B7E74E3A-94E8-42CC-A1E7-870620C95C3A',1 UNION ALL 
        SELECT 5035, 'You are prepared to take only a small amount of investment risk.  This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns.  A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. Because you are a Very Cautious investor there will be slightly more invested in fixed interest and cash. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Very Cautious',466,1,18,28,'FD599F18-DD7E-41FD-9798-B520520D2B61','04C5EA0E-DA33-41C1-9CA1-943749754E31',3 UNION ALL 
        SELECT 5036, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment.  A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash.  The range of asset types helps reduce the overall risks as well as increasing the chance of better returns.', 'Moderate',466,6,48,54,'FD599F18-DD7E-41FD-9798-B520520D2B61','C4346732-60A1-42B4-9751-EFE97CC43FB2',1 UNION ALL 
        SELECT 5037, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance.  You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term.  A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities. Because you are a Very Adventurous investor there will be slightly more invested in specialised equities.', 'Very Adventurous',466,10,75,87,'FD599F18-DD7E-41FD-9798-B520520D2B61','DD975614-6886-4123-B141-1D4380CDEF57',1 UNION ALL 
        SELECT 5038, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns.  A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious',466,2,29,33,'FD599F18-DD7E-41FD-9798-B520520D2B61','0B611B0E-6F07-4582-9E06-7A594280DEC6',3 UNION ALL 
        SELECT 5039, 'You are prepared to take a limited investment risk in order to increase the chances of achieving a positive return but you only want to risk a small part of your capital to achieve this.  A typical Cautious to Moderate portfolio will have up to half invested in fixed interest products which are low risk but have low returns. The larger part of the portfolio will be invested in equities and property which can boost longer term returns but are associated with more risk.  The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious to Moderate',466,4,38,42,'FD599F18-DD7E-41FD-9798-B520520D2B61','2DC83230-23E9-4C28-8A7D-52A1DC966B37',1 UNION ALL 
        SELECT 5040, 'You are prepared to take a medium degree of risk with your investment in return for the prospect of improving longer term investment performance.  Short term capital protection is not important to you and you are willing to sacrifice some long term protection for the likelihood of greater returns.  A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'Moderate to Adventurous',466,8,61,67,'FD599F18-DD7E-41FD-9798-B520520D2B61','F2DD29A9-3264-4A2E-AABD-062635AAD83C',1 UNION ALL 
        SELECT 5041, 'You are comfortable in taking a reasonable amount of investment risk in order to increase the chance of achieving a better return. Capital protection is less important to you than the return on the investment. A typical Moderate to Low Adventurous investor will usually invest in a variety of assets to obtain diversification. There would be a higher proportion of equities compared to fixed interest and cash, and the range of assets provides diversification benefits.', 'High end of Moderate',466,7,55,60,'47D79A15-68DD-46DE-97EA-79E327EB6636','A203CE13-50E9-47E0-AE85-149036BAD590',1 UNION ALL 
        SELECT 5042, 'You are comfortable in taking a small amount of investment risk and capital protection is fairly important. This means that your portfolio will contain a relatively small amount of riskier assets in order to increase the chance of obtaining better long term returns. A typical Cautious to Low Moderate investor will be invested in fixed interest and cash and will also include an element of equities and property. The range of assets provides diversification benefits to reduce the overall risk.', 'High end of Cautious',466,3,34,37,'47D79A15-68DD-46DE-97EA-79E327EB6636','CB0FA57D-DDD5-4118-8184-A7A325B13E31',1 UNION ALL 
        SELECT 5043, 'You are comfortable in taking some investment risk in order to increase the chances of achieving a reasonable return but would still like to ensure that capital protection is still considered.  A typical Low Moderate investor will be invested in a moderate amount of fixed interest, but with a greater proportion in equities and property. At the shorter terms there may also be some cash. ', 'High end of Cautious - Moderate',466,5,43,47,'47D79A15-68DD-46DE-97EA-79E327EB6636','FD233A9E-DD3B-4390-B803-B0E290579511',1 UNION ALL 
        SELECT 5044, 'You are comfortable in taking some risk with your investment in return for the prospect of the improving longer term investment performance as short term capital protection is not important. A typical Low Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'High end of Moderate-Adventurous',466,9,68,74,'47D79A15-68DD-46DE-97EA-79E327EB6636','7E60A183-6994-49A1-842F-54ED8AF34519',1 UNION ALL 
        SELECT 5045, 'You are not prepared to take investment risk. This means you are prepared to accept lower long term returns to meet your risk criteria.  A typical Very Cautious investor would invest mainly in cash and fixed interest investments, but could include small elements of equity or property for longer term investment objectives.', 'Very Cautious',466,1,18,28,'47D79A15-68DD-46DE-97EA-79E327EB6636','BA7FBDE7-2EAD-4FE1-BE27-913A3A50D024',2 UNION ALL 
        SELECT 5046, 'You are prepared to take a reasonable amount of investment risk in order to increase the chance of achieving a better return. Capital protection is less important to you than the return on the investment. A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a higher proportion of equities compared to fixed interest and cash, and the range of assets provides diversification benefits.', 'Low end of Moderate',466,6,48,54,'47D79A15-68DD-46DE-97EA-79E327EB6636','D57C1B3B-C8DD-477B-A0CC-705166102CE8',1 UNION ALL 
        SELECT 5047, 'You are prepared to take greater risks with your investment in return for the prospect of the highest longer term investment performance. You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term. A typical Adventurous investor will be invested fully in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities.', 'Adventurous',466,10,75,87,'47D79A15-68DD-46DE-97EA-79E327EB6636','CB519A05-1134-4877-A90C-6E3EA609081F',1 UNION ALL 
        SELECT 5048, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will contain a small amount of riskier assets in order to increase the chance of obtaining better long term returns. A typical Cautious investor will be invested in fixed interest and cash and will also include an element of equities and property. The range of assets provides diversification benefits to reduce the overall risk.', 'Low end of Cautious',466,2,29,33,'47D79A15-68DD-46DE-97EA-79E327EB6636','06311BDB-45C3-42DB-9C02-A823A876876B',2 UNION ALL 
        SELECT 5049, 'You are prepared to take some investment risk in order to increase the chances of achieving a reasonable return but would still like to ensure that capital protection is still considered.  A typical Cautious to Moderate investor will be invested in a moderate amount of fixed interest, but with a greater proportion in equities and property. At the shorter terms there may also be some cash.', 'Low end of Cautious  Moderate',466,4,38,42,'47D79A15-68DD-46DE-97EA-79E327EB6636','ADB517A3-A71B-4469-8842-023838A65539',1 UNION ALL 
        SELECT 5050, 'You are prepared to take some risk with your investment in return for the prospect of the improving longer term investment performance as short term capital protection is not important. A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'Low end of Moderate-Adventurous',466,8,61,67,'47D79A15-68DD-46DE-97EA-79E327EB6636','8FA682CC-E49E-428A-8847-7CEB1DE33BF2',1 UNION ALL 
        SELECT 5143, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment. A typical moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash.  The range of asset types helps reduce the overall risks as well as increasing the chance of better returns.', 'Moderate',466,3,32,39,'8C93A7CE-3931-4CB5-9D96-6A130E8F37B8','4A723EED-C1C3-400A-8421-2274335BF56E',1 UNION ALL 
        SELECT 5144, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance.  You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term.  A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities.', 'Adventurous',466,5,50,63,'8C93A7CE-3931-4CB5-9D96-6A130E8F37B8','084FA005-9694-462F-BF7E-4F429BA7AFA1',1 UNION ALL 
        SELECT 5145, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns.  A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious',466,1,13,24,'8C93A7CE-3931-4CB5-9D96-6A130E8F37B8','B3DEC8BE-378B-4347-9362-59958A0CB60C',3 UNION ALL 
        SELECT 5146, 'You are prepared to take a limited investment risk in order to increase the chances of achieving a positive return but you only want to risk a small part of your capital to achieve this.  A typical Cautious to Moderate portfolio will have up to half invested in fixed interest products which are low risk but have low returns. The larger part of the portfolio will be invested in equities and property which can boost longer term returns but are associated with more risk.  The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious to Moderate',466,2,25,31,'8C93A7CE-3931-4CB5-9D96-6A130E8F37B8','D3B8F00D-1707-4A7A-860F-57603B5A88B8',1 UNION ALL 
        SELECT 5147, 'You are prepared to take a medium degree of risk with your investment in return for the prospect of improving longer term investment performance.  Short term capital protection is not important to you and you are willing to sacrifice some long term protection for the likelihood of greater returns.  A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'Moderate to Adventurous',466,4,40,49,'8C93A7CE-3931-4CB5-9D96-6A130E8F37B8','1AFDBAD8-CE42-493A-97DC-80352E7FB73A',1 UNION ALL 
        SELECT 5148, 'You are prepared to take a medium degree of risk with your investment in return for the prospect of improving longer term investment performance.  Short term capital protection is not important to you and you are willing to sacrifice some long term protection for the likelihood of greater returns.  A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio. Because you are a Low end of Moderate to Adventurous investor there will be slightly more invested in fixed interest and cash.', 'Low end of Moderate to Adventurous',466,7,55,60,'136E7C5C-F177-4093-8D7E-027CB663B785','77A3833D-D6DA-4A50-B40A-DE8BC5845D99',1 UNION ALL 
        SELECT 5149, 'You are prepared to take a limited investment risk in order to increase the chances of achieving a positive return but you only want to risk a small part of your capital to achieve this.  A typical Cautious to Moderate portfolio will have up to half invested in fixed interest products which are low risk but have low returns. The larger part of the portfolio will be invested in equities and property which can boost longer term returns but are associated with more risk. Because you are a Low end of Cautious to Moderate investor there will be slightly more invested in fixed interest and cash.  The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Low end of Cautious to Moderate',466,3,34,37,'136E7C5C-F177-4093-8D7E-027CB663B785','4D77F5F5-F0F8-4C84-B6AD-C92BC58BBA53',1 UNION ALL 
        SELECT 5150, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment.  A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash. Because you are a Low end of Moderate investor there will be slightly more invested in fixed interest and cash.  The range of asset types helps reduce the overall risks as well as increasing the chance of better returns.', 'Low end of Moderate',466,5,43,47,'136E7C5C-F177-4093-8D7E-027CB663B785','95FAEEDF-08BD-46C7-8ED6-1951E6EBAD84',1 UNION ALL 
        SELECT 5151, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance.  You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term.  A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities.', 'Adventurous',466,9,68,74,'136E7C5C-F177-4093-8D7E-027CB663B785','789154F1-2561-476A-8C8E-03F4635770A3',1 UNION ALL 
        SELECT 5152, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns.  A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. Because you are a Very Cautious investor there will be slightly more invested in fixed interest and cash. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Very Cautious',466,1,18,28,'136E7C5C-F177-4093-8D7E-027CB663B785','42475889-504B-45EE-A07E-AFF9753EBFF8',3 UNION ALL 
        SELECT 5153, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment.  A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash.  The range of asset types helps reduce the overall risks as well as increasing the chance of better returns.', 'Moderate',466,6,48,54,'136E7C5C-F177-4093-8D7E-027CB663B785','4439C7B5-7A5C-4B98-9545-A344E7436200',1 UNION ALL 
        SELECT 5154, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance.  You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term.  A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities. Because you are a Very Adventurous investor there will be slightly more invested in specialised equities.', 'Very Adventurous',466,10,75,87,'136E7C5C-F177-4093-8D7E-027CB663B785','5B4AF05F-E8F7-4495-9F41-BD158365226D',1 UNION ALL 
        SELECT 5155, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns.  A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious',466,2,29,33,'136E7C5C-F177-4093-8D7E-027CB663B785','4A875D16-1DCE-4683-8166-79FB4D6645B6',3 UNION ALL 
        SELECT 5156, 'You are prepared to take a limited investment risk in order to increase the chances of achieving a positive return but you only want to risk a small part of your capital to achieve this.  A typical Cautious to Moderate portfolio will have up to half invested in fixed interest products which are low risk but have low returns. The larger part of the portfolio will be invested in equities and property which can boost longer term returns but are associated with more risk.  The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious to Moderate',466,4,38,42,'136E7C5C-F177-4093-8D7E-027CB663B785','235CDB81-24C1-4A54-9309-995773D21E73',1 UNION ALL 
        SELECT 5157, 'You are prepared to take a medium degree of risk with your investment in return for the prospect of improving longer term investment performance.  Short term capital protection is not important to you and you are willing to sacrifice some long term protection for the likelihood of greater returns.  A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'Moderate to Adventurous',466,8,61,67,'136E7C5C-F177-4093-8D7E-027CB663B785','08ACBA56-4B29-49B3-B147-1EF732D7FF15',1 UNION ALL 
        SELECT 5158, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment. A typical moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash.  The range of asset types helps reduce the overall risks as well as increasing the chance of better returns.', 'Moderate',466,3,32,39,'2B128DA8-539A-4681-847B-6F9680F474B6','55A7B0D7-5997-4347-A871-828710143EC8',1 UNION ALL 
        SELECT 5159, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance.  You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term.  A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities.', 'Adventurous',466,5,50,63,'2B128DA8-539A-4681-847B-6F9680F474B6','DE14CBCF-A57E-4592-BEF5-8F8D4724AAB2',1 UNION ALL 
        SELECT 5160, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns.  A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious',466,1,13,24,'2B128DA8-539A-4681-847B-6F9680F474B6','16860A6F-DB18-48F3-947E-53193EE95A47',3 UNION ALL 
        SELECT 5161, 'You are prepared to take a limited investment risk in order to increase the chances of achieving a positive return but you only want to risk a small part of your capital to achieve this.  A typical Cautious to Moderate portfolio will have up to half invested in fixed interest products which are low risk but have low returns. The larger part of the portfolio will be invested in equities and property which can boost longer term returns but are associated with more risk.  The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious to Moderate',466,2,25,31,'2B128DA8-539A-4681-847B-6F9680F474B6','EB00A9B3-F5BB-4D85-A5BC-5EC454202CEF',1 UNION ALL 
        SELECT 5162, 'You are prepared to take a medium degree of risk with your investment in return for the prospect of improving longer term investment performance.  Short term capital protection is not important to you and you are willing to sacrifice some long term protection for the likelihood of greater returns.  A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'Moderate to Adventurous',466,4,40,49,'2B128DA8-539A-4681-847B-6F9680F474B6','BB8CC4DE-87CF-4A64-85EC-82E0911FB68D',1 UNION ALL 
        SELECT 5163, 'You are prepared to take a medium degree of risk with your investment in return for the prospect of improving longer term investment performance.  Short term capital protection is not important to you and you are willing to sacrifice some long term protection for the likelihood of greater returns.  A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio. Because you are a Low end of Moderate to Adventurous investor there will be slightly more invested in fixed interest and cash.', 'Low end of Moderate to Adventurous',466,7,55,60,'75F4708D-EC93-4C57-A6DF-0269BB24B82E','FB2DA540-A77C-4F99-965D-1209A776766A',1 UNION ALL 
        SELECT 5164, 'You are prepared to take a limited investment risk in order to increase the chances of achieving a positive return but you only want to risk a small part of your capital to achieve this.  A typical Cautious to Moderate portfolio will have up to half invested in fixed interest products which are low risk but have low returns. The larger part of the portfolio will be invested in equities and property which can boost longer term returns but are associated with more risk. Because you are a Low end of Cautious to Moderate investor there will be slightly more invested in fixed interest and cash.  The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Low end of Cautious to Moderate',466,3,34,37,'75F4708D-EC93-4C57-A6DF-0269BB24B82E','8B8F8483-07F3-4907-840B-F74AEBA4FCCD',1 UNION ALL 
        SELECT 5165, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment.  A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash. Because you are a Low end of Moderate investor there will be slightly more invested in fixed interest and cash.  The range of asset types helps reduce the overall risks as well as increasing the chance of better returns.', 'Low end of Moderate',466,5,43,47,'75F4708D-EC93-4C57-A6DF-0269BB24B82E','0B48C6E0-9244-4F64-9046-C9A172CF6CBA',1 UNION ALL 
        SELECT 5166, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance.  You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term.  A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities.', 'Adventurous',466,9,68,74,'75F4708D-EC93-4C57-A6DF-0269BB24B82E','D305F512-E3D4-40CA-87C4-23B867370467',1 UNION ALL 
        SELECT 5167, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns.  A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. Because you are a Very Cautious investor there will be slightly more invested in fixed interest and cash. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Very Cautious',466,1,18,28,'75F4708D-EC93-4C57-A6DF-0269BB24B82E','EAB7EE81-608A-4CBB-A832-C33035A9F9DA',3 UNION ALL 
        SELECT 5168, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment.  A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash.  The range of asset types helps reduce the overall risks as well as increasing the chance of better returns.', 'Moderate',466,6,48,54,'75F4708D-EC93-4C57-A6DF-0269BB24B82E','CD26EEF2-A4BD-4922-BDBE-5AD3A1CFAD9B',1 UNION ALL 
        SELECT 5169, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance.  You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term.  A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities. Because you are a Very Adventurous investor there will be slightly more invested in specialised equities.', 'Very Adventurous',466,10,75,87,'75F4708D-EC93-4C57-A6DF-0269BB24B82E','F6916508-5A9A-49FE-87D3-B86D707385D2',1 UNION ALL 
        SELECT 5170, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns.  A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious',466,2,29,33,'75F4708D-EC93-4C57-A6DF-0269BB24B82E','35BF780B-8133-4EC4-8616-2FD6FA610B35',3 UNION ALL 
        SELECT 5171, 'You are prepared to take a limited investment risk in order to increase the chances of achieving a positive return but you only want to risk a small part of your capital to achieve this.  A typical Cautious to Moderate portfolio will have up to half invested in fixed interest products which are low risk but have low returns. The larger part of the portfolio will be invested in equities and property which can boost longer term returns but are associated with more risk.  The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious to Moderate',466,4,38,42,'75F4708D-EC93-4C57-A6DF-0269BB24B82E','B7030190-642F-4438-A8EF-032C8698D377',1 UNION ALL 
        SELECT 5172, 'You are prepared to take a medium degree of risk with your investment in return for the prospect of improving longer term investment performance.  Short term capital protection is not important to you and you are willing to sacrifice some long term protection for the likelihood of greater returns.  A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'Moderate to Adventurous',466,8,61,67,'75F4708D-EC93-4C57-A6DF-0269BB24B82E','79AA02FB-0205-4485-8879-48F2967267DA',1 UNION ALL 
        SELECT 6757, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns.  A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious',466,1,13,23,'27730FDE-BDC3-4D83-9324-3D06CA573CC7','29919FCC-15D7-4754-BFA0-90BC20F92611',3 UNION ALL 
        SELECT 6758, 'You are prepared to take a limited investment risk in order to increase the chances of achieving a positive return but you only want to risk a small part of your capital to achieve this.  A typical Cautious to Moderate portfolio will have up to half invested in fixed interest products which are low risk but have low returns. The larger part of the portfolio will be invested in equities and property which can boost longer term returns but are associated with more risk.  The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious to Moderate',466,2,24,31,'27730FDE-BDC3-4D83-9324-3D06CA573CC7','A1FBD63E-76CF-44DA-98D2-00034C119BCC',1 UNION ALL 
        SELECT 6759, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment. A typical moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash.  The range of asset types helps reduce the overall risks as well as increasing the chance of better returns.', 'Moderate',466,3,32,41,'27730FDE-BDC3-4D83-9324-3D06CA573CC7','C047CFF2-6B6F-4E5B-843B-E1B7A5586E38',1 UNION ALL 
        SELECT 6760, 'You are prepared to take a medium degree of risk with your investment in return for the prospect of improving longer term investment performance.  Short term capital protection is not important to you and you are willing to sacrifice some long term protection for the likelihood of greater returns.  A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'Moderate to Adventurous',466,4,42,50,'27730FDE-BDC3-4D83-9324-3D06CA573CC7','2268F92C-2E40-46AB-8A9E-2E303B38954A',1 UNION ALL 
        SELECT 6761, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance.  You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term.  A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities.', 'Adventurous',466,5,51,63,'27730FDE-BDC3-4D83-9324-3D06CA573CC7','CEEAEB37-B3CF-451C-8DBF-EF72D5CEC38A',1 UNION ALL 
        SELECT 6762, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns.  A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious',466,1,13,23,'3F9A3F08-0E82-4085-9DD1-D8BD53336D35','B84EC8AC-B61E-4DA0-81EA-17CFAF135BB7',3 UNION ALL 
        SELECT 6763, 'You are prepared to take a limited investment risk in order to increase the chances of achieving a positive return but you only want to risk a small part of your capital to achieve this.  A typical Cautious to Moderate portfolio will have up to half invested in fixed interest products which are low risk but have low returns. The larger part of the portfolio will be invested in equities and property which can boost longer term returns but are associated with more risk.  The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious to Moderate',466,2,24,31,'3F9A3F08-0E82-4085-9DD1-D8BD53336D35','C351EAB4-DD9C-4E33-AB19-A36C33B7AC75',1 UNION ALL 
        SELECT 6764, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment. A typical moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash.  The range of asset types helps reduce the overall risks as well as increasing the chance of better returns.', 'Moderate',466,3,32,41,'3F9A3F08-0E82-4085-9DD1-D8BD53336D35','3DA33017-85BF-49DC-B8EA-BDBB479DCA0D',1 UNION ALL 
        SELECT 6765, 'You are prepared to take a medium degree of risk with your investment in return for the prospect of improving longer term investment performance.  Short term capital protection is not important to you and you are willing to sacrifice some long term protection for the likelihood of greater returns.  A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'Moderate to Adventurous',466,4,42,50,'3F9A3F08-0E82-4085-9DD1-D8BD53336D35','484FB053-F25F-46F7-BDDA-C3DFAEC542F7',1 UNION ALL 
        SELECT 6766, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance.  You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term.  A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities.', 'Adventurous',466,5,51,63,'3F9A3F08-0E82-4085-9DD1-D8BD53336D35','D26DAC40-4D8F-4040-96B0-DA3C3FEC02B4',1 UNION ALL 
        SELECT 6767, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns.  A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. Because you are a Very Cautious investor there will be slightly more invested in fixed interest and cash. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Very Cautious',466,1,18,26,'0D20E9E2-C379-4E06-8922-3C2F2C95719E','37A6D2BE-5F28-44AB-8E80-D5E4D924551A',3 UNION ALL 
        SELECT 6768, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns.  A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious',466,2,27,31,'0D20E9E2-C379-4E06-8922-3C2F2C95719E','8948E1E9-665D-404A-8E57-2313BD9D8839',3 UNION ALL 
        SELECT 6769, 'You are prepared to take a limited investment risk in order to increase the chances of achieving a positive return but you only want to risk a small part of your capital to achieve this.  A typical Cautious to Moderate portfolio will have up to half invested in fixed interest products which are low risk but have low returns. The larger part of the portfolio will be invested in equities and property which can boost longer term returns but are associated with more risk. Because you are a Low end of Cautious to Moderate investor there will be slightly more invested in fixed interest and cash.  The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Low end of Cautious to Moderate',466,3,32,35,'0D20E9E2-C379-4E06-8922-3C2F2C95719E','2DCEF15B-0A35-418A-88EE-2426A804E4E3',1 UNION ALL 
        SELECT 6770, 'You are prepared to take a limited investment risk in order to increase the chances of achieving a positive return but you only want to risk a small part of your capital to achieve this.  A typical Cautious to Moderate portfolio will have up to half invested in fixed interest products which are low risk but have low returns. The larger part of the portfolio will be invested in equities and property which can boost longer term returns but are associated with more risk.  The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious to Moderate',466,4,36,42,'0D20E9E2-C379-4E06-8922-3C2F2C95719E','247E9C6D-852F-497A-AF70-556EB7E7B33E',1 UNION ALL 
        SELECT 6771, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment.  A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash. Because you are a Low end of Moderate investor there will be slightly more invested in fixed interest and cash.  The range of asset types helps reduce the overall risks as well as increasing the chance of better returns.', 'Low end of Moderate',466,5,43,48,'0D20E9E2-C379-4E06-8922-3C2F2C95719E','1F36DCCE-DB1C-4E9C-86CF-B6FD08136F9A',1 UNION ALL 
        SELECT 6772, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment.  A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash.  The range of asset types helps reduce the overall risks as well as increasing the chance of better returns.', 'Moderate',466,6,49,55,'0D20E9E2-C379-4E06-8922-3C2F2C95719E','464B927A-0DDA-475A-9EF4-2303E6381CC2',1 UNION ALL 
        SELECT 6773, 'You are prepared to take a medium degree of risk with your investment in return for the prospect of improving longer term investment performance.  Short term capital protection is not important to you and you are willing to sacrifice some long term protection for the likelihood of greater returns.  A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio. Because you are a Low end of Moderate to Adventurous investor there will be slightly more invested in fixed interest and cash.', 'Low end of Moderate to Adventurous',466,7,56,62,'0D20E9E2-C379-4E06-8922-3C2F2C95719E','E341BBFA-427F-4317-8C4F-61715F9D3865',1 UNION ALL 
        SELECT 6774, 'You are prepared to take a medium degree of risk with your investment in return for the prospect of improving longer term investment performance.  Short term capital protection is not important to you and you are willing to sacrifice some long term protection for the likelihood of greater returns.  A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'Moderate to Adventurous',466,8,63,68,'0D20E9E2-C379-4E06-8922-3C2F2C95719E','B0A15229-CF07-4C98-9805-D889463ADFDE',1 UNION ALL 
        SELECT 6775, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance.  You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term.  A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities.', 'Adventurous',466,9,69,74,'0D20E9E2-C379-4E06-8922-3C2F2C95719E','3622AAB5-3887-4740-BC11-6CD043FE2963',1 UNION ALL 
        SELECT 6776, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance.  You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term.  A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities. Because you are a Very Adventurous investor there will be slightly more invested in specialised equities.', 'Very Adventurous',466,10,75,86,'0D20E9E2-C379-4E06-8922-3C2F2C95719E','021710A5-E3F4-4C9E-8766-E147D7D7EFD2',1 UNION ALL 
        SELECT 6777, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns.  A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. Because you are a Very Cautious investor there will be slightly more invested in fixed interest and cash. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Very Cautious',466,1,18,26,'9E3FBB8E-646D-41BA-A2F3-527525474581','44E88DD0-04A5-4E63-9CEE-A2EDD625409F',3 UNION ALL 
        SELECT 6778, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns.  A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious',466,2,27,31,'9E3FBB8E-646D-41BA-A2F3-527525474581','0EC60938-986F-45DA-8B18-9CCD11020FD7',3 UNION ALL 
        SELECT 6779, 'You are prepared to take a limited investment risk in order to increase the chances of achieving a positive return but you only want to risk a small part of your capital to achieve this.  A typical Cautious to Moderate portfolio will have up to half invested in fixed interest products which are low risk but have low returns. The larger part of the portfolio will be invested in equities and property which can boost longer term returns but are associated with more risk. Because you are a Low end of Cautious to Moderate investor there will be slightly more invested in fixed interest and cash.  The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Low end of Cautious to Moderate',466,3,32,35,'9E3FBB8E-646D-41BA-A2F3-527525474581','FDDCB798-8E27-4A25-8314-8DD4FC538BB7',1 UNION ALL 
        SELECT 6780, 'You are prepared to take a limited investment risk in order to increase the chances of achieving a positive return but you only want to risk a small part of your capital to achieve this.  A typical Cautious to Moderate portfolio will have up to half invested in fixed interest products which are low risk but have low returns. The larger part of the portfolio will be invested in equities and property which can boost longer term returns but are associated with more risk.  The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious to Moderate',466,4,36,42,'9E3FBB8E-646D-41BA-A2F3-527525474581','E0A0D10C-38F7-428C-AD23-BEF91B7941C5',1 UNION ALL 
        SELECT 6781, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment.  A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash. Because you are a Low end of Moderate investor there will be slightly more invested in fixed interest and cash.  The range of asset types helps reduce the overall risks as well as increasing the chance of better returns.', 'Low end of Moderate',466,5,43,48,'9E3FBB8E-646D-41BA-A2F3-527525474581','5F410A5B-0429-40FF-A676-32DFDB3D4FEC',1 UNION ALL 
        SELECT 6782, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment.  A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash.  The range of asset types helps reduce the overall risks as well as increasing the chance of better returns.', 'Moderate',466,6,49,55,'9E3FBB8E-646D-41BA-A2F3-527525474581','D31FD400-B8FF-4416-83AF-28E9674FB13A',1 UNION ALL 
        SELECT 6783, 'You are prepared to take a medium degree of risk with your investment in return for the prospect of improving longer term investment performance.  Short term capital protection is not important to you and you are willing to sacrifice some long term protection for the likelihood of greater returns.  A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio. Because you are a Low end of Moderate to Adventurous investor there will be slightly more invested in fixed interest and cash.', 'Low end of Moderate to Adventurous',466,7,56,62,'9E3FBB8E-646D-41BA-A2F3-527525474581','A458B166-2F38-432E-BCE6-71B5083E4FFC',1 UNION ALL 
        SELECT 6784, 'You are prepared to take a medium degree of risk with your investment in return for the prospect of improving longer term investment performance.  Short term capital protection is not important to you and you are willing to sacrifice some long term protection for the likelihood of greater returns.  A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'Moderate to Adventurous',466,8,63,68,'9E3FBB8E-646D-41BA-A2F3-527525474581','2BB839A0-D73B-4B11-9BED-99F204E165F6',1 UNION ALL 
        SELECT 6785, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance.  You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term.  A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities.', 'Adventurous',466,9,69,74,'9E3FBB8E-646D-41BA-A2F3-527525474581','002FC108-DAF3-4855-B888-15E2F6996F28',1 UNION ALL 
        SELECT 6786, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance.  You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term.  A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities. Because you are a Very Adventurous investor there will be slightly more invested in specialised equities.', 'Very Adventurous',466,10,75,86,'9E3FBB8E-646D-41BA-A2F3-527525474581','FE283A1A-7678-4984-B1B5-C1391C7017CD',1 UNION ALL 
        SELECT 8752, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns. A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. Because you are a Very Cautious investor there will be slightly more invested in fixed interest and cash. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Very Cautious',466,1,18,26,'CA2E0E7C-2A68-405B-8B91-A70E01024C5C','3C3E1D34-E1C6-4354-8169-A70E01026FD2',3 UNION ALL 
        SELECT 8753, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns. A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious',466,2,27,31,'CA2E0E7C-2A68-405B-8B91-A70E01024C5C','DF50A7C8-F500-42B2-B8E8-A70E010286A6',3 UNION ALL 
        SELECT 8754, 'You are prepared to take a limited investment risk in order to increase the chances of achieving a positive return but you only want to risk a small part of your capital to achieve this. A typical Cautious to Moderate portfolio will have up to half invested in fixed interest products which are low risk but have low returns. The larger part of the portfolio will be invested in equities and property which can boost longer term returns but are associated with more risk. Because you are a Low end of Cautious to Moderate investor there will be slightly more invested in fixed interest and cash. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Low end of Cautious - Moderate',466,3,32,35,'CA2E0E7C-2A68-405B-8B91-A70E01024C5C','1DFD519F-ABCB-4C2A-B08D-A70E0102F3BA',1 UNION ALL 
        SELECT 8755, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment. A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash. Because you are a Low end of Moderate investor there will be slightly more invested in fixed interest and cash. The range of asset types helps reduce the overall risks as well as increasing the chance of better returns.', 'Cautious to Moderate',466,4,36,42,'CA2E0E7C-2A68-405B-8B91-A70E01024C5C','3706B769-DD4B-43D5-8DBA-A70E01030ABC',1 UNION ALL 
        SELECT 8756, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment. A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash. Because you are a Low end of Moderate investor there will be slightly more invested in fixed interest and cash. The range of asset types helps reduce the overall risks as well as increasing the chance of better returns.', 'Low end of Moderate',466,5,43,48,'CA2E0E7C-2A68-405B-8B91-A70E01024C5C','97369562-5D36-4506-B7AF-A70E010335B5',1 UNION ALL 
        SELECT 8757, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment. A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash. The range of asset types helps reduce the overall risks as well as increasing the chance of better returns', 'Moderate',466,6,49,55,'CA2E0E7C-2A68-405B-8B91-A70E01024C5C','6601F9D7-1AE9-47DF-B51A-A70E01034F4F',1 UNION ALL 
        SELECT 8758, 'You are prepared to take a medium degree of risk with your investment in return for the prospect of improving longer term investment performance. Short term capital protection is not important to you and you are willing to sacrifice some long term protection for the likelihood of greater returns. A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio. Because you are a Low end of Moderate to Adventurous investor there will be slightly more invested in fixed interest and cash', 'Low end of Mod - Adventurous',466,7,56,62,'CA2E0E7C-2A68-405B-8B91-A70E01024C5C','4391D7C4-7D70-40E3-9FFE-A70E01038B20',1 UNION ALL 
        SELECT 8759, 'You are prepared to take a medium degree of risk with your investment in return for the prospect of improving longer term investment performance. Short term capital protection is not important to you and you are willing to sacrifice some long term protection for the likelihood of greater returns. A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio', 'Moderate to Adventurous',466,8,63,68,'CA2E0E7C-2A68-405B-8B91-A70E01024C5C','E63EF5E3-914D-4563-8E52-A70E0103AF68',1 UNION ALL 
        SELECT 8760, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance. You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term. A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities.', 'Adventurous',466,9,69,74,'CA2E0E7C-2A68-405B-8B91-A70E01024C5C','6154D4D0-347B-48FE-B35D-A70E0103D159',1 UNION ALL 
        SELECT 8761, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance. You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term. A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities. Because you are a Very Adventurous investor there will be slightly more invested in specialised equities.', 'Very Adventurous',466,10,75,86,'CA2E0E7C-2A68-405B-8B91-A70E01024C5C','2CF04264-F627-40D0-BB6E-A70E01040FB8',1 UNION ALL 
        SELECT 8931, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns. A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. Because you are a Very Cautious investor there will be slightly more invested in fixed interest and cash. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Very Cautious',466,1,15,22,'B50CD81A-F8CE-4DD2-9EDF-A7300096D06F','98C19B1D-63ED-4CF4-8C07-A7300096EE37',3 UNION ALL 
        SELECT 8932, 'You are prepared to take only a small amount of investment risk. This means that your portfolio will concentrate on investments which provide low returns in the long term but present low risk to your capital. Only a small amount of riskier assets will be included in your portfolio in order to increase the chance of obtaining better long term returns. A typical Cautious investor will be invested mostly in fixed interest and cash with a small element (up to about one third) in equities and property which can boost longer term returns but are associated with more risk. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious',466,2,23,29,'B50CD81A-F8CE-4DD2-9EDF-A7300096D06F','5F72F829-02FB-4314-B861-A730009702B1',3 UNION ALL 
        SELECT 8933, 'You are prepared to take a limited investment risk in order to increase the chances of achieving a positive return but you only want to risk a small part of your capital to achieve this. A typical Cautious to Moderate portfolio will have up to half invested in fixed interest products which are low risk but have low returns. The larger part of the portfolio will be invested in equities and property which can boost longer term returns but are associated with more risk. The range of assets provides diversification benefits which also help to reduce the overall risk.', 'Cautious to Moderate',466,3,30,37,'B50CD81A-F8CE-4DD2-9EDF-A7300096D06F','6311AB70-6ED3-40B4-99BB-A73000971FFA',1 UNION ALL 
        SELECT 8934, 'You are prepared to take a moderate amount of investment risk in order to increase the chance of achieving a positive return. Capital protection is less important to you than achieving a better return on the investment. A typical Moderate investor will usually invest in a variety of assets to obtain diversification. There would be a substantially higher proportion of equities and property compared to fixed interest and cash. The range of asset types helps reduce the overall risks as well as increasing the chance of better returns.', 'Moderate',466,4,38,45,'B50CD81A-F8CE-4DD2-9EDF-A7300096D06F','6E36E7D2-209D-459A-BE13-A7300097CB30',1 UNION ALL 
        SELECT 8935, 'You are prepared to take a medium degree of risk with your investment in return for the prospect of improving longer term investment performance. Short term capital protection is not important to you and you are willing to sacrifice some long term protection for the likelihood of greater returns. A typical Moderate to Adventurous investor will be invested mainly in equities but with other assets included to provide some diversification. There may be a small amount of specialised equity within the portfolio.', 'Moderate to Adventurous',466,5,46,53,'B50CD81A-F8CE-4DD2-9EDF-A7300096D06F','4ABD8F73-9A13-4B88-AD3B-A73000983A40',1 UNION ALL 
        SELECT 8936, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance. You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term. A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities.', 'Adventurous',466,6,54,61,'B50CD81A-F8CE-4DD2-9EDF-A7300096D06F','384CF9AE-F6E2-4D2E-8683-A730009873FB',1 UNION ALL 
        SELECT 8937, 'You are prepared to take a substantial degree of risk with your investment in return for the prospect of the highest possible longer term investment performance. You appreciate that over some periods of time there can be significant falls, as well as rises, in the value of your investment and you may get back less than you invest. This strategy holds significant risk in the shorter term. A typical Adventurous investor will be invested entirely in equities, both in the UK and overseas. There may be a significant proportion of the investment in specialised equities. Because you are a Very Adventurous investor there will be slightly more invested in specialised equities.', 'Very Adventurous',466,7,62,71,'B50CD81A-F8CE-4DD2-9EDF-A7300096D06F','536DCB0E-647C-48FA-97C2-A73000989D49',1 
 
        SET IDENTITY_INSERT TRiskProfile OFF
 
        -- record execution so the script won't run again
        INSERT INTO TExecutedDataScript (ScriptGuid, Comments, TenantId, Timestamp) 
        VALUES (
         'D6C8E4F2-E129-4BFC-88DC-CA2D875F47B0', 
         'Initial load (127 total rows, file 1 of 1) for table TRiskProfile',
         466, 
         getdate() )
 
   IF @starttrancount = 0
    COMMIT TRANSACTION
 
END TRY
BEGIN CATCH
    DECLARE @ErrorMessage varchar(1000), @ErrorSeverity INT, @ErrorState INT, @ErrorLine INT, @ErrorNumber INT
    SELECT @ErrorMessage = ERROR_MESSAGE() , @ErrorSeverity = ERROR_SEVERITY(), @ErrorState = ERROR_STATE(), @ErrorNumber = ERROR_NUMBER(), @ErrorLine = ERROR_LINE()
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState, @ErrorNumber, @ErrorLine)
END CATCH
 
 SET XACT_ABORT OFF
 SET NOCOUNT OFF
-----------------------------------------------------------------------------
-- #Rows Exported: 127
-- Created by AndyF's RefDataExtractor, Nov 12 2020  3:48PM
-----------------------------------------------------------------------------
