USE [policymanagement];

DECLARE @ScriptGUID UNIQUEIDENTIFIER
      , @Comments VARCHAR(255)
      , @ErrorMessage VARCHAR(MAX)

SELECT 
    @ScriptGUID = '8E01017B-7981-42E1-8F43-01622FE83353',
    @Comments = 'AIOCA-257 ADD additional US providers to the global provider list'

IF EXISTS (SELECT 1 FROM TExecutedDataScript WHERE ScriptGUID = @ScriptGUID)
    RETURN;

-----------------------------------------------------------------------------------------------
-- Summary: Add additional US provider

-- Expected records added:  (with audit tables)
-- ~ 5000
-- Expected rows deleted:
-- 42
-- Expected rows updated:
-- 72
-----------------------------------------------------------------------------------------------

SET NOCOUNT ON
SET XACT_ABORT ON

DECLARE @starttrancount int
       ,@StampAction char(1) = 'C'
       ,@StampDateTime AS DATETIME = GETUTCDATE()
       ,@StampUser AS VARCHAR(255) = '0'
       ,@RegionCode varchar(2) = 'US'	   

BEGIN TRY

        IF OBJECT_ID('tempdb..#TCorporate') IS NOT NULL
            DROP TABLE #TCorporate
        CREATE TABLE #TCorporate(CorporateId INT, CorporateName varchar(250))

        -- TCorporate
        INSERT INTO crm..TCorporate (IndClientId, CorporateName, RefCorporateTypeId) 
        OUTPUT inserted.CorporateId, inserted.CorporateName
        INTO #TCorporate
		VALUES
        (0, 'A.W. Jones Advisors', 1),
        (0, 'Abbey Capital Limited', 1),
        (0, 'Abn Amro', 1),
        (0, 'Acadia Life International Limited', 1),
        (0, 'Accrued Equities', 1),
        (0, 'ACP Venture Capital Management Fund', 1),
        (0, 'Adirondack Funds', 1),
        (0, 'ADP', 1),
        (0, 'Advanced Advisor Group', 1),
        (0, 'Adviser Dealer Services', 1),
        (0, 'AEI Fund Management', 1),
        (0, 'AIF Capital Services', 1),
        (0, 'Aimcor Group', 1),
        (0, 'Alder Alternative Income Spe', 1),
        (0, 'Alera Management Group', 1),
        (0, 'Alexander Capital Ventures', 1),
        (0, 'Alggoritmica Portfolio Management', 1),
        (0, 'Alight Solutions', 1),
        (0, 'Allegheny Investments', 1),
        (0, 'Alliancebernstein Investments', 1),
        (0, 'Allianz Life', 1),
        (0, 'Allstate', 1),
        (0, 'Alpine Securities Corporation', 1),
        (0, 'Alps', 1),
        (0, 'Altegris', 1),
        (0, 'Amcap Management', 1),
        (0, 'American Century Investment Services', 1),
        (0, 'American Enterprise Investment Services', 1),
        (0, 'American Funds', 1),
        (0, 'American General Life Insurance Company', 1),
        (0, 'American National Insurance Company', 1),
        (0, 'American Portfolios Financial Services', 1),
        (0, 'American United Life Insurance Company', 1),
        (0, 'Amerifunds Diversified Funding', 1),
        (0, 'Ameritas', 1),
        (0, 'AMG Funds', 1),
        (0, 'Amherst Pierpont Securities', 1),
        (0, 'Amundi', 1),
        (0, 'Angelo, Gordon & Company', 1),
        (0, 'Annuity Marketing Services', 1),
        (0, 'Apex Clearing Corporation', 1),
        (0, 'Apexone Investment Partners', 1),
        (0, 'Aplifi', 1),
        (0, 'APW Capital', 1),
        (0, 'APX Energy', 1),
        (0, 'Aquila', 1),
        (0, 'AR Global Investments', 1),
        (0, 'Arbor Court Capital', 1),
        (0, 'Arbor Research & Trading', 1),
        (0, 'Arboretum Investment Advisors', 1),
        (0, 'Archer', 1),
        (0, 'Archipelago Securities', 1),
        (0, 'Aria Retirement Solutions', 1),
        (0, 'Ariel', 1),
        (0, 'Artisan Partners', 1),
        (0, 'Artivest Advisors', 1),
        (0, 'Ascensus', 1),
        (0, 'Ascentia Real Estate Holding Company', 1),
        (0, 'Ashmore Investment Management         (US) Corporation', 1),
        (0, 'Aspargo Laboratories', 1),
        (0, 'Assetmark Trust Company', 1),
        (0, 'Associated Investment Services', 1),
        (0, 'Ategra Capital Management', 1),
        (0, 'Atel Securities Corporation', 1),
        (0, 'Athene Annuity and Life Company', 1),
        (0, 'Atlas Fund Services         (USA)', 1),
        (0, 'Attain Portfolio Advisors', 1),
        (0, 'Ausdal Financial Partners', 1),
        (0, 'Avantax Investment Services', 1),
        (0, 'Avenue Capital Management II', 1),
        (0, 'AVM', 1),
        (0, 'AXA', 1),
        (0, 'Axonic Capital', 1),
        (0, 'Axos Clearing', 1),
        (0, 'Axys Capital', 1),
        (0, 'Ayco Company', 1),
        (0, 'Azzad Funds', 1),
        (0, 'B.C. Ziegler and Company', 1),
        (0, 'Babson Capital Securities', 1),
        (0, 'Baceline Investments', 1),
        (0, 'Baillie Gifford Funds Services', 1),
        (0, 'Bancorp Bank', 1),
        (0, 'Bancwest Investment Services', 1),
        (0, 'Bank of Oklahoma', 1),
        (0, 'Bankers Bank', 1),
        (0, 'Bankers Life', 1),
        (0, 'Bankoh Investment Services', 1),
        (0, 'Banner Life Insurance Company', 1),
        (0, 'Barings', 1),
        (0, 'Barnum Financial Group', 1),
        (0, 'Baron Capital', 1),
        (0, 'Baru Capital Partners', 1),
        (0, 'Benefit Street Partners', 1),
        (0, 'Benefit Trust Company', 1),
        (0, 'Bertolet Capital Trust', 1),
        (0, 'Beta Capital Securities', 1),
        (0, 'BGC Financial', 1),
        (0, 'BGV VC Management', 1),
        (0, 'Birge & Held Asset Management', 1),
        (0, 'Biscayneamericas Advisers', 1),
        (0, 'Bitwise Asset Management', 1),
        (0, 'Black Creek', 1),
        (0, 'Blackrock', 1),
        (0, 'Blackstone Securities Partners', 1),
        (0, 'Bluerock Fund Advisor', 1),
        (0, 'BNP Paribas', 1),
        (0, 'Bolton Global Capital', 1),
        (0, 'Boston Partners Trust Company', 1),
        (0, 'Bourne Financial Group', 1),
        (0, 'Breakwater Group Distribution Services', 1),
        (0, 'Bridgeport Financial Technology', 1),
        (0, 'Brighthouse Life Insurance  Company', 1),
        (0, 'Broadfield Capital Management', 1),
        (0, 'Broadmark Private Reit', 1),
        (0, 'Brokers Alliance', 1),
        (0, 'Brokers International', 1),
        (0, 'Brookstone Capital Management', 1),
        (0, 'Brown Brothers Harriman & Company', 1),
        (0, 'BTG Pactual Asset Management US', 1),
        (0, 'Bulldog Management', 1),
        (0, 'Buttonwood Group Advisors', 1),
        (0, 'C.M. Life Insurance Company', 1),
        (0, 'Cache Private Capital Management', 1),
        (0, 'Cadaret, Grant & Company', 1),
        (0, 'Calamos Financial Services', 1),
        (0, 'Calcap Income Fund I', 1),
        (0, 'Calchoice Financial', 1),
        (0, 'Caldwell Trust Company', 1),
        (0, 'Calibogue Capital', 1),
        (0, 'Calton & Associates', 1),
        (0, 'Cambridge Investment Research', 1),
        (0, 'Campbell & Company', 1),
        (0, 'Canaras Capital Management', 1),
        (0, 'Cantella & Company', 1),
        (0, 'Cantor Fitzgerald & Company', 1),
        (0, 'Canyon Capital Advisors', 1),
        (0, 'Capital Group Companies Global', 1),
        (0, 'Capital Institutional Services', 1),
        (0, 'Capital Integration Systems', 1),
        (0, 'Capital Investment Brokerage', 1),
        (0, 'Capital Investment Group', 1),
        (0, 'Capital Q Management', 1),
        (0, 'Capitas Financial', 1),
        (0, 'Capitol Life Insurance Company', 1),
        (0, 'Capstack Partners', 1),
        (0, 'Carillon Fund', 1),
        (0, 'Carlson Capital', 1),
        (0, 'Carmignac Gestion Sa', 1),
        (0, 'Carter Validus Mission Critical REIT', 1),
        (0, 'Catenary Alternatives Asset Management', 1),
        (0, 'CBIZ Financial Solutions', 1),
        (0, 'CCO Capital', 1),
        (0, 'CCV', 1),
        (0, 'CDS Clearing and Depository Services', 1),
        (0, 'CDS-Settlement', 1),
        (0, 'Cedar Street Asset Management', 1),
        (0, 'Centaurus Financial', 1),
        (0, 'Center Street Securities', 1),
        (0, 'Central Park Group', 1),
        (0, 'Central Trust Bank', 1),
        (0, 'Cetera', 1),
        (0, 'CF Secured', 1),
        (0, 'CFD Investments', 1),
        (0, 'Chalice Capital Partners', 1),
        (0, 'Chatham Capital Holdings', 1),
        (0, 'Chevy Chase Trust Company', 1),
        (0, 'CIG Asset Management', 1),
        (0, 'Cion Investment Group', 1),
        (0, 'CIR Feeder Fund Management', 1),
        (0, 'Citadel', 1),
        (0, 'Citizens Securities', 1),
        (0, 'Clarion Partners', 1),
        (0, 'Clear Street', 1),
        (0, 'Client One Securities', 1),
        (0, 'CLS Investment Firm', 1),
        (0, 'CMFG Life Insurance Company', 1),
        (0, 'CNL Capital Markets', 1),
        (0, 'Cobalt Capital', 1),
        (0, 'Cohen & Steers Securities', 1),
        (0, 'Cohen Real Estate Advisors', 1),
        (0, 'Columbia Management Investment', 1),
        (0, 'Commonwealth Annuity and Life Insurance Company', 1),
        (0, 'Commonwealth Equity Services', 1),
        (0, 'Comprehensive Brokerage Services', 1),
        (0, 'Comprehensive Financial Planning Corporation', 1),
        (0, 'Concise Capital Management LP', 1),
        (0, 'Concorde Funds', 1),
        (0, 'Concorde Investment Services', 1),
        (0, 'Conduent HR Services', 1),
        (0, 'Conestoga Funds', 1),
        (0, 'Conifer Financial Services', 1),
        (0, 'Constitution Capital Credit Partners', 1),
        (0, 'Copper Financial', 1),
        (0, 'Core Capital Management', 1),
        (0, 'Cortland Fund Services', 1),
        (0, 'Cottonwood Residential', 1),
        (0, 'Country Capital Management Company', 1),
        (0, 'Covenant Capital Investors', 1),
        (0, 'Cowen and Company', 1),
        (0, 'Credit Agricole Securities', 1),
        (0, 'Credit Andorra S.A.', 1),
        (0, 'Credit Suisse Securities         (USA)', 1),
        (0, 'Crescent Capital Group LP', 1),
        (0, 'Crescent Securities Group', 1),
        (0, 'Crews & Associates', 1),
        (0, 'Cross Creek Advisors', 1),
        (0, 'Crossmark', 1),
        (0, 'Crowdkey', 1),
        (0, 'Crown Capital Securities', 1),
        (0, 'Crystal Capital Partners', 1),
        (0, 'Cuna Brokerage Services', 1),
        (0, 'Curex Capital Advisors', 1),
        (0, 'Cuso Financial Services', 1),
        (0, 'D.A. Davidson & Company', 1),
        (0, 'D.L. Harris & Associates Insurance Services', 1),
        (0, 'DAI Securities', 1),
        (0, 'Daiwa Capital Markets America', 1),
        (0, 'Dash Financial Technologies', 1),
        (0, 'Davenport & Company', 1),
        (0, 'David Lerner Associates', 1),
        (0, 'Davis', 1),
        (0, 'Dealerweb', 1),
        (0, 'Delaware', 1),
        (0, 'Delaware Life Insurance Company', 1),
        (0, 'Delta Data Software', 1),
        (0, 'Dempsey Lord Smith', 1),
        (0, 'Derby and Company', 1),
        (0, 'Destra Capital Investments', 1),
        (0, 'DFA Securities', 1),
        (0, 'DLP Capital Advisors', 1),
        (0, 'Dodge & Cox Funds', 1),
        (0, 'DSIL Investment Services', 1),
        (0, 'DST Market Services', 1),
        (0, 'Dunham & Associates Investment Counsel', 1),
        (0, 'Dupree & Company', 1),
        (0, 'DWS', 1),
        (0, 'E D & F Man Capital Markets', 1),
        (0, 'Eagle Life Insurance Company', 1),
        (0, 'EAS Accounting Services, CPA', 1),
        (0, 'Eastern Bank Capital Markets', 1),
        (0, 'Eaton Vance', 1),
        (0, 'Ebix', 1),
        (0, 'Edmond De Rothschild Asset Management', 1),
        (0, 'Edward Jones', 1),
        (0, 'EF Legacy Securities', 1),
        (0, 'Ekon Benefits', 1),
        (0, 'Electronic Transaction Clearing', 1),
        (0, 'Emerson Equity', 1),
        (0, 'Equinoxe Alternative Investment Services Holdings Limited', 1),
        (0, 'Equitable', 1),
        (0, 'Equitrust Life Insurance Company', 1),
        (0, 'Equity Services', 1),
        (0, 'Essential Fund Services', 1),
        (0, 'Esulep Management', 1),
        (0, 'Eulav Securities', 1),
        (0, 'Evolution Real Estate', 1),
        (0, 'Exchangeright Real Estate', 1),
        (0, 'Fairview Investment Administration', 1),
        (0, 'Fairway America', 1),
        (0, 'Farm Bureau Life Insurance Company', 1),
        (0, 'Farmers Financial Solutions', 1),
        (0, 'Farmers New World Life Insurance Company', 1),
        (0, 'FBL Marketing Services', 1),
        (0, 'Federated Administrative Services', 1),
        (0, 'Federated Securities Corporation', 1),
        (0, 'FEF', 1),
        (0, 'Fenimore Asset Management Trust', 1),
        (0, 'Fenix Securities', 1),
        (0, 'FHN Financial Securities Corporation', 1),
        (0, 'Fidelity & Guaranty Life Insurance Company', 1),
        (0, 'Fidelity Security Life Insurance Company', 1),
        (0, 'Fiduciary Exchange', 1),
        (0, 'Fiduciary Management', 1),
        (0, 'Fiduciary Trust Company International', 1),
        (0, 'Filippini Wealth Management', 1),
        (0, 'Financial Enhancement Group', 1),
        (0, 'First Allied Securities', 1),
        (0, 'First Capital Real Estate Trust Incorporated', 1),
        (0, 'First Caribbean International Bank', 1),
        (0, 'First Citizens Investor Services', 1),
        (0, 'First Command Financial Planning', 1),
        (0, 'First Dominion Capital Corp', 1),
        (0, 'First Financial Equity Corporation', 1),
        (0, 'First Heartland Capital', 1),
        (0, 'First Horizon Advisors', 1),
        (0, 'First Manhattan Company', 1),
        (0, 'First National Bankers Bank', 1),
        (0, 'First Republic Securities Company', 1),
        (0, 'First South Carolina Securities', 1),
        (0, 'First Symetra National Life Insurance Company of New York', 1),
        (0, 'First Trust Portfolios', 1),
        (0, 'FIS Brokerage & Securities Services', 1),
        (0, 'Fivepoint Capital Management', 1),
        (0, 'Flat Rock Global', 1),
        (0, 'Flexible Plan Investments', 1),
        (0, 'Fmsbonds', 1),
        (0, 'Folio Investments', 1),
        (0, 'Foreside', 1),
        (0, 'Forester Funds', 1),
        (0, 'Forethought Life Insurance Company', 1),
        (0, 'Fort Point Capital Partners', 1),
        (0, 'Forward Securities', 1),
        (0, 'Founders Financial Securities', 1),
        (0, 'Founders Properties', 1),
        (0, 'Four Springs Capital Trust', 1),
        (0, 'Fourthstone', 1),
        (0, 'Frank Funds', 1),
        (0, 'Franklin Templeton', 1),
        (0, 'Frazer Lanier Company', 1),
        (0, 'Fred Alger & Company', 1),
        (0, 'Frontier Funds', 1),
        (0, 'FS Investment Solutions', 1),
        (0, 'FSC Securities Corporation', 1),
        (0, 'Fulcrum Equity Partners', 1),
        (0, 'Fundamental Capital Management', 1),
        (0, 'Funds Distributor', 1),
        (0, 'Futu Clearing', 1),
        (0, 'G. Research', 1),
        (0, 'G.A. Repple & Company', 1),
        (0, 'Gabelli & Company Investment Advisers', 1),
        (0, 'Galileo Investment Management', 1),
        (0, 'GAM Fund Management', 1),
        (0, 'Garden State Securities', 1),
        (0, 'GCG Financial', 1),
        (0, 'Gemini Fund Services', 1),
        (0, 'Gen II Fund Services', 1),
        (0, 'Geneos Wealth Management', 1),
        (0, 'Gentry Mills Capital', 1),
        (0, 'Genworth Life Insurance Company', 1),
        (0, 'Gladstone Securities', 1),
        (0, 'Glen Eagle Wealth', 1),
        (0, 'Glenmede Trust Company', 1),
        (0, 'Glide Capital', 1),
        (0, 'Global Ai Internet Freedom Fund LP', 1),
        (0, 'Global Atlantic', 1),
        (0, 'Global Financial & Leasing Services', 1),
        (0, 'Global Sme Growth Fund Lp', 1),
        (0, 'Global Trust Company', 1),
        (0, 'Goldman Sachs & Company', 1),
        (0, 'Gradient Securities', 1),
        (0, 'Great American Life Insurance Company', 1),
        (0, 'Great Gable Partners', 1),
        (0, 'Great Lakes Fund Solutions', 1),
        (0, 'Great-West Life & Annuity Insurance Company', 1),
        (0, 'Greenbacker Group', 1),
        (0, 'Greenlake Real Estate Fund', 1),
        (0, 'Griffin Capital Management', 1),
        (0, 'Griffin Capital Securities', 1),
        (0, 'Grove Point Investments', 1),
        (0, 'GTIS OZ', 1),
        (0, 'Guaranty Income Life Insurance Company', 1),
        (0, 'Guardian Insurance & Annuity Company', 1),
        (0, 'Guggenheim', 1),
        (0, 'Guterman Real Estate Partners-47', 1),
        (0, 'GWFS Equities', 1),
        (0, 'GWG Holdings', 1),
        (0, 'GWN Securities', 1),
        (0, 'Hall Structured Finance II', 1),
        (0, 'Hamilton Point Investments', 1),
        (0, 'Hamlin Capital Management', 1),
        (0, 'Hancock Whitney Investment Services', 1),
        (0, 'Hand Benefits & Trust Company', 1),
        (0, 'Hantz Financial Services', 1),
        (0, 'Harbor Funds', 1),
        (0, 'Harmonic Fund Services Canada', 1),
        (0, 'Hartford Funds', 1),
        (0, 'Harvard Property Trust', 1),
        (0, 'Hazlett, Burt & Watson', 1),
        (0, 'HC Global Fund Services', 1),
        (0, 'Heim, Young & Associates', 1),
        (0, 'Heptagon Fund Plc', 1),
        (0, 'Highlands REIT', 1),
        (0, 'Hightower', 1),
        (0, 'Hill Street Realty', 1),
        (0, 'Hilltop Securities', 1),
        (0, 'Hines Securities', 1),
        (0, 'HM Capital Management', 1),
        (0, 'Hold Brothers Capital', 1),
        (0, 'Home Financial Services Inc', 1),
        (0, 'Homestead Funds', 1),
        (0, 'Horace Mann Life Insurance Company', 1),
        (0, 'Horan Securities', 1),
        (0, 'Hornor, Townsend & Kent', 1),
        (0, 'Horseshoe Fund Services', 1),
        (0, 'Hospitality Investors Trust', 1),
        (0, 'HRT Financial LP', 1),
        (0, 'Huntington National Bank', 1),
        (0, 'Huntleigh Securities Corporation', 1),
        (0, 'IBKR Securities Services', 1),
        (0, 'ICAP Corporates', 1),
        (0, 'iCapital', 1),
        (0, 'Ice Securities Execution & Clearing', 1),
        (0, 'ICG Advisors', 1),
        (0, 'ICMA-RC Services', 1),
        (0, 'Icon Capital', 1),
        (0, 'IFP Securities', 1),
        (0, 'Impact Partnership', 1),
        (0, 'Incline Investment Management', 1),
        (0, 'Independent Financial Group', 1),
        (0, 'Infinex Investments', 1),
        (0, 'Infosys Mccamish Systems', 1),
        (0, 'ING Financial Markets', 1),
        (0, 'Ingalls & Snyder', 1),
        (0, 'Inland Real Estate Investment Corporation', 1),
        (0, 'Instinet', 1),
        (0, 'Insurance Designers of Kansas City', 1),
        (0, 'Insurance Technologies', 1),
        (0, 'Insured Connect', 1),
        (0, 'Integrity Funds Distributor', 1),
        (0, 'Integrity Life Insurance Company', 1),
        (0, 'Interactive Brokers', 1),
        (0, 'International Assets Advisory', 1),
        (0, 'Interval Partners', 1),
        (0, 'Intesa Sanpaolo IMI Securities Corporation', 1),
        (0, 'Inventrust Properties Corporation', 1),
        (0, 'Invesco', 1),
        (0, 'Investment Center', 1),
        (0, 'Investment Partners Asset Management', 1),
        (0, 'Itau USA Asset Management', 1),
        (0, 'ITB Capital Management', 1),
        (0, 'J.W. Cole Financial', 1),
        (0, 'J.W. Korth & Company Limited Partnership', 1),
        (0, 'Jackson National Life', 1),
        (0, 'Jackson National Life Insurance Company of New York', 1),
        (0, 'James Baker & Associates', 1),
        (0, 'James I. Black & Company', 1),
        (0, 'Jane Street Capital', 1),
        (0, 'Janney Montgomery Scott', 1),
        (0, 'Janus', 1),
        (0, 'JB Capital Management', 1),
        (0, 'Jefferies', 1),
        (0, 'Jefferson National Life Insurance Company', 1),
        (0, 'John Hancock', 1),
        (0, 'Johnson Investment Counsel', 1),
        (0, 'Johnstone Brokerage Services', 1),
        (0, 'JSQ Administrative Services', 1),
        (0, 'Jump Trading', 1),
        (0, 'JVM Realty Corporation', 1),
        (0, 'JWB Real Estate Capital', 1),
        (0, 'K.W. Chambers & Company', 1),
        (0, 'Kalos Capital', 1),
        (0, 'Kansas City Life Insurance Company', 1),
        (0, 'Kayne Anderson Capital Advisors', 1),
        (0, 'KBS Capital Markets Group', 1),
        (0, 'Kestra Investment Services', 1),
        (0, 'Keystone Capital Corporation', 1),
        (0, 'King Strategic Energy Funds LP', 1),
        (0, 'Knightsbridge Advisers', 1),
        (0, 'Koonce Securities', 1),
        (0, 'Kovack Securities', 1),
        (0, 'L.M. Kohn & Company', 1),
        (0, 'Larson Financial Group', 1),
        (0, 'Lasalle Investment Management', 1),
        (0, 'Lasalle St. Securities', 1),
        (0, 'Lazard Asset Management Securities', 1),
        (0, 'LDR Capital Management', 1),
        (0, 'Leafhouse Financial Advisors', 1),
        (0, 'Lee Financial Mutual Fund', 1),
        (0, 'Legacy NW Fund', 1),
        (0, 'Legacy Opportunity Fund', 1),
        (0, 'Legendary Capital', 1),
        (0, 'Legg Mason Investor Services', 1),
        (0, 'Lehman Brothers', 1),
        (0, 'Leigh Baldwin & Company', 1),
        (0, 'Lek Securities Corporation', 1),
        (0, 'Liberty Bankers Life Insurance Company', 1),
        (0, 'Lifemark Securities Corporation', 1),
        (0, 'Lightstone Group', 1),
        (0, 'Lincoln Benefit Life Company', 1),
        (0, 'Lincoln Financial', 1),
        (0, 'Lincoln Investment Planning', 1),
        (0, 'Lincoln Life & Annuity Company of New York', 1),
        (0, 'Lincoln Life Assurance Company of Boston', 1),
        (0, 'Lincoln National Life Insurance Company', 1),
        (0, 'Lincoln Variable Insurance Products Trust', 1),
        (0, 'Lion Street Financial', 1),
        (0, 'Lionscrest Funds SPC', 1),
        (0, 'LLK Insurance Brokerage Services', 1),
        (0, 'Lockton Financial Advisors', 1),
        (0, 'Lombard International Life Assurance Company', 1),
        (0, 'Loomis Sayles Trust Company', 1),
        (0, 'Lord Abbett Distributor', 1),
        (0, 'LPL Financial', 1),
        (0, 'M Fund', 1),
        (0, 'M Holdings Securities', 1),
        (0, 'M&T Securities', 1),
        (0, 'M.H. Leblang', 1),
        (0, 'Mackay Shields', 1),
        (0, 'Mackenzie Realty Capital', 1),
        (0, 'Macquarie Capital         (USA)', 1),
        (0, 'Madison Avenue Securities', 1),
        (0, 'Madoff         (Bernard L.) Investment Securities', 1),
        (0, 'Manning & Napier Investor Services', 1),
        (0, 'MarketAxess Corporation', 1),
        (0, 'Marsco Investment Corporation', 1),
        (0, 'Massachusetts Mutual Life Insurance Company', 1),
        (0, 'Matrix 360', 1),
        (0, 'Matrix Trust Company', 1),
        (0, 'Matthew 25 Fund', 1),
        (0, 'Maxim Group', 1),
        (0, 'Megatel Capital Investment', 1),
        (0, 'Mercer Investments', 1),
        (0, 'Mercer Trust Company', 1),
        (0, 'Merrill Lynch', 1),
        (0, 'Metlife Investors', 1),
        (0, 'Metropolitan Life Insurance Company', 1),
        (0, 'Metropolitan Partners Group Management', 1),
        (0, 'MFD Distributor', 1),
        (0, 'MFS', 1),
        (0, 'MFS Heritage Trust Company', 1),
        (0, 'Michael J. Liccar & Company', 1),
        (0, 'Mid Atlantic Capital', 1),
        (0, 'Midas Securities Group', 1),
        (0, 'Midland National Life Insurance Company', 1),
        (0, 'Militello Capital', 1),
        (0, 'Millennium Trust Company', 1),
        (0, 'Mills Value Adviser', 1),
        (0, 'Minnesota Life Insurance Company', 1),
        (0, 'Mirae Asset Securities         (USA)', 1),
        (0, 'MML', 1),
        (0, 'MML Bay State Life Insurance Company', 1),
        (0, 'Modern Woodmen of America', 1),
        (0, 'Monte Capital Group', 1),
        (0, 'Monticello Financial Group', 1),
        (0, 'Moody National', 1),
        (0, 'Morgan Creek Capital Management', 1),
        (0, 'MRW Financial', 1),
        (0, 'MS Capital Partners Adviser', 1),
        (0, 'MUFG', 1),
        (0, 'Mundoval Funds', 1),
        (0, 'Muriel Siebert & Company', 1),
        (0, 'Mutual of Omaha', 1),
        (0, 'Mutual Securities', 1),
        (0, 'Mutual Shareholder Services', 1),
        (0, 'Nassau Life Insurance Company', 1),
        (0, 'National Asset Management', 1),
        (0, 'National Bank of Canada Financial', 1),
        (0, 'National Financial Services', 1),
        (0, 'National Integrity Life Insurance Company', 1),
        (0, 'National Life Insurance Company', 1),
        (0, 'National Securities Corporation', 1),
        (0, 'National Security Life and Annuity Company', 1),
        (0, 'National Western Life Insurance Company', 1),
        (0, 'Nationwide', 1),
        (0, 'Natixis', 1),
        (0, 'Nav Consulting', 1),
        (0, 'Neiman Funds', 1),
        (0, 'Nelson Brothers Professional Real Estate', 1),
        (0, 'Neptune Global Holdings', 1),
        (0, 'Nesf Investment Services', 1),
        (0, 'Nest Investments BD', 1),
        (0, 'Neuberger Berman Management', 1),
        (0, 'New Vernon Investment Management', 1),
        (0, 'New York Life Insurance and Annuity Corporation', 1),
        (0, 'Newport Group Securities', 1),
        (0, 'Nexpoint Advisors LP', 1),
        (0, 'Noble Royalties', 1),
        (0, 'Noetic Investment Advisors', 1),
        (0, 'Nomura Securities International', 1),
        (0, 'Nordea Investment Funds S.A.', 1),
        (0, 'North American Company For Life and Health Insurance', 1),
        (0, 'North Capital Administrator Services', 1),
        (0, 'North Capital Private Securities Corporation', 1),
        (0, 'Northeast Investors Trust', 1),
        (0, 'Northeast Retirement Services', 1),
        (0, 'Northern Lights', 1),
        (0, 'Northern Trust', 1),
        (0, 'Northwestern Mutual', 1),
        (0, 'Nuveen Securities', 1),
        (0, 'Nylife', 1),
        (0, 'O.N. Equity Sales Company', 1),
        (0, 'Oak Bridge Royalties', 1),
        (0, 'Oakmark Fund', 1),
        (0, 'Oaktree Real Estate Income Trust', 1),
        (0, 'Oberweis Securities', 1),
        (0, 'Oceanview Life and Annuity Company', 1),
        (0, 'OConnor Davies Administration', 1),
        (0, 'OFS Capital Management', 1),
        (0, 'Ohio National', 1),
        (0, 'One America Securities', 1),
        (0, 'One Resource Group Corporation', 1),
        (0, 'Oppenheimer & Company', 1),
        (0, 'Opus Fund Services         (USA)', 1),
        (0, 'Origin Holding Company', 1),
        (0, 'Orion Advisor Services', 1),
        (0, 'Owl Rock', 1),
        (0, 'Oxford Life Insurance Company', 1),
        (0, 'P.J. Robb Variable Corporation', 1),
        (0, 'Pacific Life', 1),
        (0, 'Pacific Oak Capital Advisors', 1),
        (0, 'Pacific Select', 1),
        (0, 'Packerland Brokerage Services', 1),
        (0, 'Palmer Square Capital Management', 1),
        (0, 'Pangburn Group', 1),
        (0, 'Panorama Point Partners', 1),
        (0, 'Paradigm Funds', 1),
        (0, 'Park Avenue Securities', 1),
        (0, 'Parking REIT', 1),
        (0, 'Parkland Securities', 1),
        (0, 'Parnassus Investments', 1),
        (0, 'Participant Capital', 1),
        (0, 'Payden & Rygel', 1),
        (0, 'Peachcap Securities', 1),
        (0, 'Peachtree PC Advisors', 1),
        (0, 'Peco Strategic Investment Fund III', 1),
        (0, 'Pembrook Capital Management', 1),
        (0, 'Pen-Cal Administrators', 1),
        (0, 'Pender Capital Management', 1),
        (0, 'Penn Mutual Life Insurance Company', 1),
        (0, 'Penn Square Real Estate Group', 1),
        (0, 'Peoples Securities', 1),
        (0, 'Perennial Fund Services', 1),
        (0, 'Persimmon Capital Management', 1),
        (0, 'PFM Asset Management', 1),
        (0, 'PFS Funds', 1),
        (0, 'PFS Investments', 1),
        (0, 'Phillip Capital', 1),
        (0, 'PHL Variable Insurance Company', 1),
        (0, 'Phoenix American Financial Services', 1),
        (0, 'Piedmont Fund Services', 1),
        (0, 'PIMCO Investments', 1),
        (0, 'Piping Rock Partners', 1),
        (0, 'Planmember Securities Corporation', 1),
        (0, 'Platform Investments', 1),
        (0, 'Pomona Investment Fund', 1),
        (0, 'PPB Advisors', 1),
        (0, 'Praedium Group', 1),
        (0, 'Praxis Capital', 1),
        (0, 'Precision Capital Advisors', 1),
        (0, 'Preferred Capital Securities', 1),
        (0, 'Preferred Product Network', 1),
        (0, 'Presidential Bank, FSB', 1),
        (0, 'Principal Life Insurance Company', 1),
        (0, 'Principal Securities', 1),
        (0, 'Private Client Services', 1),
        (0, 'Proequities', 1),
        (0, 'Profunds', 1),
        (0, 'Prospera Financial Services', 1),
        (0, 'Protective Life & Annuity Insurance Company', 1),
        (0, 'Proteus', 1),
        (0, 'Provident Trust Group', 1),
        (0, 'Pruco Life Insurance Company', 1),
        (0, 'Prudential', 1),
        (0, 'Purshe Kaplan Sterling Investments', 1),
        (0, 'Putnam', 1),
        (0, 'Qualis Capital', 1),
        (0, 'Quasar', 1),
        (0, 'Rafferty Capital Markets', 1),
        (0, 'Rare Beauty Brands', 1),
        (0, 'RealAmerica Development', 1),
        (0, 'Reassure America Life Insurance Company', 1),
        (0, 'Regulus Advisors', 1),
        (0, 'Related Fund Management', 1),
        (0, 'Reliance Capital Markets II', 1),
        (0, 'Reliance Standard Life Insurance Company', 1),
        (0, 'Reliance Trust Company', 1),
        (0, 'Reliastar Life Insurance Company', 1),
        (0, 'Resource Real Estate', 1),
        (0, 'Resource Royalty', 1),
        (0, 'Reynolds Funds Inc', 1),
        (0, 'RFS Partners', 1),
        (0, 'Richmond Quantitative Advisors', 1),
        (0, 'Riverrock Trust', 1),
        (0, 'Riversource Life Insurance Company', 1),
        (0, 'Rmb Capital Management', 1),
        (0, 'Robert W. Baird & Company Incorporated', 1),
        (0, 'Robinhood Securities', 1),
        (0, 'Royal Alliance Associates', 1),
        (0, 'Royal Oak Realty Trust', 1),
        (0, 'Royce Fund Services', 1),
        (0, 'Rreef America', 1),
        (0, 'Russell', 1),
        (0, 'S.USA Life Insurance Company', 1),
        (0, 'S2K Servicing', 1),
        (0, 'Sagepoint Financial', 1),
        (0, 'Sammons Financial Network', 1),
        (0, 'Sanctuary Securities', 1),
        (0, 'Sanford C. Bernstein & Company', 1),
        (0, 'Saturna', 1),
        (0, 'Saxony Securities', 1),
        (0, 'SBLI USA Life Insurance Company', 1),
        (0, 'Schroder Fund Advisors', 1),
        (0, 'Scotia Capital         (USA)', 1),
        (0, 'Sealy & Company', 1),
        (0, 'Second Century Ag', 1),
        (0, 'Securian Financial Services', 1),
        (0, 'Securities America', 1),
        (0, 'Securities Transfer Corporation', 1),
        (0, 'Security Benefit Life Insurance Company', 1),
        (0, 'Security Life of Denver Insurance Company', 1),
        (0, 'Security Mutual Life Insurance Company of New York', 1),
        (0, 'SEI', 1),
        (0, 'Sentinus-Halo Securities', 1),
        (0, 'SG Americas Securities', 1),
        (0, 'SGGG Fund Services Inc', 1),
        (0, 'Shearson Lehman', 1),
        (0, 'Shopoff Realty Investments', 1),
        (0, 'SIA Securities Corp.', 1),
        (0, 'Sierra Income Corporation', 1),
        (0, 'Sigma Financial Corporation', 1),
        (0, 'SignatureFD', 1),
        (0, 'Simkowitz & Company', 1),
        (0, 'Smartstop Asset Management', 1),
        (0, 'SMBC Nikko Securities America', 1),
        (0, 'Sorrento Pacific Financial', 1),
        (0, 'Sortis Holdings', 1),
        (0, 'Sound Equity Management Group', 1),
        (0, 'South State Bank, National Association', 1),
        (0, 'Southwest Value Partners Enterprise', 1),
        (0, 'Sower Capital Management', 1),
        (0, 'Sower Farm Management', 1),
        (0, 'Spire Securities', 1),
        (0, 'Spruceview Capital Partners', 1),
        (0, 'SQN Capital Management', 1),
        (0, 'SS&C Technologies', 1),
        (0, 'Standard Insurance Company', 1),
        (0, 'Starwood Real Estate Income Trust', 1),
        (0, 'Statetrust Capital', 1),
        (0, 'Steadfast Apartment REIT', 1),
        (0, 'Steben & Company', 1),
        (0, 'Sterling Bridge Insurance Agency', 1),
        (0, 'Stifel, Nicolaus & Company', 1),
        (0, 'Stone Coast Fund Services', 1),
        (0, 'Stonecrest Managers', 1),
        (0, 'Stonex Financial', 1),
        (0, 'Straits Financial Fund Management', 1),
        (0, 'Strategic Capital Fund Management', 1),
        (0, 'Sudrania Fund Services Corp', 1),
        (0, 'Sun Life', 1),
        (0, 'Swiss Financial Services', 1),
        (0, 'Symetra Life Insurance Company', 1),
        (0, 'Syndicated Capital', 1),
        (0, 'T. Rowe Price', 1),
        (0, 'T2 Holdings', 1),
        (0, 'Talcott Resolution Life Insurance Company', 1),
        (0, 'TCA Global Credit Master Fund LP', 1),
        (0, 'TCW Funds', 1),
        (0, 'TD Ameritrade', 1),
        (0, 'Teachers Advisors', 1),
        (0, 'Terra Income Advisors', 1),
        (0, 'TFA Associates', 1),
        (0, 'The Variable Annuity Life Insurance Company', 1),
        (0, 'Theorem Fund Services', 1),
        (0, 'Thompson Davis & Company', 1),
        (0, 'Thornburg Securities Corporation', 1),
        (0, 'Thrivent', 1),
        (0, 'Time Equities Securities', 1),
        (0, 'Tocqueville Securities', 1),
        (0, 'Touchstone Securities', 1),
        (0, 'Tradebot Systems', 1),
        (0, 'Tradelink Securities', 1),
        (0, 'Tradestation Securities', 1),
        (0, 'Tradition Securities and Derivatives', 1),
        (0, 'Transamerica', 1),
        (0, 'Trans-Oceanic Life Insurance Company', 1),
        (0, 'Triad Advisors', 1),
        (0, 'Trident Fund Services', 1),
        (0, 'Trilinc Advisors', 1),
        (0, 'True Life Companies', 1),
        (0, 'Trust Asset Management', 1),
        (0, 'Tullett Prebon Financial Services', 1),
        (0, 'U.S. Boston Capital Corporation', 1),
        (0, 'Ultimus Fund', 1),
        (0, 'Ultimus Private Fund Solutions', 1),
        (0, 'UMB Fund Services', 1),
        (0, 'United Bankers Bank', 1),
        (0, 'United Brokerage Services', 1),
        (0, 'United Life Insurance Company', 1),
        (0, 'United of Omaha Life Insurance Company', 1),
        (0, 'United Planners Financial Services of America', 1),
        (0, 'United States Life Insurance Company In The City of New York', 1),
        (0, 'Universal Life Insurance Company', 1),
        (0, 'Upright Investments Trust', 1),
        (0, 'US Bancorp Fund Services', 1),
        (0, 'US Bank', 1),
        (0, 'US Capital Global Investment Management', 1),
        (0, 'Valic Financial Advisors', 1),
        (0, 'Valmark Securities', 1),
        (0, 'Valueworks Limited Partners', 1),
        (0, 'Van Eck Securities Corporation', 1),
        (0, 'Vancouver Stock Exchange', 1),
        (0, 'Vanguard', 1),
        (0, 'Vantage Retirement Plans', 1),
        (0, 'Vantis Life Insurance Company', 1),
        (0, 'Velocity', 1),
        (0, 'Velox Clearing', 1),
        (0, 'Venerable Insurance and Annuity Company', 1),
        (0, 'Veridos Advisors', 1),
        (0, 'Vertical Management Systems', 1),
        (0, 'Vigilant', 1),
        (0, 'VII Peaks Capital', 1),
        (0, 'Vining-Sparks IBG', 1),
        (0, 'Virtu Americas', 1),
        (0, 'Virtus Real Estate', 1),
        (0, 'Vision Financial Markets', 1),
        (0, 'Vistra USA', 1),
        (0, 'Vivaldi Capital Management', 1),
        (0, 'Voya', 1),
        (0, 'W.P. Carey & Company', 1),
        (0, 'Wachtel & Company', 1),
        (0, 'Waddell & Reed', 1),
        (0, 'Walker Financial Services', 1),
        (0, 'Walthausen Funds', 1),
        (0, 'Walton', 1),
        (0, 'Watermark Lodging Trust', 1),
        (0, 'Waterway Capital', 1),
        (0, 'Waveland Capital Partners', 1),
        (0, 'Waypoint Residential', 1),
        (0, 'Wedbush Securities', 1),
        (0, 'Weitz Investment Management', 1),
        (0, 'Wellington Trust Company', 1),
        (0, 'West Coast Stock Transfer', 1),
        (0, 'Western International Securities', 1),
        (0, 'Western-Southern Life Assurance Company', 1),
        (0, 'WFI Management II', 1),
        (0, 'William Blair & Company', 1),
        (0, 'William Penn Life Insurance Company of New York', 1),
        (0, 'Wilshire Finance Partners', 1),
        (0, 'Wilson-Davis & Company', 1),
        (0, 'Winslow, Evans & Crocker', 1),
        (0, 'Wolverine Execution Services', 1),
        (0, 'Woodbury Financial Services', 1),
        (0, 'Woodmen Financial Services', 1),
        (0, 'World Capital Brokerage', 1),
        (0, 'World Equity Group', 1),
        (0, 'Wunderlich Securities', 1),
        (0, 'Yankee Advisers', 1),
        (0, 'Z Capital Credit Partners', 1),
        (0, 'Ziv Investment Company', 1),
        (0, 'Zurich', 1)


        -- TCorporateAudit
        INSERT INTO crm..TCorporateAudit  
              ([IndClientId],[CorporateName],[ArchiveFG],[BusinessType],[RefCorporateTypeId],[CompanyRegNo],[EstIncorpDate],[YearEnd],[VatRegFg]
              ,[Extensible],[VatRegNo],[ConcurrencyId],[CorporateId],[StampAction],[StampDateTime],[StampUser],[MigrationRef],[LEI],[LEIExpiryDate])
        SELECT [IndClientId],[CorporateName],[ArchiveFG],[BusinessType],[RefCorporateTypeId],[CompanyRegNo],[EstIncorpDate],[YearEnd],[VatRegFg]
              ,[Extensible],[VatRegNo],[ConcurrencyId],[CorporateId],@StampAction, @StampDateTime, @StampUser,[MigrationRef],[LEI],[LEIExpiryDate]
        FROM  crm..TCorporate
        WHERE CorporateId IN (SELECT CorporateId FROM #TCorporate) 

        IF OBJECT_ID('tempdb..#TCRMContact') IS NOT NULL
              DROP TABLE #TCRMContact
        CREATE TABLE #TCRMContact(CrmContactId INT)

        -- TCRMContact
        INSERT INTO crm..TCRMContact (CorporateId, CorporateName, IndClientId)
              OUTPUT inserted.CRMContactId
              INTO #TCRMContact
        SELECT CorporateId, CorporateName, 0 
        FROM #TCorporate

        -- TCRMContactAudit
        INSERT INTO crm..TCRMContactAudit
        ([RefCRMContactStatusId],[PersonId],[CorporateId],[TrustId],[AdvisorRef],[RefSourceOfClientId],[SourceValue],[Notes],[ArchiveFg],[LastName]
              ,[FirstName],[CorporateName],[DOB],[Postcode],[OriginalAdviserCRMId],[CurrentAdviserCRMId],[CurrentAdviserName],[CRMContactType],[IndClientId]
              ,[FactFindId],[InternalContactFG],[RefServiceStatusId],[AdviserAssignedByUserId],[_ParentId],[_ParentTable],[_ParentDb],[_OwnerId],[MigrationRef]
              ,[CreatedDate],[ExternalReference],[AdditionalRef],[CampaignDataId],[FeeModelId],[ConcurrencyId],[CRMContactId],[StampAction],[StampDateTime],[StampUser]
              ,[ServiceStatusStartDate],[ClientTypeId],[IsHeadOfFamilyGroup],[FamilyGroupCreationDate],[IsDeleted])
        SELECT 
        [RefCRMContactStatusId],[PersonId],[CorporateId],[TrustId],[AdvisorRef],[RefSourceOfClientId],[SourceValue],[Notes],[ArchiveFg],[LastName]
              ,[FirstName],[CorporateName],[DOB],[Postcode],[OriginalAdviserCRMId],[CurrentAdviserCRMId],[CurrentAdviserName],[CRMContactType],[IndClientId]
              ,[FactFindId],[InternalContactFG],[RefServiceStatusId],[AdviserAssignedByUserId],[_ParentId],[_ParentTable],[_ParentDb],[_OwnerId],[MigrationRef]
              ,[CreatedDate],[ExternalReference],[AdditionalRef],[CampaignDataId],[FeeModelId],[ConcurrencyId],[CRMContactId],@StampAction,@StampDateTime,@StampUser
              ,[ServiceStatusStartDate],[ClientTypeId],[IsHeadOfFamilyGroup],[FamilyGroupCreationDate],[IsDeleted]
        FROM crm..TCRMContact
        WHERE CRMContactId IN (SELECT CRMContactId FROM #TCRMContact)

        IF OBJECT_ID('tempdb..#TRefProdProvider') IS NOT NULL
        DROP TABLE #TRefProdProvider
        CREATE TABLE #TRefProdProvider(RefProviderId INT)

        -- TRefProdProvider
        INSERT INTO TRefProdProvider (CRMContactId, RegionCode, IsConsumerFriendly)
              OUTPUT inserted.RefProdProviderId
              INTO #TRefProdProvider
        SELECT CRMContactId, @RegionCode, 1
        FROM #TCRMContact

        -- TRefProdProviderAudit
        INSERT INTO TRefProdProviderAudit
        ([CRMContactId],[FundProviderId],[NewProdProviderId],[RetireFg],[ConcurrencyId],[RefProdProviderId],[StampAction],[StampDateTime],[StampUser],[IsTransactionFeedSupported]
              ,[IsConsumerFriendly],[RegionCode],[IsBankAccountTransactionFeed])
        SELECT 
        [CRMContactId],[FundProviderId],[NewProdProviderId],[RetireFg],[ConcurrencyId],[RefProdProviderId] ,@StampAction,@StampDateTime,@StampUser,[IsTransactionFeedSupported]
              ,[IsConsumerFriendly],[RegionCode],[IsBankAccountTransactionFeed]
        FROM TRefProdProvider
        WHERE RefProdProviderId IN (SELECT RefProviderId FROM #TRefProdProvider)

        -- TRefLicenseTypeToRefProdProvider
        INSERT INTO TRefLicenseTypeToRefProdProvider (RefProdproviderId, RefLicenseTypeId)
              OUTPUT inserted.RefLicenseTypeToRefProdProviderId,
                      inserted.RefProdproviderId,
                      inserted.RefLicenseTypeId, 
                      inserted.ConcurrencyId,
                      @StampAction,
                      @StampDateTime,
                      @StampUser
              INTO TRefLicenseTypeToRefProdProviderAudit
        SELECT RefProviderId, 1
        FROM #TRefProdProvider


		-- Start deleting providers
		SET @StampAction = 'D'

		IF OBJECT_ID('tempdb..#ProvidersToDelete') IS NOT NULL
				DROP TABLE #ProvidersToDelete
		CREATE TABLE #ProvidersToDelete(CRMContactId INT, CorporateId INT, RefProdProviderId INT, ProviderName VARCHAR(250))

		INSERT INTO #ProvidersToDelete (CRMContactId, CorporateId, RefProdProviderId, ProviderName)
		SELECT contacts.CRMContactId, contacts.CorporateId, rProviders.RefProdProviderId, contacts.CorporateName as ProviderName
		FROM crm..TCRMContact contacts
		INNER JOIN TRefProdProvider rProviders ON rProviders.CRMContactId = contacts.CRMContactId 
		WHERE CorporateName in('Barclays Bank Delaware',
		'Charles Schwab Premier Bank',
		'Charles Schwab Trust Bank',
		'Morgan Stanley Private Bank',
		'U.S. Bank',
		'Wells Fargo Bank South Central',
		'Wells Fargo National Bank West',
		'TD Bank USA')
		AND rProviders.RegionCode = @RegionCode

		DELETE FROM TRefLicenseTypeToRefProdProvider
		OUTPUT  deleted.RefLicenseTypeToRefProdProviderId,
				deleted.RefProdproviderId,
				deleted.RefLicenseTypeId, 
				deleted.ConcurrencyId,
				@StampAction,
				@StampDateTime,
				@StampUser
        INTO TRefLicenseTypeToRefProdProviderAudit (
               RefLicenseTypeToRefProdProviderId,
               RefProdproviderId,
               RefLicenseTypeId, 
               ConcurrencyId,
               StampAction,
               StampDateTime,
               StampUser)
		WHERE TRefLicenseTypeToRefProdProvider.RefProdproviderId IN (SELECT RefProdProviderId FROM #ProvidersToDelete)

		DELETE FROM TRefProdProvider
		OUTPUT deleted.RefProdProviderId,
				deleted.CRMContactId,
				deleted.FundProviderId,
				deleted.NewProdProviderId,
				deleted.RetireFg,
				deleted.ConcurrencyId,
				deleted.IsTransactionFeedSupported,
				deleted.IsConsumerFriendly,
				deleted.RegionCode,
				deleted.IsBankAccountTransactionFeed,			
				@StampAction,
				@StampDateTime,
				@StampUser
		INTO TRefProdProviderAudit(
				RefProdProviderId,
				CRMContactId,
				FundProviderId,
				NewProdProviderId,
				RetireFg,
				ConcurrencyId,
				IsTransactionFeedSupported,
				IsConsumerFriendly,
				RegionCode,
				IsBankAccountTransactionFeed,			
				StampAction,
				StampDateTime,
				StampUser)
        WHERE TRefProdProvider.RefProdProviderId IN (SELECT RefProdProviderId FROM #ProvidersToDelete)

        DELETE FROM crm..TCRMContact
        OUTPUT deleted.RefCRMContactStatusId,
              deleted.PersonId,
              deleted.CorporateId,
              deleted.TrustId,
              deleted.AdvisorRef,
              deleted.RefSourceOfClientId,
              deleted.SourceValue,
              deleted.Notes,
              deleted.ArchiveFg,
              deleted.LastName,
              deleted.FirstName,
              deleted.CorporateName,
              deleted.DOB,
              deleted.Postcode,
              deleted.OriginalAdviserCRMId,
              deleted.CurrentAdviserCRMId,
              deleted.CurrentAdviserName,
              deleted.CRMContactType,
              deleted.IndClientId,
              deleted.FactFindId,
              deleted.InternalContactFG,
              deleted.RefServiceStatusId,
              deleted.AdviserAssignedByUserId,
              deleted._ParentId,
              deleted._ParentTable,
              deleted._ParentDb,
              deleted._OwnerId,
              deleted.MigrationRef,
              deleted.CreatedDate,
              deleted.ExternalReference,
              deleted.AdditionalRef,
              deleted.CampaignDataId,
              deleted.FeeModelId,
              deleted.ConcurrencyId,
              deleted.CRMContactId,
              @StampAction,
              @StampDateTime,
              @StampUser,
              deleted.ServiceStatusStartDate,
              deleted.ClientTypeId,
              deleted.IsHeadOfFamilyGroup,
              deleted.FamilyGroupCreationDate,
              deleted.IsDeleted
        INTO crm..TCRMContactAudit (
              RefCRMContactStatusId,
              PersonId,
              CorporateId,
              TrustId,
              AdvisorRef,
              RefSourceOfClientId,
              SourceValue,
              Notes,
              ArchiveFg,
              LastName,
              FirstName,
              CorporateName,
              DOB,
              Postcode,
              OriginalAdviserCRMId,
              CurrentAdviserCRMId,
              CurrentAdviserName,
              CRMContactType,
              IndClientId,
              FactFindId,
              InternalContactFG,
              RefServiceStatusId,
              AdviserAssignedByUserId,
              _ParentId,
              _ParentTable,
              _ParentDb,
              _OwnerId,
              MigrationRef,
              CreatedDate,
              ExternalReference,
              AdditionalRef,
              CampaignDataId,
              FeeModelId,
              ConcurrencyId,
              CRMContactId,
              StampAction,
              StampDateTime,
              StampUser,
              ServiceStatusStartDate,
              ClientTypeId,
              IsHeadOfFamilyGroup,
              FamilyGroupCreationDate,
              IsDeleted)
        WHERE crm..TCRMContact.CRMContactId IN (SELECT CRMContactId FROM #ProvidersToDelete)

        DELETE FROM crm..TCorporate
        OUTPUT deleted.CorporateId,
              deleted.IndClientId,
              deleted.CorporateName,
              deleted.ArchiveFg,
              deleted.BusinessType,
              deleted.RefCorporateTypeId,
              deleted.CompanyRegNo,
              deleted.EstIncorpDate,
              deleted.YearEnd,
              deleted.VatRegFg,
              deleted.VatRegNo,
              deleted.Extensible,
              deleted.ConcurrencyId,
              deleted.MigrationRef,      
              deleted.LEI,
              deleted.LEIExpiryDate,
              deleted.BusinessRegistrationNumber,
              @StampAction,
              @StampDateTime,
              @StampUser
        INTO crm..TCorporateAudit (
              CorporateId,
              IndClientId,
              CorporateName,
              ArchiveFg,
              BusinessType,
              RefCorporateTypeId,
              CompanyRegNo,
              EstIncorpDate,
              YearEnd,
              VatRegFg,
              VatRegNo,
              Extensible,
              ConcurrencyId,
              MigrationRef,
              LEI,
              LEIExpiryDate,
              BusinessRegistrationNumber,
              StampAction,
              StampDateTime,
              StampUser)
        WHERE crm..TCorporate.CorporateId IN (SELECT CorporateId FROM #ProvidersToDelete)


		-- Start update providers
		SET @StampAction = 'U'

		CREATE TABLE #ProvidersToRename
              (OldProviderName VARCHAR(200), NewProviderName VARCHAR(200))

		INSERT INTO #ProvidersToRename
              (OldProviderName, NewProviderName)
		VALUES ('BMO Harris Bank', 'BMO Harris'),
              ('BOKF', 'BOK Financial'),
              ('Charles Schwab Bank', 'Charles Schwab'),
              ('CIBC Bank USA', 'CIBC Bank'),
              ('Deutsche Bank Trust Company', 'Deutsche Bank'),
              ('E*TRADE Bank', 'E*Trade'),
              ('Fidelity Bank', 'Fidelity'),
              ('Fifth Third Bank', 'Fifth Third'),
              ('HSBC Bank USA', 'HSBC Bank'),
              ('INDUSTRIAL and COMMERCIAL BANK of CHINA FINANCIAL SERVICES', 'Industrial and Commercial Bank of China'),
              ('JPMorgan Chase Bank', 'JPMorgan Chase'),
              ('Mizuho Bank (USA)', 'Mizuho'),
              ('Morgan Stanley Bank', 'Morgan Stanley'),
              ('Raymond James Bank', 'Raymond James'),
              ('Truist Bank', 'Truist'),
              ('UBS Bank USA', 'UBS'),
              ('USAA Federal Savings Bank', 'USAA')

        UPDATE corp		 
                SET CorporateName = providers.NewProviderName
        OUTPUT inserted.CorporateId,
              inserted.IndClientId,
              inserted.CorporateName,
              inserted.ArchiveFg,
              inserted.BusinessType,
              inserted.RefCorporateTypeId,
              inserted.CompanyRegNo,
              inserted.EstIncorpDate,
              inserted.YearEnd,
              inserted.VatRegFg,
              inserted.VatRegNo,
              inserted.Extensible,
              inserted.ConcurrencyId,
              inserted.MigrationRef,      
              inserted.LEI,
              inserted.LEIExpiryDate,
              inserted.BusinessRegistrationNumber,
              @StampAction,
              @StampDateTime,
              @StampUser
        INTO crm..TCorporateAudit (
              CorporateId,
              IndClientId,
              CorporateName,
              ArchiveFg,
              BusinessType,
              RefCorporateTypeId,
              CompanyRegNo,
              EstIncorpDate,
              YearEnd,
              VatRegFg,
              VatRegNo,
              Extensible,
              ConcurrencyId,
              MigrationRef,
              LEI,
              LEIExpiryDate,
              BusinessRegistrationNumber,
              StampAction,
              StampDateTime,
              StampUser)
        FROM crm..TCorporate corp
        INNER JOIN #ProvidersToRename providers ON providers.OldProviderName = corp.CorporateName
        INNER JOIN crm..TCRMContact crmContact ON crmContact.CorporateId = corp.CorporateId
        INNER JOIN policymanagement..TRefProdProvider refProviders ON crmContact.CRMContactId = refProviders.CRMContactId
        WHERE refProviders.RegionCode = @RegionCode


        UPDATE crmContact
            SET CorporateName = providers.NewProviderName
        OUTPUT inserted.RefCRMContactStatusId,
              inserted.PersonId,
              inserted.CorporateId,
              inserted.TrustId,
              inserted.AdvisorRef,
              inserted.RefSourceOfClientId,
              inserted.SourceValue,
              inserted.Notes,
              inserted.ArchiveFg,
              inserted.LastName,
              inserted.FirstName,
              inserted.CorporateName,
              inserted.DOB,
              inserted.Postcode,
              inserted.OriginalAdviserCRMId,
              inserted.CurrentAdviserCRMId,
              inserted.CurrentAdviserName,
              inserted.CRMContactType,
              inserted.IndClientId,
              inserted.FactFindId,
              inserted.InternalContactFG,
              inserted.RefServiceStatusId,
              inserted.AdviserAssignedByUserId,
              inserted._ParentId,
              inserted._ParentTable,
              inserted._ParentDb,
              inserted._OwnerId,
              inserted.MigrationRef,
              inserted.CreatedDate,
              inserted.ExternalReference,
              inserted.AdditionalRef,
              inserted.CampaignDataId,
              inserted.FeeModelId,
              inserted.ConcurrencyId,
              inserted.CRMContactId,
              @StampAction,
              @StampDateTime,
              @StampUser,
              inserted.ServiceStatusStartDate,
              inserted.ClientTypeId,
              inserted.IsHeadOfFamilyGroup,
              inserted.FamilyGroupCreationDate,
              inserted.IsDeleted
        INTO crm..TCRMContactAudit (
              RefCRMContactStatusId,
              PersonId,
              CorporateId,
              TrustId,
              AdvisorRef,
              RefSourceOfClientId,
              SourceValue,
              Notes,
              ArchiveFg,
              LastName,
              FirstName,
              CorporateName,
              DOB,
              Postcode,
              OriginalAdviserCRMId,
              CurrentAdviserCRMId,
              CurrentAdviserName,
              CRMContactType,
              IndClientId,
              FactFindId,
              InternalContactFG,
              RefServiceStatusId,
              AdviserAssignedByUserId,
              _ParentId,
              _ParentTable,
              _ParentDb,
              _OwnerId,
              MigrationRef,
              CreatedDate,
              ExternalReference,
              AdditionalRef,
              CampaignDataId,
              FeeModelId,
              ConcurrencyId,
              CRMContactId,
              StampAction,
              StampDateTime,
              StampUser,
              ServiceStatusStartDate,
              ClientTypeId,
              IsHeadOfFamilyGroup,
              FamilyGroupCreationDate,
              IsDeleted)
        FROM crm..TCRMContact crmContact
        INNER JOIN #ProvidersToRename providers ON providers.OldProviderName = crmContact.CorporateName
        INNER JOIN policymanagement..TRefProdProvider refProviders on crmContact.CRMContactId = refProviders.CRMContactId
        WHERE refProviders.RegionCode = @RegionCode


        INSERT TExecutedDataScript (ScriptGUID, Comments) VALUES (@ScriptGUID, @Comments)

        IF OBJECT_ID('tempdb..#TCorporate') IS NOT NULL
              DROP TABLE #TCorporate

        IF OBJECT_ID('tempdb..#TCRMContact') IS NOT NULL
              DROP TABLE #TCRMContact			  

        IF OBJECT_ID('tempdb..#TRefProdProvider') IS NOT NULL
              DROP TABLE #TRefProdProvider

		IF OBJECT_ID('tempdb..#ProvidersToDelete') IS NOT NULL
              DROP TABLE #ProvidersToDelete

		IF OBJECT_ID('tempdb..#ProvidersToRename') IS NOT NULL
              DROP TABLE #ProvidersToRename
		

END TRY
BEGIN CATCH

       DECLARE @ErrorSeverity INT
       DECLARE @ErrorState INT
       DECLARE @ErrorLine INT
       DECLARE @ErrorNumber INT

       SELECT @ErrorMessage = ERROR_MESSAGE(),
       @ErrorSeverity = ERROR_SEVERITY(),
       @ErrorState = ERROR_STATE(),
       @ErrorNumber = ERROR_NUMBER(),
       @ErrorLine = ERROR_LINE()

       RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState, @ErrorNumber, @ErrorLine)

END CATCH


SET XACT_ABORT OFF
SET NOCOUNT OFF

RETURN;  